### ISSUE TITLE
Update project instructions to include "How to start"

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1007]
A classic student questions before starting a project is what boilerplate to use: Should I clone the project repository? or create a new project from the empty boilerplate? Or the vanilla js boilerplate?

We have to go [over each project](http://projects.breatheco.de/) and update the English and Spanish README.md files to specify how to start the project:

OPTION A:
```md
## 🌱  Where to start this project

The following boilerplate: [4Geeks Academy Vanilla.js](https://github.com/4GeeksAcademy/vanillajs-hello) is recommended to start this project, clone the repository locally or open it with gitpod for a better experience.
```

OPTION B:
```md
## 🌱  Where to start this project

This project comes with all the necessary files to start working right away, clone this repository locally or open it with gitpod for a better experience.

Then run the following command on the terminal: npx live-reload
```

Here is a video on how to start a project:
https://www.loom.com/share/f684b87d0a984374ab6570b9f0d914b0

**Comment by ElviraQDP** [comment]
to-do-list with cloud: https://github.com/breatheco-de/exercise-todo-list-cli-with-cloud/pull/2

**Comment by ElviraQDP** [comment]
https://github.com/breatheco-de/exercise-file-hierarchy-report/pull/1
https://github.com/breatheco-de/exercise-file-hierarchy-report/pull/2

**Comment by ElviraQDP** [comment]
link for the following updates: https://docs.google.com/spreadsheets/d/18L00IbRb-P6x_dwfDqNGW9XgVRT6jc_ZTrd9X8YTTvA/edit?usp=sharing
