### ISSUE TITLE
Links desde Breathcode

### ISSUE THREAD

**Issue by marcelovaldebenito** [4GeeksAcademy/About-4Geeks-Academy#1019]
Hrs: <hrs>1</hrs>

En Breathco.de crear un vínculo en el menú y uno en el footer hacia 4geeksacademy.com

**Comment by alesanchezr** [comment]
@ArielCalisaya ayudanos con esto porfa, aqui esta el repositorio del la pagina: https://github.com/breatheco-de/web

![links a 4geeks](https://user-images.githubusercontent.com/426452/110686666-ae634a00-81ad-11eb-8455-b8706610d193.png)

**Comment by ArielCalisaya** [comment]
I created a [PR for this issue](https://github.com/breatheco-de/website/pull/54) and, is waiting for review
