### ISSUE TITLE
Link Juice

### ISSUE THREAD

**Issue by marcelovaldebenito** [4GeeksAcademy/About-4Geeks-Academy#1020]
Que tipo de redirect es el que se está ocupando para dirigir del dominio .co al .com? 301, 302 o 307??

**Comment by alesanchezr** [comment]
para averiguar los tipos de redirect puedes escribir en tu terminal: 

```
curl <url>
```

Tendrias que reemplazar `<url>` por la url que quieres revisar, por ejemplo:

<img width="576" alt="Screen Shot 2021-03-08 at 12 17 31 PM" src="https://user-images.githubusercontent.com/426452/110356460-49222400-8008-11eb-9615-d07c34ef383a.png">

En este caso puedes ver que https://4geeksacademy.co/ redirige a https://4geeksacademy.com/ usando 301

**Comment by marcelovaldebenito** [comment]
comprendo gracias! voy a revisar las URLs principales
