### ISSUE TITLE
Corregir Imagenes de assets

### ISSUE THREAD

**Issue by ElviraQDP** [4GeeksAcademy/About-4Geeks-Academy#1024]
Aqui es donde debes reemplazar los URL de las imagenes:
https://github.com/breatheco-de/assets/blob/master/apis/resources/data/resources.json

Primero guarda la imagen en este repo:
https://github.com/breatheco-de/content/tree/master/src/assets/assets/assets

Y luego peudes "copy image address" y ponerla en el resourse.json

**Comment by ElviraQDP** [comment]
https://github.com/breatheco-de/assets/pull/198

**Comment by alesanchezr** [comment]
los url de las imagenes deben tener `?raw=true` si son de github
