### ISSUE TITLE
React spotify music player no esta igual en ingles que en español y las imagenes estan rotas en español

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1026]

**Comment by ElviraQDP** [comment]
repo: https://github.com/breatheco-de/exercise-music-player-react

**Comment by ElviraQDP** [comment]
pr english: https://github.com/breatheco-de/exercise-music-player-react/pull/3
Pr Spanish:https://github.com/breatheco-de/exercise-music-player-react/pull/2
