### ISSUE TITLE
Crear propiedad en GA Universal y G4 para el dominio 4geeksacademy.com, actualmente existe sólo para .co. Después de eso incorporar los objetivos que se encuentran la vista producción. Luego vincular GA con SC y Google Ads.

### ISSUE THREAD

**Issue by marcelovaldebenito** [4GeeksAcademy/About-4Geeks-Academy#1041]

**Comment by marcelovaldebenito** [comment]
![analytics](https://user-images.githubusercontent.com/77856148/110831885-fca24700-829a-11eb-99cd-2e893e202f04.png)
favor vincular google analytics en search console cómo aparece en la imagen, sólo puede hacerlo el owner

**Comment by marcogonzalo** [comment]
Este template de Google Analytics me ahorró un buen tiempo de trabajo: https://www.simoahava.com/custom-templates/eec-products-ga4-items/

Igualmente esta guía, del mismo autor: https://www.simoahava.com/analytics/google-analytics-4-ecommerce-guide-google-tag-manager/
