### ISSUE TITLE
Planificar cuales articulos se vna a traducir y pegarlos en este issue.

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1044]
- [ ] Revisar los que estan en la pagina
- [ ] Revisar los de medium

**Comment by marcelovaldebenito** [comment]
Hola, hice un filtro pequeño, yo creo que éstos contenidos serviría traducirlos al inglés:

--
5 Diferencias entre un Bootcamp y un curso de programación
¿Cómo adquirir experiencia antes de tu primer trabajo?
¿Por qué 4Geeks enseña Python como lenguaje de programación? (Versión Latam)
Programming, el superpoder de crear
5 Habilidades que desarrollas trabajando desde casa
Razones para aprender a programar: Testimonios de nuestros estudiantes
¿Por qué las mujeres en programación? ¿Por qué no?
Desarrollo web durante y despues del COVID-19
Transformación digital: un mundo de opciones
¿Es necesario estudiar una carrera universitaria para aprender a programar?
La duda del futuro programador: ¿Universidad o Coding Bootcamp?

Quedo atento a comentarios, saludos!

**Comment by ElviraQDP** [comment]
5 Differences between a Bootcamp and a programming course
How to get experience before your first job?
Why does 4Geeks teach Python as a programming language? (Latam version)
Programming, the super power to create
5 Skills you develop working from home
Reasons to learn to code: Testimonials from our students
Why women in programming? Why not?
Web development during and after COVID-19
Digital transformation: a world of options
Is it necessary to study a university degree to learn to program?
The Future Programmer's Doubt: College or Coding Bootcamp?

listo @marcelovaldebenito
