### ISSUE TITLE
Create leads list view

### ISSUE THREAD

**Issue by Omonroy36** [4GeeksAcademy/About-4Geeks-Academy#1057]
Hrs: <hrs>6</hrs>

- From the leads list i should be able to filter the following: 
[] Lead cohort
[] Soft and hard status (dropdown)
[] Source (dropdown)
[] Location (dropdown)
[] First name, last name, email
[] utm medium, utm source
[] Tag (dropdown)
[] starting_date and ending_date

The list should have the following columns 

[] id
[] first name and last name
[] utm_url
[] tag name

Hidden columns

[] gclid 
[] course
[] email 

With pagination and filter using querys

**Comment by Jtoledo88** [comment]
Pagado las 6hr en abril 2021
