### ISSUE TITLE
Export list of student form BC admin (The heroku version)

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#1065]
**Is your feature request related to a problem? Please describe.**
Download this list:
https://breathecode.herokuapp.com/admin/admissions/cohortuser/
And filter by country or/and cohort

**Describe the solution you'd like**
I need to get a list of students in real time and download to analyze

**Describe alternatives you've considered**

**Additional context**

**Comment by alesanchezr** [comment]
This was fixed with the SQL Explorer.
