### ISSUE TITLE
Media Gallery Front-End

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1121]
Hrs: <hrs>15</hrs>

- [x] Search media by name and slug
- [x] filter media by category
- [x] filter media by type (image, video or document)
- [x] Upload a new media
- [ ] Delete media (with warning)
- [ ] Update media but keep original URL.
- [ ] Create a new category.
- [ ] Delete a category.
- [ ] Rename a category.

<img width="1140" alt="Screen Shot 2021-03-26 at 12 25 44 PM" src="https://user-images.githubusercontent.com/426452/112662749-6e979600-8e2e-11eb-89c4-8b634488f5de.png">

**Comment by Omonroy36** [comment]
In the edit media, the form its no prefilling the info of the file, mus be prefilled to avoid blank fields
