### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/About-4Geeks-Academy#1143]
Link in lesson intro-to-4geeks doesn't load https://sep.4geeksacademy.com/

![image](https://user-images.githubusercontent.com/48845580/113721268-5f7dd700-96bd-11eb-93d4-deb0a8130d87.png)

![image](https://user-images.githubusercontent.com/48845580/113721412-83d9b380-96bd-11eb-90ca-d64901cba4b1.png)

**Comment by jatv93** [comment]
@ElviraQDP

**Comment by ElviraQDP** [comment]
fixed!!!!
