### ISSUE TITLE
Changes when adding a new cohort

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1156]
Hrs: <hrs>3</hrs>

- When adding a new cohort, the end_date must be included (it's already included when updating the cohort).
- Let the user pick "this cohort never ends" when creating or updating the cohort, if the user picks that, the end date must be set to null.
- Validate that the only way the cohort end_date is null is when the toggle "this cohort never ends" is activated.

**Comment by Jtoledo88** [comment]
bug no se paga

**Comment by jagtrrz** [comment]
https://github.com/breatheco-de/admin/pull/56

**Comment by jagtrrz** [comment]
https://github.com/breatheco-de/admin/pull/58
