### ISSUE TITLE
Cannot add many teachers if status is active

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1157]
There is a validation that prevents adding the same student into two different cohorts unless he/she dropped or postponed from the previous one.

That validation should not affect the teachers or assistants.

If you try to add a teacher into two different cohorts right now it will validate that the teacher has to have status dropped or postponed in the previous ones, but that is not true, the educational status does not really matter if your cohort role is different from `student`.

I did a quick fix here: https://github.com/breatheco-de/apiv2/blob/development/breathecode/admissions/serializers.py#L284

But the unit test has to be created to validate this the right way.

**Comment by jefer94** [comment]
It's done https://github.com/breatheco-de/apiv2/blob/development/breathecode/admissions/tests/urls/tests_academy_cohort_id_user_id.py#L111

**Comment by alesanchezr** [comment]
What about the other role for assistant or reviewer?
