### ISSUE TITLE
The default image for the user profile is not the right one

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1158]
![Screen Shot 2021-04-12 at 2 29 57 PM](https://user-images.githubusercontent.com/426452/114443382-9d866980-9b9b-11eb-80ff-4f34416e880c.png)

Use the github.avatar_url that comes in the request you are already making to get the student info: `v1/auth/academy/member/1331`

![Screen Shot 2021-04-12 at 2 31 33 PM](https://user-images.githubusercontent.com/426452/114443570-d7f00680-9b9b-11eb-8893-9847bca1e145.png)

**Comment by Jtoledo88** [comment]
bug no se paga
