### ISSUE TITLE
Save academy id on localStorage to avoid asking for academy on every website reload

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1167]
Hrs: <hrs>1</hrs>

- Save the academy id on the localStorage
- Every time the website refreshes you have to look for the academy id on the localStorage, and:
      1. If its empty you ask the user to pick the academy (like it happens right now)
      2. If it was a value you don't ask and you put it back into the store and axios.
      
Definition of done:
1. Login with a user that has access to several academies
2. The user picks one academy and gets take to the dashboard
3. The user reloads the browser
4. The user gets taken to dashboard again without having to pick the academy again.
5. The user clicks on the profile to switch to another academy
6. The systems promps to pick the academy
7. The user picks the new academy
8. The user reloads the window and gats take to the dashboard but with the new academy

**Comment by Jtoledo88** [comment]
Pagada la hora en abril 2021
