### ISSUE TITLE
Cambio de guía de colores en indicadores de 'stage' de cursos en admin de BC

### ISSUE THREAD

**Issue by marcogonzalo** [4GeeksAcademy/About-4Geeks-Academy#1175]
Sugerencia: pondría en verde los activos y en muted o gris los terminados. Con el tiempo y acumulación de cursos, lo que importará es detectar rápidamente lo activo, lo que está por terminar o lo que está por empezar.
![Screenshot_2021-04-12 BreatheCode Academy Admin](https://user-images.githubusercontent.com/410890/114750576-6c04ce00-9d54-11eb-8ecc-74b0712717bd.png)

**Comment by alesanchezr** [comment]
para nosotros la prioridad es que te acuerdes de cambiarle los estados, por eso los colores son verdes cuando ya se termino y no hay nada mas que hacer.
