### ISSUE TITLE
Deberian de organizar mejor las preguntas del tutorial

### ISSUE THREAD

**Issue by ccarcache** [4GeeksAcademy/About-4Geeks-Academy#1220]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ccarcache** [comment]
Considero que deberian organizar o formular mejor las preguntas en los items planteados, para que cuando personas que no tenemos conocimientos previos a programacion puedan encontrar un camino favorable para resolver las atividades sugeridas.

**Comment by alesanchezr** [comment]
A que tutorial te refieres @ccarcache? Hacemos un esfuerzo por formular mejor las preguntas y siempre estamos actualizando. Si tienes ejmplos especificos de preguntas que sonideras deberian etar mejor planteadas, por favor abre un nuevo ticket sobre esa pregunta.
