### ISSUE TITLE
Github authenticate current breathecode members

### ISSUE THREAD

**Issue by jefer94** [4GeeksAcademy/About-4Geeks-Academy#1230]
Hrs <hrs>3</hrs>

Conectar github luego de que yo ya tenga un user_id y un correo diferente

Si ya un usuario tiene su usuario y clave, y se esta conectando a github sin fines de autenticacion, el servicio de autentificacion a github debe poder recibir un breathecode user_id (opcional), de recibirlo, la conexion a github sera asociada a ese user_id, sin importar si su correo electronico hace match

**Comment by 99lalo** [comment]
https://github.com/breatheco-de/apiv2/pull/98

**Comment by 99lalo** [comment]
https://github.com/breatheco-de/apiv2/pull/104
