### ISSUE TITLE
Migrate decorator for security implementation on Slack Commands from `only` to `capable_of`

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1232]
Inittially I proposed a `@only` decorator to all the slack commands like this:
 
```python
@command(only='staff')
def execute(channel_id, **context):
    # anything
    return response
```

But now that we have a role & capability based security system we should migrate to:

```python
@command(capable_of='do_something')
def execute(channel_id, **context):
    # anything
    return response
```

That way we can create more capabilities easily. There are two commands already implemented: student and cohort.
- student.py should have the `read_student` capability.
- cohort.py should have the `read_cohort` capability.

**Comment by jefer94** [comment]
That's related to https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2184
