### ISSUE TITLE
Listado de alumnos se pone en blanco al seleccionar el primer estudiante

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#1235]
**Describe the bug**
Al seleccionar primer estudiante se pone en blanco
![image](https://user-images.githubusercontent.com/62053368/115554115-6b1cf080-a2ae-11eb-808d-25aa00fc5ca1.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alesanchezr** [comment]
@Omonroy36 its only happening when you select students that have not accepted the invite.

**Comment by victormgomezp** [comment]
Indeed i cannot delet it, i tried but it was imposible.

**Comment by Jtoledo88** [comment]
bug no paga
