### ISSUE TITLE
Bulk delete the following entities

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1236]
Hrs: <hrs>5</hrs>

Cohort
Staff
Certificate
Lead

Note: you can copy the functionality from bulk delete student that is already implemented.

- [ ] Confirm before deleting
- [ ] Implement bulk delete on the backend if needed.
- [ ] You should be able to delete yourself (backend).
- [ ] Only country_manager is able to delete student, staff, lead, or certificate (capable_of)
- [ ] Check for this: When a student is deleted, its certificates or any other information should not be deleted.

**Comment by alesanchezr** [comment]
@jefer94 are we a ready to bulk delete these entities?

**Comment by jefer94** [comment]
Bulk:
- certificate https://github.com/breatheco-de/apiv2/blob/47ab82c7c94a7277a2aa4df14747ad01bf1e2589/breathecode/admissions/views.py#L597
- cohort https://github.com/breatheco-de/apiv2/blob/47ab82c7c94a7277a2aa4df14747ad01bf1e2589/breathecode/admissions/views.py#L525
- staff https://github.com/breatheco-de/apiv2/blob/47ab82c7c94a7277a2aa4df14747ad01bf1e2589/breathecode/authenticate/views.py#L142
- student https://github.com/breatheco-de/apiv2/blob/47ab82c7c94a7277a2aa4df14747ad01bf1e2589/breathecode/authenticate/views.py#L262
