### ISSUE TITLE
Smart MUIDatatable

### ISSUE THREAD

**Issue by Omonroy36** [4GeeksAcademy/About-4Geeks-Academy#1255]
Hrs: <hrs>6</hrs>

The current MUIDatatable for each of the list components is getting very similar to each other that is causing.

**Comment by alesanchezr** [comment]
El history replace lo puedes obtener del URL actual, elimina esa propiedad.

**Comment by jagtrrz** [comment]
I have added the query sort and modified the` historyReplace` property to `history.location.pathname`
