### ISSUE TITLE
Toggle to make a cohort as private and/or "never ending"

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1262]
Hrs: <hrs>2.5</hrs>

- [x] On the cohort details I should be able to mark a cohort as private by clicking on the toggle, there is not need to save the cohort because once the toggle is on or off, if should automatically update the cohort.
- [x] Next to the "ending_date" input there should be checkbox that can be check and says "this cohort never ends".... when checked the ending_date input should disappear and when POSTing the cohort payload to the backend the ending_date must be null if the cohort never ends, also include a boolean never_ends=true.

**Comment by Jtoledo88** [comment]
bug no se paga

**Comment by alesanchezr** [comment]
- [ ] The call to action to make a cohort private is ok where it is on the "additional actions"
- [ ] Add a status next to the cohort status with a lock icon or open lock icon depending on if its private.
