### ISSUE TITLE
Front end gallery updates and bugs

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1264]
Hrs <hrs>2.5</hrs>

- [x] The category slug will be automatically generated form the backend, do not allow modification.
- [x] Two types of sorting: default is from created_at (recent first) and you can also pick  `-created_at` that will be (oldest first). 
```
?sort=-created_at
```
- [ ] The file name must be hidden, nobody cares :smile:
- [ ] The backend is going to return a `thumbnail_url` for each file on the media gallery, that will be the preview on the gallery, not the image URL.
- [x] Clear all filters in not working.
- [x] List view is weird, the preview image is all misplaced and each row item should be a lot smaller, no need for a big picture.

**Comment by Jtoledo88** [comment]
bug no se paga

**Comment by alesanchezr** [comment]
El estilo de la galeria vertical (no grid)

![Screen Shot 2021-05-18 at 5 38 55 PM](https://user-images.githubusercontent.com/426452/118726920-fb901780-b7ff-11eb-8287-47b95e9f472d.png)

**Comment by alesanchezr** [comment]
- [ ] The filters don't work when reloading the website, make sure you apply them on the useEffect.
- [ ] The same problem happens when the upload is finished.
- [ ] Bring back the names of the files.
- [ ] Fix the list view with what we discussed.
- [ ] The category slug will be automatically generated form the backend, do not allow modification.
- [ ] Confirm delete
