### ISSUE TITLE
New tests for the blog:

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1270]
This is for the new website as well as the old one, PR to the `next` branch

Here are the blog tests: https://github.com/4GeeksAcademy/website-v2/tree/master/src/test/blog

Each of those javascript files takes care of validating something in a blog post, we need to validate the following:

- [ ] Every post must have a front matter.
- [ ] Every blogpost must have a image_url and image_alt
- [ ] There must be an author field and it must be someone [from this list](https://github.com/4GeeksAcademy/website-v2/blob/master/src/utils/twitter.js), if it's not in that list it should be included.
- [ ] The property `avatar` is deprecated, it cannot be on the front matter.
- [ ] `slug` property is mandatory.
- [ ] The blog post should not have an `h1` heading because it will be automatically created already.

**Comment by ArielCalisaya** [comment]
**Necesito mas informacion** sobre la ultima tarea, no entiendo a que se refiere con `h1`, ¿El `title` en frontmatter?
Created PR [#722](https://github.com/4GeeksAcademy/website-v2/pull/722) in websitev2
