### ISSUE TITLE
Bulk retry to generate certificates for student,cohort

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1273]
Hrs: <hrs>15</hrs>

This is the view that handles the creation or re-creation of a certificate:

https://github.com/breatheco-de/apiv2/blob/4010d6e079d6884880baf27498b9a01bd3f2226a/breathecode/certificate/views.py#L81

We need to create one endpoint that can receive several tuples with (`student id` and `cohort`) and re-attempts to create a certificate for them.

![RAUWAVQaJf](https://user-images.githubusercontent.com/426452/116767177-6f5ab380-a9fc-11eb-9770-49bece5c9c11.gif)

Note: ask @jefer94 for help.

**Comment by jagtrrz** [comment]
back end pull https://github.com/breatheco-de/apiv2/pull/69

**Comment by jagtrrz** [comment]
fron end pull https://github.com/breatheco-de/admin/pull/80
