### ISSUE TITLE
Change cohort current date

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1275]
Hrs: <hrs>3</hrs>

- [x] From the cohort details view, we need an option to change the cohort current day
- [x] In the numeric picker only allow to increase up to the maximum amount of days that the syllabus has.
- [x] On a separate note, when the user changes the stage of the cohort to "ENDED" the current day should also be set to the max amount of days.
- [x] The backend must return the cohort's current day to be able to displayed on the front end.
- [x] Also, when the user changes the stage of the cohort to any other stage, in the same modal window there should be a numeric picker allowing to also specify the cohort current day.

![change-day](https://user-images.githubusercontent.com/426452/116767467-4dfac700-a9fe-11eb-8529-ddff86577176.png)

**Comment by jagtrrz** [comment]
https://github.com/breatheco-de/admin/pull/55

**Comment by jagtrrz** [comment]
backend pull request https://github.com/breatheco-de/apiv2/pull/59

**Comment by jefer94** [comment]
It is not testeable because the backend pull request is not accepted, but the change in back look great, cannot look if, the automatic test in the push i don't see it, but it look great

**Comment by jagtrrz** [comment]
https://github.com/breatheco-de/admin/pull/68
