### ISSUE TITLE
Sorting functionality for cohorts

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1281]
Hrs: <hrs>1</hrs>

If the header of any of the columns on the table is clicked it needs to fetch for the cohorts and also pass the `sort` attribute to the backend.

Make sure you don't break pagination or any other filters, just incorporate the `sort`attribute to the queryString URL.

Depending on ascending or descending you have to add the `-` to the sort, for example:

`?sort=-starting_at` or `?sort=starting_at`

**Comment by jagtrrz** [comment]
https://github.com/breatheco-de/admin/pull/61

**Comment by jefer94** [comment]
In `/admissions/cohorts` it filter by `sort`, if I click in slug, it do one request with `slug` and if I do click again if change to `-slug`, but in backend the sort by querystring is not implemented

It for me work
