### ISSUE TITLE
Student certificates (userspecialty) can only be generated if its cohort has stage=ENDED or if it never ends

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1284]
Hrs: <hrs>2</hrs>

**Comment by jagtrrz** [comment]
class BlogPostSerializer(serializers.Serializer):
    title = serializers.CharField(max_length=100)
    content = serializers.CharField()

    def validate_title(self, value):
        """
        Check that the blog post is about Django.
        """
        if 'django' not in value.lower():
            raise serializers.ValidationError("Blog post is not about Django")
        return value
https://www.django-rest-framework.org/api-guide/serializers/#field-level-validation

**Comment by jagtrrz** [comment]
Hacer la validación antes de encolar. 

Traer todas las validaciones acerca de los cohorts a la view `CertificateCohortView`. Y validar antes de llamar a `generate_certificates.` Que no entren a la llamada de generate_certificates cohorts que no esten correctamente validados. 

https://github.com/breatheco-de/apiv2/blob/master/breathecode/certificate/views.py#L99
