### ISSUE TITLE
The menu shows blank days

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/About-4Geeks-Academy#1287]
![image](https://user-images.githubusercontent.com/48845580/116789979-fdc44900-aa7f-11eb-8668-aed32e01b157.png)

![image](https://user-images.githubusercontent.com/48845580/116789984-06b51a80-aa80-11eb-8216-efac8a7858f2.png)

![image](https://user-images.githubusercontent.com/48845580/116789993-0f0d5580-aa80-11eb-856c-a4586c0c8b7a.png)

**Comment by alesanchezr** [comment]
This will be fixed in the new version of breathecode that we are about to publish in a few days.
