### ISSUE TITLE
BreatheCode Academy Admin

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1294]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-4109-25821-c01acb45a74fec2d7eee4fc39104e49b) 

 Hrs <hrs>0.3</hrs>

You are supposed to wait for the second .then in the promise, you are probably redirecting even if the request was not successful.

---
**Source URL**:
[https://admin.breatheco.de/admissions/students/new](https://admin.breatheco.de/admissions/students/new)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 90.0.4430.93</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x671</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by jefer94** [comment]
In local of Orlando it's work
