### ISSUE TITLE
Copy invite URL feature

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1295]
Hrs <hrs>1</hrs>

When a new user is invited to breathecode, sometimes the email takes time to arrive, is a good idea to have a "copy invite link" button on the student or staff member, **we have to update both views (staff invites and students)** by adding one icon to copy the invite URL.

When the button is clicked, the front end will [fetch to invite info to this URL](https://documenter.getpostman.com/view/2432393/T1LPC6ef#e4eb0ff1-1e9f-4517-a113-99f63baf910f) and then  automatically copy to the incoming `invite_url` to the clipboard and a toast green notification will say that "The invitation link has successfully been added to your clipboard"

You can find the icon by the name `assignment`.

![BreatheCode-Academy-Admin (1)](https://user-images.githubusercontent.com/426452/117509364-15a43d00-af58-11eb-9721-d49377582abd.png)

**Comment by Omonroy36** [comment]
@alesanchezr  there is an issue with this, and is that the id the endpoint requires to get the invite url is the academy_profile_id wich at the moment comes null because the user havent registered yet.
