### ISSUE TITLE
Test for tags and utm integrity on the website

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1349]
There are several ymls in the website were we ask the content managers to set the tags, automation and utm fields.

- [The landing tempaltes](https://github.com/4GeeksAcademy/website-v2/blob/d3ef8139aff986e7cfe82870169cdb86494f1b90/src/data/landing/template.us.yml#L14)

We need to develop a small testing script that tests for those tags, automation or utm fields to be valid, they are valid because they match with one of the possible options.

For example:

- [ ] locations have to match with any yml in the ./src/data/location.yml specifically the property `breathecode_location_slug` inside the yml. [For example.](https://github.com/4GeeksAcademy/website-v2/blob/d3ef8139aff986e7cfe82870169cdb86494f1b90/src/data/location/madrid-spain.es.yaml#L192)
- [ ] utm_course has to match with any of the file names inside the `./src/data/course/` file names (ignoring language). For example: full-stack
- [ ] The ./src/data/course file names have to match the bc_slug property inside them
- [ ] Automations and tags have to match with their respective tags or automation  coming from the API:
```
GET: breathecode.herokuapp.com/v1/marketing/academy/tag
GET: breathecode.herokuapp.com/v1/marketing/academy/automation
```
- [ ] The locations in the ./src/data/location, the property `breathecode_location_slug` has to match one of the breathecode locations. 
```
GET: breathecode.herokuapp.com/v1/admissions/academy
```
- [ ] The `author` property in the blog post frontmatter has to match any of the `./src/utils/twitter.js` usernames.
- [ ] Any YML must have a Spanish and English version unless is called "example.yml".
- [ ] Any relative image on any YML or Markdown (md) should match from its respective image file inside the static folder.
- [ ] The image gallery for each location should have exactly 5 images.

**Comment by ArielCalisaya** [comment]
The url ( `breathecode.herokuapp.com/v1/`): not works it needs a auth key

![notWork](https://user-images.githubusercontent.com/51676628/119056532-d551af80-b998-11eb-9563-672aad4b03bc.png)

**Comment by ArielCalisaya** [comment]
Hrs: <hrs>9.5</hrs>
