### ISSUE TITLE
This link is not correct

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#1360]
**Describe the bug**
Should go to the comparisson  but is going to the home

![image](https://user-images.githubusercontent.com/62053368/118868812-ee992400-b8e4-11eb-9e90-a2c4211c776a.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jatv93** [comment]
Listo! Puedes cerrar el issue
