### ISSUE TITLE
IMPORTANTE AFECTA A LAS VENTAS: Si ponemos que la sede es MADRID la gente se va a pensar que es presencial

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#1362]
**Describe the bug**
Si ponemos MADRID la gente no va a saber que es en remoto, creerán que es en presencial y perderemos clientes

Full-Time: Madrid / Remoto
Part-Time: Remoto

![image](https://user-images.githubusercontent.com/62053368/118869267-72eba700-b8e5-11eb-8087-1817f92d6e6a.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Andrearcastillo** [comment]
Para solucionar esto se me ocurre que cambiemos la palabra "Sede" por "Campus y que cuando el usuario busque por ejemplo "Madrid" se especifiqué los que son online como "Madrid/online".

<img width="1064" alt="Captura de Pantalla 2021-05-19 a la(s) 05 21 19 p  m" src="https://user-images.githubusercontent.com/80764131/118879129-b5ea5200-b8c6-11eb-89d6-d8987e2effe6.png">

**Comment by victormgomezp** [comment]
genial!!!!!!

pero utilizaría la palabra Remoto en vez de Online, al menos para España.

 *| **Victor M. Gómez P.*
 *|** Country Manager Spain*
 *|** (+34)** 684332581*
 *|* *www.4GeeksAcademy.com <http://www.4geeksacademy.com/>*


* <https://www.facebook.com/4Geeks-Academy-Espa%C3%B1a-101572954626711/>
<https://twitter.com/4geeksacademyes>
<https://www.linkedin.com/company/4geeksacademyes>
<https://www.instagram.com/4geeksacademyes/>*
De conformidad con lo dispuesto en el Reglamento (UE) 2016/679 de 27 de
abril de 2016 (GDPR) y la Ley Orgánica 3/2018, de 5 de diciembre, de
Protección de Datos Personales y garantía de los derechos digitales, le
informamos que los datos personales y dirección de correo
electrónico, recabados del propio interesado o de fuentes públicas, serán
tratados bajo la responsabilidad de 4GEEKS ACADEMY ESPAÑA, S.L. para el
envío de comunicaciones ordinarias así como sobre nuestros productos y
servicios y se conservarán mientras exista un interés mutuo para ello o
subsista la base legitimadora para dicho tratamiento. Los datos no serán
comunicados a terceros, salvo obligación legal. Le informamos que puede
ejercer los derechos de acceso, rectificación, portabilidad y supresión de
sus datos y los de limitación y oposición a su tratamiento dirigiéndose a
C/ Edison, 3, Madrid 28006 (Madrid). Email: ***@***.*** Si
considera que el tratamiento no se ajusta a la normativa vigente, podrá
presentar una reclamación ante la autoridad de control en www.agpd.es.
