### ISSUE TITLE
IMPORTANTE AFECTA A LAS VENTAS: formato de fecha incorrecto

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#1363]
Hrs: <hrs>0.5</hrs>

**Describe the bug**
Este es el formato de fecha americano, debe estar en español. Confunde y la gente no va a entender cuándo es el programa, puede afectar a las ventas

![image](https://user-images.githubusercontent.com/62053368/118869399-a29aaf00-b8e5-11eb-827f-d2fb1066e096.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ArielCalisaya** [comment]
Lo acabo de arreglar, pero ¿y si especificamos al menos la duración del año? algo asi

![maybeThis](https://user-images.githubusercontent.com/51676628/119016838-60668180-b968-11eb-894a-fbc238fceada.png)

De todas formas haré el PR con los cambios esperaados

**Comment by ArielCalisaya** [comment]
Hrs <hrs>0.5<hrs>
>No se contó este PR en el mes de mayo
