### ISSUE TITLE
La palabra Campus no tiene plural Campuses no existe

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#1365]
**Describe the bug**
La palabra campus se escribe en plural igual, Campus, ya que la palabra Campuses, no existe.

![image](https://user-images.githubusercontent.com/62053368/118870303-ae3aa580-b8e6-11eb-9a55-ff0ae27c6eb3.png)

![image](https://user-images.githubusercontent.com/62053368/118870355-beeb1b80-b8e6-11eb-86cf-ecfd08947f5b.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jatv93** [comment]
Lo corregí yo, lo puedes cerrar
