### ISSUE TITLE
This link is not working and image doesn't fit perfect

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#1366]
**Describe the bug**
https://next.4geeksacademy.com/es/empleo-programacion

![image](https://user-images.githubusercontent.com/62053368/118870565-f954b880-b8e6-11eb-95af-f8ee5ae4bb6a.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alesanchezr** [comment]
Como llegaste a esto @victormgomezp ?? donde esta este link?

**Comment by victormgomezp** [comment]
La verdad no tengo mucha idea, no recuerdo.
