### ISSUE TITLE
IMPORTANTE: Faltan muchas imágenes de Madrid esto está muy pobre

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#1374]
**Describe the bug**
![image](https://user-images.githubusercontent.com/62053368/118873087-9d3f6380-b8e9-11eb-9a11-65a23b2c05aa.png)

**To Reproduce**
1. Go to '...'  https://next.4geeksacademy.com/es/coding-campus/bootcamp-programacion-madrid

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alesanchezr** [comment]
pues le pedi a edgar otra foto de madrid porque no se cual poner.

**Comment by victormgomezp** [comment]
@alesanchezr en la galería te puse varias
