### ISSUE TITLE
IMPORTANTE AFECTA VENTAS: Indicar también que estamos en Remoto

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#1375]
Hay que decir si es remoto, en persona y/o hybrid.
![image](https://user-images.githubusercontent.com/62053368/118873220-c3650380-b8e9-11eb-9f6e-22da5b5278d4.png).

**Comment by victormgomezp** [comment]
Lo que indica Andrea Castillo  no me parece nada mal

Para solucionar esto se me ocurre que cambiemos la palabra "Sede" por "Campus y que cuando el usuario busque por ejemplo "Madrid" se especifiqué los que son online como "Madrid/online".


sin embargo yo preferiría utilizar, al menos para España la palabra "REMOTO"

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?node-id=5627%3A3218
