### ISSUE TITLE
Check requisites no indica los requisitos

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#1377]
**Describe the bug**

Debería decir "Tan solo necesitas un ordenador y una conexión a internet"
https://next.4geeksacademy.com/es/coding-bootcamp/full-stack-part-time

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alesanchezr** [comment]
@victormgomezp  No tengo ni idea de que hablas.

**Comment by victormgomezp** [comment]
@alesanchezr 
aquí te dejo la imagen

Dice "Ver requisitos" pero no es un link a los requisitos


![image](https://user-images.githubusercontent.com/62053368/122055560-0af78600-cde9-11eb-88b8-38441fe6140b.png)
