### ISSUE TITLE
IMPORTANTE ERROR ORTOGRAFICO

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#1378]
**Describe the bug**
Buscan no lleva acento en la u

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alesanchezr** [comment]
@victormgomezp No encuentro nigún "Búscan" en la pagina, tal vez ya se corrigió.

**Comment by victormgomezp** [comment]
yo tampoco lo consigo ahora, la próxima vez pongo una foto para asegurarnos :) sorry
