### ISSUE TITLE
IMPORTANTE Texto redundante cuando das a descargar curriculo y teléfono para españa debería ser obligatorio

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#1379]
**Describe the bug**
En 2 min. recibirás en tu buzón de correo un PDF con información muy detallada sobre nuestra metodología, tecnologías, financiación e información del curso.

Debería decir algo como 

En 2 min. recibirás un correo con un PDF que tendrá información muy detallada sobre nuestra metodología, tecnologías, financiación e información general del curso.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alesanchezr** [comment]
no te entendi bien, el texto es casi identico.

Por otro lado, estas pidiendo que pongamos un campo de telefono adicional y que lo hagamos obligatorio?

**Comment by victormgomezp** [comment]
Es un tema de lenguaje.

El teléfono debería ser obligatorio para españa, sí.
