### ISSUE TITLE
Validación de teléfono incorrecta

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#1380]
**Describe the bug**
Los número en españa tienen 9 números y la validación cuenta 8
![image](https://user-images.githubusercontent.com/62053368/118874156-df1cd980-b8ea-11eb-9d68-0c899eb7f50e.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alesanchezr** [comment]
Si el problema es que depende del pais, en otros paises son 8 por eso hay que validar internacional
