### ISSUE TITLE
Website Error: Dates

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/About-4Geeks-Academy#1386]
https://next.4geeksacademy.com/es/inicio?lang=es

![image](https://user-images.githubusercontent.com/48845580/118884826-f34de000-b8c4-11eb-808a-5c80af90eda0.png)

That's not the next cohort, please check because the admin has all the dates correctly

**Comment by alesanchezr** [comment]
Esperando por @Omonroy36 para solucionar esto
