### ISSUE TITLE
Replicate Quiz App

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1398]
Hrs <hrs>10</hrs>

Using [this repository](https://github.com/breatheco-de/assessment) that is based on Next.js, replicate [this functionality](https://assets.breatheco.de/apps/quiz/html) for an application that allows students to quiz themselves.

You should use material design as component framework.

This is the API endpoint to retrieve assessments: `GET https://breathecode.herokuapp.com/v1/assessment/`
You can get the details of one particular assignment with `v1/assessment/<slug>` for example: `v1/assessment/html`

Example steps for the app:

1. The user types on the URL: assessment.breatheco.de/quiz/html
2. Quiz description shows up and button to start the quiz
3. User press start the quiz 
4. First questions displays with possible options to answer (because the question type is either SELECT or MULTISELECT)
5. Compatibility with other types of questions will be added later.
6. The application also starts a timer visible on the screen
7. If the question is type 'SELECT' the student picks one option and the system validates if its correct and displays on the screen the feedback.
8. IF the question is type 'MULTISELECT' the student pick on option but it can also pick many others, a button shows up saying "Send". When the Send button is pressed the user is taken to the next question.
9. At the end of the assessment the student gets a report on the screen saying how many answers were current our of the total and the total time it took him/her to answer.
10. During the entire quiz there is also an indicator with the current question index an the total amount of questions.

**Comment by ArielCalisaya** [comment]
Hrs <hrs>14<hrs>
