### ISSUE TITLE
El buscador del admin no funciona correctamente

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#1406]
**Describe the bug**
Solo busca la primera palabra, cuando hay espacios ya no lo toma en cuenta, por ejemplo el estudiante Felipe Silva solo se encuentra al escribir felipe 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alesanchezr** [comment]
Cerrando esto porque va a ser desarrollado con #1436
