### ISSUE TITLE
Better "like" search operator for first name and last name

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1436]
Hrs: <hrs>5</hrs>

If we are searching for full name using the like operator, for example: `?like=Diana Flores` django right now will not be able to find diana flores because it will not know that `diana` and `flores` are separate words, it will treat them as a whole.

We need to implement a standard util function for searching full names like this:
https://stackoverflow.com/questions/9009635/django-queryset-searching-for-firstname-and-lastname#17361757

We need to apply that function to any full_name search in the API.
- [ ] student (from admissions)
- [ ] staff (from auth)
- [ ] invite (form auth)
- [ ] lead (from the marketing module)
- [ ] answer (from the feedback module)
- [ ] certificate (from certificate module)

**Comment by jagtrrz** [comment]
https://github.com/breatheco-de/apiv2/pull/83
