### ISSUE TITLE
Translate youtube videos

### ISSUE THREAD

**Issue by ElviraQDP** [4GeeksAcademy/About-4Geeks-Academy#1457]
Hernan: https://youtu.be/ln3bQsV1BaQ
Joao: https://www.youtube.com/watch?v=MBXqEnhodx0
Luisa: https://www.youtube.com/watch?v=PWkgaAT8pHg

**Comment by ElviraQDP** [comment]
videos subtitulados @alesanchezr

**Comment by alesanchezr** [comment]
😄
