### ISSUE TITLE
Update Flask Blueprints version to 2.0.0 to get nested blueprints

### ISSUE THREAD

**Issue by marcogonzalo** [4GeeksAcademy/About-4Geeks-Academy#1461]
**Describe the solution you'd like**
Flask Blueprints are in version 2.0.0 now https://flask.palletsprojects.com/en/1.1.x/blueprints/

The new version includes Nested Blueprints: https://flask.palletsprojects.com/en/2.0.x/blueprints/#nesting-blueprints. This could be helpful for creating a more organized RESTful APIs in final projects. Having all the RESTful endpoints grouped by model o functionality, imported in routes.py.

**Comment by JimenaEB** [comment]
I really agree with this!
