### ISSUE TITLE
Unit testing for AcademyAlias

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1465]
- [ ] If there is an incoming marketing lead, its corresponging academy will be obtained by looking for AcademyAlias.activecampaign_slug or Academy.activecampaign_slug

- [ ] When procesing marketing leads (form entries) the AcademyAlias is more important than the academy itself, for example: If a lead is coming with location="locA" and there is a location with active_campaign_slug="locA" but there is another location B with Alias "locA" then the form_entry will be owned by location B.

**Comment by 99lalo** [comment]
https://github.com/breatheco-de/apiv2/pull/111

**Comment by jefer94** [comment]
I was merged this fixture of @99lalo
