### ISSUE TITLE
z-index on financial options

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1466]
The finantial months should not block the dropdown

![Screen Shot 2021-06-08 at 1 54 06 AM](https://user-images.githubusercontent.com/426452/121130548-8ad78c00-c7fc-11eb-899b-f3e9db0b2588.png)

**Comment by ArielCalisaya** [comment]
Hrs <hrs>0.3<hrs>
