### ISSUE TITLE
Seccion: Conoce a tu instructor

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1467]
Debemos agregar esta seccion a la vista de programa, es una seccion opcional que solo aparecera cuando este especificado uno o mas instructores para un curso, puedes revisar figma para obtener mejor las proporciones:

![Screen Shot 2021-06-08 at 1 57 24 AM](https://user-images.githubusercontent.com/426452/121130813-f02b7d00-c7fc-11eb-8e63-5af1c4ed1870.png)

**Comment by ArielCalisaya** [comment]
Hrs <hrs>13..5<hrs>
> Total de horas de componente "conoce a tu instructor" + la correccion de issues que he ido encontrando y mejorando, durante la semana 1ra y 2da semana de Junio
