### ISSUE TITLE
Importante: Logo de partner cortado

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#1468]
**Describe the bug**
El logo del partner está cortado

![image](https://user-images.githubusercontent.com/62053368/121225729-1a774c00-c88a-11eb-9a31-e573d22a6367.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alesanchezr** [comment]
@victormgomezp lo resolvi buscando en internet otra version del logo que es mas horizontal.
