### ISSUE TITLE
URGENTE: Full-time tiene duración e información de part-time

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#1469]
**Describe the bug**
al darle clic a full-time te lleva a https://4geeksacademy.com/es/coding-bootcamps/full-stack-part-time

pero al entrar directamente a https://4geeksacademy.com/es/coding-bootcamps/full-stack-full-time la información es la del part-time (en duración no en precios)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by victormgomezp** [comment]
Si estás en la pagina principal y le das a full time se queda en la pagina principal

**Comment by victormgomezp** [comment]
@alesanchezr me cerraste esta issue pero no está resuelta

![image](https://user-images.githubusercontent.com/62053368/122054671-2f069780-cde8-11eb-99cf-4410ccfd8eb6.png)

**Comment by alesanchezr** [comment]
@ArielCalisaya para saber el nro de semanas en el calendario tendremos que buscar si el certificate incluye `-ft` dentro de su slug.

**Comment by ArielCalisaya** [comment]
Hrs <hrs>1.5<hrs>
