### ISSUE TITLE
When you retry certificates in bulk also remember to update the status to pending in the backend and also in the front end

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1473]
![Screen Shot 2021-06-08 at 5 44 06 PM](https://user-images.githubusercontent.com/426452/121261969-6d98d100-c881-11eb-9d65-301f77fb6efe.png)

**Comment by jagtrrz** [comment]
https://github.com/breatheco-de/admin/pull/80
