### ISSUE TITLE
IMPORTANTE AFECTA VENTAS: Las locaciones generan confusión 

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#1477]
**Describe the bug**
Si lo primero que encuentra un cliente que vive en Barcelona o Valencia, en el DESPLEGABLE DE LOCACIONES, es ONLINE va a darle clic a online y va a ver las próximas fechas de online. Debería decir "Madrid o Online" y lo mismo para todas las locaciones.

![image](https://user-images.githubusercontent.com/62053368/121324878-6e794380-c911-11eb-985b-43ed5c52db4d.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alesanchezr** [comment]
Listo, ninguna dice online ahora. Asi era como estaba planeado.

**Comment by victormgomezp** [comment]
Perfecto, pero ahora habría que poner Madrid, España o Online 
o sencillanente poner España.

@alesanchezr
