### ISSUE TITLE
Las cifras de contratados y graduados no coinciden en inglés y en español

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#1478]
**Describe the bug**
En ingles decimos 86% graduados y 1500 estudiantes
En español decimos 89% graduados y 1100 estudiantes

Tenemos que ser consistentes en la información que damos en la web 

@ElviraQDP sería bueno ver la web tanto en inglés como en español y comprobar este tipo de traducciones. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by victormgomezp** [comment]
@alesanchezr  esta issue no está resuelta 
![image](https://user-images.githubusercontent.com/62053368/122054463-fcf53580-cde7-11eb-8ae1-a50525e5a54d.png)

**Comment by alesanchezr** [comment]
bueno ahora es que veo donde es, porque hice una busqueda de "89" y no salio nada (por alguna razon)... ya lo cambio.

**Comment by victormgomezp** [comment]
Por qué no creamos variables que sea:

alumni
hiring rate
campus

y se utilizan cada vez que queremos llamar a estos datos y así solo se cambia una vez y no estamos mostrando números inconsistentes?
