### ISSUE TITLE
IMPORTANTE: No se sabe que son Part time

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#1479]
**Describe the bug**
No se sabe si estos cursos son part-time, el cliente no sabe que 16 semanas es part-time

![image](https://user-images.githubusercontent.com/62053368/121328261-7686b280-c914-11eb-8fb6-b09839ff4068.png)

Y en estos programas no se sabe nada, es imposible entender si es part-time o full-time solo por ver el tiempo

![image](https://user-images.githubusercontent.com/62053368/121328316-843c3800-c914-11eb-8fd8-675aade84517.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alesanchezr** [comment]
@Andrearcastillo como quieres resolver esto? Le ponemos en parentesis `(part time)` debajo de 16 sem? Mandanos una foto o actualiza el figma.

**Comment by Andrearcastillo** [comment]
El "Part Time" y "Full time" debe ir junto con el nombre del programa, ya que es el link de acceso directo a cada landing del programa. Acá adjunto ejemplo:

<img width="809" alt="Captura de Pantalla 2021-06-10 a la(s) 10 52 56 a  m" src="https://user-images.githubusercontent.com/80764131/121717522-a5895980-cab7-11eb-95fa-b2efe637256e.png">

**Comment by ArielCalisaya** [comment]
Hrs <hrs>1.8<hrs>
