### ISSUE TITLE
Las locations no se ven correctamente en Versión movil 

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#1480]
**Describe the bug**
Se ven mal las ubicaciones en versión movil (Samsung S20 ultra desde Chrome)

![Screenshot1](https://user-images.githubusercontent.com/62053368/121373785-a6977b00-c93f-11eb-91d2-33b616d29aee.jpg)

como se ve en la imagen los cuadros no son del mismo tamaño y están pegados al borde

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ArielCalisaya** [comment]
Hrs <hrs>0.6<hrs>
