### ISSUE TITLE
General Issue - Estilos del Menu

### ISSUE THREAD

**Issue by Andrearcastillo** [4GeeksAcademy/About-4Geeks-Academy#1484]
Se necesita emprolijar los dropdown del menú. 

1. El espacio en blanco que hay debajo de la linea que divide el titulo del dropdown y las secciones debe ser la misma que la del texto superior y la linea. Actualmente tenemos mucho espacio debajo de la linea.
2. Por otro lado, la flechita que indica cuál titulo del menu, se desplego actualmente está defasado. Si clickeas en "Academia", la flechita te sale en próximas fechas. Además ahora no tiene sombra como el resto del componente, debe tener sombra. Como está ahora se ve roto porque no se aprecia la flechita.

Adjunto acá el como se ve ahora.
![12](https://user-images.githubusercontent.com/80764131/121438617-b4a6c500-c95a-11eb-95ab-c5858bd1657b.jpg)

3. El título dentro de los dropdown es decir "Why 4geeks", "Programas", "Nuestros campuses", debe tener la tipografía en bold. 
4. Desarrollar el efecto de hover propuesto en el diseño. Cuando el usuario pasa el cursor sobre la sección debe verse el fondo azul clarito (#e6f5fb) como está en el ejemplo a continuación.
![lala](https://user-images.githubusercontent.com/80764131/121439000-6a721380-c95b-11eb-8d34-946e19485884.jpg)

4. Revisa en el Figma los tamaños de los dropdowns. Algunos quedaron con un componente muy gran y desproporcionado a la información. El dropdown de "Por qué 4geeks" está bien en tamaño pero el de "Academia" quedo muy extendido a lo horizontal.

Ejemplo implementado
<img width="1616" alt="Captura de Pantalla 2021-06-09 a la(s) 05 45 58 p ┬ám" src="https://user-images.githubusercontent.com/80764131/121439368-33e8c880-c95c-11eb-9db1-f1778a9816aa.png">

Diseño propuesta
<img width="964" alt="Captura de Pantalla 2021-06-09 a la(s) 07 35 30 p  m" src="https://user-images.githubusercontent.com/80764131/121439394-3e0ac700-c95c-11eb-9d49-869c952a37f8.png">

Lo mismo para campuses.

**Comment by ArielCalisaya** [comment]
Hrs <hrs>2.5<hrs>
