### ISSUE TITLE
Financiación - Header

### ISSUE THREAD

**Issue by Andrearcastillo** [4GeeksAcademy/About-4Geeks-Academy#1485]
Hay dos puntos a arreglar en el header de la landing de Financiación.

1. El fondo propuesto en el header es diferente al implementado. No tiene los elementos gráficos (circulos, y lineas) sobre el fondo azul claro.
2. Los campos de "campus", "modalidad" y "programa", tienen los textos justificados al centro. Todos los campos deben tener el llenado del campo justificado a la izquierda. 

Actualmente se ve así
<img width="1600" alt="Captura de Pantalla 2021-06-09 a la(s) 05 45 14 p ┬ám" src="https://user-images.githubusercontent.com/80764131/121440624-9e9b0380-c95e-11eb-9177-f80caa62b2fa.png">

Como debería verse
<img width="1009" alt="Captura de Pantalla 2021-06-09 a la(s) 05 45 38 p ┬ám" src="https://user-images.githubusercontent.com/80764131/121440631-a490e480-c95e-11eb-9a04-b60c76d45c31.png">

3. ¿Por que no implementaron el comportamiento de seleccionar los campos y luego clickear en el boton "Buscar" para ver los resultados como estaba propuesta? ¿Hubo otra definición? En el diseño propuesta hay un boton de buscar.

PD: Si necesitas que te envie la imagen en vectores de los elementos del header solo mandame un msj al slack.

**Comment by ArielCalisaya** [comment]
Hrs <hrs>0.8<hrs>
