### ISSUE TITLE
Home - Espaciados del Componentes de Premios

### ISSUE THREAD

**Issue by Andrearcastillo** [4GeeksAcademy/About-4Geeks-Academy#1486]
Podemos mejorar los espaciados del home. Especialmente en el componente de premios y reconocimientos ya que hay espacio hacia arriba con los "contratados" pero abajo el componente está muy pegado de "se parte de la comunidad". De hecho en el diseño en Figma hay una linea fina y clara entre los logos de premios y el otro componente. 

Hagamos que el espacio superior del componente sea el mismo que el espacio inferior. Así está ahora:
<img width="1605" alt="Captura de Pantalla 2021-06-09 a la(s) 05 48 19 p ┬ám" src="https://user-images.githubusercontent.com/80764131/121441009-5defba00-c95f-11eb-99f1-fed889f16ef8.png">

Intentemos mejorar esos espacios para que se vea así (diseño propuesto)
<img width="1061" alt="Captura de Pantalla 2021-06-09 a la(s) 08 16 07 p  m" src="https://user-images.githubusercontent.com/80764131/121441319-f4bc7680-c95f-11eb-8992-dfe27c1f75a4.png">

**Comment by ArielCalisaya** [comment]
Hrs <hrs>0.8<hrs>
