### ISSUE TITLE
General - Componente "Próximas Fechas" Alineaciones

### ISSUE THREAD

**Issue by Andrearcastillo** [4GeeksAcademy/About-4Geeks-Academy#1487]
Algunas filas del componente de "Próximas fechas" están desalineadas del resto. Hay que justificarlas y alinearlas todas.
Este issue se repite en todas las pantallas que tienen este componente.

<img width="1290" alt="Captura de Pantalla 2021-06-09 a la(s) 05 51 20 p ┬ám" src="https://user-images.githubusercontent.com/80764131/121446481-fbe88200-c969-11eb-999d-0694798ee6b2.png">

**Comment by ArielCalisaya** [comment]
Hrs <hrs>0.8<hrs>
