### ISSUE TITLE
Quiénes nosotros y Partnership - Elementos gráficos sobre la imagen

### ISSUE THREAD

**Issue by Andrearcastillo** [4GeeksAcademy/About-4Geeks-Academy#1489]
En las pantallas de "Quienes somos" y "Partnership", la imagen .svg de elementos gráficos (circulos y lineas) debe ir por encima de la imagen full size. Actualmente están por detrás.

Actualmente
<img width="1620" alt="Captura de Pantalla 2021-06-09 a la(s) 05 53 55 p ┬ám" src="https://user-images.githubusercontent.com/80764131/121446917-fb9cb680-c96a-11eb-97b9-d3503160d486.png">

Propuesta
<img width="963" alt="Captura de Pantalla 2021-06-09 a la(s) 09 38 34 p  m" src="https://user-images.githubusercontent.com/80764131/121447008-28e96480-c96b-11eb-8ef4-a58ddc9c95ac.png">

**Comment by ArielCalisaya** [comment]
Hrs <hrs>0.8<hrs>
