### ISSUE TITLE
Componente carousel de partners

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#1492]
<img width="869" alt="Screen Shot 2022-10-27 at 12 14 04 PM" src="https://user-images.githubusercontent.com/426452/198343694-d2df6bc9-6cdb-4316-97be-2a2354cec63d.png">

Incluir una sección de testimoniales de partners con:

- [ ] Opcional: Foto del partner (pequeña para evitar malas resoluciones)
- [ ] Nombre y apellido.
- [ ] (opcional) Linkedin url
- [ ] Nombre de empresa.
- [ ] (opcional) Link a document (pdf or word).
- [ ] Cita del testimoanial (maximo 140 caracteres).
- [ ] (opcional) Link a articulo del blog con el testimonial publicado.

Nota: Asegurar que los opcionales sean opcionales.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?node-id=5691%3A3539

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?node-id=6276%3A6904

**Comment by alesanchezr** [comment]
<img width="495" alt="Screen Shot 2022-11-03 at 12 37 32 PM" src="https://user-images.githubusercontent.com/426452/199780573-4b768aba-165f-48d2-a1ee-8c9768f927c0.png">

**Comment by tommygonzaleza** [comment]
Esta bien pero quizas hay que cambiarle la ubicacion del componente en la pagina

**Comment by tommygonzaleza** [comment]
Add more padding between the dots and the sections below
