### ISSUE TITLE
ERROR ORTOGRÁFICO: Dice EXALUMOS falta una N

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#1499]
Dice exalumos en vez de exalumnos

![image](https://user-images.githubusercontent.com/62053368/121486996-f58df080-c9d1-11eb-9376-0442b13a6dfa.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jatv93** [comment]
Fixed on https://github.com/4GeeksAcademy/website-v2/pull/969 @alesanchezr

**Comment by jatv93** [comment]
@victormgomezp ya puedes cerrar el issue, está listo en la web
