### ISSUE TITLE
ERROR ORTOGRAFICO: sobra una comilla al final de la cita

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#1500]
**Describe the bug**
![image](https://user-images.githubusercontent.com/62053368/121515700-c5ece180-c9ed-11eb-9ccc-ac0e549cae88.png)

tiene dos comillas al final de la cita "La academia estaba tan comprometida como yo"

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jatv93** [comment]
Fixed on https://github.com/4GeeksAcademy/website-v2/pull/969 @alesanchezr
