### ISSUE TITLE
InputGallery adds the URL to the wrong input.

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1508]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-4109-26729-0beddf61804dda2c9daa17aa73af18b9) 

---
**Source URL**:
[https://admin.breatheco.de/events/NewEvent](https://admin.breatheco.de/events/NewEvent)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 90.0.4430.212</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1677x785</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by Omonroy36** [comment]
This is solved
