### ISSUE TITLE
Titulo demasiado grande en móviles, prueba con iphone x en el emulador de chrome

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1514]
Hrs <hrs>0.2<hrs>

![Screen Shot 2021-06-14 at 6 35 24 PM](https://user-images.githubusercontent.com/426452/121967989-6b31ed80-cd3f-11eb-8207-129e2cb26699.png)

**Comment by ArielCalisaya** [comment]
Hrs <hrs>0.2<hrs>
