### ISSUE TITLE
Color bubbles should show up on mobile, but they don't.

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1515]
Original design is shown on the right side of this picture:

![Screen Shot 2021-06-14 at 6 45 50 PM](https://user-images.githubusercontent.com/426452/121968751-e2b44c80-cd40-11eb-9804-390514c96c64.png)

**Comment by ArielCalisaya** [comment]
Hrs <hrs>0.8<hrs>
