### ISSUE TITLE
Botones de redes sociales en thank-you se solapan

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1516]
En la version movil: 

![Screen Shot 2021-06-14 at 7 52 28 PM](https://user-images.githubusercontent.com/426452/121972946-38d9bd80-cd4a-11eb-852d-d2bbbd0e1e13.png)

Despues de que hagan check podemos quitar el titulo de la red social para que le deje espacio al boton, que te parece @Andrearcastillo

**Comment by Andrearcastillo** [comment]
@alesanchezr No me queda claro en qué parte de la web está este componente. Tiene la isual vieja.
