### ISSUE TITLE
Spanish version not available

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/About-4Geeks-Academy#1517]
Is not possible to change the language, the Spanish readme is created https://github.com/breatheco-de/exercise-unit-test-with-jest/blob/main/README.es.md

![image](https://user-images.githubusercontent.com/48845580/122062504-775c9000-cdbd-11eb-932f-8ee5ba7420bc.png)

**Comment by jatv93** [comment]
@ElviraQDP cuando puedas revísalo por fa

**Comment by ElviraQDP** [comment]
lo estamos viendo

**Comment by jatv93** [comment]
Arreglado
