### ISSUE TITLE
Half of the blogposts are gone

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1523]
For some reason there is very little posts in the blog, a lot of [the markdown files](https://github.com/4GeeksAcademy/website-v2/tree/master/src/data/blog) are not showing as blog posts, for example:

https://4geeksacademy.com/us/post/full-stack-web-development-at-miami-dade-college

**Comment by ArielCalisaya** [comment]
Hrs <hrs>2.5<hrs>
