### ISSUE TITLE
Add "scollarships" section to the finantials

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1532]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-4109-26890-2ec62a62bbf0fc9be6efb18b86df323a) 

---
**Source URL**:
[https://4geeksacademy.com/us/financials](https://4geeksacademy.com/us/financials)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 90.0.4430.212</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1919x784</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by Andrearcastillo** [comment]
@alesanchezr Si, perfectamente se pueden agregar los tipos de financiaciones que se necesiten, siempre y cuando se respete el diseño de las cajas que ya existen en la página. Ver siguiente ejemplo:

![Captura de Pantalla 2021-12-02 a la(s) 03 01 09 p  m](https://user-images.githubusercontent.com/80764131/144479558-a33a9062-03ea-4ad9-9972-bac475eed536.png)
