### ISSUE TITLE
Add prettier and linter to admin

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1539]
https://www.inkoop.io/blog/setup-eslint-for-react-with-prettier-pre-commit-and-vscode/

**Comment by ArielCalisaya** [comment]
Hrs <hrs>2.3</hrs>

**Comment by alesanchezr** [comment]
El linter esta funcionando pro con un plugin y no con pre-commit.

Hay que volver a intentar hacer funcionar a husky para que haga prettier y linter al momento de commit.
