### ISSUE TITLE
tutorials

### ISSUE THREAD

**Issue by c0venn** [4GeeksAcademy/About-4Geeks-Academy#1545]
the tutorials for the loops and list are empty, im in 4 geeks academy and i think the tutorial explain more the contents in the academy, thnk u so much :D

**Comment by alesanchezr** [comment]
Hello @c0venn what do you mean "empty"? Here are the tutorials for the loops: 
https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial
