### ISSUE TITLE
Aplica no se usa en españa, cambiar por "Solicita tu plaza ahora"

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#1549]
**Describe the bug**
Se debe cambiar PARA ESPAÑA, no necesariamente para todos los que entren en idioma español:

Aplica por "Solicita tu plaza ahora" 

@Andrearcastillo no sé si tengas que ver cosas de diseño aquí porque la frase será mucho más larga, pero sería importante cambiarlo porque Aplica no se usa en España. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ArielCalisaya** [comment]
Actualmente se trata de queys `yaml` que se dividen en
`navbar.us`: "apply"
`navbar.es`: "aplicar"

mi propuesta es cambiar ~~`aplicar`~~ por `solicitar`.

![Madrid · 4Geeks Academy - 4geeksacademy com](https://user-images.githubusercontent.com/51676628/124305981-d3504400-db33-11eb-9908-9c2a2819fa16.png)

**Comment by victormgomezp** [comment]
@Andrearcastillo qué nos recomiendas aquí.
@ArielCalisaya "solicitar" no dice nada a efectos del usuario, solicitar qué: beca plaza, información? no sería el mejor call to action. la competencia en españa usa "Solicita tu plaza" así que vamos a ver qué nos dice andrea.

**Comment by Andrearcastillo** [comment]
La palabra más utilizada para el CTA principal en bootcamps en España es "Aplicar" o "Aplica ahora". 

"Solicita tu plaza" no creo que aplique mucho para el resto de las versiones en español que son el LATAM. No se si este boton pueden cambiar solamente para usuarios que entren desde España. @ArielCalisaya
