### ISSUE TITLE
Actualizar outcomes de la pagina

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#1561]
Nuestros OUTCOMES están todos desactualizados AFECTA IMAGEN Y VENTAS

Esto hay que cambiarlo tenemos un montón de números y datos que discrepan entre sí.

Hay que poner los datos de la web dinámicos y que cuando se cambie uno se cambie en todos lados.

![image](https://user-images.githubusercontent.com/62053368/123955624-1d0d2300-d9aa-11eb-9beb-fec3fd45a431.png)

https://4geeksacademy.com/us/outcomes

**Comment by alesanchezr** [comment]
Se le pregunto a Marcelo por el nuevo reporte de outcomes, estamos esperando por el para republicar y actualizar la pagina.

**Comment by alesanchezr** [comment]
falta español
