### ISSUE TITLE
Fixes to media gallery

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1563]
Hrs: <hrs>1</hrs>

- [x] Stop event propagation if the media is clicked on the pencil, that way the "select" functionality does not get triggered.
- [x] Update media with redux after new tags are applied to avoid having to do a hard core refresh.
- [ ] #1924

**Comment by Omonroy36** [comment]
Stop event propagation if the media is clicked on the pencil, that way the "select" functionality does not get triggered. - Done
 Update media with redux after new tags are applied to avoid having to do a hard core refresh. - Done
 Add icon to image thumbnails on the gallery that specifies if that image is owned by another academy or is shared with you - Do i have something in the media info that tells me this information or something else must be done?
