### ISSUE TITLE
Wrong photos

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/About-4Geeks-Academy#1567]
The staff photos on the chile website are wrong https://4geeksacademy.com/us/coding-campus/coding-bootcamp-santiago

![image](https://user-images.githubusercontent.com/48845580/124148228-73876980-da5d-11eb-8a2f-2bbd3825fd38.png)

The photos are in the media gallery, please change

**Comment by alesanchezr** [comment]
@jatv93 veo bastantes imagenes en el media gallery, cuales quieres poner aqui? quieres agregar miembros?

**Comment by jatv93** [comment]
@alesanchezr colocar las fotos de todos los que trabajan en Chile, que ninguno aparece ahí

**Comment by alesanchezr** [comment]
Lux, como se estan cargando estas imagenes? Tal vez deberian cargarse solo aquellas personas q trabajen en el session.location primero, y luego el resto (si hay mas slots disponibles).

**Comment by alesanchezr** [comment]
Si el arreglo location en el yml es null, o arreglo vacio (loque se pueda) entonces se muestra en todos los locations. Si en cambio tiene uno o mas locations adentro entonces solo se muestra en esos.
