### ISSUE TITLE
TEST: Scan for relative linkes inside the blog and throw error if they are not poining to a real destination inside pathDictionary.json

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1579]
- [ ] First make sure pathDictionary.json also includes the paths to the blog posts.
- [ ] Then start building your test, and scan for the broken relative links.

https://www.loom.com/share/186811bab100431cae57b4be05af7a8c

**Comment by ArielCalisaya** [comment]
**Idea: create a file called redirectDictionary and compare if it exists in absolute paths in case of finding no similarities with pathDictionary**
