### ISSUE TITLE
Footer - Boton del field para newsletter no tiene icono

### ISSUE THREAD

**Issue by Andrearcastillo** [4GeeksAcademy/About-4Geeks-Academy#1581]
El botón para enviar el newsletter en el footer que originalmente tiene un icono de un avioncito no se está mostrando. Visiblemente algo se rompió. Necesitamos que se muestre el icono.

Actualmente
<img width="1657" alt="Captura de Pantalla 2021-07-12 a la(s) 07 06 44 p  m" src="https://user-images.githubusercontent.com/80764131/125362622-965f2b00-e345-11eb-93d5-8ab09ed85745.png">

**Comment by ArielCalisaya** [comment]
@Andrearcastillo icon fixed!
