### ISSUE TITLE
Add `academy` to the media object, the academy property must return the academy id, not the whole academy object.

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1583]
In the media gallery, the front-end wants to to what academy each image belongs to, we need to include the academy id inside the serializer in the API response.

https://github.com/breatheco-de/apiv2/blob/2198859cd9a6ac8b9cd9865c68d5a6849c1dc211/breathecode/media/serializers.py#L61

**Comment by jefer94** [comment]
Assigned to @brcre001
