### ISSUE TITLE
Include profile avatar and remove github's avatar on serializers

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1595]
The following endpoints must include user.profile.avatar_url, some of the methods should also NOT CONTAIN the github information. The profile avatar will become the defacto standard.

| Method | Profile Avatar | Github |
| -------- | -------- | -------- |
| GET /auth/academy/member | add profile.avatar | remove |
| GET /auth/academy/member/`<id>` | add profile.avatar | keep |
| GET /auth/academy/student | add profile.avatar | remove |
| GET /auth/academy/student/`<id>` | add profile.avatar | keep |
| GET /feedback/academy/answer | add profile.avatar | remove |

**Comment by jefer94** [comment]
PR https://github.com/breatheco-de/apiv2/pull/181
