### ISSUE TITLE
The number of weeks is wrong, full time is 9 weeks

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/About-4Geeks-Academy#1631]
The number of weeks is wrong, full time is 9 weeks 

![image](https://user-images.githubusercontent.com/48845580/127920360-c2d2763a-2fae-46fc-a097-bf8063c3a53a.png)

![image](https://user-images.githubusercontent.com/48845580/127920382-19e2295d-5831-42c0-8140-c8ea56fb5cbc.png)

**Comment by ArielCalisaya** [comment]
This issue has been fixed on the branch `development`
![Upcoming dates, ](https://user-images.githubusercontent.com/51676628/130292365-d4c7d2a8-a8ba-42ae-bdbe-4742c5235337.png)

**Comment by ArielCalisaya** [comment]
### Changes applied
![Upcoming dates,  (1)](https://user-images.githubusercontent.com/51676628/130292568-646b1a93-3550-4ecf-af8c-b39cb79e1ab5.png)
