### ISSUE TITLE
Survey report: how many days ago?

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1685]
Duration: <hrs>1</hrs>

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-4109-28025-bfbd2a6fb482fed31eebee452a95502a) 

 It should say "This survey expired 23 days ago"

---

**Source URL**:
[https://admin.breatheco.de/feedback/surveys/miami-xxvi/44](https://admin.breatheco.de/feedback/surveys/miami-xxvi/44)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 92.0.4515.115</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1966x1012</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@0.8999999761581421x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by ingindIsrael** [comment]
This commit should fix it.

[https://github.com/breatheco-de/admin/commit/4fe29bebf8d4ebed529e060d13023b92986c46ef](https://github.com/breatheco-de/admin/commit/4fe29bebf8d4ebed529e060d13023b92986c46ef)
<img width="1280" alt="Screen Shot 2021-12-29 at 6 36 11 PM" src="https://user-images.githubusercontent.com/19786923/147711011-b781c948-61f9-46a2-a698-9472f4fa90c1.png">

but there is a cypress test (unrelated to this commit) that is failing.

![Screen Shot 2021-12-29 at 6 36 11 PM (2)](https://user-images.githubusercontent.com/19786923/147711034-5c327b2b-5fb7-4b70-b9fa-737496602c2a.png)

**Comment by alesanchezr** [comment]
Duration: <hrs>1</hrs>
