### ISSUE TITLE
<MarkdownParser> component (bc app)

### ISSUE THREAD

**Issue by ArielCalisaya** [4GeeksAcademy/About-4Geeks-Academy#1695]
- [x] Component must have a **source** property that will contain the original markdown text to be interpreted.
- [x] component property `tableOfContents` (boolean) that if true will generate a table of contents in top of the content (check image below) #1967.

### Example Article
- [Read and render md files with next.js and nx](https://blog.nrwl.io/read-and-render-md-files-with-next-js-and-nx-89a85c1d9b44)

### Preview expected and [Example](https://breatheco-de.github.io/react-components/?path=/story/markdownparser--default-configuration) from [Breathecode (react-components)](https://github.com/breatheco-de/react-components/tree/master/src/markdown-parser)
![BreatheCode – mdparser](https://user-images.githubusercontent.com/51676628/131375754-b7da693b-66f9-4c85-84e9-f24ff8ab8414.png)

**Comment by alesanchezr** [comment]
Missing table of content, property boolean that displays a table of contents on the top of the lesson.

**Comment by Omonroy36** [comment]
<hrs>9<hrs>

**Comment by alesanchezr** [comment]
Probe con este lesson y tiene los siguientes errores:
https://content.breatheco.de/en/lesson/what-is-css-learn-css/

- [ ] La tabla de contenidos es una jerarquia, pero la que tu generaste tiene solo un nivel, revisa la lesson original que tiene la tabla de contenidos para que veas la jerarqua que deberia tener.
- [ ] El front-matter no deberia aparecer en el texto.

**Comment by alesanchezr** [comment]
Para una segunda version:
- Syntax highlighting no está funcionando algunas veces, probaste con python y react.js? si pongo ```py o ````python funciona?
- Darle responsibildad a las tablas, que en mobiles puedas hacer horizontal scroll.

**Comment by Omonroy36** [comment]
Solution @alesanchezr  https://github.com/breatheco-de/app/pull/83

**Comment by alesanchezr** [comment]
- [ ] The spacing is not right, make sure to comply with the image.
- [ ] The H3 are not looking right
- [ ] "The live demo" link i
<img width="878" alt="Screen Shot 2022-01-25 at 6 15 00 PM" src="https://user-images.githubusercontent.com/426452/151075602-11dc91ae-6555-4afb-a1c5-6a804b714b46.png">
s way out of line because its being moved down by the other h3 on the menu

**Comment by alesanchezr** [comment]
<hrs>19</hrs>
