### ISSUE TITLE
timeline component (bc app)

### ISSUE THREAD

**Issue by ArielCalisaya** [4GeeksAcademy/About-4Geeks-Academy#1696]
### Previw expected
![BreatheCode – timeline](https://user-images.githubusercontent.com/51676628/131373883-dbd6b0ac-0781-4c62-b307-24c29c59a350.png)

**Comment by alesanchezr** [comment]
This is how it looks on my screen:
![Screen Shot 2021-10-05 at 4 33 41 PM](https://user-images.githubusercontent.com/426452/136098482-c80b5b98-5516-4c28-9f23-48d514011a3b.png)
