### ISSUE TITLE
component teacher sidebar (bc app)

### ISSUE THREAD

**Issue by ArielCalisaya** [4GeeksAcademy/About-4Geeks-Academy#1697]
### Preview expected
![BreatheCode – teacher sidebar](https://user-images.githubusercontent.com/51676628/131370334-e1b6e336-d271-4b1e-9190-98f052b595ca.png)

> Just need to work responsive design, 
> after finish the page test it with `storybook`

**Comment by ingindIsrael** [comment]
Steps to complete the task:
- Watch Storybooks tutorial
- Clone the repo from app (https://github.com/breatheco-de/app)
- Familiarize with it, it uses Chakra UI, ReactRouter and others
- Run Storybook and start building your component as a story

**Comment by Omonroy36** [comment]
<hrs>3<hrs>

**Comment by alesanchezr** [comment]
<hrs>3</hrs>

**Comment by alesanchezr** [comment]
<hrs>3</hrs>
