### ISSUE TITLE
modal for student version when login (bc app)

### ISSUE THREAD

**Issue by ArielCalisaya** [4GeeksAcademy/About-4Geeks-Academy#1699]
### Preview Expected
![BreatheCode Student](https://user-images.githubusercontent.com/51676628/131368515-2a65ed23-511c-4773-a898-0587ed5864ff.png)

**Comment by moldovanjason** [comment]
-Clone the repo for app.breathecode and make sure to run smoothly.
 -Develop this entire view. pixel perfect. (very detailed).
 -This is a new view that I have to create inside the project attach it to the path /choose.
 -This project is using Chakra UI.
