### ISSUE TITLE
el mensaje de error debe ser mas específico

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#1739]
el mensaje de error en el formulario, en la parte del número de teléfono, debería ser más específicos y decir que NO debes colocar espacios. 

En el ejemplo He tapado algunos número pero lo importante de la imagen es que la persona ha puesto ESPACIOS y el formulario solo le dice que está mal pero no por qué.

![image](https://user-images.githubusercontent.com/62053368/133167621-7a4b8b84-e384-4e94-b92d-ab0a58f76cc9.png)

**Comment by alesanchezr** [comment]
ya no se puede poner espacios.
