### ISSUE TITLE
Fix function to replicate same timeslots in all academies

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1745]
If I try to replicate timeslots among all academies I get an error:

![Screen Shot 2021-09-14 at 8 32 59 PM](https://user-images.githubusercontent.com/426452/133351477-a8a1eefa-6106-4775-9a05-0f1f875b1ebe.png)

This is probably because the table certificate does not exist anymore, the function code must be fix to comply with the new database struture.

```
def replicate_in_all(modeladmin, request, queryset):
    cert_timeslot = queryset.all()
    academies = Academy.objects.all()
    for a in academies:
        to_filter = {}
        for c in cert_timeslot:
            # delete all timeslots for that academy and certificate ONLY the first time
            if c.certificate.slug not in to_filter:
                SpecialtyModeTimeSlot.objects.filter(certificate=c.certificate, academy=a).delete()
                to_filter[c.certificate.slug] = True
            # and then re add the timeslots one by one
            new_timeslot = SpecialtyModeTimeSlot(recurrent=c.recurrent,
                                                 starting_at=c.starting_at,
                                                 ending_at=c.ending_at,
                                                 certificate=c.certificate,
                                                 academy=a)
            new_timeslot.save()
```

**Comment by jefer94** [comment]
PR https://github.com/breatheco-de/apiv2/pull/193

**Comment by jefer94** [comment]
This should work
https://github.com/breatheco-de/apiv2/blob/37dee9edddf06082b872cca7b6a563de7d19b326/breathecode/admissions/tests/admin/tests_replicate_in_all.py#L75

https://github.com/breatheco-de/apiv2/blob/37dee9edddf06082b872cca7b6a563de7d19b326/breathecode/admissions/tests/admin/tests_replicate_in_all.py#L99
