### ISSUE TITLE
Broken images on certificate generation landing

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1747]
Here is an example link: https://certificate.breatheco.de/226e720cd2beab2e726ca2c75517f251db186841

Basically the problem is that flaticon is down, its better to use the images from a local source.

![Screen Shot 2021-09-16 at 10 32 04 AM](https://user-images.githubusercontent.com/426452/133631150-334cce84-641a-4635-b453-e58c51cd7d21.png)

**Comment by Omonroy36** [comment]
Solved
