### ISSUE TITLE
There are invalid options in the "schedule" dropdown when editing one cohort

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1749]
Instead of the schedule,s its loading the syllabus in it.

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-4109-28562-c14652ce5cb1150e6f7185a48aaa727c) 

---
**Source URL**:
[https://admin.breatheco.de/admissions/cohorts/delete-me-cohort](https://admin.breatheco.de/admissions/cohorts/delete-me-cohort)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 92.0.4515.115</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1833x895</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@0.8999999761581421x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by jefer94** [comment]
PR https://github.com/breatheco-de/admin/pull/158

**Comment by jefer94** [comment]
PR https://github.com/breatheco-de/admin/pull/160
