### ISSUE TITLE
Cant change cohort current day

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1750]
When I try to change the cohort current day I get an error in the modal "This syllabus has a maximum duration of `null` days".

![Screen Shot 2021-09-16 at 12 56 16 PM](https://user-images.githubusercontent.com/426452/133653940-f7e593e2-41c3-4661-b700-31c54e132e9f.png)

You can replicate the error by choosing the "Additional Actions => change cohort current day" option.

![Screen Shot 2021-09-16 at 12 56 36 PM](https://user-images.githubusercontent.com/426452/133654199-1de49804-473a-4b7f-b3a0-56c9a0107b43.png)

**Comment by jefer94** [comment]
PR https://github.com/breatheco-de/admin/pull/158
