### ISSUE TITLE
The cohort has no certificate

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1753]
The error message is not accurate here:
https://github.com/breatheco-de/apiv2/blob/2d9adda1fbdbdacd866a94fa46168c4f7c3d2d43/breathecode/certificate/actions.py#L50

If should be "The cohort has no schedule assigned, please edit the cohort to specify a schedule"

**Comment by jefer94** [comment]
PR https://github.com/breatheco-de/apiv2/pull/188
