### ISSUE TITLE
General Website - Sustituir Logo 4Geeks Academy del Header y Footer

### ISSUE THREAD

**Issue by Andrearcastillo** [4GeeksAcademy/About-4Geeks-Academy#1756]
Hay que sustituir el logo de 4Geeks Academy al nuevo logo ajustado de todo el website. 

- Menú
- Footer

_Los logos a sustituir van a ser enviados por correo, ya que Github no soporta .svg_

**Comment by alesanchezr** [comment]
Andre, no vamos a usar SVG sino PNG porqe a google no le gusta que usemos SVG.

**Comment by LuxSalgado** [comment]
Hola, cómo podría hacer para recibir el logo que se va a sustituir? @Andrearcastillo 
Mi correo es Luis14salgado@gmail.com

**Comment by Andrearcastillo** [comment]
Adjunto el logo en PNG @alesanchezr @LuxSalgado 

![Logo4GeeksA](https://user-images.githubusercontent.com/80764131/135135108-214b2a20-e0f6-4e1e-b25b-2ecf05d94fd1.png)
