### ISSUE TITLE
As admin I want to be able to update student information without having all details

### ISSUE THREAD

**Issue by ColbyWTaylor** [4GeeksAcademy/About-4Geeks-Academy#1775]
IE: https://admin.breatheco.de/admissions/students/2708

I cannot add a phone number without the address. I don't have the address, and cannot modify without both.

**Comment by alesanchezr** [comment]
I prefer if we force ourselves to have this info. How is admissions able to avoid this?

**Comment by ColbyWTaylor** [comment]
This is preventing me from updating a profile. If a student has no address and no phone number, then I try to add the phone number, it is requiring I also add what I don't have.

If it gets entered initially that wouldn't be an issue at all, but only being able to pass with all the information when it is not all available is leaving us with either less complete profiles or false information. We should be able to add with what is available for the most accurate profile, not all or nothing. This also means if an address (which is not required when entering, see below...) if I need to make an update to the information that is there, I can not 😢

![image](https://user-images.githubusercontent.com/16373392/134587036-6c9e3f87-6af5-4335-9328-2ad9ce0a0f39.png)

**Comment by alesanchezr** [comment]
Students should be added by admissions team (marcelo or manuel) and they need to specify all data. Lets just talk to them and avoid this issue in the future

With current students I gues you will have to ask the student directly.

**Comment by ColbyWTaylor** [comment]
Then maybe require that field when they are being added?
