### ISSUE TITLE
As an admin I want to be able to add a new student to both prework and the class they are signing up for

### ISSUE THREAD

**Issue by ColbyWTaylor** [4GeeksAcademy/About-4Geeks-Academy#1776]
Currently can only add to one cohort to begin with, which is always "prework". It would be more efficient to be able to add to the cohort they are intended to be a part of at the same time.

Additionally, it would be best to edit a student profile before they have confirmed access to breathecode. This way the process is not held up or determined solely when they are added.

**Comment by alesanchezr** [comment]
The problem is that the Profile is not created until it accepts the invite 😢

**Comment by ColbyWTaylor** [comment]
How are they added to prework then, by default it is for everyone?

And how about for an invite, which will be either accepted or not, is allowed a field to automatically tie in to a cohort that gets triggered to update when confirmed?
