### ISSUE TITLE
Small changes to the cohort details view

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1786]
<hrs>2</hrs>

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-4109-28683-b7cf96d09cafb922f23bf8955c44d973) 

---
**Source URL**:
[https://admin.breatheco.de/admissions/cohorts/miami-xxvi](https://admin.breatheco.de/admissions/cohorts/miami-xxvi)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 92.0.4515.115</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>2132x815</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@0.8999999761581421x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by ingindIsrael** [comment]
This commit reorders the list of students as requested and displays the number of individuals in the list. [https://github.com/breatheco-de/admin/commit/e5dc85d1f38a38c5d33f3abb8e7b39086235b745](https://github.com/breatheco-de/admin/commit/e5dc85d1f38a38c5d33f3abb8e7b39086235b745)
