### ISSUE TITLE
Functionality - after login, student can choose program provided from the session account

### ISSUE THREAD

**Issue by ArielCalisaya** [4GeeksAcademy/About-4Geeks-Academy#1805]
Example page [learn.breatheco.de/choose](https://learn.breatheco.de/choose) 
Origin Repository [#student-client - choose view](https://github.com/breatheco-de/student-client/blob/master/src/js/views/ChooseView.js)

### Example: programs provided from session account
![account data response](https://user-images.githubusercontent.com/51676628/135175796-e9d983c1-aae9-4df5-a106-36dd6fa8b9c2.png)

**Comment by alesanchezr** [comment]
repeated with #1917
