### ISSUE TITLE
Code: Learn in Public

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/About-4Geeks-Academy#1807]
The Spanish version doesn't have the same information that the English version. In the Spanish version, the video (Here is a 12min video explaining pull requests.) doesn't exist. Please check the Readme

https://github.com/4GeeksAcademy/learn-in-public

@ElviraQDP

**Comment by ElviraQDP** [comment]
https://github.com/4GeeksAcademy/learn-in-public/pull/63

**Comment by jatv93** [comment]
Como van con esto? @alesanchezr @ElviraQDP

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/learn-in-public/pull/95
