### ISSUE TITLE
Code: Sorting Cards using the selection algorithm

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/About-4Geeks-Academy#1808]
The GIF is not loading in both versions (Spanish and English) on breathe code 

![image](https://user-images.githubusercontent.com/48845580/135185853-e237c41f-7aa4-4b72-91ad-582d6107b8f2.png)

The code: https://github.com/breatheco-de/exercise-sorting-cards-with-select

@ElviraQDP

**Comment by jatv93** [comment]
Revisaron esto? @ElviraQDP @alesanchezr

**Comment by alesanchezr** [comment]
cerrando esto porque va a ser solucionado en la nueva version q sale el prox mess.
