### ISSUE TITLE
Code: React TODO application

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/About-4Geeks-Academy#1810]
The Spanish version cannot be selected from breathe code

This is the exercise: https://github.com/breatheco-de/exercise-todo-list. The problem is only that is not shown on the platform because Readme.es.md exists in the repository

![image](https://user-images.githubusercontent.com/48845580/135186597-67e4b763-e878-4bde-a5f9-d9ceac2961dc.png)

@ElviraQDP

**Comment by jatv93** [comment]
@alesanchezr esto parece ser un bug que está afectando varios codes, puedes revisarlo?

**Comment by alesanchezr** [comment]
cerrando esto porque va a ser solucionado en la nueva version q sale el prox mess.
