### ISSUE TITLE
Code: Todo List API in Python Flask

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/About-4Geeks-Academy#1814]
The Spanish version cannot be selected from breathe code

This is the exercise: https://github.com/breatheco-de/python-flask-api-tutorial. The problem is only that is not shown on the platform because Readme.es.md exists in the repository

![image](https://user-images.githubusercontent.com/48845580/135187013-9aa29de3-2f1f-4a16-8804-278fba40d97f.png)

@ElviraQDP

**Comment by jatv93** [comment]
@ElviraQDP @alesanchezr vieron esto?

**Comment by ElviraQDP** [comment]
ya lo veo
