### ISSUE TITLE
Code: StarWars Blog API

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/About-4Geeks-Academy#1815]
The Spanish version cannot be selected from breathe code

This is the exercise: https://github.com/breatheco-de/exercise-starwars-blog-api The problem is only that is not shown on the platform because Readme.es.md exists in the repository

![image](https://user-images.githubusercontent.com/48845580/135187509-55e9f0fc-de4c-4e89-bf55-880cc59a888d.png)

@ElviraQDP

**Comment by jatv93** [comment]
@alesanchezr esto me parece que es un bug, hay varios codes así, puedes revisarlo?

**Comment by alesanchezr** [comment]
cerrando esto porque va a ser solucionado en la nueva version q sale el prox mess.
