### ISSUE TITLE
Code: JWT Authentication With Flask & React.js

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/About-4Geeks-Academy#1816]
The Spanish version is not available and the repository doesn't have the readme.es.md

This is the exercise: https://github.com/breatheco-de/jwt-authentication-with-flask-react

![image](https://user-images.githubusercontent.com/48845580/135187630-dee5fffe-c6b0-46c0-80bf-d1ee251935f8.png)

@ElviraQDP

**Comment by ElviraQDP** [comment]
https://github.com/breatheco-de/jwt-authentication-with-flask-react/pull/1

**Comment by jatv93** [comment]
Cuando va a estar listo esto?  @ElviraQDP @alesanchezr

**Comment by jatv93** [comment]
Done
