### ISSUE TITLE
Code: Full-Stack Final Project

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/About-4Geeks-Academy#1817]
The Spanish version is not available and the repository doesn't have the readme.es.md

This is the exercise: https://github.com/4GeeksAcademy/final-project-full-stack

![image](https://user-images.githubusercontent.com/48845580/135187827-1afd7dd4-0f42-48c6-9692-c22856533895.png)

@ElviraQDP

**Comment by ElviraQDP** [comment]
https://github.com/4GeeksAcademy/final-project-full-stack/pull/2
