### ISSUE TITLE
Two new inputs to the cohort creation and update form

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1834]
- [ ] The form for creating a cohort should contain a Live meeting URL (optional) and a dropdown to pick timezone that loads as default with the front-end current timezone.
- [ ] The form for updating a cohort should contain a Live meeting URL (optional) and a dropdown to pick timezone.

You can fetch a list of all the possible timezones using `GET /v1/admissions/catalog/timezones`

**Comment by ingindIsrael** [comment]
This issue was merge here: [https://github.com/breatheco-de/admin/commit/1ff3797a53d2deecb1d600b537b8da357cd12f6a](https://github.com/breatheco-de/admin/commit/1ff3797a53d2deecb1d600b537b8da357cd12f6a)
