### ISSUE TITLE
Imposible to clear certificate search keyword

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1835]
### Steps to reproduce 

1. Browse to: https://dev.admin.breatheco.de/certificates?limit=10&offset=0&like=miami
2. Try to clear the search

### Expected

It should clear the input and display the whole list of results again and update the URL.

![Screen Shot 2021-10-05 at 3 58 20 PM](https://user-images.githubusercontent.com/426452/136093981-92d41cd8-4040-4311-a59a-413a92359466.png)

**Comment by ingindIsrael** [comment]
This issue was merge here: breatheco-de/admin@1ff3797

**Comment by alesanchezr** [comment]
This is not working, when I click on the X mark it needs to clear the search and show the entire list again.
