### ISSUE TITLE
Wrong Date on the Website

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/About-4Geeks-Academy#1836]
**Describe the bug**
The date that is shown on the website 

**To Reproduce**
1. Go to https://4geeksacademy.com/es/coding-campus/bootcamp-programacion-santiago
2. Click on Spanish Version (In both versions is the same mistake)
3. Scroll down to Next Dates

**Expected behavior**
The date must be the same everywhere, because is the date on breathecode and in the syllabus 

**Screenshots**
Wrong Date 
![image](https://user-images.githubusercontent.com/48845580/136204840-df48671f-3991-4e9d-8587-9d0539fad778.png)

Right Date
![image](https://user-images.githubusercontent.com/48845580/136204916-6d0b990e-4784-4d27-b06a-9f9b121bc5bd.png)

**Comment by alesanchezr** [comment]
Lets review this on the next iteration for november.
