### ISSUE TITLE
Test for marketing.downloadables

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1854]
A marketing downloadable is a file that can be downloaded from the 4geeks website, it first has to be uploaded to breathe code so that the website can refer to it. Here is an example of a [Python Guide Downloadable](https://4geeksacademy.com/us/downloadable/example-downloadable).

- GET all downloadables: /marketing/downloadable
- GET single downloadable /marketing/downloadable/<slug> 
- Redirect to single downloadable, same as above but add the`?raw=true`, you should be redirected to de downloadable.destination_url
- Update the `POST /marketing/lead` test to make sure that the `current_download` field is being property sent to activecampaign like all the other fields.

**Comment by jefer94** [comment]
@alesanchezr the `current_download` is passed to `create_contact` of ActiveCampaign?

**Comment by alesanchezr** [comment]
@jefer94 recuerda revisar esto.

**Comment by brcre001** [comment]
Pull request just merged
