### ISSUE TITLE
Cohort Visibilty for Started Cohorts Only

### ISSUE THREAD

**Issue by ColbyWTaylor** [4GeeksAcademy/About-4Geeks-Academy#1857]
In https://learn.breatheco.de/choose, if the cohort date has not started, the cohort should not display. This is to help remove any stress about the upcoming cohort.

**Comment by alesanchezr** [comment]
We can do this by reviewing the cohort.stage when looping all the cohorts, we can display only the ones "ACTIVE", "ENDED" or "FINAL_PROJECT"

Here is the choose.js where the cohorts are being rendered, just filter that array before mapping it:
https://github.com/breatheco-de/student-client/blob/master/src/js/views/ChooseView.js#L34
