### ISSUE TITLE
New Student Information Submission

### ISSUE THREAD

**Issue by ColbyWTaylor** [4GeeksAcademy/About-4Geeks-Academy#1864]
When a new student is being added, I want to be able to make a "mistake" with the phone number input field and not have it force me out completely. Currently if a number is added in the format of XXX-XXX-XXXX it will return to the students list, and removes all the information previously entered. It should simply either:
provide a warning there is an issue with the formatting, or preferably, just replace non-numerical values with "" to strip it (something like **number.replace(/[^\d]/g, '')**)

**Comment by ingindIsrael** [comment]
This issue should be resolved here [https://github.com/breatheco-de/admin/pull/194](https://github.com/breatheco-de/admin/pull/194)
