### ISSUE TITLE
Student Profile Redundant Information

### ISSUE THREAD

**Issue by ColbyWTaylor** [4GeeksAcademy/About-4Geeks-Academy#1870]
On this student profile page (https://admin.breatheco.de/admissions/students/XXXX), within the "Additional Actions" component, the "Open Student Information" redundant because it is one the same page.

As an admin (and for future admins), relocating the other "Additional Actions" options makes better UI sense on the left hand side with the profile information, or moving that entire "Additional Actions" component to inside of the profile information and removing redundant options. I prefer to be able to click and edit directly.

![image](https://user-images.githubusercontent.com/16373392/137187982-10353f64-02dd-4f97-b1bd-635321b221eb.png)

**Comment by alesanchezr** [comment]
Actually that “student peofile” will be another page with very detailed info about the student performance, its just not ready yet.
