### ISSUE TITLE
Implement login/signup functionality

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1880]
<hrs>11</hrs>

This functionality will be peer-programed between jason and orlando.

- [x] Use the useTost hook for displaying the alert error.
- [x] Also display the error on theform (inline).
- [x] Make sure the button to login disables and says "loading" while login (impossible to click again).
- [ ] Make sure to redirect to dashboard after login.
- [x] Use redux to interact with the backend.
- [x] All breathecode API calls should be wrapped on a single file.
- [x] Create hook for useSession that retrives the session to any view but also syncs with localStorage when the website re-loads.
- [x] Use the services from the current API, copy from the network tab on learn.breatheoc.de
- [ ] Redirect to choose_program after login.

**Comment by alesanchezr** [comment]
The redirection is broken, only redirect if I'm trying to see any of the `/course` sub-paths.

**Comment by Omonroy36** [comment]
https://github.com/breatheco-de/app/pull/76 This pull request solves the issue that ocurred when trying to acces another route and it redirects to choose only when active_cohort is missing.

**Comment by Omonroy36** [comment]
<hrs>11<hrs>

**Comment by alesanchezr** [comment]
<hrs>11<hrs>

**Comment by alesanchezr** [comment]
<hrs>11<hrs>
