### ISSUE TITLE
You should not be able to approve tasks that have not been yet delivered by the student.

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1912]
In the breathecode.assignments API the `Task` model has two different status: [Task.task_status and Task.revision_status.](https://github.com/breatheco-de/apiv2/blob/master/breathecode/assignments/models.py#L42).

Right now, teachers are approving student tasks even if they don't deliver them, and that is obviously wrong. Teachers should only be able to approve delivered tasks.

We can fix that in this [serializer that takes care of updating a task](https://github.com/breatheco-de/apiv2/blob/master/breathecode/assignments/serializers.py#L94).

We should add a condition to ask for that particular scenario, and trigger a ValidationExecption if true.

Her is a video explanation:
https://www.loom.com/share/a271692899a444a0a41aaf4c2cf50f53

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/282
