### ISSUE TITLE
Changes to new syllabus mode implementation

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1921]
- [ ] Back: There is no need to have a `SpecialtyMode.slug`, let's use the ids instead.
- [ ] Front: The timeslot does not have a slug, remove it from the form.
- [ ] Front: Don't use browser timeozne, the timezone information must come from the Cohort.timezone or Academy.timezone.
- [ ] Front: Migrate from moment.js to datejs, [here is an example](https://github.com/breatheco-de/admin/blob/8140cd24a1bd61bf1406e20a8018ff35709bdf66/src/app/views/events/forms/EventForm.jsx#L61).
- [ ] Front: When new timeslot is added, the schedule should update without need for refreshing.
- [ ] Front: Use `<MediaInput>` for banner URL. [Here is an example.](https://github.com/breatheco-de/admin/blob/8140cd24a1bd61bf1406e20a8018ff35709bdf66/src/app/views/events/forms/EventForm.jsx#L163)
- [ ] Front: If a syllabus is private, a alert waning must show like this:
![Screen Shot 2021-11-05 at 3 24 42 PM](https://user-images.githubusercontent.com/426452/140567343-57882ba6-4c6e-454f-bd14-38bdb5936082.png)
- [ ]

**Comment by jefer94** [comment]
* [ ] Back: There is no need to have a SpecialtyMode.slug, let's use the ids instead.
* [ ] Front: The timeslot does not have a slug, remove it from the form.
* [ ] Front: Don't use browser timeozne, the timezone information must come from the Cohort.timezone or Academy.timezone.
* [ ] Front: Migrate from moment.js to datejs, here is an example.
* [ ] Front: When new timeslot is added, the schedule should update without need for refreshing.
* [ ] Front: Use <MediaInput> for banner URL. Here is an example.
* [ ] Front: If a syllabus is private, a alert waning must show like this:
* [ ]

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/218

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/220

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/221
