### ISSUE TITLE
Website - Partners Page Redesign

### ISSUE THREAD

**Issue by Andrearcastillo** [4GeeksAcademy/About-4Geeks-Academy#1944]
Surgió la necesidad de re diseñar la landing de Partnerships, ya que necesitamos mostrar más información al respecto. Adjunto el link de Figma con la nueva Landing a ver diseñada.

https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?node-id=4437%3A2492

Es super importante que los logotipos de partners no se repitan, los que encontrarás en el diseño son netamente referencial pero los logos a sustituir estan en la siguiente carpeta: https://drive.google.com/drive/u/2/folders/1OXNbDHMpZrdp2lEgaMhUg7osYeFj17SG

Cuando esté listo el desarrollo de la landing, por favor compartan el link conmigo para revisarlo y validarlo antes de colocarla al aire.

Imagen de la nueva Landing

![Partnership](https://user-images.githubusercontent.com/80764131/141849484-556f4455-3447-448a-ae16-f7fa35db7d22.jpg)

**Comment by ArielCalisaya** [comment]
New Partners Page (not a landing)

**Comment by Andrearcastillo** [comment]
En la sección de _Become part of our Partnership Network_. Podemos ajustar un poco mas los espaciados entre los datos para que no quede tanto espacio vacio abajo en la caja amarilla?

![image](https://user-images.githubusercontent.com/80764131/146815082-0877bc55-83b8-47af-ad66-a3012cdcde0b.png)

**Comment by Andrearcastillo** [comment]
@ArielCalisaya Por otro lado, los iconos de los partners se ven muy pixelados, hay que re ver eso

**Comment by alesanchezr** [comment]
No se puede porque varia mucho entre dispositivos.
