### ISSUE TITLE
Coding Course Landing - Miami

### ISSUE THREAD

**Issue by Andrearcastillo** [4GeeksAcademy/About-4Geeks-Academy#1945]
Necesitamos rediseñar la landing de Coding Course no solo en cuanto a visual sino también en cuanto estructura. La propuesta está en el siguiente link de FIGMA.

Figma: https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?node-id=4143%3A2616

La idea es poder ver con estos ajustes cómo se re organizan las demás landings, entendiendo que los componentes son compartidos.

Imagen de la propuesta
![Landing - Ejemplo General de Un programa en particular](https://user-images.githubusercontent.com/80764131/141852136-81ab5056-1d78-4d4c-9546-634df1f36a11.jpg)

**Comment by alesanchezr** [comment]
Several bugs were reported that you can fix right now.

Still, meet with andrea on Wednesday to get her feedback.

**Comment by Andrearcastillo** [comment]
@ArielCalisaya  Estuve revisando la landing desarrollada en: https://dev.4geeksacademy.com/us/landing/coding-course

Y tengo dos comentarios al respecto:

1. En el header, el texto que tiene bullets tiene una sombra. Hay que eliminarla.
![image](https://user-images.githubusercontent.com/80764131/146808510-cd6d1516-90b5-48ec-a449-3251254c9574.png)

2. En el componente de Proyectos, falta el título y el texto introductorio. 
![image](https://user-images.githubusercontent.com/80764131/146808595-46f1b9b7-daf2-42ee-892c-15969eb463a7.png)

Diseño
![image](https://user-images.githubusercontent.com/80764131/146808653-db705599-e5cc-4a80-b1ac-3b6e723c1ac7.png)

**Comment by alesanchezr** [comment]
Faltan lso comentarios de andrea, revisa el comentario anterior.
