### ISSUE TITLE
🤯 Create a preloader screen that renders until the page fetch the session page

### ISSUE THREAD

**Issue by ArielCalisaya** [4GeeksAcademy/About-4Geeks-Academy#1949]
Expect to render in `_app.jsx`, inside `<ChakraProvider>`

>This feature will avoid noticing the sudden change of `src/common/context/PrivateRouteWrapper.jsx` that redirects to the >login page until it finds the user session

More info:

___

- [Example preloader in nextjs (hardcoded)](https://dev.to/seven/how-to-create-a-preloader-in-nextjs-15n8)
![Preloader example](https://res.cloudinary.com/practicaldev/image/fetch/s--3N8mrZ6u--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_66%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/b42dd2hwzen23ycjl353.gif)
)

**Comment by alesanchezr** [comment]
Lets make it similar to admin.breathecode.

Here is the logic for it:
https://github.com/breatheco-de/admin/blob/master/src/matx/components/MatxGlobalLoading/MatxGlobalLoading.jsx

**Comment by Omonroy36** [comment]
<hrs>2</hrs>

**Comment by alesanchezr** [comment]
<hrs>2</hrs>
