### ISSUE TITLE
4Geeks Platform - Menu

### ISSUE THREAD

**Issue by Andrearcastillo** [4GeeksAcademy/About-4Geeks-Academy#1957]
El menú que se ve actualmente (app.dev) en las pantallas externas (cuando el usuario no esta logueado) es el menu que propuse cuando el usuario se loguea. No son iguales. Debemos desarrollar el menu de las pantallas externas, además de actualizar en nuevo logo, etc.

Actual
![Captura de Pantalla 2021-11-18 a la(s) 12 02 10 p  m](https://user-images.githubusercontent.com/80764131/142464050-20010f6b-3f0d-435d-84f8-6541049dd74a.png)

Propuesta
<img width="847" alt="Captura de Pantalla 2021-11-18 a la(s) 02 11 29 p  m" src="https://user-images.githubusercontent.com/80764131/142464511-3761524a-5b2d-4064-a607-4b110a41ccae.png">

**Comment by Omonroy36** [comment]
These changes have been solved, logo have change to match proposal and height have been lowered down, now when the user is not logged in the toggle theme is not showing

**Comment by Omonroy36** [comment]
<hrs>0.5</hrs>

**Comment by alesanchezr** [comment]
<hrs>0.5</hrs>
