### ISSUE TITLE
4Geeks Platform - Error en campo de email

### ISSUE THREAD

**Issue by Andrearcastillo** [4GeeksAcademy/About-4Geeks-Academy#1958]
En el nuevo BreatheCode, en el home cuando el usuario clickea el campo email, hay un par de issues que hay que solucionar.

1. Si el usuario clickea el campo y no ha escrito nada pero tampoco ha clickeado el boton de "Join the waiting list", se muestra un error. Esto no debe funcionar así, le estamos señalando un error cuando el usuario no ha intentado hacer nada. El error solo debe mostrarse cuando el usuario haya escrito un email que no cumple con la estructura de email (@ y .com) y que haya apretado el CTA (boton). 

2. En caso de que el usuario haya apretado el CTA sin haber introducido un email correctamente. El Error de Email is required, no se debe mostrar como label superior encima del campo, debe mostrarse debajo. Por favor ver los estilos de los campos en la Page de UI KIT - Assets del Figma del proyecto.

![Captura de Pantalla 2021-11-18 a la(s) 12 01 22 p  m](https://user-images.githubusercontent.com/80764131/142464860-bbdea0b0-115a-4e1b-9312-8a0785d1055a.png)

<img width="392" alt="Captura de Pantalla 2021-11-18 a la(s) 02 26 01 p  m" src="https://user-images.githubusercontent.com/80764131/142465819-09d8e02e-4ef3-4d20-b406-779cc56fc60f.png">

**Comment by Omonroy36** [comment]
The form error is now showing in the bottom and occurs only when the user puts a wrong email or is missing in the field

**Comment by Omonroy36** [comment]
<hrs>0.3</hrs>

**Comment by Andrearcastillo** [comment]
@Omonroy36  In which link can I check this adjustment? I can't see this adjustment reflected in https://app.dev.breatheco.de/

**Comment by alesanchezr** [comment]
revisar posicion del error
<img width="607" alt="Screen Shot 2022-02-22 at 4 47 43 PM" src="https://user-images.githubusercontent.com/426452/155225215-ae4ab9a1-5a76-4aa4-ab3e-c4c284f65263.png">
