### ISSUE TITLE
4Geeks Platform - Detalles de Practice/Build

### ISSUE THREAD

**Issue by Andrearcastillo** [4GeeksAcademy/About-4Geeks-Academy#1959]
Hay dos detalles a mejorar en las pantallas que son el Detalle de una Practice o de una Build.

1. En algunas pantallas la imagen relacionada no se adapta 100% a la grilla del contenido (no pasa en todos los casos). 
2 El componente de Goals que está siempre a la derecha, tiene la linea inferior alineada con los contenidos de la izquierda. El componente debe terminar cuando terminan los datos. Actualmente queda con un espacio innecesario.

ACTUAL
![Captura de Pantalla 2021-11-18 a la(s) 12 57 22 p  m](https://user-images.githubusercontent.com/80764131/142470749-5eba122b-a3fb-4b16-bbca-557128e82c1b.png)

DISEÑO
<img width="998" alt="Captura de Pantalla 2021-11-18 a la(s) 03 07 33 p  m" src="https://user-images.githubusercontent.com/80764131/142472356-25ab5f8a-e603-4721-93b0-031cd44f7d26.png">

**Comment by Omonroy36** [comment]
I made a little change to center the elements

**Comment by Omonroy36** [comment]
<hrs>0.5</hrs>
