### ISSUE TITLE
MarkdownParser does not receive storybook content

### ISSUE THREAD

**Issue by ArielCalisaya** [4GeeksAcademy/About-4Geeks-Academy#1967]
### The component is expected to be able to receive any text and render with storybook

![Components _ Mar](https://user-images.githubusercontent.com/51676628/143138860-cfd4b121-b29a-4413-b04f-6707b76a8cf5.png)

**Comment by Omonroy36** [comment]
https://github.com/breatheco-de/app/pull/76 This PR solve this
