### ISSUE TITLE
Componente "Elige Tu Programa" - Versión Responsive

### ISSUE THREAD

**Issue by Andrearcastillo** [4GeeksAcademy/About-4Geeks-Academy#1974]
Podemos reducir un poco la altura y mejorar la apariencia del componente de "Elige tu Programa" en la versión responsive del Website.

A continuación muestro el ejemplo actual y la propuesta a mejorar. El diseño propuesto está en el siguiente link de Figma: 
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?node-id=103%3A10873

ACTUAL
![image](https://user-images.githubusercontent.com/80764131/143597144-a32e458e-1556-48e2-b47f-bfee2d33315b.png)

PROPUESTA
![image](https://user-images.githubusercontent.com/80764131/143597186-628461e6-abc1-4a1c-b3bf-f5a72ae1c508.png)

**Comment by alesanchezr** [comment]
no lo veo, seguro lo temrinaste?

**Comment by Andrearcastillo** [comment]
@ArielCalisaya Esta Ok. Sugiero un pequeño ajuste ya que las alturas del componente no quedaron como el diseño. 

Ajustemos la altura de la caja, dejando el mismo padding inferior que el superior. Y que el icono quede exactamente en la mistad de la caja. Ejemplo:

![image](https://user-images.githubusercontent.com/80764131/146812424-8d6bbe50-7d01-4b2d-9f81-cf2b855146cf.png)

**Comment by alesanchezr** [comment]
todavia pendiente.
