### ISSUE TITLE
Refactor  sync_with_eventbrite signal

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1981]
https://github.com/breatheco-de/apiv2/blob/6f00c267b91f0de11460e816f545d84048056a83/breathecode/events/receivers.py#L15

- [ ] Rename signal `sync_with_eventbrite` to a more generic `event_saved`
- [ ] I would do the logic the other way around to allow multiple future side effects on the event_saved:

```py
# @receiver(post_save, sender=Event)
@receiver(event_saved, sender=Event)
def post_save_event(sender, instance: Event, **kwargs):
    logger.debug('Procesing event save')
    if instance.sync_with_eventbrite  and instance.eventbrite_sync_status == 'PENDING':
           async_export_event_to_eventbrite.delay(instance.id)
```

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/blob/development/breathecode/events/receivers.py#L11
