### ISSUE TITLE
Add cohort_created to breathecode.admissions.signals and update tes cohort tagging functionality 

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#1989]
Create new signal admissions.signals.cohort_created and recieve it on the marketing.receivers to create a new tag in active campaign when the cohort is created

- [ ] Add the new signal in admissions.signals
- [ ] Trigger the signal from the Cohort model (on save) but only when it is created.
- [ ] Receive the signal from marketing.receivers and call a delayed task 
- [ ] The delayed task on marketing.task is to create a new tag on active campaign with the cohort slug
- [ ] Make sure the tag is also added into the marketing.models.Tag and its associated with its corresponding the ActiveCampaignAcademy
- [ ] Test the whole funcionality
- [ ] Add a bulk action on cohort called "Add tag to active campaign".
- [ ] Also test that when a student is added to a cohort (as active) the cohort tag is applied on active campaign.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/270
