### ISSUE TITLE
I can't change cohort from assignments view

### ISSUE THREAD

**Issue by marcogonzalo** [4GeeksAcademy/About-4Geeks-Academy#1997]
The option for changing cohort from assignments view shows an empty dropdown and it doesn`t show results on search.
![Screenshot 2021-12-06 at 12-32-17 Teachers - BreatheCo de Platform](https://user-images.githubusercontent.com/410890/144839065-64652834-7430-457f-8931-bce17770b0c1.png)

**Comment by alesanchezr** [comment]
I can't replicate, can you share your URL by the time you are doing that?
Also the console inspector output please.
