### ISSUE TITLE
When an event is published on eventbrite it should also be marked as published on breathecode

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2008]
- [ ] Events created on breathecode a created on eventbrite as draft
- [ ] The event status on breathecode also remains as draft.
- [ ] When the event is finally published on eventbrite the status it should be updated on breathecode
- [ ] Reminder script to publish draft events (monitoring app).

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/323

**Comment by alesanchezr** [comment]
- [ ] The moniting script has to be per academy, make sure to filter the events by academy.
- [ ] Everything that says `draw` should be renamed to `draft`
