### ISSUE TITLE
Refactor breathecode.authenticate.models.Token class for more friendly usage

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2035]
Notice: we have to keep compatibility wit the old get_or_create method.

Methods:

### Token.get_or_create(user, type=['one_time', 'temporal', 'permanent'])

Type is mandatory and it has to be one of:
```
One time: this is a token that will be deleted after the first use.
Temporal: will be deleted after a specific time.
Permanent: will always exist, it doe snot expire.
```
It will look for tokens of the same given `type` and find the first valid match, if nothing is found it will created.
If the token type is `one_time` it will always create a new token instead of retrieve the old one.

### Token.validate_and_destroy(user: User, hash: string): bool

It retrieves a `one_time` token from a user, it deletes the token after finding it and returns the boolean. If the token was not found it throws validation error.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/281
