### ISSUE TITLE
Validate student form locally to prevent redirection

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2037]
<hrs>3</hrs>

Based on this issue: https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/1864

- [ ] Validate valid email
- [ ] Cohort should be mandatory

**Comment by ingindIsrael** [comment]
Solved [https://github.com/breatheco-de/admin/pull/194/commits/3d6fb548ed73d651886ff71958b7b832fe4f4302](https://github.com/breatheco-de/admin/pull/194/commits/3d6fb548ed73d651886ff71958b7b832fe4f4302)
