### ISSUE TITLE
4Geeks - My Profile (Edición de Data y Certificados)

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#2043]
<img width="739" alt="Screen Shot 2022-04-29 at 10 55 49 AM" src="https://user-images.githubusercontent.com/426452/165969912-de0c3b97-eed7-4244-9454-df7ed27c5def.png">

Debemos desarrollar la pantalla de "Mi Perfil" dentro de la plataforma 4Geeks. Accederemos a esta sección desde el menú desplegable que vemos al clickear el avatar (desde donde vemos el nombre de usuario y el cerrar sesión). 

La sección constará de un índice clickeable en la parte izquierda y el contenido en la parte derecha. El contenido se dividirá en dos secciones una de "Basic Profile Information" y otra de "My certificates".

Primero tendremos la parte de "Basic Profile Information", donde tendremos el avatar con el botón de "Remplzar", este botón permitirá al usuario subir una imagen para cambiar su avatar; y a la derecha tendremos los datos de Nombre (s), Apellidos, Email (campo bloqueado), Teléfono y Github. También tendremos el botón de "Save Changes" que unicamente se habilitará cuando se destecte que el usuario ha editado o hecho algún ajuste en alguno de los campos. De lo contrario se mostrará siempre deshabilitado.

Luego tendremos la sección de certificados, que constará de celdas (tantos certificados como tenga el usuario) y un icono, la fecha en que le le fue otorgado el certificado y el curso. A la derecha de la celda estará presente el botón de "View certificate" desde donde se podrá acceder a la previsualización del certificado y su respectiva opción a descarga.

Diseños y flujo completo en Figma:
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/BreatheCode?node-id=2348%3A3708

**Comment by alesanchezr** [comment]
Esto se va a hacer en el perfil del alumno al menos por ahora.

**Comment by alesanchezr** [comment]
You are missing to create and update the profile:

https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2666

**Comment by alesanchezr** [comment]
You are also waiting for this issue to be published to be able to retive the user certificates: https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2667

**Comment by alesanchezr** [comment]
Get certificate: `GET /v1/certificate/me`
