### ISSUE TITLE
Survey response rate

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2044]
We have a feedback system in place based on NPS Surveys, we basically ask students feedback every 4 weeks, [you can read about it here](https://www.notion.so/4geeksacademy/Cohort-Surveys-ca7955fc61ec4b3fa51e8c5d430ba048). And we need to include a property to track the response rate of survey on each academy.

- Answers are collected on the breathecode.feedback.answer model.
- Every time an answer is answered (status=ASWERED) a `survey_answered` signal is dispatched, you can [see the dispatch here](https://github.com/breatheco-de/apiv2/blob/62ace81e3ffa479f303d13e142ab39753a6294c8/breathecode/feedback/models.py#L141).
- That signal is received [here in breathecode.feedback.receivers](https://github.com/breatheco-de/apiv2/blob/62ace81e3ffa479f303d13e142ab39753a6294c8/breathecode/feedback/receivers.py#L22) and a celery task takes care of [re-calculating the entire survey average score asyncrunosly](https://github.com/breatheco-de/apiv2/blob/62ace81e3ffa479f303d13e142ab39753a6294c8/breathecode/feedback/tasks.py#L197).

## Instructions

- We neet to start calculating the `response_rate` as well, you must add that property on the breathecode.feedback.models.Survey object and create the migration.
- Include the property in the survey serializers.
- Calculate the property on the same celery task, don't create a new task.
- The response rate is a percentage: (total_answered / total_questions) * 100

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/341
