### ISSUE TITLE
Listado de sedes con online duplicado

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#2066]
Nosotros sabemos cuales sedes tienen version online tambien porque esta en los YML de las locaciones:

- [ ] Agregar n mensaje de "online y presencial" / "remote & in-person" en cada locacion que tenga ambos casos.
- [ ] Eliminar las locacion "online" de la lista.

![image](https://user-images.githubusercontent.com/62053368/148246856-539f9b84-0b84-4aa4-86d5-0fe1bb625409.png)

**Comment by alesanchezr** [comment]
@Andrearcastillo estamos esperando por ti para ver como poner el mensaje de "online y presencial"
