### ISSUE TITLE
Include language dropdown on cohort creation as well

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#2067]
When editing a cohort you can specify its language but:

- [ ] By default it your be pre-selected with the academy language.
- [ ] We need to include the same field on the cohort creation.
- [ ] it cannot be null.

![image](https://user-images.githubusercontent.com/62053368/148248684-9f3c923a-d5bc-4b57-a509-71129aeaaaad.png)

pero no se ha colocado el campo en la creación de la cohorte 

![image](https://user-images.githubusercontent.com/62053368/148248765-f9fac83c-9474-43bf-a76b-a140c78a4091.png)

**Comment by alesanchezr** [comment]
Tambien tenemos que asegurarnos que agarre automaticamente por defecto on el lenguaje de su academy.

**Comment by ingindIsrael** [comment]
Ready [https://github.com/breatheco-de/admin/pull/198](https://github.com/breatheco-de/admin/pull/198)
