### ISSUE TITLE
Responsive font-size improvement ✨: clamp(css function) to calculate the size smart

### ISSUE THREAD

**Issue by ArielCalisaya** [4GeeksAcademy/About-4Geeks-Academy#2077]
This issue, **solves the problem** of `font-size` **excessively large** that exceed the screen.
Now with the [`clamp()`](https://developer.mozilla.org/en-US/docs/Web/CSS/clamp()) function it will not be necessary to use breakpoints, since it will be calculated by itself !!!

>This problem could be applied to all current projects

---

Predefined text:
```css
/*                 clamp(MIN, VAL, MAX) */
  --text-size-300: clamp(0.83rem, 0.8rem + 0.18vw, 0.93rem);
  --text-size-400: clamp(0.88rem, 0.83rem + 0.24vw, 1rem);
  --text-size-500: clamp(1.09rem, 1rem + 0.47vw, 1.33rem);
  --text-size-600: clamp(1.37rem, 1.21rem + 0.8vw, 1.78rem);
  --text-size-700: clamp(1.71rem, 1.45rem + 1.29vw, 2.37rem);
  --text-size-800: clamp(2.14rem, 1.74rem + 1.99vw, 3.16rem);
  --text-size-900: clamp(2.67rem, 2.07rem + 3vw, 4.21rem);
  --text-size-1000: clamp(3.34rem, 2.45rem + 4.43vw, 5.61rem);
```
---

Example pages:

- [piccalil.li](https://piccalil.li/quick-tip/flow-utility/)
- [ahumanfuture.co (page with laaarge Font-size)](https://ahumanfuture.co/)

**Comment by alesanchezr** [comment]
Can you explain more about this? Have you test it before? Remind me about it during the SCRUM
