### ISSUE TITLE
Add functionanilites for Start class Modal (teacher version)

### ISSUE THREAD

**Issue by ArielCalisaya** [4GeeksAcademy/About-4Geeks-Academy#2083]
![BreatheCode – Figma](https://user-images.githubusercontent.com/51676628/149032312-17c7aefb-5171-4232-9726-45d5a4bd7fbb.png)

**Comment by alesanchezr** [comment]
- [ ] Validate that attendace cannot be take twice the same day:https://github.com/breatheco-de/teacher-client/blob/65925a4c39d3ed99bf750dd597ec5077a3937480/src/js/contexts/cohort-context.js#L54
- [ ] Hide students with education_status != 'ACTIVE'
- [ ] Add a small not saying that `Only showing students with active educational status`.

**Comment by alesanchezr** [comment]
- [ ] The error message for taking attendancy again on the same day should be `Attendancy for day 22 has already been take`
- [ ] Don't let lower the current day.
