### ISSUE TITLE
Upgrade to the UserInvite to accept waiting list

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2085]
Right now the UserInvite its only used for inviting emails into a particular academy.

But we can re-use the same UserInvite to create a "waiting list functionality"

We can allow the creation of invites with the status `WAITING_LIST` that are not related to any academy or course and don't need an author. Once the user invite is created we don't need to do anything with it, it can stay like that until we decide to process the waiting list.

In the admin, we need to be able to filter the invites by status.

Eventually, we will probably have an admin action to process invites from the waiting list to finally create a user for each of those invites, with specific priviledges.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/305

**Comment by alesanchezr** [comment]
Fix small issues: https://github.com/breatheco-de/apiv2/pull/305#pullrequestreview-863016396
