### ISSUE TITLE
Upgrades to the public breathecode

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2087]
- [x] Dark mode buggy, some colors are not properly set, for example: https://app-git-fork-arielcalisaya-fix-friday7-breathecode.vercel.app/lessons?child=1
- [x] On the `/lessons` if one day comes without any activities (lessons, etc) don't include it on the list.
- [x] The "Direct Access Request" form on the interactive exercises should replicate the same request that we did on the website for downloadable, the `current_download` will be the interactive exercise slug.
- [x] The other syllabus are not being loaded (sw engineering and machine learning)
- [x] When clicking on coding BootCamp open in anew window.
- [x] About us does not need table of contents.

**Comment by ArielCalisaya** [comment]
@alesanchezr 
## Problem with task:

- [ ] The other syllabus are not being loaded (sw engineering and machine learning)

I am having problems with the endpoint, as it does not receive the output that I receive with` full-stack`

### with machine learning
https://breathecode-test.herokuapp.com/v1/admissions/syllabus/machine-learning/version/latest
**`status 500`**
```bash
ValueError at /v1/admissions/syllabus/machine-learning/version/latest

Request Method: GET
Request URL: https://breathecode-test.herokuapp.com/v1/admissions/syllabus/machine-learning/version/latest
Django Version:: 3.2.9
Exception Type:: ValueError
Exception Value:: Field 'version' expected a number but got 'latest'.
Exception Location:: /app/.heroku/python/lib/python3.9/site-packages/django/db/models/fields/__init__.py, line 1825, in get_prep_value
Python Executable:: /app/.heroku/python/bin/python
Python Version:: 3.9.7
Python Path:: ['/app',  '/app/.heroku/python/bin',  '/app',  '/app/.heroku/python/lib/python39.zip',  '/app/.heroku/python/lib/python3.9',  '/app/.heroku/python/lib/python3.9/lib-dynload',  '/app/.heroku/python/lib/python3.9/site-packages']
```

### with software-engineering
https://breathecode-test.herokuapp.com/v1/admissions/syllabus/software-engineering/version/latest
**`status 200`**
```json
{
    "json": "{\"msg\":\"Syllabus slug not found\"}",
    "version": 1,
    "updated_at": "2021-09-14T23:33:08.643777Z",
    "created_at": "2021-09-14T23:33:08.643755Z",
    "slug": "software-engineering",
    "name": "Software Engineering",
    "syllabus": 37,
    "duration_in_hours": 350,
    "duration_in_days": 35,
    "week_hours": 9,
    "github_url": null,
    "logo": null,
    "private": false
}
```
