### ISSUE TITLE
Avoid using scrollbar on mobile quizzes

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2088]
Based on this updade: https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/1715

If you open a quiz on a mobile device, some of the questions (the majority) does not display entirely and the user needs to scroll down to see the rest of the options. We need the quiz on mobile to avoid using the scrollbar at least for 5 options.

![quiz-scroll](https://user-images.githubusercontent.com/426452/149201271-6b7f104b-cf00-4e5b-b6fd-3944fe0a309c.gif)

**Comment by ashwani3011** [comment]
I can do this 
Should I proceed ahead

**Comment by gustavomm19** [comment]
I already dit it. I madera the pr yesterday
