### ISSUE TITLE
Syllabus schedule timeslot not being generated correctly

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2089]
- Tried adding a new weekly recurrent timeslot from 6pm to 9pm on Mondays but it added 9:08pm to 9:08p
<img width="574" alt="Screen Shot 2022-01-11 at 7 09 00 PM" src="https://user-images.githubusercontent.com/426452/149041025-256c3de6-4070-4cae-bba2-be765a2c308f.png">
m

**Comment by jefer94** [comment]
https://github.com/breatheco-de/admin/pull/220
