### ISSUE TITLE
Error en website

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/About-4Geeks-Academy#2097]
![Captura de pantalla 2022-01-13 171159](https://user-images.githubusercontent.com/48845580/149402252-83bca2f0-2bf7-4b06-aca2-f30b4d480f01.png)

La palabra test no debe estar ahí @alesanchezr

**Comment by alesanchezr** [comment]
No logro replicar esto @jatv93

**Comment by alesanchezr** [comment]
Me das el URL?

**Comment by jatv93** [comment]
Estaba acá: https://4geeksacademy.com/us/coding-bootcamps/part-time-full-stack-developer/?lang=en

Pero me parece que lo cambiaron, voy a cerrar este issue, y si lo veo en algún sitio más lo vuelvo a abrir @alesanchezr
