### ISSUE TITLE
Manage mentors from the admin

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2102]
This is a feature that requires front-end and backend development.

- [x] We need a new [global menu option on the sidebar](https://tinyurl.com/y7kamfm6) called "mentorships" that contains 3 sub-menus: Mentors, Services and Sessions. Remember to add the "beta" option in the menu to hide the menu on production [(here is an example)](https://github.com/breatheco-de/admin/blob/master/src/app/navigations.js#L101).
- [ ] The `mentors` section will be a paginated list with all the mentors included in that academy, they can be retrieved using `GET /v1/mentorship/academy/mentor`, the list must include the following columns: Mentor full name, the service that it provides, the status, licon to open the open the booking page, icon to copy the meeting URL and icon to edit the mentor (check the other lists for reference, just copy paste and adapt).
- [ ] The mentor status column in the list must be background colored similar to the [cohort stage](https://admin.breatheco.de/admissions/cohorts): INVITED: red, ACTIVE: green, INNACTIVE: grey.
- [ ] The `services` sections, this list can be retrieved using `GET /v1/mentorship/academy/session` and the list must include the columns: Slug, name and status.
- [ ] The service status column in the list must be background colored similar to the [cohort stage](https://admin.breatheco.de/admissions/cohorts): DRAFT: yellow, ACTIVE: green, INNACTIVE: grey.

## Edit a mentor:

- [ ] The view to edit a mentor is similar to the view to [edit one student](https://admin.breatheco.de/admissions/students/3475), it most have to main areas: on the left the information about the mentor profile (including an autocomplete async dropdown with the service), on the right side the list of syllabus that the mentor can work with.
- [ ] If you want to add new syllabus to the mentor, on the right side, you can search for the syllabus and press "add syllabus" (very similar to how you add cohorts to a student).
- [ ] Each of the syllabus for that mentor will come with a "trash" icon to delete the syllabus from the mentor.

## Edit a service:

- [ ] The view to edit a services is very similar to the view to [edit a cohort](https://admin.breatheco.de/admissions/cohorts/miami-xxxiii), it must have to main areas: On the left it has the service properties and on the right it has the paginated list of mentors that can provide that service. Each mentor has a trash can that can delete the mentorship profile entirely (with a confirmation).
- [ ] If the user wants to add a new mentor into the service it will have to do it on a separate URL because there is a lot of questions that need to be answered to allow adding a new mentor.

## Adding a new mentor

- [ ] New mentors are first invited to the academy, the have to accept the invite in order to become mentors.
- [ ] When listing all the academy mentors, if the mentor status is "invited" we need to add an icon to copy the invite link.

**Comment by xenogenesis20** [comment]
> This is a feature that requires front-end and backend development.
> 
> * [ ]  We need a new [global menu option on the sidebar](https://tinyurl.com/y7kamfm6) called "mentorships" that contains 3 sub-menus: Mentors, Services and Sessions. Remember to add the "beta" option in the menu to hide the menu on production [(here is an example)](https://github.com/breatheco-de/admin/blob/master/src/app/navigations.js#L101).
> * [ ]  The `mentors` section will be a paginated list with all the mentors included in that academy, they can be retrieved using `GET /v1/mentorship/academy/mentor`, the list must include the following columns: Mentor full name, the service that it provides, the status, licon to open the open the booking page, icon to copy the meeting URL and icon to edit the mentor (check the other lists for reference, just copy paste and adapt).
> * [ ]  The mentor status column in the list must be background colored similar to the [cohort stage](https://admin.breatheco.de/admissions/cohorts): INVITED: red, ACTIVE: green, INNACTIVE: grey.
> * [ ]  The `services` sections, this list can be retrieved using `GET /v1/mentorship/academy/session` and the list must include the columns: Slug, name and status.
> * [ ]  The service status column in the list must be background colored similar to the [cohort stage](https://admin.breatheco.de/admissions/cohorts): DRAFT: yellow, ACTIVE: green, INNACTIVE: grey.
> 
> ## Edit a mentor:
> * [ ]  The view to edit a mentor is similar to the view to [edit one student](https://admin.breatheco.de/admissions/students/3475), it most have to main areas: on the left the information about the mentor profile (including an autocomplete async dropdown with the service), on the right side the list of syllabus that the mentor can work with.
> * [ ]  If you want to add new syllabus to the mentor, on the right side, you can search for the syllabus and press "add syllabus" (very similar to how you add cohorts to a student).
> * [ ]  Each of the syllabus for that mentor will come with a "trash" icon to delete the syllabus from the mentor.
> 
> ## Edit a service:
> * [ ]  The view to edit a services is very similar to the view to [edit a cohort](https://admin.breatheco.de/admissions/cohorts/miami-xxxiii), it must have to main areas: On the left it has the service properties and on the right it has the paginated list of mentors that can provide that service. Each mentor has a trash can that can delete the mentorship profile entirely (with a confirmation).
> * [ ]  If the user wants to add a new mentor into the service it will have to do it on a separate URL because there is a lot of questions that need to be answered to allow adding a new mentor.
> 
> ## Adding a new mentor
> * [ ]  New mentors are first invited to the academy, the have to accept the invite in order to become mentors.
> * [ ]  When listing all the academy mentors, if the mentor status is "invited" we need to add an icon to copy the invite link.

**Comment by alesanchezr** [comment]
- [ ] You not sending the mentor email, please include it the payload when creating or editing a new mentor.
- [ ] When creating or editing a new mentor the service should be a dropdown with all the services that the academy has available.
- [ ] On the mentor list, remove the column "service" and replace the email with the mentor.service.name instead, if the service is too big and the column needs more space you make the other columns smaller because they don't need the space and also trunk the service name at some character limit and allow the user to hover to the the entire service name instead.
- [ ] Missing email on the update mentor form.
- [ ] In the list of session (everywhere where there is a list of sessions) the columns should be: mentee full_name, mentor full name, status, started_at and mentor_joined_at. Note: Do not add the column mentor full name if we are editing a mentor. Add colors to the status.
- [ ] Every time you display a session status, include a tooltip that displayes the summary of the session when you hover on the status.
- [ ] On the service edit, the list of mentors should include the following columns: Mentor Name with the mentor slug below, do not include the service column,

**Comment by xenogenesis20** [comment]
> * [ x]  You not sending the mentor email, please include it the payload when creating or editing a new mentor.
> * [ ]  When creating or editing a new mentor the service should be a dropdown with all the services that the academy has available.
> * [ ]  On the mentor list, remove the column "service" and replace the email with the mentor.service.name instead, if the service is too big and the column needs more space you make the other columns smaller because they don't need the space and also trunk the service name at some character limit and allow the user to hover to the the entire service name instead.
 > * [ ] Missing email on the update mentor form.
> * [ ]  In the list of session (everywhere where there is a list of sessions) the columns should be: mentee full_name, mentor full name, status, started_at and mentor_joined_at. Note: Do not add the column mentor full name if we are editing a mentor. Add colors to the status.
> * [ ]  Every time you display a session status, include a tooltip that displayes the summary of the session when you hover on the status.
> * [ ]  On the service edit, the list of mentors should include the following columns: Mentor Name with the mentor slug below, do not include the service column,
