### ISSUE TITLE
add functionality to lesson content page

### ISSUE THREAD

**Issue by ArielCalisaya** [4GeeksAcademy/About-4Geeks-Academy#2118]
use the component MarkdownParser
and the left side Timeline component

expected path: `/syllabus/<full-stack>/lesson/<lesson-slug>`

![BreatheCode – Figma (3)](https://user-images.githubusercontent.com/51676628/150035455-7d55fb17-5932-46d6-ba6b-ca110c69b256.png)

**Comment by Omonroy36** [comment]
<hrs>9</hrs>

**Comment by alesanchezr** [comment]
<hrs>9</hrs>

**Comment by alesanchezr** [comment]
<hrs>9</hrs>
