### ISSUE TITLE
add functionality to sticky sidebar teacher tool

### ISSUE THREAD

**Issue by ArielCalisaya** [4GeeksAcademy/About-4Geeks-Academy#2119]
Evitar poner:
- lessons
- replits
- assignments

Añadir:
- key concepts
- detail

#Current 
![Teachers - BreatheCo de Platform](https://user-images.githubusercontent.com/51676628/150037479-ddabb6f1-ee15-4a32-90fe-3577920a660a.png)

#Expected
![BreatheCode – Figma (4)](https://user-images.githubusercontent.com/51676628/150036501-409c0d2e-5d42-4461-a1b4-81bdd41999df.png)

**Comment by alesanchezr** [comment]
not working

**Comment by alesanchezr** [comment]
The buttons show up but the teacher instructions come in two pieces:
- Short: Small paragraph with todays summary.
- Long: Detailed article in markdown explaining what to do today.
