### ISSUE TITLE
Refactoring assignment app

### ISSUE THREAD

**Issue by jefer94** [4GeeksAcademy/About-4Geeks-Academy#2120]
That issue describe a list of incoherencies related to the assignment app related to the tasks endpoints:

1. `v1/assignments/task`.
2. `v1/assignments/user/me/task`.
3. `v1/assignments/user/<int:user_id>/task`.
4. `v1/assignments/user/<int:user_id>/task/<int:task_id>`.
5. `v1/assignments/academy/user/<int:user_id>/task`.
6. `v1/assignments/task/<int:task_id>`.

The views are:

- `TaskTeacherView` is used in the endpoint `1`.
- `TaskMeView` is used in the endpoint `2`, `3`, `4`, `5` and `6`.

The views are thinking for:

- `TaskTeacherView` is used for teachers, but it just check if the user have a profile academy.
- `TaskMeView` is used for the current student, but the latest version of `Breathecode` allow get tasks different of the logged user.

This are some troubles related to this views:

- `TaskTeacherView`
  - The validations are very soft https://github.com/jefer94/apiv2/blob/f28c0a14cc194faf559503f33b9c3da93a0cd997/breathecode/assignments/views.py#L34 considering the original purposed of this view.
- `TaskMeView` 
  - Allow get the task from other student or academy https://github.com/jefer94/apiv2/blob/f28c0a14cc194faf559503f33b9c3da93a0cd997/breathecode/assignments/views.py#L111 that is a privacy issue.
  - This should filter also for academy or get the global tasks https://github.com/jefer94/apiv2/blob/f28c0a14cc194faf559503f33b9c3da93a0cd997/breathecode/assignments/views.py#L119  .
  - That allow edit the task of other user and is not necessary be a teacher, their teacher or part of staff of any academy, that is very problematic https://github.com/jefer94/apiv2/blob/f28c0a14cc194faf559503f33b9c3da93a0cd997/breathecode/assignments/views.py#L125 .
  - The teacher just should edit the status of a staff, I think the normal behavior in this case is the student prepare their task and it is sended to the teacher, and it can approved or disapprove the task.
  - Sometime some student should try to send some inappropriate material, the first think we need to check if this situation should occur and also if this material is some public, in this case a `country manager` should hide this material, should be necessary read the legislation over the country in the 4Geeks provide their services.

**Comment by alesanchezr** [comment]
Lets review this during the scrum.

**Comment by alesanchezr** [comment]
I agree with everything.
