### ISSUE TITLE
Event information not being saved into eventbrite

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2127]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-4109-30920-995db5b95deea4e8b721f58bfcb3f7be) 

 When an evenet its created on breathecode its not being updated on evenbrite with the same information
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 97.0.4692.71</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1047x962</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@0.8999999761581421x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by jefer94** [comment]
I think that @alesanchezr has resolve this issue, in the frontend I added the event `265` and it works fine

**Comment by jefer94** [comment]
The input of `tags` is not being filled by the frontend in the edit view
