### ISSUE TITLE
Event tags, type, host and venue is not being properly loaded on the edit event page

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2128]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-4109-30922-94bd07c2bf1b25527a2ecceb4f28fdb8) 

 In the following url you will find the form to edit an event:
https://admin.breatheco.de/events/EditEvent/253

- [ ] I know for a fact that the event has a type, tags, host and venue but it's not properly loading into this form.
- [ ] Please update the URL of this view to `/events/event/253` no need for the `edit` word, its implicit.

---
**Source URL**:
[https://admin.breatheco.de/events/EditEvent/253](https://admin.breatheco.de/events/EditEvent/253)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 97.0.4692.71</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>2133x962</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@0.8999999761581421x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by gustavomm19** [comment]
Ya está casi listo, pero no consigo la data del host en lo que me trae el get.
academy: {id: 4, slug: "downtown-miami", name: "4Geeks Academy Miami", city: {name: "Miami"}}
banner: "https://storage.googleapis.com/media-breathecode/7f7dd3f372b05c4e128e3710dc76160c794a2b4c1e3cb1a16dbeab545f675b44"
capacity: 1
description: "hi"
ending_at: "2022-01-20T22:19:00Z"
event_type: {id: 1, slug: "workshop", name: "workshop"}
eventbrite_sync_description: null
eventbrite_sync_status: "PENDING"
excerpt: "bye"
id: 254
lang: "en"
online_event: true
slug: null
starting_at: "2022-01-20T22:19:00Z"
status: "DRAFT"
sync_with_eventbrite: false
tags: ""
title: "new"
url: "https://google.com"
venue: {id: 4, title: "4Geeks Academy", street_address: "1801 Southwest 3rd Avenue", city: "Miami",…}

**Comment by alesanchezr** [comment]
done

**Comment by alesanchezr** [comment]
- [ ] If there is not venue the dropdown should say "select an event"
- [ ] If there is not `event type` the dropdown should say "select an event type"
- [ ] Make sure the tags show up.
