### ISSUE TITLE
Display organization venues

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2131]
Using the following endpoints you can retrieve the academy organization venues

- Get academy venues: `GET /events/academy/venues`
- Display the list in the following URL: https://admin.breatheco.de/events/settings
- Let list must have the following columns: venue name, city, updated_at

![Screen Shot 2022-01-20 at 2 00 27 PM](https://user-images.githubusercontent.com/426452/150405267-50fb102b-c057-462d-a75b-72495f05936f.png)

**Comment by gustavomm19** [comment]
I finished this, but the data of the GET response does not include the attribute updated_at

**Comment by alesanchezr** [comment]
done
