### ISSUE TITLE
🚨🚨 Important! Application form isn't accepting 2 letters domains like .co or .es

### ISSUE THREAD

**Issue by Gfervic** [4GeeksAcademy/About-4Geeks-Academy#2145]
**Describe the bug**

All applications forms aren't accepting domains with 2 letter like .co or .es. However if there is a .com before, i.e. with .com.ve it works. Please review

**To Reproduce**
1. Go to any of the applications or Syllabus Request forms on the web
2. Click on email
3. Write gonzalo@hotmal.es

**Expected behavior**
It should accept mails with 2 letter domains

**Screenshots**

![Screenshot 2022-01-27 at 12 17 50](https://user-images.githubusercontent.com/28119213/151348666-2c5cd06e-6a6e-4ab7-b290-b263c4969aa7.png)

**Desktop (please complete the following information):**
Chrome last version

**Comment by ArielCalisaya** [comment]
This issue has already been resolved [try with apply page](https://4geeksacademy.com/us/apply)
