### ISSUE TITLE
When a new downloadable is created, make sure a tag is also created

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2149]
- [ ] Add a new signal for downloadable saved on the [breathecode.marketing.signals](https://github.com/breatheco-de/apiv2/blob/master/breathecode/marketing/signals.py), make sure is called every time a downloadable is saved.
- [ ] Add a new task that will take care of adding the tag into the active campaign.
- [ ] Add a new receiver on breathecode.marketing.receivers and make sure it calls the delayed task when the downloadable is created. Important: you don't want to call the delayed task every time the downloadable is `saved`, you only want to call it when it's created.
- [ ] The tag that is created must be of type=DOWNLOADABLE
- [ ] Make sure you unit test

**Comment by alesanchezr** [comment]
@gustavomm19 was thinking on assigning this to @jefer94 and have you keep working on the front end instead, what do you think?

**Comment by gustavomm19** [comment]
Well I got this almost ready. I just have to fix something and finish the tests

**Comment by alesanchezr** [comment]
- [ ] prepend word "down-" to downlodable tags that are created on active campaign.
