### ISSUE TITLE
Preview Error on Breathecode 

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/About-4Geeks-Academy#2187]
**Describe the bug**
The lesson: https://github.com/breatheco-de/content/blob/master/src/content/lesson/what-is-html-learn-html.md in English and Spanish, shows the tags incomplete. 

**To Reproduce**
1. Go to 'https://learn.breatheco.de/course/coding-introduction.v1/1/l/what-is-html-learn-html' - This is in prework
2. Click on 'Learn HTML'
3. Scroll down to 'The <body> is Similar to any MS Word Document'

![image](https://user-images.githubusercontent.com/48845580/152203671-162473d1-d5ca-4cc5-b063-37309302202e.png)

![image](https://user-images.githubusercontent.com/48845580/152203714-34a105cf-71b1-4b70-944e-34dc615f5834.png)

**Expected behavior**
The tags should close correctly as in the readme in both versions, like this:

![image](https://user-images.githubusercontent.com/48845580/152203854-e51ff324-3ab0-4ca8-8b11-721b07ab978d.png)

![image](https://user-images.githubusercontent.com/48845580/152203903-2ef945c1-b498-43b1-81cd-bc27e6933a76.png)

**Comment by alesanchezr** [comment]
This will be fixed in the new version of breathecode that we are about to publish in a few days: https://app.breatheco.de/lesson/what-is-html-learn-html
