### ISSUE TITLE
There is an incongruence in Syllabus days for Full-Stack Part-Time

### ISSUE THREAD

**Issue by marcogonzalo** [4GeeksAcademy/About-4Geeks-Academy#2188]
![Screenshot 2022-02-02 at 18-29-15 Teachers - BreatheCo de Platform](https://user-images.githubusercontent.com/410890/152207967-6f6b7363-3300-4328-8e96-b20ebd13e0d5.png)

Day 20 is last day for Frontend.
Day 21 is SQL day
But Day 22 is for Data Modeling (using Python and SQLAlchemy) when Python hasn't started yet, it starts the next day (23). 

I think Data Modeling should be after Python classes.

**Comment by alesanchezr** [comment]
No this is not really python, its just doing a data model
