### ISSUE TITLE
Create Timeslot form has gone crazy

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2195]
When I try with 4Geeks Academy Madrid (probably because it does nto have a timeslot)

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-4109-31140-d468c99c00b34c88a1174b9fb6cb2139) 

 When a choose a particular hour on the clock, it selectes a completely diferent one.

---
**Source URL**:
[https://dev.admin.breatheco.de/admin/syllabus/mentoring](https://dev.admin.breatheco.de/admin/syllabus/mentoring)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 97.0.4692.71</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>2132x966</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@0.8999999761581421x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by jefer94** [comment]
Their correspondent medicament to the timeslot https://github.com/breatheco-de/admin/pull/220

**Comment by alesanchezr** [comment]
Still not working propertly, see related issue: https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2264

**Comment by alesanchezr** [comment]
related to https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2089

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/353
