### ISSUE TITLE
Waiting list functionality bug with token integrity (duplicated)

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2196]
I added two users to the waiting list via POST and the second one gave this error, a quick solution will be to generate a unique token for each user dynamically:

![Screen Shot 2022-02-03 at 2 30 24 AM](https://user-images.githubusercontent.com/426452/152299807-efc7fda9-c348-4157-80e8-a76e95b0e510.png)

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/322

**Comment by jefer94** [comment]
![image](https://user-images.githubusercontent.com/3018142/152912891-eac93389-4356-44c5-b978-30a9a2e45fee.png)
