### ISSUE TITLE
Madrid FT-V exercises

### ISSUE THREAD

**Issue by JimenaEB** [4GeeksAcademy/About-4Geeks-Academy#2198]
**Describe the bug**
There is a problem with Madrid FT-V.
I can't review the exercises because all are shown as that:
![image](https://user-images.githubusercontent.com/4335179/152373983-98fc492a-2b9c-4d89-b4be-625e7665664c.png)

**Comment by alesanchezr** [comment]
@victormgomezp a mi esto no me ocurre, mira: 
https://assignments.breatheco.de/?cohort=madrid-ft-5&token=0f967721bf30bd74f4e9a282e9290a14edb4f29f

**Comment by victormgomezp** [comment]
¿serán tus permisos?
Yo veo esto y es muy raro
<img width="865" alt="image" src="https://user-images.githubusercontent.com/62053368/155323713-ff33fb21-0d66-4a24-bca0-803b08a47666.png">

no debería tener activo el botón de review si ya está approved, bueno creo yo
