### ISSUE TITLE
Componente "4geek Academy en 3 historias"

### ISSUE THREAD

**Issue by Andrearcastillo** [4GeeksAcademy/About-4Geeks-Academy#2201]
En componente con el título "4Geeks Academy en 3 historias" que tiene los 3 videos testimoniales de Joao, Hernan y Luisa, por alguna razón solo está mostrando dos videos. Está oculto el video de Joao.

Como se ve actualmente
![Captura de Pantalla 2022-02-02 a la(s) 02 31 30 p  m](https://user-images.githubusercontent.com/80764131/152426030-75e14862-0117-4472-a954-8da256b1bba7.png)

Como debe verse
![Captura de Pantalla 2022-02-03 a la(s) 05 40 12 p  m](https://user-images.githubusercontent.com/80764131/152426051-84b13647-cbc2-438a-984a-0a5ddd943f22.png)

**Comment by alesanchezr** [comment]
This is not a coding but, @jatv93 will take care of this using the YMLs
