### ISSUE TITLE
When the website is localized to santiago de chile, the testimonial videos are wrong

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2202]
We can do one of three options:

- Put back joao's video (that way we have 3 videos).
- Add another video to replace joao.
- Change the title of the videos to THE 4GEEKS WAY IN `TWO` STORIES

**Comment by jatv93** [comment]
We can put back Joao's video meanwhile I ask for the edition of a new video, we got 3 testimonials but they are too long right now or the last option, change the title of the videos.

**Comment by alesanchezr** [comment]
You have the `location` property on both YMLs, english and spanish.
Actually the problem is only happening on chile and venezuela that I know of.

**Comment by jatv93** [comment]
Done @alesanchezr
