### ISSUE TITLE
You should not be able to add users to ENDED, INNACTIVE or DELETED cohorts

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2204]
- [ ] update all the endpoints used to add a new CohortUser to a cohort to make sure it raises a ValidationException with message `This cohort is {status} and you cannot add users to it"
- [ ] Make sure to add one unit test for it.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/579
