### ISSUE TITLE
Split capability `read_cohort` by including a `read_all_cohorts` (that students will not be having)

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2212]
This capability `read_cohort` may not be needed by the student, he does need to be able to get details from a single cohort ID as long as the student belongs to it.

## Implementation Recomendations

- We can split the capability `read_cohort` into two differnt caps: `read_single_cohort` and `read_all_cohorts` and the first one is applied to everyone but the second one is only applied to academy staff members and academy tokens.

**Comment by jefer94** [comment]
Assigned to Gabriel Salazar
