### ISSUE TITLE
Add new bulk action on django admin and endpoint to accept waiting list invite

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2214]
https://breathecode.herokuapp.com/admin/authenticate/userinvite/

- [ ] Add action into the UserInvite admin to accept invite
- [ ] When invite gets accepted a new User and Profile gets created with user info.
- [ ] Send email notification and let the user pick password.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/458
