### ISSUE TITLE
Why event downloaded from eventbrite have short description twice

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2216]
- [ ] Instead of descrion and short description separately we are fulling both fields with the same "short descrption"
- [ ] During the evnet creation the same problem is happening, the short description is the only one sent to eventbrite.

![Screen Shot 2022-02-08 at 5 29 21 PM](https://user-images.githubusercontent.com/426452/153086495-4cecad26-f93b-4bac-91d7-0b1391dba1ef.png)

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/338
