### ISSUE TITLE
The user must be staff member to this academy before it can be a teacher

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/About-4Geeks-Academy#2236]
Admin Error when updating financial status 

https://user-images.githubusercontent.com/48845580/154122846-1ceae86b-4bf6-414d-b850-5fc624640f19.mp4

**Comment by alesanchezr** [comment]
por alguna razon el admin esta mandando ese request con `role: TEACHER` cuando deberia ser STUDENT, por eso da el error.
revisa ese formulario a ver porque lo manda como teacher
