### ISSUE TITLE
Landing - Nueva Landing "United Way"

### ISSUE THREAD

**Issue by Andrearcastillo** [4GeeksAcademy/About-4Geeks-Academy#2256]
Debemos desarrollar una nueva Landing para la iniciativa United Way.

Definiciones y comportamientos:
- Todos los botones de "Apply now" redigirán al usuario a un link externo de un formulario para aplicar (Link en creación).
-  En el tercer componente de "Eligibility in this Program", tenemos un texto antes de el botón "Learn more about eligibility conditions and apply". Las palabras "eligibility conditions" serán clickeables y abrirán un modal de lectura con la información. Es importante que el modal tenga los estilos planteados, el fondo negro con un 80% de transparencia para que el usuario vea la landing de fondo y entienda que no ha salido de la página, solo es un modal (lo comento porque se que había un modal, con fondo totalmente blanco que ya no aplicamos pero era un estilo viejo).
- 
![image](https://user-images.githubusercontent.com/80764131/155011892-ffe4a123-2569-4092-ac5e-7d50c46a4466.png)

Diseño y Link de Figma: https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?node-id=4950%3A2678

![image](https://user-images.githubusercontent.com/80764131/155011987-aaad1aa7-b12d-4699-abbb-294339c0365e.png)

También adjunto imágenes donde se puede ver el equivalente de los componentes utilizados que ya existen en otras landing para optimizar el desarrollo. También están visibles en el Figma.

![image](https://user-images.githubusercontent.com/80764131/155012193-caa237af-998c-42c1-8f03-c5022af5796d.png)
![image](https://user-images.githubusercontent.com/80764131/155012212-d96e1d85-4582-47b9-8a31-be3502e36168.png)
![image](https://user-images.githubusercontent.com/80764131/155012235-6c4e2b88-8984-44a8-b77b-b357a183d509.png)

**Comment by alesanchezr** [comment]
@gustavomm19 

- You can find the landing [examples here](https://4geeksacademy.com/landings/) and each of those landings is represented in a YML you can find it by clicking "edit" next to the landing name.
- We need to create the landing without doing any additional coding just use the components we already have.
