### ISSUE TITLE
Specialty Mode should have an academy owner instead of infering from the syllabus

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2264]
- The syllabus es owned by a specific academy.
- Then any other academy can have specialty modes associated to that syllabus.
- Then any academy can create timeslots but timeslots don't have owners, they belong to a specific specialty mode, therefore the timeslot owner will be inherited from the specialty mode owner.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/352
