### ISSUE TITLE
Unit test that waiting list does not accept current breathecode users

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2266]
Implementation is already done, but we need the test.

https://github.com/breatheco-de/apiv2/blob/046bf575d9c3a7a9da2c4d9f838f71adde277e44/breathecode/authenticate/serializers.py#L566

The error message should say: `You have already signed up, go ahead and log in or reset your password`

**Comment by alesanchezr** [comment]
Ya hice esto, pero hace falta hacer la prueba.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/402
