### ISSUE TITLE
Fix asset url when its not a lesson

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2269]
The current URL is always: https://4geeks.com/syllabus/miami-xxx/lesson/html-exercises

But depending on the asset type you should update `lesson` with `practice` or any other asset type. For example:
```
https://4geeks.com/syllabus/miami-xxx/exercise/html-exercises
```

**Comment by ArielCalisaya** [comment]
Orlando solved this problem with an merged PR
changes to new file `src/pages/syllabus/[cohortSlug]/[lesson]/[lessonSlug]/index.jsx`

**Comment by Omonroy36** [comment]
<hrs>1</hrs>
