### ISSUE TITLE
4Geeks Academy - Module Remain

### ISSUE THREAD

**Issue by Andrearcastillo** [4GeeksAcademy/About-4Geeks-Academy#2277]
En la nueva plataforma 4Geeks, actualmente tenemos un componente al final de los listados de Modulos llamado "Modules Remain" que debemos eliminar.

Los modulos ya completados deberán mostrarse en el orden correspondiente dentro del listado total de modulos. En dado caso, solo se muestra el titulo, la cantidad de lecciones, la descripción y un botón de "Start Module"

A continuación adjunto link de Figma y imagen de referencia:
 
![image](https://user-images.githubusercontent.com/80764131/155763359-e2ce9320-2601-4342-80ea-ad2ba3cafd1c.png)

**Comment by alesanchezr** [comment]
Creo que si el modulo no se ha abierto el boton de "start module" no destaca demasiado, podria pasarse desapercibido, como podriamos hacer que ese modulo se vea bien?

Por otro lado, se me ocurre ocular los siguientes modulos hacia abajo si este no se ha abierto. Ais logramos que sigan el hilo del programa sin abrir el modulo q no es.

Tambien se me ocurre que no se puedan abrir modulos mas arriba del `current_module` de la cohort.

**Comment by alesanchezr** [comment]
@Andrearcastillo que opinas??
