### ISSUE TITLE
Website - Componente de Sedes

### ISSUE THREAD

**Issue by Andrearcastillo** [4GeeksAcademy/About-4Geeks-Academy#2280]
Debemos rediseñar el componente de "sedes" que tenemos en el website, en la sección del home y sedes. Necesitamos mostrar de forma más clara la presencia online del bootcamp para optimizar SEO.

Los enunciados "america, europa y online" funcionarán como un selector que mostrará todas las sedes pertenecientes a esa modalidad o region. La que estará seleccionada por defecto siempre será Online.

También debemos modificar en el menu, el dropdown de sedes para que funcione con la misma dinamica del selector por region. Ver diseños adjuntos.

A continuuación el link de Figma con los diseños correspondientes y las imagenes de referencia:

https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?node-id=4917%3A2730

![Nuevo componente de Sedes - Ajustes en el menú](https://user-images.githubusercontent.com/80764131/155806437-ebe9c3dc-a954-482e-8bf2-0fdcbe7c34f9.jpg)

![Sedes Mobile](https://user-images.githubusercontent.com/80764131/155806444-f6a3cf9d-cb99-4e8f-a5c0-d7b2087ebb67.jpg)

![Nuevo componente de Sedes en el Home](https://user-images.githubusercontent.com/80764131/155806447-86dcad3c-5055-4038-aba1-ba39bb4d909d.jpg)

![Nuevo componente de Sedes en el Home-1](https://user-images.githubusercontent.com/80764131/155806454-b4f5f4a0-750c-4cd4-a909-0546d470c7f1.jpg)

**Comment by alesanchezr** [comment]
add no follow and remember its `href` and not `src` on the anchor tag.

**Comment by alesanchezr** [comment]
La ultima columna es muy ancha, todas las columnas menos la de la foto deberian tener un width especifico y la que crece es la foto si sobra espacio.
