### ISSUE TITLE
Code example is missing in pre-work lesson.

### ISSUE THREAD

**Issue by xenogenesis20** [4GeeksAcademy/About-4Geeks-Academy#2291]
**Describe the bug**
There should be a code snippet showcasing the aforementioned information : "In the next example we are applying an "odd" class to the cells of this table, and then with CSS we are assigning the yellow background to class .odd:"

**To Reproduce**
1. Go to 'https://learn.breatheco.de/course/coding-introduction.v1/1/l/what-is-css-learn-css'
2. Click on the "Class Selector" topic
3. See error: There's no example. 

**Expected behavior**
There should be a code snippet showing the HTML, CSS and result. 

**Screenshots**
https://www.awesomescreenshot.com/image/23320655?key=e0b86158edb9fe18da2042c89404800a

**Desktop :**
 - OS: Windows
 - Browser  chrome

**Comment by Lorenagubaira** [comment]
@alesanchezr and I already created the missing example sometime ago.

**Comment by Lorenagubaira** [comment]
![image](https://user-images.githubusercontent.com/102861577/183083638-f44aa8ea-2389-4fa6-978e-a242f8a577f0.png)
