### ISSUE TITLE
Allow the visualization of jupyter notebooks

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2295]
In addition to the `MarkedownReader` component, we need this new `JupyterViewer` component.
Lets try using the component first if you want: https://www.npmjs.com/package/@thomasvu/react-jupyter-notebook

If not we can copy the code and do it ourselfs (not recomended for now, maybe for a v2.0)
https://github.com/alesanchezr/react-jupyter-notebook

Here is a demo on the component output: https://joeyonng.github.io/react-jupyter-notebook/

It is possible to detect when a lessons is written in Markdown or Jupyter format, the app must render it accordingly.

**Comment by ArielCalisaya** [comment]
## The component uses global css, so it causes incompatibility with nextjs (this issue must be left for version 2.0)

![globalImportNextjsIssue](https://user-images.githubusercontent.com/51676628/159341169-f615c879-84f6-411b-9fa8-68a7a4b06712.png)
