### ISSUE TITLE
Attendancy should show the date of each checked day

### ISSUE THREAD

**Issue by marcogonzalo** [4GeeksAcademy/About-4Geeks-Academy#2311]
In the attendance report, it should show the date of each checked day to give control about last day attendance was checked . Where there are several courses running, it's difficult to know what is the current day number of each one, so, showing the date of each day where attendance was checked give a fast reference about the last time attendance was updated.

Another option is to show the last update date, in general :-)

![each one](https://user-images.githubusercontent.com/410890/157509975-cf73c374-9004-46a4-ac46-c50fefb63c78.png)

**Comment by alesanchezr** [comment]
It was included in the new design.
