### ISSUE TITLE
Invite Tests

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2313]
- [ ] If a user that `already exists` on the system gets invited to another academy a ProfileAcademy objects should be created with status=invited, no UserInvite should be created.
- [ ] If a user `does not exist` on the system gets invited to any academy, a UserInvite should be created with the cohort and academy that it was invited to, also the ProfileAcademy should also be created but without real user (null).
- [ ] When the user accept the UserInvite (because its joining breathecode) the ProfileAcademy object related to that invite should also have the status changed to 'ACTIVE'.

**Comment by jefer94** [comment]
Endpoints related to `AcademyInviteView`
- [x] `v1/auth/member/invite/resend/<int:invite_id>`
- [x] `v1/auth/academy/invite/<int:invite_id>`
- [x] `v1/auth/academy/member/<int:profileacademy_id>/invite`
- [x] `v1/auth/academy/user/invite`

Endpoints related to `ProfileInviteMeView`
- [x] `v1/auth/profile/invite/me` (tested before this issue)

Endpoints related to `render_invite`
- [ ] `v1/auth/member/invite/<str:token>`

Endpoints related to `MeInviteView`
- [x] `v1/auth/academy/user/me/invite`
- [x] `v1/auth/academy/user/me/invite/<slug:new_status>`
- [x] `v1/auth/user/me/invite`
- [x] `v1/auth/user/me/invite/<slug:new_status>`

Endpoints related to `render_academy_invite`
- [ ] `v1/auth/academy/html/invite`

Have 121 new tests related to this issue

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/390

**Comment by jefer94** [comment]
Is acceptable a invite without academy and cohort when it will accepted it just create a user? is possible says in the form occur a unexpected error with the invite and he/she contact the admin with a error code (for hide the error)
