### ISSUE TITLE
Add call to action to several current blog posts

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2332]
Each of use will add call to action to 3 articles and we will see the PR next week.

Example of call cation:

```html
<call-to-action button_text="Ver programa" button_link="#" background="rgba(0, 151, 205, 0.15)" title="Impulsa tu carrera, gracias a la programación" text="Te invitamos a impulsa tu carrera, aprendiendo a programar con nuestro Programa Full Stack Developer."></call-to-action>
```

<img width="766" alt="Screen Shot 2022-03-14 at 12 52 25 PM" src="https://user-images.githubusercontent.com/426452/158221501-b2e7f092-e3bd-41e2-8462-96611e1ce219.png">

**Comment by PedroModesto1** [comment]
coloque en el cta en estos dos artículos
- https://4geeksacademy.com/es/desarrollo-profesional/ventajas-de-trabajar-en-tecnologia 
- https://4geeksacademy.com/es/aprender-a-programar/disyuntiva-para-futuros-programadores-universidad-o-bootcamp
pero no aparece la modificación
