### ISSUE TITLE
Unify all GET invites into just one endpoint for simplicity on the front end

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2349]
- [ ] Endpoings to GET.POST,PUT and DELETE on the user and probile invites should stay the same (all 6 endpoings) and they will not unify invitations.
- [ ] There should be one additional endpoint only for fetch `me` invites, it can only be called by the logged in user and it will return a list with all the notifications not matter the type (UserInvite, AcademyProfil with status=invited, MentoshipProfile with status=invited).
- [ ] The endpoint will be `GET /v1/auth/profile/invite/me`

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/371
