### ISSUE TITLE
Implement duration picker for the entire website and used in your session forms

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2352]
<hrs>1</hrs>

**Comment by alesanchezr** [comment]
You implemented correctly the inputs with minutes on the service creation but is still missing on the service update.

**Comment by xenogenesis20** [comment]
- Aligned the input fields when editing a service. 
- Removed unnecessary margin with helper text. 
- Durations were being received as seconds from the backend, converted the seconds to minutes.

**Comment by xenogenesis20** [comment]
<HRS>1<HRS/>
