### ISSUE TITLE
Automatically generate service slug while the title is being modified

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2353]
<hrs>1.5<hrs>

Dont make it read only, just allow the user to update if they want, but if the title is updated the slug will get replaced /generated again.

**Comment by xenogenesis20** [comment]
Changed all duration inputs to accept minutes which will then be converted to HHMMSS format.

**Comment by xenogenesis20** [comment]
- The service slug is being automatically generated when the `name` input changes. 
- The slug can be edited manually as well. 
- If the `name` input is changed, the slug generates again. 

### question: 
When the service is being edited,  you can change the name of the service but the slug does not change. Do we want slugs to always be editable or ONLY on service creation.

**Comment by alesanchezr** [comment]
cannot create service, it says the slug is empty but also then it started having the same issue with the duration

**Comment by xenogenesis20** [comment]
Issue was that slug was not being passed. 
Also fixed the issue with the durations which was the same when editing a service.

**Comment by xenogenesis20** [comment]
<hrs>0.5</hrs>
