### ISSUE TITLE
The "additional actions" menu should have the option to "activate" or innactivate" the mentorship service.

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2355]
<hrs>1.3</hrs>

When clicked you do PUT request with just the status

**Comment by xenogenesis20** [comment]
- There is now a button to toggle the service status when viewing a service.

### question:
Why is the red color working but green is not? 

```jsx
          {service && service.status === "ACTIVE" ? (
            <Icon syle={{ color: "green" }}>toggle_on</Icon>
          ) : (
            <Icon style={{ color: "red" }}>toggle_off</Icon>
          )}
```

**Comment by xenogenesis20** [comment]
<HRS>0.8<HRS/>

**Comment by xenogenesis20** [comment]
When editing a serview, add additional actions drop down. 
Remove the Status input and move it to the actions drop down.

**Comment by xenogenesis20** [comment]
- When editing a service, you can toggle the status. Via the additional actions button.

**Comment by alesanchezr** [comment]
Its working, but please also add the status below the name like it is in the cohort form. (green or yellow)

**Comment by xenogenesis20** [comment]
Status added under the service name.

**Comment by xenogenesis20** [comment]
<hrs>0.5</hrs>
