### ISSUE TITLE
Bug Fixes on the mentorship service

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2372]
- [ ] When editing a mentor withut Profile (like Victor Salcedo) the website breaks.
- [ ] Redirect back to list when successfully added the service and mentor.
- [ ] When creating a mentorship session, make status read-only and add a help_text saying "You can turn it "ACTIVE" after creation"
- [x] #2419
- [ ] #2420
- [ ] On the service creation or edition add the following help text:
             - duration: "The wanted duration for every session"
             - max_duration: "If session takes longer it wont be paid more than this"
             - missed meeting duration: "How much the mentor should wait for the mentee, if mentee never comes this duration will be accounted for".
             - Allow mentee to extend session: "Once the session is longer than expected duration, the mentee will be able to extended up to max duration"
             - Allow mentor to extend session: "Once the session is longer than expected duration, the mentor will be able to extended up to max duration"
   
- [ ] The default valid for the service language should be the academy.default_language

**Comment by xenogenesis20** [comment]
- [ ] When editing a mentor withut Profile (like Victor Salcedo) the website breaks.

- [ ] Redirect back to list when successfully added the service and mentor.

- [ ] When creating a mentorship session, make status read-only and add a help_text saying "You can turn it "ACTIVE" after creation"

- [ ] The service description should be textarea not text input (on edit and on creation).

- [ ] On the service details, the list of sessions should show the symbos icons overtime, late, survey, etc. Similar to this report:
https://breathecode.herokuapp.com/v1/mentorship/academy/bill/1/html

 - [ ] On the service creation or edition add the following help text:
- duration: "The wanted duration for every session"
- max_duration: "If session takes longer it wont be paid more than this"
- missed meeting duration: "How much the mentor should wait for the mentee, if mentee never comes this duration will be accounted for".
- Allow mentee to extend session: "Once the session is longer than expected duration, the mentee will be able to extended up to max duration"
- Allow mentor to extend session: "Once the session is longer than expected duration, the mentor will be able to extended up to max duration"

 The default valid for the service language should be the academy.default_language
