### ISSUE TITLE
4Geeks - Componente y funcionalidad "Live"

### ISSUE THREAD

**Issue by Andrearcastillo** [4GeeksAcademy/About-4Geeks-Academy#2390]
Deberemos agregar un nuevo componente de "Live" a la página de Cohorte dentro de la plataforma 4geeks. A continuación los comportamientos generales y de acuerdo a cada usuario (estudiante profesor).

**Estructura general**

En componente se compone de una imagen que será animada en caso de que haya un "live" activo. La animación se adjuntará en formato Lottie desde su web de recursos. También tendremos el título del "live", por ejemplo: Today's Live Class. Y tendremos el tiempo que ha transcurrido desde que se activo la transmisión, ejemplo: 00:40 min ago.

https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/BreatheCode?node-id=2122%3A6548

El link del icono animado en estado activo para implementar en dev es el siguiente: https://lottiefiles.com/100247-live

<img width="585" alt="Captura de Pantalla 2022-03-22 a la(s) 05 14 27 p  m" src="https://user-images.githubusercontent.com/80764131/159567896-53b09d77-d9b6-4b03-a76f-4cbaf73fa99d.png">

**Ubicación del componente**
En el caso de la vista del estudiante irá de primero en la parte superior derecha, por encima del componente de "About your Class".
<img width="1022" alt="Captura de Pantalla 2022-03-22 a la(s) 05 04 23 p  m" src="https://user-images.githubusercontent.com/80764131/159568181-674690a3-6924-4368-9a9f-71f6df0fbc82.png">

En el caso de la vista del profesor irá de primero en la parte superior derecha, por encima del componente de "Actions".
<img width="1022" alt="Captura de Pantalla 2022-03-22 a la(s) 05 04 10 p  m" src="https://user-images.githubusercontent.com/80764131/159568201-52db6d69-0e92-411c-9b5a-3ffcb6a02f4a.png">

**Comportamientos del componente**

**Vista Estudiante:**
El componente se mostrará visible para el estudiante cuando sean 20 minutos antes de la clase. En este estado se mostrará con un icono sin animación tal cual como en la imagen planteada.

**En caso de que el profesor active el live de la clase,  el estado del componente pasará a ser con el icono animado de Lottie y un mensaje diferente. Y el componente se hará clickeable.**

https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/BreatheCode?node-id=2122%3A6548

<img width="322" alt="Captura de Pantalla 2022-03-24 a la(s) 12 19 28 p  m" src="https://user-images.githubusercontent.com/80764131/159956420-2a095127-c6ef-4efe-a974-d853ce150c8a.png">

**Vista Profesor:**
El componente se mostrará cuando haya un "live" activo como una clase o un workshop. 
En el caso del profesor, el tendrá la posibilidad de "activar" el live cuando se trate de una clase y el componente sólo será visible cuando sean 15 minutos antes del horario de la clase. 

**En este caso se mostrará en un estado "desactivado", sin animación (solo una imagen estática) y con diferente colores y texto.** (Assets en el Figma)

Al profesor clickear el componente, lo redigirá al Zoom de la clase y activará el "live" para la vista de los estudiantes y para la del mismo profesor (animación y texto con Live en rojo como el ejemplo superior).

<img width="383" alt="Captura de Pantalla 2022-03-22 a la(s) 05 26 10 p  m" src="https://user-images.githubusercontent.com/80764131/159569895-94b4ccd0-1a11-43e7-bb40-33959d0b0cbf.png">

**Casos de Workshops**
Tanto para profesores y estudiantes se hará visible el componente cuando esté un workshop activo en "live". Al clickear en el componente los redirigirá a la plataforma desde dónde se esté transmitiendo.

En el caso de los workshops, agregaremos icono de bandera al lado del tiempo, de esta forma indicaremos a los usuarios el idioma de workshop que está en vivo.

<img width="583" alt="Captura de Pantalla 2022-03-22 a la(s) 05 30 41 p  m" src="https://user-images.githubusercontent.com/80764131/159570511-aaaa4a3e-d9b6-43d9-bd65-b370de48c3a0.png">

**Comment by alesanchezr** [comment]
@jefer94 how can we implement this?

I was thinking having and endpoint with the student events?
