### ISSUE TITLE
Inline code should not jump the line

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2394]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/24498920?key=f83b63d28230a2963c97be9ac90a71ed&size=orig) 

---
**Source URL**:
[https://4geeks.com/syllabus/miami-xxxii/code/simple-counter-react](https://4geeks.com/syllabus/miami-xxxii/code/simple-counter-react)

**Comment by ArielCalisaya** [comment]
Already fixed https://4geeks.com/interactive-coding-tutorial/beginner/simple-counter-react
