### ISSUE TITLE
Innactive academies cannot use the API, only login and update their status.

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2400]
In the table breathecode.admissions.models.Academy there is a `status`.

Innactive academies should not use the API, only login or a method to "activate" again, maybe `PUT /admissions/academy/activate`?

**Comment by brcre001** [comment]
Error needs to say 'This academy is not active'

**Comment by brcre001** [comment]
https://github.com/breatheco-de/apiv2/pull/448
