### ISSUE TITLE
Sync button should have transparent background

### ISSUE THREAD

**Issue by Andrearcastillo** [4GeeksAcademy/About-4Geeks-Academy#2413]
El botón "Sync Now" del componente de actividades actualmente está con fondo blanco. Este es un ghost botón no debe tener ese fondo blanco.

Actual
<img width="836" alt="Captura de Pantalla 2022-03-26 a la(s) 09 49 02 p  m" src="https://user-images.githubusercontent.com/80764131/160262300-3936aa1e-c83e-488f-a4d3-339a3edb53a4.png">

Diseño
<img width="587" alt="Captura de Pantalla 2022-03-26 a la(s) 10 06 50 p  m" src="https://user-images.githubusercontent.com/80764131/160262308-bb519dfa-844e-467d-be62-7d40d6ba2fa0.png">

**Comment by alesanchezr** [comment]
@Andrearcastillo donde esta este boton en el ui kit, digo para hacerlo standard y que nunca mas vuelva a pasar esto.

<img width="553" alt="Screen Shot 2022-03-27 at 10 41 47 AM" src="https://user-images.githubusercontent.com/426452/160286850-23d85c23-142c-4e03-9fa2-e7794ef7ff41.png">
?

**Comment by Andrearcastillo** [comment]
@alesanchezr  Listo. Añadido al UI Kit del documento
<img width="718" alt="Captura de Pantalla 2022-03-27 a la(s) 03 38 04 p  m" src="https://user-images.githubusercontent.com/80764131/160295728-30df84fc-cbdc-478d-8c1f-5b2c1433d572.png">
.
