### ISSUE TITLE
When adding or editing a new service

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2418]
<hrs>0.8</hrs>
 
When adding a new service
- [x] When adding a service make the language default to the academy language.
- [x] If the session.academy.language is indefined then make the language mandatory to select.
When updating a service:
- [x] The language is not being filled.
- [x]  The description should not be a textarea but a textfield with multiple lines.

**Comment by xenogenesis20** [comment]
> When adding a new service
> 
> * [ ]  When adding a service make the language default to the academy language.
> * [ ]  If the session.academy.language is indefined then make the language mandatory to select.

>   When updating a service:
> * [x]  The language is not being filled.
> * [x]   The description should not be a textarea but a textfield with multiple lines.

**Comment by xenogenesis20** [comment]
- When creating a service, it will first try to set the language select value to session.academy.language || values.language || 'en'

**Comment by xenogenesis20** [comment]
<HRS>0.8<HRS/>

**Comment by alesanchezr** [comment]
There is a weird behavior with the duration when you update several times it becomes NaN
