### ISSUE TITLE
On the service details, the list of sessions should show the symbos icons

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2420]
On the service details, the list of sessions should show the symbos icons overtime, late, survey, etc. Similar to this report: https://breathecode.herokuapp.com/v1/mentorship/academy/bill/1/html

**Comment by xenogenesis20** [comment]
In the billing column, include the `billed_str` also include if went over duration limit with a red overtime text.

**Comment by alesanchezr** [comment]
Replacing this card with https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2512
