### ISSUE TITLE
Bux Fixes

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2433]
- [x] "remove project delivery" not working, it says "success" but the modal does not close and the red indicator does not go away.
- [x] When trying to load exercise instructions in spanish, if the instructions don't exist in that language, it should load the english version.
- [x] If I go into coding introduction, the syllabus that loads is still fullstack.
- [x] When I click on "start today's module" it doe snot take me anywhere, its supposed to scroll down to the current module.

**Comment by ArielCalisaya** [comment]
>There are task that can't be fixed

- [x]  "remove project delivery" not working, it says "success" but the modal does not close and the red indicator does not go away.
- [ ]  When trying to load exercise instructions in spanish, if the instructions don't exist in that language, it should load the english version.
> it's imposible to fix this task because the data comes from get(`${url}/academy/${academyVersion}/syllabus/${slug}/version/${version}`) and it not have translations
- [x]  If I go into coding introduction, the syllabus that loads is still fullstack.
- [ ] When I click on "start today's module" it doe snot take me anywhere, its supposed to scroll down to the current module.
> The `current_module` exist but in some cohorts the endpoint not have assigned any value in `current_module`

**Comment by alesanchezr** [comment]
If I go into coding introduction, the syllabus that loads is still fullstack.
