### ISSUE TITLE
4Geeks - Rejected Project Modal

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2434]
Relacionado al flujo de "Asignaciones", debemos re diseñar el modal de "Proyecto Rechazado" en el que el estudiante puede re-enviar la asignatura o removerla.

En éste modal tendremos el título con la opción para cerrar el modal, el feedback del profesor con su nombre y comentario, y el campo de URL para el link del proyecto. A su vez, tendremos dos botones uno de "Remove Delivery" y otro para "Resubmit Assignment".

El campo mostrará de forma completada el link enviado por el estudiante actualmente y será un campo editable en caso de que el estudiante quiere subir otro link.

Adjunto diseño en Figma y imagen de referencia:
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/BreatheCode?node-id=2210%3A2288

![image](https://user-images.githubusercontent.com/80764131/162260852-a2e53ee3-6e7a-4bf8-b162-2c9eb0cba07c.png)

**Comment by Andrearcastillo** [comment]
@alesanchezr Esta tarea esta lista para ser desasignada a mi y comenzarla en desarrollo
