### ISSUE TITLE
4Geeks - Search in Module Map

### ISSUE THREAD

**Issue by Andrearcastillo** [4GeeksAcademy/About-4Geeks-Academy#2437]
Necesitamos agregar un componente de filtro y buscador en el Module Map.

Agregaremos un icono de lupa que al clickearse de convertirá en un campo de texto que se extenderá a la izquierda y ocultará el título "Module Map". 

Al lado izquierda del buscador tendremos un checkbox que funcionará para filtrar y poder ver únicamente las tareas pendientes.

Adjunto Links de figma con el componente y funcionamiento y imágenes de referencia:

https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/BreatheCode?node-id=2122%3A5806
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/BreatheCode?node-id=2223%3A4542

![image](https://user-images.githubusercontent.com/80764131/162258870-bbca2b13-1587-4847-b7a1-a063e5a5dd17.png)

![image](https://user-images.githubusercontent.com/80764131/162258911-0f7fce0f-677a-4ed2-bd90-4f4414402b0e.png)

![image](https://user-images.githubusercontent.com/80764131/162258948-4bc42d0c-6d48-4511-97da-0a8c1c8d1936.png)

**Comment by alesanchezr** [comment]
Can we also add filters to show only tasks pending?

**Comment by Andrearcastillo** [comment]
@alesanchezr  Esta tarea está lista para ser desasignada a mi y pasarla a desarrollo.
