### ISSUE TITLE
Button to "mark as read" a lesson after scrolling down

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#2439]
Al final de todas las lecciones tendremos un componente de cierre que constará de un botón a la derecha para marcar dicha lección como lista, y a la derecha dos botones de navegación para ir a la lección anterior y a la lección siguiente.

Una vez que el botón de "mark as done" es presionada cambia su estado a "Lesson done" y se deshabilitará visiblemente, si no es un lesson pues dira 'Practice done' o 'Project done' o 'Quiz done'

En caso de que el usuario vaya a la lección siguiente sin antes marcar la lección como leída, se le mostrará un modal, consultandole si quiere marcar la `lección|practice|quiz` como leída antes de avanza a la siguiente lección. En el modal el usuario tendrá la opción de marcar como lista o marcar como lista luego.

En el caso de los projects es mejor que no salga el boton.

Adjunto comportamientos y estados del componente en los siguientes links de Figma:

https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/BreatheCode?node-id=2331%3A2882

https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/BreatheCode?node-id=2331%3A3199

**Comment by alesanchezr** [comment]
Se va a discutir alternativas con el equipo de UI/UX

**Comment by alesanchezr** [comment]
When delivering a project the tooltip shows and hides immediatly.

<img width="899" alt="Screen Shot 2022-05-17 at 4 23 36 PM" src="https://user-images.githubusercontent.com/426452/168903495-aa6ca2b3-3fa4-4933-b8bf-5a55fd41c9a4.png">
