### ISSUE TITLE
Cuando estás dentro de una lectura o ejercicio la única manera de vovler atrás es con el navegador

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#2440]
Cuando estás aquí:
<img width="952" alt="image" src="https://user-images.githubusercontent.com/62053368/161317915-0ee9debc-986e-43e0-bc6a-37c102e39684.png">

Si quieres vovler atrás solo puedes usar las flechas del navegador, me quedé un rato pensando cómo vovler a atrás, le di clic a dashboard pero siempre que le das clic a dashboard te lleva a la parte donde seleccionas los programas 
<img width="950" alt="image" src="https://user-images.githubusercontent.com/62053368/161318072-e8d6f449-5104-4c8e-b6b7-548761342ecb.png">

El dashboard debería recordar qué curso has escogido y llevarte aquí:

<img width="944" alt="image" src="https://user-images.githubusercontent.com/62053368/161318154-d53bf669-07b3-4934-b6ba-3da70cbe3763.png">

que es el verdadero dashboard

**Comment by alesanchezr** [comment]
Creo que ya esta arreglado, puedes confirmar @victormgomezp ?
