### ISSUE TITLE
Nuevo BC sin un botón para ver únicamente las tareas pendientes

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#2442]
No puedo ver las tareas que tengo pendientes, la única manera que tendría sería revisar el contenido entero para ver qué me falta. Debe existir un botón o algo que te indique las tareas que tienes por hacer.

mi primera reacción fue hacer clic en esta parte:
<img width="658" alt="image" src="https://user-images.githubusercontent.com/62053368/161319065-1c065333-c7a7-43d8-9668-03cd4bd8166c.png">

pero no tiene funcionalidad más que informarte cuánto hay pendiente, pero no sabes el qué

**Comment by alesanchezr** [comment]
Closing this issue because its resolve in https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2437
