### ISSUE TITLE
Change son the service details view

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2444]
<hrs>1</hrs>

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/25087605?key=0b3bba9a1650e651c2abea9702a587a8&size=orig) 

---
**Source URL**:
[https://admin.4geeks.com/mentors/services/1](https://admin.4geeks.com/mentors/services/1)

**Comment by xenogenesis20** [comment]
For the booking link, assuming we still want to keep it? 
When I successfully trunc the first 10 mentors using
```jsx
                {serviceMentor && serviceMentor.booking_url.substring(0, 15)}
                {serviceMentor && serviceMentor.booking_url.length > 5 && "..."}
```
However when paginating the table it throws an error. 
![otherissue](https://user-images.githubusercontent.com/78182780/161412998-b75429bb-5ba0-4f68-98c8-b718c93dbbfa.PNG)

**Comment by xenogenesis20** [comment]
Requested changes are in place but the `online_meeting_url` I get from the backend does not match the "https://s.4geeks.co/mentor" format. 
Also, there's no `backup` URL coming from the backend unless the `online_meeting_url`  is supposed to be `backup` which would explain the different formatting.

**Comment by xenogenesis20** [comment]
<hrs>1</hrs>
