### ISSUE TITLE
BC - Translation Not Found

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/About-4Geeks-Academy#2469]
@ArielCalisaya no consigo el json que traduce esta parte, ni ningún subtítulo. 

![image](https://user-images.githubusercontent.com/48845580/161849401-9251f7e3-e6b1-4f8a-8729-9448f07a7c19.png)

![image](https://user-images.githubusercontent.com/48845580/161849544-6e23f30c-62cc-4aa5-be15-ede12059e1b9.png)

**Comment by ArielCalisaya** [comment]
El título y texto se obtienen desde el Api

**Comment by alesanchezr** [comment]
Eso no se va a poder traducir en el corto plazo.
