### ISSUE TITLE
BC - Update Code Instructions

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/About-4Geeks-Academy#2472]
The instructions must be updated at least the images 

https://4geeks.com/es/syllabus/santiago-pt-22/code/fix-the-misspell

![image](https://user-images.githubusercontent.com/48845580/161853320-bdd06a84-a9ba-4511-91f3-d2e5c0990c4d.png)

**Comment by alesanchezr** [comment]
Estamos esperando que este este listo para luego actualizar la foto

https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2483

**Comment by Lorenagubaira** [comment]
PR: https://github.com/breatheco-de/the-misspell-chalenge/pull/105
