### ISSUE TITLE
Data for language "es" not found, showing the english version

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/About-4Geeks-Academy#2474]
It doesn't show any version

https://4geeks.com/es/syllabus/santiago-pt-22/code/jwt-authentication-with-flask-react

![image](https://user-images.githubusercontent.com/48845580/161853806-6dc1c194-371a-4cef-b168-76c954349b10.png)

**Comment by alesanchezr** [comment]
Solucionado @jatv93 pero necesita traduccion al español, podrias ayudar con eso?
