### ISSUE TITLE
Cohort.Timezone ignored when creating the Cohort.Timeslots

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2482]
https://github.com/breatheco-de/apiv2/blob/36d2a3f4de5bafdb2ddda0f76d019b52b34ef9fa/breathecode/admissions/actions.py#L20

## Test case:

- The academy timezone is America/New York
- The cohort timezone is America/Bogota
- The cohort.timeslots being generated have `America/New York` instead of `America/Bogota`

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/387
