### ISSUE TITLE
Assignment tests v2

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2487]
- [ ] You can update your tasks in bulk
- [ ] You can delete your own tasks in bulk.
- [ ] You cannot delete other peoples tasks in bulk, only yours.

**Comment by alesanchezr** [comment]
ponle esto a el chamo nuevo

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/507
