### ISSUE TITLE
Finances in Latam

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2492]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/25449439?key=905d6bfb4a5611237cb2688877f51a13&size=orig) 

---
**Source URL**:
[https://4geeksacademy.com/us/coding-bootcamps/part-time-full-stack-developer](https://4geeksacademy.com/us/coding-bootcamps/part-time-full-stack-developer)

**Comment by mafecasvi** [comment]
We should have more specific information for each Latam location.
