### ISSUE TITLE
Mark mentor as unlisted so he/she can manage mentorships only for their students

### ISSUE THREAD

**Issue by marcogonzalo** [4GeeksAcademy/About-4Geeks-Academy#2494]
Un mentor necesita marcar horas de mentorías a su curso pero no quiere que gente de otros cursos le reserven mentorías porque luego no tiene disponibles para el suyo.En ese caso, ¿cuál sería la solución? ¿Tener disponibilidad en Calendly, pero no tener servicios asignados en BC Mentorships? ¿De ser así, igual contabilizaría las horas reservadas?
12 respuestas

Alejandro
Podriamos habilitar una opcion "unlisted"
para que no salga en la lista, entonces el le comparte su booking link a la gente direcamente

**Comment by alesanchezr** [comment]
ya se implemento unlisted.
