### ISSUE TITLE
Show mentor bills

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2512]
- [ ] Add a tab like this one: https://admin-theme.vercel.app/pages/view-customer
<img width="1112" alt="Screen Shot 2022-04-12 at 6 12 45 PM" src="https://user-images.githubusercontent.com/426452/163063486-80f8b3c7-d0e9-48d8-b647-36560e07c18e.png">

- [ ] The mentor info its not part of the tab, only "sessions" and "bills"
- [ ] In the addional actions add a "generate bills" button that when called will generate the bills and give you back an array of bills
- [ ] In the bills tab, show the list of all the bils generate separate by status, the bills should load when the tab si selected, don;t realy on the reponse of the "genreate bills" service.
- [ ] The "session" dont show the billed time anymore because some of the will ahve it none, instead how the duration of the meeting (and if its overtime) on that column.
- [ ] On the first column instead of the duration add "days ago" (humanize it).
- [ ] If you click on a bill details it will show the bill from breathecode, the one we are using right now, for example: https://breathecode.herokuapp.com/v1/mentorship/academy/bill/9/html?attempt=1&token=<session_token>

**Comment by xenogenesis20** [comment]
> * [x]  Add a tab like this one: https://admin-theme.vercel.app/pages/view-customer
> 
> <img alt="Screen Shot 2022-04-12 at 6 12 45 PM" width="1112" src="https://user-images.githubusercontent.com/426452/163063486-80f8b3c7-d0e9-48d8-b647-36560e07c18e.png">
> 
> * [ ]  The mentor info its not part of the tab, only "sessions" and "bills"
> * [ ]  In the addional actions add a "generate bills" button that when called will generate the bills and give you back an array of bills
> * [ ]  In the bills tab, show the list of all the bils generate separate by status, the bills should load when the tab si selected, don;t realy on the reponse of the "genreate bills" service.
> * [ ]  The "session" dont show the billed time anymore because some of the will ahve it none, instead how the duration of the meeting (and if its overtime) on that column.
> * [ ]  On the first column instead of the duration add "days ago" (humanize it).
> * [ ]  If you click on a bill details it will show the bill from breathecode, the one we are using right now, for example: https://breathecode.herokuapp.com/v1/mentorship/academy/bill/9/html?attempt=1&token=<session_token>

**Comment by xenogenesis20** [comment]
Change the filter to a drop down
This year, past year, previous years(3 years or older)

**Comment by xenogenesis20** [comment]
<hrs>14</hrs>

**Comment by xenogenesis20** [comment]
<hrs>3</hrs

**Comment by alesanchezr** [comment]
remove padding from the tab content and make sure the dropdown for billint period has a little margin top and bottom

**Comment by xenogenesis20** [comment]
- [ ] remove padding from the tab content and make sure the dropdown for billint period has a little margin top and bottom
- [ ] you aded the tokne to the wrong url, the token needs to be added to the url when you open the bill on a new window, you should not be asked for login.
- [ ] Fix the hash query
- [ ] Make sure the SmartMuiDatatable and your SmartTabs keep compatibility with current querystring and hashstring

**Comment by xenogenesis20** [comment]
<hrs>1.3</hrs>
