### ISSUE TITLE
Fallos en el generador de eventos d BC

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#2552]
Basado en este video, vamos a revisar bien el flujo completo de eventos:
- Crea un evento 
- Asegurate que se creo que eventbrite como draft
- Asegurate q se creo con el organizer correcto, fecha correca, descripcion correcta, etc.
- Asegurate que aparece en la lista del admin correctamente con los mismos datos.
- Entra al detalle del evento en admin y asegurate de que todos los campos esten llenos.
- 
https://www.loom.com/share/4ea4f4396634473a87039ac8a52326e6

**Comment by jefer94** [comment]
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2597
