### ISSUE TITLE
Connect with github not working

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2558]
There is a feature to connect your github to your current user by clicking on a link, for example:

1. First a new token [is generated here](https://breathecode.herokuapp.com/v1/auth/member/<member_id>/token).
2. When the token is received we use it to reset the github connection with the following email:
https://breathecode.herokuapp.com/v1/auth/github/98255805014f795936bd95a86da330dbc8114ea3?url=https://student.breatheco.de/login
3. When this endpoint is called it gives the following error:
<img width="1188" alt="Screen Shot 2022-04-25 at 11 21 52 AM" src="https://user-images.githubusercontent.com/426452/165120683-70a5b48b-33b5-4261-8252-6e1e89886f9b.png">

Apparently the CredentialsGithub gets a Null `github_id`.

4. If you start the process again from scratch you will see how it does not give any errors, the error only occurs the first time.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/400
