### ISSUE TITLE
Error generating calendar events

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2559]
https://breathecode.herokuapp.com/v1/events/ical/cohorts?academy=1,2,3,4,5,6,7,8,9,10

<img width="1182" alt="Screen Shot 2022-04-25 at 12 35 45 PM" src="https://user-images.githubusercontent.com/426452/165133880-61410c0f-c109-4733-aa73-0ce9ea3379c6.png">

Al parecer alguna de las dos fechas es nula:
https://github.com/breatheco-de/apiv2/blob/master/breathecode/events/actions.py#L460

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/396
