### ISSUE TITLE
Include a warning on cohort dashboard about pending projects

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2567]
A month and a half before graduation a new alert should show on the front end stating:

You have 3 `mandatory` projects to complete before graduation.
You need to complete at least 60% of the rest of the projects.

You can tell which are the mandatory projects because on the syllabus json the have a `mandatory: true` property.

-----------------------------------------

Andrea: Definiciones de Diseño

En los dos casos descritos por @alesanchezr anteriormente. En el dashboard de la cohorte, mostraremos un cintillo de advertencia justo debajo del menu, desde donde podremos mostrar el mensaje correspondiente a cada caso.

Si el mensaje de advertencia es:  "You have 3 `mandatory` projects to complete before graduation". Lo complementaremos agregando un estado de "Alerta" a la tabla del module map, resaltando las lecciones que debe ver el estudiante antes de la graduación. De ésta forma, el estudiante puede identificar rapidamente en el listado de esas "3 lecciones mandatorias" cuáles son las que debe completar.

Diseño de la pantalla en Figma:
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/BreatheCode?node-id=2122%3A5806

Estilo del componente de tabla con Alerta en Figma:
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/BreatheCode?node-id=2414%3A3992

Imágenes de Referencia:
![Program landing - Student](https://user-images.githubusercontent.com/80764131/167011241-d02288c5-a93f-4edf-be42-f4230c562dde.jpg)

![Module Map Styles List](https://user-images.githubusercontent.com/80764131/167011256-0f20c180-db2f-414c-ab04-52f1e6ea8d70.jpg)

**Comment by alesanchezr** [comment]
- [ ] Only make mandatory projects yellow, ignore the quizzes or any other.
- [ ] Only make yellow after the task was created 2 weeks ago.

**Comment by ArielCalisaya** [comment]
@alesanchezr Some issues to make changes:
- How to check the date of a task created?
- property `mandatory` in `json.days` does not exist in any `assignment`(project)

**Comment by alesanchezr** [comment]
You can now check the `json.days[].assignments[].mandatory` property.
Also, the tasks also include now a `created_at` property.

**Comment by ArielCalisaya** [comment]
@alesanchezr, I still can't find any `mandatory `property in `json.days[].assignments[]`
>tried in development and production endpoint

**Comment by ArielCalisaya** [comment]
>Commit [remind message for mandatory projects and sort by position property](https://github.com/breatheco-de/app/commit/a15289818768080c367f1500b1ed63da9370b1f1) created for this issue
