### ISSUE TITLE
4Geeks - Repensar componente de acciones a la derecha

### ISSUE THREAD

**Issue by Andrearcastillo** [4GeeksAcademy/About-4Geeks-Academy#2573]
El estudiante y el prof tienen un menu a la derecha que va a cambiar segun el contexto:

- video solucion
- intrucciones

<img width="127" alt="Screen Shot 2022-05-12 at 12 57 35 PM" src="https://user-
images.githubusercontent.com/426452/168128932-157b2117-4191-42f6-8c02-22ec890ed6eb.png">

**Comment by alesanchezr** [comment]
Van a haber dos: el prfe y "dont get stuck"

**Comment by alesanchezr** [comment]
agregar al icono de dont get stuck un signo de interrogacion

**Comment by alesanchezr** [comment]
Una vez que apretas en la burbuja como se va a mostar? Que no sean mas circulitos sino un menu formal.
Las opciones para "Dont get stuck" seran:
- Video tutorial
- Solution
- Slack
