### ISSUE TITLE
Mentorship section

### ISSUE THREAD

**Issue by Andrearcastillo** [4GeeksAcademy/About-4Geeks-Academy#2574]
Debemos desarrollar la sección de Mentorship.

La página consta de un título desde dónde se pueden cambiar diferentes meses, siendo el mostrado por defecto, el mes en curso. A la derecha del header tendremos los 2 KPI principales. En el componente de los KPI tendrá un componente de "flecha" que al clickear desplegará 3 KPI más.

Posterior al componente de KPIs tendremos la tabla de "Mentorship Session", Events y Billed. 
Al clickear en "ver eventos" aparece un modal con los "mentoring topics" y una linea temporal de eventos. 

Diseños y Flujos en Figma:
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/BreatheCode?node-id=2423%3A3988

Imagen de referencia
![Program landing - Profesor](https://user-images.githubusercontent.com/80764131/167016441-73cd72ba-0ea3-4c50-b905-bc66a4c4836b.jpg)

**Comment by alesanchezr** [comment]
A que te refieres con esto @Andrearcastillo

**Comment by alesanchezr** [comment]
We need a way of being able to have up to 5 KPIS but also 2,3 or 4 some times.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=2760%3A6678

**Comment by alesanchezr** [comment]
- [ ] If there are 3 kpis, the component will show on the right
- [ ] If there are more than three it will show below the page title instead

![Image](https://user-images.githubusercontent.com/426452/172900712-bbabc158-83be-44aa-8b4f-3dda05d9ca36.png)

**Comment by alesanchezr** [comment]
What happens if I dont have any mentorship sessions and I'm not a mentor?

**Comment by gustavomm19** [comment]
> What happens if I dont have any mentorship sessions and I'm not a mentor?

![image](https://user-images.githubusercontent.com/47191295/181854183-9c194295-3597-4217-87dc-3ead16ba4cff.png)

**Comment by alesanchezr** [comment]
- [ ] Corregir proporciones de items de la lista (sessions) para que sean similares a la de choo-program, deberian aparecer unas 6 sessions en la pantalla de alejandro.
- [ ] Revisar font-size de todo para continuar el standard de la pagina.
- [ ] Los iconos en movil van del lado derecho debajo de las horas, hacer los iconos mas pequeños en movil.
- [ ] Falta la modal de details que tiene la historia compelta.

**Comment by alesanchezr** [comment]
By default make the month dropdon to say the current month
