### ISSUE TITLE
I should be able to invite the same user to two different cohorts

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2611]
Right now, if I try inviting a user that already has an invitation to the same academy bug different cohort it will not allow it, it will consider it duplicate and  ignore the new invitation.

The criteria for duplciate is wrong: A duplicate invite has the same cohort, academy and email. But if any of this three properties is different the invite should be not considered a duplcate.

Maybe [this validation ](https://github.com/breatheco-de/apiv2/blob/9f4beb685432c6569a7955fa8ed43c5e723a3b3b/breathecode/authenticate/serializers.py#L546)is to strict?

On the other hand, when the user finally accept any of the invites it should be redirected to accept the other pending invites. Using somthing like this function to render_invite:
https://github.com/breatheco-de/apiv2/blob/9f4beb685432c6569a7955fa8ed43c5e723a3b3b/breathecode/authenticate/views.py#L1256

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/409

**Comment by alesanchezr** [comment]
double check if its redirecting
