### ISSUE TITLE
Reject github logins for users who's email does not exist on the User table

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2632]
If the user is on the waiting list the error message should say: You are still number 34 on the waiting list, we will email you once you are given access"

If there user is not on the waiting list we say: "We could not find in our records the email associated to this github account, perhaps you want to signup to the platform first?"

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/408
