### ISSUE TITLE
Implement new mentor booking in the old student breathecode.

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2645]
We want this but for all the academies:
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2064

Here is were the conditinoal is placed right now, we should stop using setmore:
https://github.com/breatheco-de/student-client/blob/a01eca4fd47a66a6504b3dc82f27a292ad512c06/src/js/utils/menu.js#L78

**Comment by gustavomm19** [comment]
https://github.com/breatheco-de/mentor/blob/master/src/js/store/flux.js

Duplicate line 7 token: qs.parse(window.location.search).token || null, to get the syllabus from the url, an then parse it to the get service on the line: const resp = await bc.fetch(`/v1/mentorship/academy/mentor?service=${service.slug}&status=ACTIVE`);
