### ISSUE TITLE
Event tags review bugs

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2654]
- Some events are not having their tags created on active campaign: For example `options-for-making-money-in-tech`, [here is the event on the admin](https://admin.4geeks.com/events/event/356?&location=downtown-miami) but the gat was not created on active campaign.
- Some event tags are being created like `event-geektalks-demoday-presentacion-de-proyectos-finales` but then, the attendies are not being tagged.
- Some event work perfect, the tag is crated and the attendies are tagged, but this happens only with a big minority of the events

<img width="784" alt="Screen Shot 2022-05-16 at 12 37 19 PM" src="https://user-images.githubusercontent.com/426452/168641402-c857fd5a-6b47-4f37-8ad9-1e442ed92d8b.png">

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/439

**Comment by jefer94** [comment]
The event `options-for-making-money-in-tech` when if run `Reattempt add event slug to Active Campaign` this tag appear in production

**Comment by jefer94** [comment]
The event `geektalks-demoday-presentacion-de-proyectos-finales` not exists

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/commit/ba1fd8216c470bdcba4cc3eaf1cd0d79331e04ce

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/commit/e79118a5c8fe15bb03e63eb7424d8c99c704675a
