### ISSUE TITLE
BUG : status posponed or dropped in Admin

### ISSUE THREAD

**Issue by ehiber** [4GeeksAcademy/About-4Geeks-Academy#2659]
When I put a student in status posponed or dropped, the still appear in the teacher view

![image](https://user-images.githubusercontent.com/56272634/168782807-7abd1580-1f6d-43ee-9278-fe38a9469549.png)
![image](https://user-images.githubusercontent.com/56272634/168783142-bfe9dcae-3344-401a-8a5c-0a6ab845dc8d.png)
![image](https://user-images.githubusercontent.com/56272634/168783272-f334a9d3-68db-4c80-8650-93facba43473.png)
![image](https://user-images.githubusercontent.com/56272634/168783460-647d431e-bfd3-404a-b0ae-1a051345cd1f.png)

**Comment by ehiber** [comment]
It's the same. I use the new platform but I'm a little nostalgic :laughing: 

![image](https://user-images.githubusercontent.com/56272634/169086001-a9d77d06-5627-4a68-a6f8-63b1bbee976c.png)

**Comment by alesanchezr** [comment]
When I put a student in status posponed or dropped, the still appear in the teacher view

![image](https://user-images.githubusercontent.com/56272634/168782807-7abd1580-1f6d-43ee-9278-fe38a9469549.png)
![image](https://user-images.githubusercontent.com/56272634/168783142-bfe9dcae-3344-401a-8a5c-0a6ab845dc8d.png)
![image](https://user-images.githubusercontent.com/56272634/168783272-f334a9d3-68db-4c80-8650-93facba43473.png)
![image](https://user-images.githubusercontent.com/56272634/168783460-647d431e-bfd3-404a-b0ae-1a051345cd1f.png)

**Comment by alesanchezr** [comment]
- Lo de los assignments se va a resolver aqui: https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2670
- Lo de la asistencia ya esta resuelta en la nueva plataforma 
- Lo de la lista de alumnos a la derecha ya esta resuelto en pruebas y se pasa a produccion el martes.
