### ISSUE TITLE
Youtube image for 4Geeks.com

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2679]
Slogan: Learn in community, live.

- [ ] Cover
- [ ] Example youtube covers
- [ ] Video intro (max 5 seconds)
- [ ] Icon

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/vSDRLyH2pJTflub0N6jJqS/Youtube-images-for-4geeks?node-id=0%3A1
