### ISSUE TITLE
Nuevos iconos para portal de internshipts

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2681]
Este es el portal: http://internships.4geeksacademy.com/

Estos son los iconos:

![marker-green](https://user-images.githubusercontent.com/426452/169146603-8581c7d6-beac-4d6f-b651-32a464cb9b8b.png)
![marker](https://user-images.githubusercontent.com/426452/169146604-a7fc7a38-5bee-4e6b-bca3-6d841ef84ed1.png)

[re4geeksacademy.zip](https://github.com/4GeeksAcademy/About-4Geeks-Academy/files/8720514/re4geeksacademy.zip)

**Comment by ali5uarez5** [comment]
![Group 10](https://user-images.githubusercontent.com/105449728/169808406-28e78388-ae7c-4d00-9719-86082f9f1c39.png)
![Group 11](https://user-images.githubusercontent.com/105449728/169808413-9eb7fd80-e9b4-4fa3-bcbb-3590280ebea1.png)

**Comment by alesanchezr** [comment]
Asking Egidijus from trainingexperience what is the difference between the orange and green icon

**Comment by ali5uarez5** [comment]
[Pin.zip](https://github.com/4GeeksAcademy/About-4Geeks-Academy/files/8890761/Pin.zip)
