### ISSUE TITLE
Better Thank you for Waiting List

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2690]
This is the current thank you page: https://4geeks.com/en/thank-you
We need better design and this will be the content:

Congratulations! You are on the waiting list.
(number)

Get ready for the new way to learn.

Share your list position on social media! Who knows, maybe it will move you to the first positions?

An example:
<img width="114" alt="Screen Shot 2022-05-19 at 1 13 20 AM" src="https://user-images.githubusercontent.com/426452/169214003-c5f9005b-52ce-4666-9e5e-60ed7b4932d7.png">

What we have right now:
<img width="1244" alt="Screen Shot 2022-05-19 at 1 01 32 AM" src="https://user-images.githubusercontent.com/426452/169212312-0db8870d-eaf7-422b-8f32-c75be181f09e.png">

**Comment by JayChavan-23** [comment]
### Hello! 
#### Is anyone working on this right now?
I'm interested in working on this

*Also please provide additional information about the task and requirement*
*Is there a need for just a UI/UX or does the whole **Greeting** page need to be coded*

**Comment by alesanchezr** [comment]
> ### Hello!
> #### Is anyone working on this right now?
> I'm interested in working on this
> 
> _Also please provide additional information about the task and requirement_ _Is there a need for just a UI/UX or does the whole **Greeting** page need to be coded_

Hi @JayChavan-23, we have this covered internally but if you want to contribute we can start using the `up for grabs` label for you.
Also, are you familiar with the codebase in Next.js?
https://github.com/breatheco-de/app
