### ISSUE TITLE
More creative profile pictures

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2701]
We need a more diverse and fun and colorful set of default profile pictures.

<img width="368" alt="Screen Shot 2022-05-20 at 3 17 30 PM" src="https://user-images.githubusercontent.com/426452/169596937-04bb07a5-bad7-4b7c-9cff-8b5a316ffc46.png">

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=2657%3A4234

**Comment by ali5uarez5** [comment]
https://drive.google.com/drive/folders/1a35vfCurd65u9I7KoRbY1rc8beFwQoxE?usp=sharing

**Comment by alesanchezr** [comment]
![Image](https://user-images.githubusercontent.com/426452/177434235-8ab1a9cf-7572-4e47-806d-1fb64b2d5d17.png)

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/475

**Comment by jefer94** [comment]
@ali5uarez5 please give me access to this file https://drive.google.com/drive/folders/1a35vfCurd65u9I7KoRbY1rc8beFwQoxE?usp=sharing
