### ISSUE TITLE
No puedo ver el Video de la lección Calculus and L. Algebra - Punto 1) Plotting Functions With Python

### ISSUE THREAD

**Issue by xalejandrow** [4GeeksAcademy/About-4Geeks-Academy#2704]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alesanchezr** [comment]
Listo!!

**Comment by xalejandrow** [comment]
Perfecto, ahora sí lo puedo ver.
Muchas gracias
