### ISSUE TITLE
Footer for 4Geeks.com

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2708]
This is just a design example: <img width="1284" alt="Screen Shot 2022-05-20 at 8 15 05 PM" src="https://user-images.githubusercontent.com/426452/169626551-6ed18a98-9471-46f1-a831-431040bcaf99.png">

**Company**
1.1 About
1.2 Contact
1.3 Media Kit

**Learning Library**
For all the self-taught geeks out there, here our content library with most of the learning materials we have produces throughout the years.
2.1. `Read and watch`: It makes sense to start learning by reading and watching videos about fundamentals and how things work.
      2.1.1. Introduction to code
      2.1.2. Front End Web Development
      2.1.3. Full Stack Development
      2.1.4. A.I. & Machine Learning Engineering
      2.1.5. Full Stack Development
2.2. `Practice Interactively`: Curated list of small interactive and incremental exercises you can take to get better at any coding skill.
2.3. `Build projects`: Curated section of projects to build while learning with simple instructions, videos, solutions and more.
2.4. `How to's`: Frequently asked questions about building things with code, setting up your learning environment and more.

**Socially & Live Learning**
The most efficient way to learn: Join a cohort with classmates like yourself, live streamings, coding jam sessions, live mentorships with real experts and keep the motivation.
3.1. `Intro to coding`
3.2. `#30DaysofGeekCoding`
3.3. `Full Stack Development`
3.5. `Data Science`
3.4. `A.I. & Machine Learning Engineering`

**4Geeks Community**
4.1. Workshops & Events
4.2. Live Mentorships
4.3. Social & Live Learning
4.4. Code of conduct

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=2657%3A4165

**Comment by alesanchezr** [comment]
- [ ] The socially & liver learning are the most improtant (add icons, and descripon to them)
- [ ] learning library only links without descriptions (on the left side)

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=2746%3A5210

**Comment by alesanchezr** [comment]
simpler mobile version

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=2782%3A5498

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=2827%3A5297

**Comment by alesanchezr** [comment]
![Image](https://user-images.githubusercontent.com/426452/174121165-690d865e-641e-4ca5-8d63-f85d368663f5.png)
