### ISSUE TITLE
Mentor Invoices

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2713]
Right now the mentor invoices are being generated and rendered by django/backend with this format:
https://breathecode.herokuapp.com/v1/mentorship/academy/bill/20/html

We need to start rendering them on the front end under the url:
https://admin.4geeks.com/mentors/<mentor_id>/invoice/<invoice_id>

The following is a sample on how the invoice should look like: 
https://admin-theme.vercel.app/invoice/fdskfjdsuoiucrwevbgd

### API

Get details for one bill: https://documenter.getpostman.com/view/2432393/T1LPC6ef#b2c579d3-3b6c-492e-8f79-46936c81cd08

**Comment by gustavomm19** [comment]
Use accounted, not suggested accounted. If they are not equal, put a pencil icon with a tooltip that says it was edited, and the original value

**Comment by alesanchezr** [comment]
https://tinyurl.com/23ygssnr

**Comment by alesanchezr** [comment]
Make sure that the API is recalculating the bill total after updating the session.

**Comment by alesanchezr** [comment]
forget about the print for now

**Comment by alesanchezr** [comment]
Re-use the function that generate bills:
https://github.com/breatheco-de/apiv2/pull/451
