### ISSUE TITLE
Upload profile picture API

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2714]
- [ ] Create endpoint to upload profile picture using endpoint: `PUT /profile/me/picure`
- [ ] If the profile object does not exist, create it.
- [ ] Profile pictures need to be uploaded to a bucket called [breathecode-profile-pictures](https://console.cloud.google.com/storage/browser/breathecode-profile-pictures;tab=objects?project=breathecode-197918&prefix=&forceOnObjectsSortingFiltering=false)
- [ ] Only allow square images to be uploaded
- [ ] Resize images before saving them to a max dimension of 100x100
- [ ] When successfully uploaded return the profile object json but now with the image url updated

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/474

**Comment by alesanchezr** [comment]
it has a bug the second time the picture is replaced

**Comment by alesanchezr** [comment]
- [ ] Its should accept png, jpeg and jpg
- [ ] The first time its upload it gives an error, the front end has to call the endpoint twice.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/585
