### ISSUE TITLE
If the user is trying to accept an UserInvite but already has a user, we should only show accept/reject buttons

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2723]
https://github.com/breatheco-de/apiv2/blob/33926c35de34a2c9c3071c36f6bddc986eb220e2/breathecode/authenticate/views.py#L1322

If a user is invite twice for the first time, we should be able to detect that the second time the user is already created.

Instead of showing the entire form with first_name, last_name and passwords, we should only show a message saying:

"You have been invited to the cohort <cohort_name> at <academy name>, please accept this invite if you want to be included in the cohort"

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/428
