### ISSUE TITLE
share on twitter or linkedin prompt

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2736]
- [x] Once a task as been finished/submited you should be able to easily share your progress on twitter or linkedin
- [ ] The dialog also shows a confetti explosion (https://github.com/alampros/react-confetti)
- [x] Please show a "share" dialog (its a component because we are going to be re-using it a lot).
- [x] Share Dialog is configurable thru properties at least with: title, service (array of possible social media sites), message (HTML string with the encouraging message).

**Comment by alesanchezr** [comment]
make it an achievement, make a party and recognize the user, add learn in public reference

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=2746%3A4726

**Comment by alesanchezr** [comment]
<img width="324" alt="Screen Shot 2022-06-09 at 12 51 57 PM" src="https://user-images.githubusercontent.com/426452/172958216-011ca410-210c-4082-ae53-be8c0e28b672.png">

**Comment by alesanchezr** [comment]
center the buttons, if there is only 3 they should be centered.

**Comment by alesanchezr** [comment]
Right after a project has been delivered, the modal window with confeti must show (prompt).

Title: Congratulations! Share your progress.
Subtitle: `You have finish the project Instagram with Bootstrap, every project you finish is worth celebrating, share your progress via:`

Twitter share message: `I just finished coding The Instagram Post at 4geeks.com #100DaysOfCode`

This is how I implemented a modal that can be programatically opened instead of using the state.
https://github.com/breatheco-de/react-notifier

**Comment by alesanchezr** [comment]
I tried twitter sharin the digital postcard on the prework (module 1) and the project URL is wrong, it ways: 4geeks.com/en/lesson/postcard 

It should be:
4geeks.com/en/lesson/postcard 


Also, when I tried sharing on LinkedInt it gave
<img width="1151" alt="Screen Shot 2022-08-05 at 8 58 34 AM" src="https://user-images.githubusercontent.com/426452/183082211-6dd7402f-4d3e-427c-9ee5-760c16de75ce.png">
 me en error: "Something went wrong"

**Comment by ArielCalisaya** [comment]
>fixed in [this commit ](https://github.com/breatheco-de/app/commit/87f01d094a60293c4709bc743b967f8ac14e50ad)
