### ISSUE TITLE
New dashboard

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2739]
The dashboard must include:
- [ ] Your programs: Each program with preview image, title and description (the progress bar will be left for future versions).
- [ ] Connect your academy classes activity to your calendar. (for example: https://breathecode.herokuapp.com/v1/events/ical/student/1)
- [ ] Upcoming events: small list of events happening un the next few days.
- [ ] Happening right now: Box with things that are live, happening right now, will only show if there is something happening, if not.. it will not show at all.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=3230%3A7718

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=3230%3A7718
