### ISSUE TITLE
Problema para enviar asignacioes

### ISSUE THREAD

**Issue by XavierSilvaB** [4GeeksAcademy/About-4Geeks-Academy#2745]
Buen dia Gusto en saludarlos 
tengo un error que no me permite entregar las asignaciones con el link de repositorio de github anteriormente funciono bien ahora me agrega este error . me dice direccion invalida, 

![image](https://user-images.githubusercontent.com/105250553/170726997-6886637a-6328-4675-b229-8bc233d91bcd.png)
estoy colocando el link del respositorio creado y no me deja porque me dice que no es valida la direccioon 

adjunto imagen 
![image](https://user-images.githubusercontent.com/105250553/170727289-09a7b317-7749-43fe-b8b1-7a650b534de3.png)
 espero que me puedan ayudar a solucionar 

espero su pronta respuesta,

agradecido por la amabilidad de su atencion

**Comment by alesanchezr** [comment]
Te fijaste que tienes un punto al final del URL? tienes que eliminar ese punto
