### ISSUE TITLE
The mentoring session has expired without even starting

### ISSUE THREAD

**Issue by StefAranzazu** [4GeeksAcademy/About-4Geeks-Academy#2752]
**Describe the bug**
When entering the session at the scheduled time I get this message despite entering on time. The extend session option doesn't do anything so I ended it.

**To Reproduce**
1. Go to https://breathecode.herokuapp.com/mentor/meet/mentor with a scheduled mentorship 
2. This view is displayed'
![image](https://user-images.githubusercontent.com/84442570/170831435-32166d48-b543-45b7-b076-5bdea22ff8ab.png)
3. Click on "extend it for another 30 minutes"

**Expected behavior**
Enter scheduled mentoring

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 101.0.4951.67

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/459
