### ISSUE TITLE
Include profile object and profile.avatar in the GET /v1/auth/user/me endpoint

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2765]
We want the front end to use the profile.avatar_url image instead of profile.github.avatar_url:

- [x] Include the profile.avatar on the GET /v1/auth/user/me endpoint
- [x] When github gets connected, if the profile.avatar_url is empty, it will be set with github.avatar_url.
- [x] If github gets disconnected with profile.avatar_url will not be deleted, it will keep whatever image it had.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/437
