### ISSUE TITLE
Share certificate button

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2766]
- [ ] Share button should be only one button
- [ ] After the button is clicked the sharing options show up (twitter, linkedin and facebook).

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-32947-0a53d946a1c5c35a0d1bb45bf53a4f1b) 

---
**Source URL**:
[https://4geeks.com/en/profile](https://4geeks.com/en/profile)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 101.0.4951.67</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x711</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=2563%3A3760

**Comment by alesanchezr** [comment]
Add elarn in public component
buttons should be the same style as the rest

**Comment by alesanchezr** [comment]
![Image](https://user-images.githubusercontent.com/426452/172897934-776abb25-2365-4e38-8800-8b600eaeff0b.png)

**Comment by alesanchezr** [comment]
In this particular case the share modal will say:

- Tile: Share your new career title
- Pick any any the following social networks to share
- Share message inside the social media post: `I have earn a new certificate as <Profession> at 4Geeks.com` and include the link to the certificate.
- The link that says "read more about..." should point to this article: https://4geeks.com/lesson/learn-in-public
