### ISSUE TITLE
Upload profile image

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2767]
- [ ] A pencil icon should show on top of the picture
- [ ] When the pencil is clicked, a modal window will show a "drag n drop" area but the user can also click on the area to see a upload dialog.
- [ ] Wait for this task to complete on the backend https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2714

<img width="806" alt="Screen Shot 2022-06-23 at 3 57 08 PM" src="https://user-images.githubusercontent.com/426452/175386440-12a550b8-15c1-4cc2-8c12-65373ebf1c70.png">

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=2961%3A8285

**Comment by alesanchezr** [comment]
<img width="806" alt="Screen Shot 2022-06-23 at 3 57 08 PM" src="https://user-images.githubusercontent.com/426452/175386440-12a550b8-15c1-4cc2-8c12-65373ebf1c70.png">

**Comment by alesanchezr** [comment]
Endpoint: PUT /profile/me/picture

Since the picture must be a square we need to allow people to fit the image on a square.

**Comment by alesanchezr** [comment]
- Make the modal for uplding the image a lot smaller (like half).
- When the server responts 500 the modal stays loading forever.
