### ISSUE TITLE
Improve link contrast in 4Geeks mentor list

### ISSUE THREAD

**Issue by marcogonzalo** [4GeeksAcademy/About-4Geeks-Academy#2771]
![image(5)](https://user-images.githubusercontent.com/410890/171461897-464de8f7-f070-454f-b743-9e09447818db.png)

The blue link could be hard to read for people with color disabilities. It's a little bit hard for me too

**Comment by alesanchezr** [comment]
Vamos a revisar otras mejoras que tambien quiero hacerle como rating del mentor y un short bio (one liner) para q se vendan bien.

**Comment by alesanchezr** [comment]
Agregar boton de volver al principio
