### ISSUE TITLE
Intro de videos

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2776]

**Comment by alesanchezr** [comment]
- [ ] Agregale el mouse encima cuando hagas click
- [ ] La palabra live haz que se vea como live despues de unos segunos con algun recurso animado pero muy muy sencillo.

**Comment by ali5uarez5** [comment]
https://drive.google.com/drive/folders/1eHzMvL-3zQsmeotYeEKbNwQXTDlTG2rx?usp=sharing

**Comment by ali5uarez5** [comment]
https://drive.google.com/drive/folders/1eHzMvL-3zQsmeotYeEKbNwQXTDlTG2rx?usp=sharing
