### ISSUE TITLE
Agregar el logo de Asottech en el Footer de 4geeksacademy.com

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#2777]
En el footer de la web la Asociación de Talento Tecnológico de España (Asottech) pide que agregemos el logo de la asociación.

La propuesta que ellos hacen la siguiente, pero no estamos obligados a hacerlo exactamente así, el diseñador puede proponer algo. Tampoco tiene que ser a nivel mundial, pero todo el que entre a la web desde españa, debería poder ver el logo en el footer. 

<img width="554" alt="image" src="https://user-images.githubusercontent.com/62053368/171689483-c0cd6308-d327-40ce-8e5e-88be9d55e519.png">

Y también indican las siguientes normativas
· si hay elementos de color y el fondo es oscuro, utilizar logo color + texto blanco
· si hay elementos de color y el fondo es claro, utilizar logo color + texto negro
· si el footer es monocromo con texto e imágenes en blanco, utilizar logo blanco
· si el footer es monocromo con texto e imágenes en oscuro, utilizar logo negro
· ubicar en zona próxima a logo de la institución y/o otros sellos

Imagen en PNG y SVG

![ASOTTECH firma institución asociada color sobre fondo claro](https://user-images.githubusercontent.com/62053368/171689921-3e84b2a1-0356-4533-a44d-99588c7d19ca.png)

![ASOTTECH firma institución asociada color sobre fondo claro](https://user-images.githubusercontent.com/62053368/171690110-e5c9f39e-55bd-4b6a-baf1-81b71e0d42ed.svg)

**Comment by JParedesArtica** [comment]
No se ha efectuado el cambio hasta el momento. Estoy a la espera de confirmación sobre si se realizará o no
