### ISSUE TITLE
Creación de sede: Escuela Autónoma de Dirección de Empresas (EADE) en Breathecode

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#2778]
Se debe crear la sede de EADE en 4geeks.com 
Debe tener el logo de EADE en vez del de 4Geeks Academy
Debe tener habilitado el Prework (le llamaremos Prework-EADE) y también el syllabus de Full-Stack con NodeJS (el de la UTEC)

Accesos: 
Marco Gómez 
Carla Alcolea
Ehiber Graterol
Victor Gómez

Logo EADE:
![EADE](https://user-images.githubusercontent.com/62053368/171692534-281aaedd-3a91-49e7-8cc1-49bf7465554a.svg)

**Comment by victormgomezp** [comment]
El logo lo he solicitado porque me han dicho que no es este

**Comment by alesanchezr** [comment]
@victormgomezp, que paso con este logo? Necesitamos uno cuadrado tambien. Como el q tienen en fb. Alta resolucion.

**Comment by victormgomezp** [comment]
Me habías dicho que necesitabas solo el circular, ya pido también el rectangular, lo subo aquí en los próximos días.

**Comment by alesanchezr** [comment]
Pero este no es circular!
