### ISSUE TITLE
NPS only for "active" students

### ISSUE THREAD

**Issue by marcogonzalo** [4GeeksAcademy/About-4Geeks-Academy#2806]
When a student moves to a different cohort, that person is not aware about evolution of the previous cohort and mentors, keeping the previous scores on every survey about it. This votes produce a distortion in the overall score that is not real.

Proposal: Send the NPS to active students only. Not postponed and, maybe, other status

**Comment by jefer94** [comment]
add `remove_invalid_answers` command to fix the answer of student is not active or graduated

PR https://github.com/breatheco-de/apiv2/pull/468
