### ISSUE TITLE
Add cohort meeting URL as a location for the cohort calendar

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2808]
<img width="620" alt="Screen Shot 2022-06-08 at 5 52 31 PM" src="https://user-images.githubusercontent.com/426452/172724530-fadcf68f-4cb3-4380-9bc0-df31101dc42e.png">

**Comment by alesanchezr** [comment]
- [ ] Add meeting url to the student calendar: /v1/events/ical/student/1

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/450
