### ISSUE TITLE
Hidden validation error when inviting staff members

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2815]
On this view: https://admin.4geeks.com/admin/staff/new

1. Write a non-exiting email so it suggest for invitation
2. Click on invite
3. Fill the form but don't add the `+` symbol on the phone
4. The form does not do anything because the phone number is wrong.

Expected behavior:

It should show an error saying the phone is wrong.

Important:

Please check if all the other validations are not hidden.

**Comment by gustavomm19** [comment]
I think the problem is actually this:
`Warning: An unhandled error was caught from submitForm() TypeError: Cannot read properties of null (reading 'id')
    at NewStaff.jsx:40:27
    at onSubmit (NewStaff.jsx:75:33)
    at Formik.tsx:849:12
    at Formik.tsx:1200:25
    at Formik.tsx:756:34`
