### ISSUE TITLE
Add link to all lessons

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2842]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-33124-4b69c85d1d361c238f131aa5a7dacb8b) 

---
**Source URL**:
[https://dev.4geeks.com/interactive-exercises?techs=javascript](https://dev.4geeks.com/interactive-exercises?techs=javascript)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 101.0.4951.67</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x710</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by ArielCalisaya** [comment]
>Already on production
