### ISSUE TITLE
New direct access functionality on interactive tutorials

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2845]
We have a similar case to github.com with the "code" button:

<img width="343" alt="Screen Shot 2022-06-16 at 3 04 06 PM" src="https://user-images.githubusercontent.com/426452/174146130-1dffa423-bf46-4064-8be4-84ab17536463.png">

We need people to understand that there are two ways of running the interactive exercises:
1. With gitpod
2. Locally in your computer

## First they have to login or fill the form

The first step is ok as it is, we ask for information.

## Then the box gets replaced with a box on how to run the exercises:

1. First option is to open it on Gitpod immediatly without any configuration.
2. Second option is to download the LearnPack plugin on vscode and clone the repository code. (We can add a link for additional instructions).

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-33151-523aa1b812f6376d1dc1d27392dcf4a8) 

---
**Source URL**:
[https://4geeks.com/interactive-exercise/pandas-exercises-tutorial](https://4geeks.com/interactive-exercise/pandas-exercises-tutorial)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 101.0.4951.67</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1397x710</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>90%</td></tr></table>

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=3413%3A14293
