### ISSUE TITLE
We need a box to display the university credit

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2846]
Some breathecode.academy's are interested in showing their brand on the cohort dashboard at 4Geeks.com

- [ ] API: Add an 'bc.admissions.models.academy.white_labeled' boolean property.
- [ ] API: Include it in the serializer /v1/admissions/user/me the `cohorts[].academy.white_labeled` and  `cohorts[].academy.icon_url` property.
- [ ] APP: On the cohort dashboard show the academy information  if the academy for that cohort is white_labeled.
- [ ] Make sure to stick with the [figma design](https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=2999%3A10914).

We want to give credit to the university with a small box on the side
![4Geeks (1)](https://user-images.githubusercontent.com/426452/174149860-89ee4fa1-0136-45c1-b61b-dae420c0a835.png)
.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=2998%3A10279

**Comment by alesanchezr** [comment]
It should only show if the `cohorts[].academy.white_labeled` is true

If its undefined or false it should not show.
