### ISSUE TITLE
Final Project mode

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2877]
- [ ] Show a big notification that celebrates that the final project has started and a call to action to submit your project (the submission will work like a modal window).
```
<h1>It's final project time!</h1>  

Congratulations on reaching to this phase of the program. We are still learning a lot but this last project will become something to showcase to friends and potential employer.

- Why building a final project.
- How to pick your final project topic.
```

- [ ] On the notification there needs to be a call to action to submit your final project.
- [ ] Permanent right side box showing a `What do you need to graduate` card that says:
```
Almost there! You are on the last sprint before graduation, please make sure to complete the following activities:
- Add your final project information (button to add).
- Complete all required projects (button with progress).
```

- [ ] In the permanent box, if you already submited everything it will say: `Congratulations you have submited all the projects`
- [ ] If you already submit your final project information then the bullet will say: `Finish the final project you have submited` and button to `view  project details`.
- [ ] When you click on the "add your final project information" a modal shows up asking for the project details.
- [ ] The project details must also allow to add team members by search for current classmates and adding them.
- [ ] If you already graduated the box will say: `Congratulations, you have graduated successfully as a: Full Stack Developer` and button to view your certificate.

# Final Project Info

Only the ones with `*` are mandatory.

- Title*
- One Line Description* (Info: Max 50 characters).
- Description* (Info: 600 words)
- Live URL (Info: Pick a URL from your hosting provider or domain name).
- Slides url (Info: Online slides like Google Sliders, Prezi, etc)
- Screenshot (Info: You home page or animated gif using the project).
- Github Repo URL: (Info: URL to repository where your project its hosted).
- Geeks members*: (Info: Each student taking part on this project)

**Comment by tommygonzaleza** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=2734%3A4663&t=2dhyh1WcsfYb8gT3-0

**Comment by tommygonzaleza** [comment]
In this section:
![image](https://user-images.githubusercontent.com/56565994/211688623-4782b1e5-d831-460a-aea5-b8ed77457bba.png)

**Comment by tommygonzaleza** [comment]
- [ ] This is the endpoint you will use to get the final project `GET /v1/assignments/user/me/final_project`
- [ ] The big modal shouldn't show if they already set the final project.

**Comment by tommygonzaleza** [comment]
- [ ] Add the blue box that's shown in the dashboard, to the storybook.
- [ ] Add the animation to the final project mode (Waiting for design)
- [ ] Add this functionality to the cohort's dashboard when a cohort stage is Final Project.

**Comment by ali5uarez5** [comment]
Este es el gif de final project mode: 
![Gif_baja](https://user-images.githubusercontent.com/105449728/214548848-fc0d0b05-dfb8-4390-a046-bb77df423aa0.gif)

Por las dudas comparto la ubicación en drive tambien https://drive.google.com/file/d/1N5tDIp08nNEDMWAlY_iQt3C1ecTMgDoc/view?usp=sharing

**Comment by tommygonzaleza** [comment]
![Uploading Screenshot 2023-01-30 at 11.59.14 AM.png…]()

**Comment by tommygonzaleza** [comment]
![Screenshot 2023-01-31 at 2 08 01 PM](https://user-images.githubusercontent.com/56565994/215846400-36937a80-b300-4400-8d6b-a8d024e46c2a.png)

**Comment by tommygonzaleza** [comment]
This is the request to upload the project

**Comment by tommygonzaleza** [comment]
It's not sending the screenshots, it's sending an empty object
