### ISSUE TITLE
Warn before updating or creating an event 

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2907]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-33309-73c1ee91b5a08ad5c83c11e2cd785b87) 

---
**Source URL**:
[https://admin.4geeks.com/events/event/415](https://admin.4geeks.com/events/event/415)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 101.0.4951.67</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x689</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by gustavomm19** [comment]
https://4geeksacademy.notion.site/Choosing-event-tags-e11bc8405ddd4ceead6a66161af03b6b
