### ISSUE TITLE
Misspelled word

### ISSUE THREAD

**Issue by andres-av** [4GeeksAcademy/About-4Geeks-Academy#2921]
**Describe the bug**
INCORRECT AND CURRENT: 
Have you every played finding Waldo?
CORRECT:
Have you ever** played finding Waldo?
**To Reproduce**
1. Full-Stack Software Developer program
2. Domain Name Generator lesson
3. Learn Javascript Arrays and Loops Interactive exercise:
07.1 Find Waldo

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/105819083/177310886-3e937199-4b42-4397-a15f-2f8924da020f.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alesanchezr** [comment]
Fixed! better late than never :(
