### ISSUE TITLE
Allow one mentor to have multiple services

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2925]
Please work on a separate banch that will not merge until we are really confident about this development.

- [ ] Make manytomany the bc.mentorship.models.MentorProfile service property.
https://github.com/breatheco-de/apiv2/blob/main/breathecode/mentorship/models.py#L90

- [ ] The URL to meet a `/mentor/meet/<mentor_slug>` will have to ask what services is the meeting about and redirect to a more specific url that also includes that specified service (the canonical url for the mentor & service.
- [ ] The canonical url to meet a mentor needs to include the service as well: `/mentor/meet/<mentor_slug>/service/<service_slug>`
- [ ] When creating and updating a mentor the service id is now a list of ids.
- [ ] When serialize a mentor, the services are a list instead of an object.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/469

**Comment by jefer94** [comment]
`generate_mentor_bills` just can generate bills from `MentorshipSession` have a `service` set, is necessary if exist a unpaid session without `service`, set it manually

**Comment by alesanchezr** [comment]
no functiona fix_avatars
