### ISSUE TITLE
Revision de algorimo de totalizacion de NPS answers y permitir IGNORAR

### ISSUE THREAD

**Issue by marcogonzalo** [4GeeksAcademy/About-4Geeks-Academy#2928]
Esta es la vista: https://admin.4geeks.com/feedback/surveys/miami-pt-xxxvii/471

- [ ] Revisar que el calculo se este haciendo correctamente con cada nueva encuesta que entra.
- [ ] Desarrollar una funcionalidad para ignorar una respuesta (status=IGNORED) y que esta no forme parte del calculo, cuando se ignore deberia volver a calcularse el promedio.
- [ ] Revisar que no se este redondeando nada, entregar los numeros completos. con todos los decimales y que el front-end se encarge de recondear al final.

**Comment by marcogonzalo** [comment]
@jefer94 aquí te dejo capturas del NPS 379

![Calificación en lista de NPS](https://user-images.githubusercontent.com/410890/186443309-23b3bc29-2989-4ef3-af54-69eb961042f9.png)
![Puntuaciones individuales recibidas](https://user-images.githubusercontent.com/410890/186443356-7c984f60-b639-4c0a-abbe-220bd53b4a2d.png)
![Totalización de puntuaciones por pregunta](https://user-images.githubusercontent.com/410890/186443379-4b275f57-5bc4-49d8-b8d9-14a43f4475e5.png)
![Puntuación total](https://user-images.githubusercontent.com/410890/186443400-5d53f4ed-9e35-496a-a0c9-61a5218383e6.png)

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/521

**Comment by jefer94** [comment]
PR https://github.com/breatheco-de/apiv2/pull/521

Changes to be apply:

- Change in the frontend `x.avg_score` to `x.scores.total`
- If `x.scores` is `null` this means Survey was not answered yet 
- If `x.scores.academy`, `x.scores.cohort` or `x.scores.total` is `null` this means the related question was not answered yet
- `x.scores.mentors` is a array of objects, contains the keys `name` and `score`, this array is sorted by `name`

**Comment by alesanchezr** [comment]
Include
