### ISSUE TITLE
Vista de análisis de evolución del curso en función de todas las consultas de calidad asociadas

### ISSUE THREAD

**Issue by marcogonzalo** [4GeeksAcademy/About-4Geeks-Academy#2929]
Sería muy útil poder graficar para cada curso la evolución que ha tenido en las encuestas, tanto a nivel del promedio global, como a nivel de cada una de las preguntas realizadas. Esto nos permitirá identificar mejor cómo evolucionan las valoraciones en función del punto en el que se encuentra el curso, de las correcciones hechas por sus mentores y ver en el tiempo el punto de partida y el punto final.

Extra: si se puedieran comparar dos cursos, ya sería brutal... 

Opción: descargar en un CSV todas las encuestas de un mismo curso para poder hacer los gráficos por fuera.

**Comment by alesanchezr** [comment]
Esto no se va a desarrollar en brico porque no es la herramienta adecuada, para reportes historicos estamos implementando una integracion con google big query y google datastudio.
