### ISSUE TITLE
New location images

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2930]
This is an example image for miami: 
https://4geeksacademy.com/static/d5c6fed11197f574b9c4eea76153b401/49191/miami-home.png

We need the same image for the following locations:

```
barcelona-spain
valencia-spain
malaga-spain
lisboa-portugal
milan-italy
rome-italy
berlin-germany
hamburg-germany
munchen-germany
dublin-ireland
toronto-canada
vancouver-canada
montreal-canada
```

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=3143%3A10213
