### ISSUE TITLE
Remove "online" as a region on the locations component

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#2933]
This is how the locations component looks right now:
<img width="1167" alt="Screen Shot 2022-07-06 at 6 26 19 PM" src="https://user-images.githubusercontent.com/426452/177653743-1e649869-2109-483e-9d8e-97c803f402e7.png">

- Regions will now be: usa-canada, europe, latam (in that order)
- All the locations teach online classes now, and we have more than 30 location so we cannot fit them all in an "online" region.
- A solution might be to remove the "online" region entirely and instead add a message on top of any other region saying: `If you are looking to learn from your home, we have a special tailored offer for remote learning with more mentoring and support to the student, click here to learn more about it`.

**Comment by Riciglianomarcelo** [comment]
I dont really like the solution! jaja
I rather keep the "in-person and online" just below every territory.

**Comment by Riciglianomarcelo** [comment]
I'll leave three territories btw:
Latianamerica: Online and in-person
USA&Canada: Online and in-person
Europe: Online and in-person

And if someone ask for in-person in Bolivia or such, admissions takes care of that!

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=3208%3A9025

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=3347%3A8545
