### ISSUE TITLE
"ToDo" List chapter hasn't got a video tutorial (the video frame doesn't work).

### ISSUE THREAD

**Issue by jingunza** [4GeeksAcademy/About-4Geeks-Academy#2935]
Description of the bug:
"ToDo" List, chapter 2 (Code), from Full Stack platform hasn't got a video tutorial (the video frame doesn't work).
Please check it.

Thanks a lot!
Jose

**Comment by jingunza** [comment]
https://www.loom.com/share/2b424d5de4354a0fb4ed407295dba6c9

**Comment by alesanchezr** [comment]
We found the error, thank you! it will fixed by next week. Here is the video in the mean time:
https://www.loom.com/share/610516d1db32405a80fc43c7e5456634
