### ISSUE TITLE
The content of page is empty if I go from this url

### ISSUE THREAD

**Issue by jefer94** [4GeeksAcademy/About-4Geeks-Academy#2960]
When I go to https://4geeks.com/cohort/Machine-learning-2/machine-learning-pt-16w/v1 the content of page is empty

![image](https://user-images.githubusercontent.com/3018142/179115835-bd87bd51-9f6a-4ba3-baaf-0ba92ca90049.png)

**Comment by ArielCalisaya** [comment]
@jefer94 prueba en dev.4geeks.com

**Comment by jefer94** [comment]
En el dev parece no fallar con ese enlace, ahora, en ocasiones da un client side exception, tienes que entrar al enlace varias veces para ver el error, pero la informacion que sale en la consola no ayuda para nada

![image](https://user-images.githubusercontent.com/3018142/179121271-99dbb258-5570-46d1-906e-fad4de408bad.png)
