### ISSUE TITLE
Mejoras en `new_locations`

### ISSUE THREAD

**Issue by ArielCalisaya** [4GeeksAcademy/About-4Geeks-Academy#2991]
# Expected changes

- Aumentar 5px margin left al svg de flecha
- El link debe tener `width: fit-content`

![Coding-Bootcamp-in-München-Germany-·-4Geeks-Academy](https://user-images.githubusercontent.com/51676628/181110044-f210607d-aec2-4320-873e-a077424ad6a3.png)

**Comment by alesanchezr** [comment]
Revisar ultima version en "FINAL"



![Image](https://user-images.githubusercontent.com/426452/182479941-932bae71-f5cf-4dd4-a041-caa8ce827523.png)

**Comment by alesanchezr** [comment]
las flechas aules a veces saltan la linea, usa flex en el padre (para q no salte la linea) y luego fit contentn en el padre del padre
