### ISSUE TITLE
Tell people after applying or RMI that the're going to get a call from Admissions

### ISSUE THREAD

**Issue by mafecasvi** [4GeeksAcademy/About-4Geeks-Academy#2994]
<img width="1345" alt="Screen Shot 2022-07-27 at 11 00 58 AM" src="https://user-images.githubusercontent.com/49531247/181281030-32ed62a2-eb29-46ea-bb6d-4c9044d4c203.png">
<img width="1330" alt="Screen Shot 2022-07-27 at 11 00 38 AM" src="https://user-images.githubusercontent.com/49531247/181281060-7bd78f81-22e9-4d7b-9bdd-161dec8917c9.png">

**Comment by alesanchezr** [comment]
Me aclaras mas este tema? Dices que pongamos eso a la derecha en los bullets?
