### ISSUE TITLE
Create Blog: "Cuanto gana un desarrollador" en Colombia, Costa Rica, Ecuador, Mexico, Peru y Venezuela

### ISSUE THREAD

**Issue by mafecasvi** [4GeeksAcademy/About-4Geeks-Academy#2995]
"Cuánto gana un desarrollador en Chile" is the blogpost with best perfomance in terms of organic traffic. Let's create the same content for other Latam locations.

CC: This is an insight from Daniel

![Image](https://user-images.githubusercontent.com/49531247/181283247-a502a298-104c-4a86-a94c-293c3114d36e.png)

**Comment by alesanchezr** [comment]
- [ ] Preguntar a michael page por datos de latam.
- [ ] Tropicalizar los articulos con: Salarios en ese pais, si e spo posible por ciudad.
- [ ] Principales empleadores.
- [ ] Leyes freelancer vs empleado

**Comment by alesanchezr** [comment]
Estos son los paises:
- USA
- Espana
- Chile (ya esta creado, buscar actualizar??)
- Colombia
- Canada
- Mexico
- Costa Rica
- Portugal
- Alemania
- Venezuela

**Comment by mafecasvi** [comment]
Vamos a tener artículos para países potenciales como Ecuador y Perú en los que podemos capitalizar tráfico con "quick-wins" como este blogpost? @alesanchezr  CC: @soydanirod , @anceli
