### ISSUE TITLE
Warn applicants with phone number from a different country than the campus

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3004]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=2734%3A4663

```
Hey! We noticed that your phone number is not from the same campus you selected. No problem. We just wanted to let you know.
```

<img width="663" alt="Screen Shot 2022-07-29 at 8 47 34 PM" src="https://user-images.githubusercontent.com/426452/181863725-813d611e-13f1-4018-bd3d-fc4ec39990be.png">

Then show this message after confirmation:

<img width="558" alt="Screen Shot 2022-07-29 at 5 01 20 PM" src="https://user-images.githubusercontent.com/426452/181842577-b71f42f7-94e4-4e22-8e22-886874c5e1bf.png">

**Comment by gustavomm19** [comment]
I did this already in this issue https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/2872

Here is the pr also https://github.com/4GeeksAcademy/website-v2/pull/1374

**Comment by alesanchezr** [comment]
- [ ] Cuando se haga click al botton "its ok, apply to <location>" la modal debe desaparecer aunque el formulario haya fallado.
- [ ] La modal en mobile tiene el layout malo (revisar foto)

![Apply-to-4Geeks-Academy-Bootcamp-·-4Geeks-Academy](https://user-images.githubusercontent.com/426452/183006565-eb593235-9af5-4c1d-aa42-ab8f60e1a596.png)
