### ISSUE TITLE
Plantear componente de mentorias para 3 tipos de usuarios

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3005]
- [ ] Anomino: Ya esta listo.
- [ ] Gratis: tiene limitado cuantas mentorias peude tomar, luego de aprengar para agendar te dice si puedes o no y cuantas te quedan.
- [ ] Pago: si todavia te quedan mentorias, simplemente te dice cuantas y te deja continuar a agendar, puede decir que tienes ilimitado.

**Comment by alesanchezr** [comment]
Repensar el texto de cuantas mentorias quedan disponibles y que hagas upgrade.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=4551%3A14134
