### ISSUE TITLE
Todas las versiones componente "live class"

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3006]
Anonimo: Ya tienes la idea, pones el texto promovioendo la funcionalidad con "read more"
Gratis y pago: Hay dos tipos de eventos, el que sale arriba y los que salen justo debajo mas pequeños, son una lista y pueden ser de uno a 5 eventos y cada uno tiene un boton de ir al evento.

Los eventos pueden ser en 3 dias, o en 10 min... 

Siempre la clase en vivo va a ser el evento mas importante, pero si no hay clase, entonces arriba peude salir un workshop o un coding jam.

Si el evento es un workshop puedes darle click a view more para ver los detalles del evento.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=3733%3A9473
