### ISSUE TITLE
ProfileBubble Component

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3021]
<img width="400" alt="Screen Shot 2022-08-04 at 6 47 27 PM" src="https://user-images.githubusercontent.com/426452/182969298-867f6e8d-92f8-4559-b16e-a6f8c5b14c7c.png">

Similar to Github, the 4Geeks avatar pictures will show a bubble tooltip when hovered with the following information.

- Avatar Picture
- Full Name
- One line bio
- Location
- Skills

Optionally if he bubble shows when the avatar is on the "About your cohort" component, the bubble will also show the user role in that cohort: `Teacher`, `Teacher Assistant` or `Student`

**Comment by ali5uarez5** [comment]
El icono al lado de cohort teacher va a cambiar
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=3557%3A10220

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=3557%3A10220
