### ISSUE TITLE
Sort assets by position on the cohort dashboard (syllabus) and inside the timeline

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3023]
- [ ] Sort assets: Now every asset (assignment, lesson, exercise or project) includes a `position` property that determine its position in the module. Each asset type has a position index independent from the other types.

1. First you will list lessons sorted by position.
2. Then exercises sorted by position.
3. Then the projects sorted by position.
4. Then the quizzes sorted by position.

Note: if the asset does not have a position you can sort with the default order it had before implementing this.

**Comment by ArielCalisaya** [comment]
>Commit [remind message for mandatory projects and sort by position property](https://github.com/breatheco-de/app/commit/a15289818768080c367f1500b1ed63da9370b1f1) created for this issue
