### ISSUE TITLE
Confirm never ending cohorts before submiting

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3033]
When creating or editing a cohort we need to confirm the form submission if the cohort has never_ending=true with the following message:
```
Are you sure you want to create a cohort that doesn't end? Some functionalities will be limited. 
Read more about never ending cohorts.
```

This is an example modal that confirms the event creation or edition, [you can find it in this event creation form befor submiting](https://dev.admin.4geeks.com/events/NewEvent):

<img width="383" alt="Screen Shot 2022-08-09 at 8 01 59 PM" src="https://user-images.githubusercontent.com/426452/183782114-241c402d-0972-4623-88d2-b5dcac1671ee.png">

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-34148-7791523cffe2020c98f3e02005f5918a) 

---
**Source URL**:
[https://admin.4geeks.com/admissions/cohorts/caracas-ft-i](https://admin.4geeks.com/admissions/cohorts/caracas-ft-i)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.5060.134</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x710</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by aayalapalacin** [comment]
modal window works on CohortsDetails.jsx but doesn't work on NewCohort.jsx  (lines 426 to 466 )
got following errors:
<img width="725" alt="image" src="https://user-images.githubusercontent.com/95265085/186257633-ea95804c-d003-4f19-b000-06927ca6f849.png">

<img width="720" alt="image" src="https://user-images.githubusercontent.com/95265085/186257735-9cd7ae72-91c2-4eef-80a0-05156bcbf4fc.png">

<img width="730" alt="image" src="https://user-images.githubusercontent.com/95265085/186257811-5293ef45-2a7e-40f5-acc7-8a799535296e.png">

**Comment by aayalapalacin** [comment]
PR: https://github.com/aayalapalacin/admin
