### ISSUE TITLE
Mentor Post endpoint does not detect academy header

### ISSUE THREAD

**Issue by gustavomm19** [4GeeksAcademy/About-4Geeks-Academy#3045]
When creating a Mentor with `v1/mentorship/academy/mentor` the endpoint does not detect the academy header, instead, it is expecting a `academy` field.

![Image](https://user-images.githubusercontent.com/47191295/184279693-b47b77b3-b834-4305-9fe5-9618bb3c4fda.png)

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/607
