### ISSUE TITLE
Interconectar contenidos relacionados al curso

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3051]
Cuando estoy en el landing de un curso, por ejemplo [fullstack](https://4geeksacademy.com/us/coding-bootcamps/part-time-full-stack-developer).

Cada curso va a tener los siguientes artículos relacionados;

Ingles (para curso de full stack, coding bootcamp)
- How much is a **coding bootcamp** in `<argentina>`
- **Coding bootcamps near** `<argentina>`
- **Online coding bootcamps** in `<argentina>`
- **Coding bootcamp cost** in `<argentina>`
- **Software Developer salaries** in `<argentina>`

Español
- **Aprender a programar** en `<argentina>`
- **Cursos de programacion** en `<argentina>`
- **Bootcamps de programacion** en `<argentina>`
- **Sueldo de programadores** en `<argentina>`

Ingles (para curso de software engineer)
- **Software Engineer** salaries in  `<argentina>`
- **Software Engineer** studies in  `<argentina>`

**Comment by alesanchezr** [comment]
Ultimos retoques faltantes

**Comment by alesanchezr** [comment]
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?node-id=5806%3A3710

![Image](https://user-images.githubusercontent.com/426452/191567187-1bb9a5a9-a225-459f-a8fb-949fbf1ade02.png)

**Comment by alesanchezr** [comment]
We need a way to know which topic cluster belongs to which course.

**Comment by tommygonzaleza** [comment]
Agregar `related_clusers` como arreglo al yml del los cursos

Cuando el page sea course, agarrar la variable "related_clusters" y meterla en el `context` para que este disponible en el query de graphql cuanvo dentro del template de curso.

Test: Un YML de un curso no puede tener vacio los related clusters.

En el graphql query cuando estas renderizando un curso, traete los markdown remark que esten featured, en esos `related clusers`

**Comment by tommygonzaleza** [comment]
Remove space between the posts, they should be aligned with the footer

![image](https://user-images.githubusercontent.com/56565994/211666123-d8905b11-1977-4c83-a9a7-3b26c507c8ed.png)
