### ISSUE TITLE
Socket connection to retrieve online status on avatar component

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3065]
![avatar](https://user-images.githubusercontent.com/426452/184984013-00e97cce-de1f-491a-83db-4a9ce4a5384c.png)

The avatar picture now will be a component that can show two icons:

- `online`=green, `active but offline`=grey, `innactive`=nothing. Someone is "active but offline" if it was connected in the past 48 hrs.
- additionally the component can show an icon on the bottom right (for example the blue hat), this is not related to the socket.

**Comment by alesanchezr** [comment]
waiting for backend to accept auth token as querystring

**Comment by alesanchezr** [comment]
Read: use `?token=<user_token>` on the querystring to authenticate.

**Comment by ArielCalisaya** [comment]
>Issue solved in PR [Websocket integration with online and offline status #429](https://github.com/breatheco-de/app/pull/429)

**Comment by tommygonzaleza** [comment]
- [ ] Implement the hook of `useOnline` that Alejandro shared with you through slack

**Comment by tommygonzaleza** [comment]
It's working well with the implementation suggested by Alejandro
