### ISSUE TITLE
Validar datos de profile academy antes de cambiar de status del mentor 

### ISSUE THREAD

**Issue by marcogonzalo** [4GeeksAcademy/About-4Geeks-Academy#3069]
Este es el user id 3440

Al cambiar de status se debe validar que el staff tenga todos los campos requeridos antes de hacer el cambio: `first_name`, `last_name`, `phone`, `address`.

**Comment by alesanchezr** [comment]
Que significa retirar del staf? lo quieres poner con status inactivo?

**Comment by tommygonzaleza** [comment]
Desde admin.4geeks.com no se puede o no encuentro como modificar el status, por lo que me imagino que se refiere a modificar el status desde el admin de django, ahora se pueden agregar validaciones asi en el admin de django?

La forma que se me ocurre es que cuando le den a guardar los cambios pues confirme que esos datos esten llenos, por lo que seria una validacion para la creacion o alteracion de un profile academy como tal mas que para cuando se modifique el valor del status, pero no se si es el mejor approach

**Comment by tommygonzaleza** [comment]
Agregar validacion a mentorship profiles en vez de profile academy

**Comment by tommygonzaleza** [comment]
### Back End:
Request URL: (PUT) https://github.com/breatheco-de/apiv2/blob/main/breathecode/mentorship/urls.py#L10
View URL: https://github.com/breatheco-de/apiv2/blob/86b9b1cda1ef11206511cecc3ae5a9635a71c171/breathecode/mentorship/views.py#L696
Repository: https://github.com/breatheco-de/apiv2

Validate only user's `name`, `lastname`, and `email`

**Comment by tommygonzaleza** [comment]
Add the unit tests on this file: https://github.com/breatheco-de/apiv2/blob/development/breathecode/mentorship/tests/urls/tests_academy_mentor.py

**Comment by tommygonzaleza** [comment]
You have to validate the data of the `ProfileAcademy` related to this `User` and from the same academy as the `MentorProfile`

**Comment by Andresgarciasch** [comment]
PR: https://github.com/breatheco-de/apiv2/pull/722
<tmr>6<tmr>

**Comment by tommygonzaleza** [comment]
<hrs>6</hrs>
