### ISSUE TITLE
Some errors show like "info" on coralogix

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3070]
We have to make sure they show as fatal errors in order for notifications and alerts to trigger.

<img width="1081" alt="Screen Shot 2022-08-17 at 2 42 58 PM" src="https://user-images.githubusercontent.com/426452/185218287-78a8810c-9543-46f3-afd7-9095040b4877.png">

**Comment by jefer94** [comment]
"status=500" OR "status=501" OR "status=502" OR "status=503" OR "status=504" OR "status=505" OR "status=506" OR "status=507" OR "status=508" OR "status=509" OR "status=510" OR "status=511"
