### ISSUE TITLE
what does // mean in python

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3071]
## Meta Info

- Number of words: 800
- Asset Type: Article (How to)
- Website: 4Geeks.com
- Primary: `what does // mean in python` (please make sure it's a pre-approved keyword).
- Technologies: `python`

## Article Information

Attach link to github markdown file with the draft lesson (even if its not done yet). 
The article mus be publised on one of the academy repositories.

## Additional Info

1. Any recommended approach for the article?
2. Recommended sources or articles for inspiration?

## Requirements for all assets:

- [ ] Use [ContentSEOChecker](http://contentseochecker.com/) and Grammarly to theck your SEO, spelling and readability.
- [ ] Pase in the comments a link to the draft article as a markdown file.
- [ ] Include code examples using syntax highlighter (if possible).
- [ ] Mention the primary keyword on the article title.
- [ ] Have at least 2 `h2` tags and mentrion the primary keyword at least on one of them.
- [ ] On assets with 800+ words include images, animated gifts or videos.
- [ ] Mention the primary keyword a couple of times during the article.

**Comment by rafmanrique** [comment]
[What Does // Mean in Python?](https://github.com/rafmanrique/python_floor_division/blob/main/README.md)

**Comment by tommygonzaleza** [comment]
PR: https://github.com/4GeeksAcademy/About-4Geeks-Academy/pull/3132

**Comment by alesanchezr** [comment]
- [ ] Make sure you wrote the article yourself after reading and learning whatever you need, do not use the "puzzle methodology" (putting pieces together from other articles).

**Comment by rafmanrique** [comment]
- [x] Make sure you wrote the article yourself after reading and learning whatever you need, do not use the "puzzle methodology" (putting pieces together from other articles).

Rewriting of the article:

[What Does // Mean in Python?](https://github.com/rafmanrique/content/blob/what-does-mean-in-python/src/content/how-to/what-does-mean-in-python.md)

PR: https://github.com/breatheco-de/content/pull/893

**Comment by tommygonzaleza** [comment]
- [ ] Add your keyword(s) in the last 100 words

**Comment by rafmanrique** [comment]
- [x] Add your keyword(s) in the last 100 words
- [x] Clean HTML code, only use markdown.

[What Does // Mean in Python?](https://github.com/rafmanrique/content/blob/what-does-mean-in-python/src/content/how-to/what-does-double-slash-mean-in-python-floor.md)

PR: https://github.com/breatheco-de/content/pull/893

**Comment by tommygonzaleza** [comment]
Waiting for video

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
