### ISSUE TITLE
Replace google project id with env variable

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3072]
We have created a new env variable GOOGLE_PROJECT_ID that must be used to replace the hard coded values of the project id `breathecode-197918` on the database.

https://github.com/breatheco-de/apiv2/search?q=breathecode-197918

**Comment by jefer94** [comment]
Pending environment to be configured:
- GOOGLE_PROJECT_ID

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/505
