### ISSUE TITLE
how to split a string in python 23

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3073]
## Meta Info

- Number of words: `800`
- Asset Type: `Article (how to)`
- Primary keyword: `how to split a string in python`
- Technologies: `python` (only one or more preapproved technologies, check admin.4geeks.com).

## Additional Info

1. Any recommended approach for the article?

- [ ] Mention every possible way to split a python string using every single function or trick
- [ ] Include an example highlighted code for each way.
- [ ] Include the example output

## Article Information

Attach link to Github markdown file with the draft lesson (even if its not done yet). 
The article mus be published on one of the academy repositories.

## Requirements for all assets:

- [ ] Use [ContentSEOChecker](http://contentseochecker.com/) and Grammarly to theck your SEO, spelling and readability.
- [ ] Pase in the comments a link to the draft article as a markdown file.
- [ ] Include code examples using syntax highlighter (if possible).
- [ ] Mention the primary keyword on the article title.
- [ ] Have at least 2 `h2` tags and mentrion the primary keyword at least on one of them.
- [ ] On assets with 800+ words include images, animated gifts or videos.
- [ ] Mention the primary keyword a couple of times during the article.

**Comment by rafmanrique** [comment]
## Additional Info
- [x]  Mention every possible way to split a python string using every single function or trick
- [x]  Include an example highlighted code for each way.
- [x]  Include the example output

## Article Information

[How to Split a String in Python](https://github.com/rafmanrique/content/blob/how-to-split-a-string-in-python/src/content/how-to/how-to-split-a-string-in-python.md)

PR: https://github.com/breatheco-de/content/pull/911

## Requirements for all assets:
- [x]  Use [ContentSEOChecker](http://contentseochecker.com/) and Grammarly to check your SEO, spelling, and readability.
- [x]  Pase in the comments a link to the draft article as a markdown file.
- [x]  Include code examples using syntax highlighter (if possible).
- [x]  Mention the primary keyword on the article title.
- [x]  Have at least 2 h2 tags and mention the primary keyword at least on one of them.
- [x]  On assets with 800+ words include images, animated gifts, or videos.
- [x]  Mention the primary keyword a couple of times during the article.

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
