### ISSUE TITLE
Turn markdown bullets into checkboxes

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3077]
We are going to replicate Github.com functionality that converts each github bullet into a checkbox.

<img width="300" alt="Screen Shot 2022-08-17 at 10 28 25 PM" src="https://user-images.githubusercontent.com/426452/185279524-916a9658-d2a0-4b97-b021-28948767d0da.png">

When the student is reading project instructions there will be an indicator on how many checkboxes are inside the instructions and how many of them have already been checked.

Check this video as a reference: https://recordit.co/KTxW7Ab1Ng

The checkboxes will be all over the text, we cannot control were they are or how they look, the only thinkg we can design is how the status will look.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=3857%3A9740

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=3857%3A9740
