### ISSUE TITLE
Translate python pdf guide to include as a downloadable on the website

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3079]
Right now we have [this landing page](https://4geeksacademy.com/es/downloadable/guia-de-python) that when leads fill the form it sends them [this pdf to their email](https://storage.googleapis.com/4geeks-academy-website/downloadables/guia-de-python.pdf).

We need to recreate the exact same thing but in english.

- [x] Get the original source of the PDF (probably on figma), ask @victormgomezp about it.
- [ ] **Duplicate it** and translate all the content to english.
- [ ] Export it to PDF.
- [ ] Send the PDF to @alesanchezr to uploaded to the website and create the landing page.
- [ ] Fork and edit the [4geeks academy downloadables section](https://github.com/4GeeksAcademy/website-v2/tree/master/src/data/downloadable) to include a new YML called `python-crash-course.us.yml` based on the content from the `guia-de-python.es.md` structure, but with all the values in spanish.
- [ ] Show the YML to @alesanchezr during the next SCRUM for validaiton.

Note: we will optimize the downloadable landing for the keyword: `python crash course pdf`

**Comment by victormgomezp** [comment]
https://www.figma.com/file/bSYSWCfePoIHd23Z6rdN4H/GUIA-DE-PYTHON?node-id=0%3A1

**Comment by Lorenagubaira** [comment]
I sent the pdf file to @alesanchezr gmail
