### ISSUE TITLE
cuanto gana un programador en colombia

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3087]
## Meta Info

- Number of words: ~800 
- Primary: `cuanto gana un programador en colombia` (please make sure it's a preapproved keyword).
- Topic Cluster: `cuanto gana un programador` (preapproved cluster).

## Additional Info

- [ ] Siempre cita tus fuentes al nombrar estadisticas, preferiblemente de intituciones del gobierno o nonprofit.
- [ ] Utiliza muchos numeros, todo el post debe ser numero tras numero.
- [ ] Empieza hablando de ciudad de bogota y luego puedes mencionar medellin, barranquilla y otras ciudades importantes.
- [ ] Utiliza el template: landing_post para tener un formato con indice de contenidos.
- [ ] Puedes mencionar salarios de junior, medio y senior. 
- [ ] Incluye in link a el [programa de inteligencia artificial](https://4geeksacademy.com/es/coding-bootcamps/curso-inteligencia-artificial) cuando hables de los seniors y tambien otro cuando hables de las especialidades.
- [ ] Cuanto tardas en ganar como senior? cuanto esperas ganar desde el dia uno?
- [ ] Como ha sido la experiencia de los alumnos colombianos o latinos de 4geeks al empezar a trabajar?
- [ ] Si tienes algun testimonial q valga la pena de un colombiano vamos a ponerle el link.
- [ ] Las diferences especialidades de programacion y como varian los sueldos entre ellas.
- [ ] Puedes mencionar a las empresas que más contratan.
- [ ] Recuerda incluir un call to action dentro del articulo.
- [ ] Pon un link a el [landing en español de la sede de 4geeks en colombia](https://4geeksacademy.com/es/coding-campus/bootcamp-programacion-colombia) con el keyword "aprender a programar en colombia"
- [ ] Pon un link al landing de [curso de programacion desde cero](https://4geeksacademy.com/es/curso-de-programacion-desde-cero/?lang=es).

## Other articles that must be linked and referenced from this one

- [ ] Make sure to include a link to the parent topic cluster.
- [ ] Think hard: What other articles are related and are worth mentioning?

## Requirements for all assets:

- [ ] Use [ContentSEOChecker](http://contentseochecker.com/) and Grammarly to theck your SEO, spelling and readability.
- [ ] Do not start writing this article if the parent topic cluster has not been published yet.
- [ ] When including an internal link, make sure you use the destination landing keyword in between the anchors.
- [ ] Create a draft markdown file, and include in the comments a link to the draft article on github.
- [ ] Include code examples using syntax highlighter (if its a tecnical article).
- [ ] Add links to topic cluster URL inside the article.
- [ ] Add `<call-to-action>` tag, you [can read how here](https://github.com/4GeeksAcademy/website-v2/blob/master/docs/call_to_action.md).
- [ ] Mention the primary keyword on the article title.
- [ ] Have at least 2 `h2` tags and mentrion the primary keyword at least on one of them.
- [ ] On assets with 800+ words include images, animated gifts or videos.
- [ ] Mention the primary keyword a couple of times during the article.
- [ ] Make sure to read [how to write an article on the 4Geeks Website here.](https://github.com/alesanchezr/website-v2/blob/master/docs/write_an_article.md)

**Comment by alesanchezr** [comment]
hay que optimizar apra toda latam

**Comment by genebrito1** [comment]
https://docs.google.com/document/d/1J1VgbRVAkpR-2lJcJD886YVA9CQ83GzhTidXx3q83Rw/edit

**Comment by genebrito1** [comment]
Link optimizado con el país. https://docs.google.com/document/d/1J1VgbRVAkpR-2lJcJD886YVA9CQ83GzhTidXx3q83Rw/edit
