### ISSUE TITLE
New validations to the create and update mentor form 

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3094]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-34351-7dc6e892cd0e30ab18de106da6ee7820) 

 Make sure to update both compennts, the one that creates a mentor and the other that updates the mentor.

The help component already exists with the tooltip and you can find it on the [form when you edit a cohort](https://dev.admin.4geeks.com/admissions/cohorts/caracas-pt-xxxvii).

<img width="267" alt="Screen Shot 2022-08-18 at 6 58 59 PM" src="https://user-images.githubusercontent.com/426452/185509531-19d01fcc-2a41-4243-afb0-c23fb6f04cd8.png">

---
**Source URL**:
[https://admin.4geeks.com/mentors/103](https://admin.4geeks.com/mentors/103)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.5060.134</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x711</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by alesanchezr** [comment]
I cannot type on the book URL field

**Comment by aayalapalacin** [comment]
> I cannot type on the book URL field

resolved.

**Comment by aayalapalacin** [comment]
PR: https://github.com/aayalapalacin/admin

**Comment by alesanchezr** [comment]
Layout bug: the questionmar and note hsould be on the same line (wrap them on a parent with display flex.

**Comment by aayalapalacin** [comment]
PR: https://github.com/aayalapalacin/admin

> Layout bug: the questionmar and note hsould be on the same line (wrap them on a parent with display flex.

fixed.
 PR: https://github.com/aayalapalacin/admin
