### ISSUE TITLE
New "programs" section on the website

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3098]
This website will live under: 4geeksacadmy.com/programs

- [ ] Show all the programs we currently offer.
- [ ] This may contain programs that are not open yet (in development) and you can join the waiting list to get notified once the next one starts.
<img width="1433" alt="Screen Shot 2022-08-19 at 11 30 54 AM" src="https://user-images.githubusercontent.com/426452/185654194-413ec460-70d0-43e2-9ca3-08c7766400f7.png">

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?node-id=5813%3A4257

**Comment by alesanchezr** [comment]
Haz que uno de los cursos este "próximamemnte" y que te puedas unir al waiting list.

`Get notified when the program is launched.`

**Comment by alesanchezr** [comment]
Ok no vamos a poner nada aqui, este issue queda cerrado porque lo de coming soon lo vamos a poner dentro del landing.
