### ISSUE TITLE
Implement a github action to test projects integrity

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3099]
This is the template for every project at 4Geeks:
https://github.com/4GeeksAcademy/project-template

- [x] We are going to validate the learn.json based on a centralized schema that will be [published always here](https://github.com/4GeeksAcademy/project-template/blob/main/.github/learn-schema.json), we are going to o a fetch to obtain it before doing the validations in the script. 
- [x] Start by defining what the learn-schema.json standard  its going to be used (I'm proposing one, but only as a reference of what are the mandatory fields right now), you can use [this library](https://github.com/tdegrunt/jsonschema) or a solid alternative to find a json standard that we can later easily maintained.
- [x] Make sure the github action runs and tests the project on every commit.
- [x] After the github action runs it must update the learn.json and include a "validation_status" property with possible values as "success", "warning" or "error" depending on what happened.
- [x] After the github action runs it must update the learn.json and include a "validation_at" property with a UTC timestamp when the last validation runed.

Validations to be check on the script:
- [x] There must be a learn.json
- [x] The learn.json must follow the learn-schema.json standard.
- [x] The preview must exists and not be 404.
- [x] the readme must contain at least 800 characters.

**Comment by tommygonzaleza** [comment]
I don't have permission to mark any of the tasks from this issue or modify the project where the GitHub action should be.

Anyway, here is my solution for the problem: https://github.com/tommygonzaleza/project-template. There is the yml with the validation and the schema lightly modified. 

Let me know when you grant me permission to create a PR

**Comment by tommygonzaleza** [comment]
This is what it looks like when you run it:
![image](https://user-images.githubusercontent.com/56565994/185814055-889eca11-be77-44e8-98f2-ba15d08f19de.png)

It's still taking so long (28s) But it is related to the LearnPack installation.

**Comment by tommygonzaleza** [comment]
Let me know if you want to modify the message that is shown

**Comment by tommygonzaleza** [comment]
Language auto-detection

**Comment by tommygonzaleza** [comment]
Using camelCase for the variable's names as is the convention:
https://stackoverflow.com/questions/5543490/json-naming-convention-snake-case-camelcase-or-pascalcase

**Comment by tommygonzaleza** [comment]
All validations added

**Comment by tommygonzaleza** [comment]
Here is the commit with the last changes: https://github.com/4GeeksAcademy/project-template/commit/72f81635b53efbc806697552dc050dc74e5898d7
