### ISSUE TITLE
Mentor bills not generating correctly

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3110]
According to @pbullor bills are not generting correctly.

- He usually generates bills on the 24th of every month, the system generates from the 1st to the 24th.
- Then, 6 days later he deletes the bill and generates again: the system generates one from the 1st to the end of the month.
- Then the system generates another bill only if we are already in the next month.

Bug

Apparently he deleted the bill from the 1st to the 24th and pressed "generate bills" again but the system is not generating the new bills, its not doing anything now.

**Comment by jefer94** [comment]
PR https://github.com/breatheco-de/apiv2/pull/518

**Comment by alesanchezr** [comment]
Implement new status "RECALCULATE" to bills that will be set when ANY session from the bill is updated.

This means that instead of recalculating immedialy we will tell the user to trigger a relaculation when he is finished with the session updates.
