### ISSUE TITLE
Write a welcome tutorial for the writers

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3111]
- [x] Very warm, happy and welcoming wording and tone.
- [x] How are the articles going to be assigned? The can go the [assigned to me](https://github.com/issues/assigned) section.
- [x] Mention the weekly scrum meeting for freelancers.
- [ ] How to approach the articles? Best practices?
- [x] How are they going to be paid (freelances module).

**Comment by tommygonzaleza** [comment]
https://www.notion.so/4geeksacademy/Writers-Welcome-Tutorial-6a056b9a89d74b51b47692998d6d679f
