### ISSUE TITLE
El buscador de estudiantes para generar el certificado siempre me devuelve los mismos resultados, sin importar lo que busque

### ISSUE THREAD

**Issue by marcogonzalo** [4GeeksAcademy/About-4Geeks-Academy#3112]
No encuentro a una estudiante porque la búsqueda no envía al backend lo que intento filtrar
`GET | https://breathecode.herokuapp.com/v1/admissions/cohort/user?academy=madrid-spain&roles=STUDENT&educational_status=ACTIVE,GRADUATED`
 y el autocompletado siempre me devuelve los mismos estudiantes, la mayoría, graduados hace mucho tiempo:

**Comment by alesanchezr** [comment]
En que vista es esto? URL? Siempre intenta poner una foto.

**Comment by alesanchezr** [comment]
En que vista es esto @marcogonzalo ? URL? Siempre intenta poner una foto.

**Comment by marcogonzalo** [comment]
Perdona, nunca había usado el buscador del listado de certificados y por eso asumí que se entendería que era en el fomrulario para generar los certificados. 

Botón de Generar certificados > Formulario > Segundo desplegable.
