### ISSUE TITLE
Bug en las asistencias

### ISSUE THREAD

**Issue by ehiber** [4GeeksAcademy/About-4Geeks-Academy#3118]
- [ ] No se esta reportando bien la asistencia desde el front end, estabamos en el dia 4 pero sin embargo el payload que se mando al backend reporto algunos alumnos como dia 0.
- [ ] Al momento de [visualizar la asistencia](https://github.com/breatheco-de/attendancy) ocurre otro problema que tal vez es lo mismo, pero todas las asistencias salen con el dia cero en lugar de dia 4.

Revisar este video: https://drive.google.com/file/d/1RNl86ue9piNWqtpFRnIFVKEYP_eQfx4_/view?usp=sharing

Video de Eder explicando el problema:
https://www.loom.com/share/e4284e9623b34c0686a29922259028f2

Detalle: 
No avanza de día y se modifica un día fijo, en el caso del curso de Eder se quedó en el día 11 y en lo que ha guardado dia 12 y 13, se ha sobreescrito el día 11. 
Este es el madrid-fs-pt-25 específicamente

En mi caso pasa igual en el curso de FRONT END DEVELOPMENT - Caracas FT I, con diferencia que se sobreescribe el dia 1

**Comment by alesanchezr** [comment]
@ehiber necesito reunirme contigo para confirmar si el bug es front end o backend.

**Comment by ehiber** [comment]
Video con pestaña en network

https://drive.google.com/file/d/1RNl86ue9piNWqtpFRnIFVKEYP_eQfx4_/view?usp=sharing
