### ISSUE TITLE
Migrate instagram-bootstrap to bootstrap v5

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3122]
- [x] Build the project with bootstrap 5
- [x] Re take all the screenshops
- [x] Deploy the solution to the `solution` branch.
- [x] Update the instructions to make sure there is no reference to bootstrap 4 anymore.

https://github.com/breatheco-de/exercise-instagram-feed-bootstrap

**Comment by alesanchezr** [comment]
la imagen animada esta muy pequeña

**Comment by tommygonzaleza** [comment]
El gif ya fue cambiado, de todas formas al comprimirlo pierde un poco la calidad, avisame que tal te parece
