### ISSUE TITLE
Warn teacher about number of days when taking attendancy

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3146]
The `syllabus.days` property will eventually be migrated to `syllabus.modules` for better accurracy. 

- [ ] Make the code to be compatible with a syllabus json that contains either `syllabus.days[]` or `syllabus.modules[]`

```js
// This is how you can have the syllabus be compatible with both.
const modules = syllabus.days || syllabus.modules;
```

The syllabus json comes now with start coming with a `syllabus.modules[].duration_in_days`.
This means, that one "module" can have a duration of one or many days.

When the user is taking attendancy he is supposed to specify in which current module is going to be taught.

- [x] Warn the teacher about duration, if the `syllabus.days[].duration_in_days` for a module is `1 days` but the teacher is staying with the same module again (according to the cohort log) show a confirmation message saying: `You are goig to slow. Are you sure you want to keep teaching <Module name>? The suggested duration for the this module is <1> days and you have only covered for <1> days.`
- [ ] Also warng the opposite, if the syllabus.days[].duration_in_days is more than the days that the teacher has covered the module according to the log, then warn the teacher: `You are going to fast `Are you sure you want to start teaching <Module name>? The suggested duration for the previous module was <2> days and you have only covered for <1> days.`

Use the `corhot.history_log` to get the information about what module was taught yesterday.

**Comment by tommygonzaleza** [comment]
It's showing the warning when the teacher tries to take the attendancy anyway, it has a bug, I recorded and explained it here: https://www.loom.com/share/9c17e92d10da4603ad8881d61f5db776

**Comment by alesanchezr** [comment]
lets wait for jefferson

**Comment by tommygonzaleza** [comment]
- [ ] La cuenta de los dias que lleva en un modulo no es correct, acumula la de los dias anteriores

**Comment by tommygonzaleza** [comment]
Sigue sin tomar bien la cuenta de los dias cuando tomas la asistencia, si tomas la asistencia de un modulo en mas de un dia, a veces acumula dias anteriores en la cuenta

**Comment by tommygonzaleza** [comment]
Utiliza el cohort log para chequear en que dias se dio el currentModule (De cada uno de los dias del cohort log) y lo comparas con el currentModule que el teacher esta tomando para la asistencia, luego chequeas el tiempo esperado en este modulo con la suma que obtuviste anteriormente para chequear si es mayor la cantidad de dias que se dio ese modulo, de ser asi, muestras el warning con esa cuenta de dias

**Comment by ArielCalisaya** [comment]
> No me esta permitiendo escoger un modulo al momento de tomar la asistencia https://www.loom.com/share/d0a36cd5a5b0478d90260859888ec90e

@tommygonzaleza now fixed in [this line](https://github.com/breatheco-de/app/pull/536/files#diff-b155d4a52cbeb1a8261f232571d9a394f7408654d111a5dfa58eb6a86a2e321aR75)

**Comment by tommygonzaleza** [comment]
It should warn the teacher when the you are teaching the same module from one more day than suggested and so on

**Comment by tommygonzaleza** [comment]
Problem fixed, maybe we should change the message shown, what do you think @alesanchezr ?

**Comment by tommygonzaleza** [comment]
Change message from:

```
Are you sure you want to start teaching <strong>{{module}}</strong>? You have been teaching the current module for {{repeated}} days and the suggested duration is {{expected}} days.
```

To:

```
Are you sure you want to start teaching <strong>{{module}}</strong>? You are about to teach the current module for {{repeated+1}} days and the suggested duration is {{expected}} days.
```
