### ISSUE TITLE
Loom videos not loading on projects inside 4geeks.com

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3149]
This [todo list project](https://4geeks.com/syllabus/miami-downtown-xix/code/todo-list) has a video from Loom that its not loading correctly on 4geeks.com when the "video tutorial" button is clicked.

![4Geeks (3)](https://user-images.githubusercontent.com/426452/187494915-b5c41263-afe6-44d3-ae48-648b474a1e72.png)

## How to solve this?

1. Try making it load.
2. If you cannot then open it on a new window and don't show the video player inside the lesson

**Comment by ArielCalisaya** [comment]
The url of the video not exists
[video received](https://www.youtube.com/watch?v=https://www.loom.com/share/610516d1db32405a80fc43c7e5456634)
