### ISSUE TITLE
Implement learnapck audit command and include `autoplay: false` on old projects

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3150]
- [x] Build a list of all the prjects that will be modified to include the autoload and the audit, add the list here.
- [ ] Include git audit commenct githuba action.

**Comment by tommygonzaleza** [comment]
Projects that will be modified:

1. https://github.com/4GeeksAcademy/react-flask-hello

**Comment by tommygonzaleza** [comment]
- [ ] https://github.com/4GeeksAcademy/react-flask-hello
- [ ] https://github.com/4GeeksAcademy/landing-page-with-node
- [ ] https://github.com/4GeeksAcademy/build-your-full-stack-developer-resume
- [ ] https://github.com/4GeeksAcademy/boosting-algorithms-project-tutorial
- [ ] https://github.com/4GeeksAcademy/machine-learning-final-project
- [ ] https://github.com/4GeeksAcademy/flask-rest-hello
- [ ] https://github.com/4GeeksAcademy/html-hello
- [ ] https://github.com/4GeeksAcademy/flask-api-vanillajs-boilerplate
- [ ] https://github.com/4GeeksAcademy/machine-learning-python-template
- [ ] https://github.com/4GeeksAcademy/expressjs-rest-hello
- [ ] https://github.com/4GeeksAcademy/cookiecutter-data-science
- [ ] https://github.com/4GeeksAcademy/django-rest-hello
- [ ] https://github.com/4GeeksAcademy/wordpress-hello
- [ ] https://github.com/4GeeksAcademy/final-project-full-stack
- [ ] https://github.com/4GeeksAcademy/react-hello-flux
- [ ] https://github.com/4GeeksAcademy/react-hello-webapp
- [ ] https://github.com/4GeeksAcademy/vanillajs-hello
- [ ] https://github.com/4GeeksAcademy/react-hello

**Comment by tommygonzaleza** [comment]
Don't have a preview image:
- https://github.com/4GeeksAcademy/machine-learning-final-project
- https://github.com/4GeeksAcademy/data-preprocessing-project-tutorial
- 

I don't have permission to, here is the PR:
- https://github.com/breatheco-de/starwars-data-model-typeorm-node/pull/2
- https://github.com/breatheco-de/calculus-and-algebra-problems-with-python/pull/5
- https://github.com/breatheco-de/exercise-todo-list-react-context/pull/3
- https://github.com/breatheco-de/jwt-authentication-with-flask-react/pull/7
- https://github.com/breatheco-de/exercise-starwars-blog-api/pull/10
-
