### ISSUE TITLE
how to call a function in javascript

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3151]
## Meta Info

- Number of words: 800 (recommendations: ~800 words for standard articles).
- Asset Type: Lesson, Article, Quiz, Project or Exercise.
- Technologies: `javascript, node, functions` (only one or more pre-approved technologies, check admin.4geeks.com).

## Article Information

Attach link to GitHub markdown file with the draft lesson (even if its not done yet). 
The article mus be published on one of the academy repositories.

## Additional Info

1. Any recommended approach for the article?

- [ ] Use the keyword in the first 100 words.
- [ ] At the top of the article include an example on how call a function easily.
- [ ] Later on: how to call the function as an arrow
- [ ] How to call the function anonymous
- [ ] How to call a class function
- [ ] Very brief explain on what is a function

2. Recommended sources or articles for inspiration?

## Requirements for all assets:

- [ ] Use [ContentSEOChecker](http://contentseochecker.com/) and Grammarly to check your SEO, spelling and readability.
- [ ] Pase in the comments a link to the draft article as a markdown file.
- [ ] Include code examples using syntax highlighter (if possible).
- [ ] Mention the primary keyword on the article title.
- [ ] Have at least 2 `h2` tags and mention the primary keyword at least on one of them.
- [ ] On assets with 800+ words include images, animated gifts or videos.
- [ ] Mention the primary keyword a couple of times during the article.
- [ ] If you have not already, please read [the guide on how to create an article inside the content repository.](https://github.com/breatheco-de/content/blob/master/CONTRIBUTING.md)

**Comment by rafmanrique** [comment]
## Additional Info

1. Any recommended approach for the article?

- [x]  Use the keyword in the first 100 words.

- [x]  At the top of the article include an example on how call a function easily.

- [x] Later on: how to call the function as an arrow

- [x]  How to call the function anonymous

- [x]  How to call a class function

- [x]  Very brief explain on what is a function

## Requirements for all assets:

- [x]  Use [ContentSEOChecker](http://contentseochecker.com/) and Grammarly to theck your SEO, spelling and readability.

- [x]  Paste in the comments a link to the draft article as a markdown file.

- [x] Include code examples using syntax highlighter (if possible).

- [x]  Mention the primary keyword on the article title.

- [x]  Have at least 2 `h2` tags and mention the primary keyword at least on one of them.

- [x]  On assets with 800+ words include images, animated gifts or videos.

- [x]  Mention the primary keyword a couple of times during the article.

- [x]  If you have not already, please read [the guide on how to create an article inside the content repository.](https://github.com/breatheco-de/content/blob/master/CONTRIBUTING.md)

[How to Call a Function in Javascript](https://github.com/rafmanrique/content/blob/how-to-call-a-function-in-javascript/src/content/how-to/how-to-call-a-function-in-javascript.md)

PR: https://github.com/breatheco-de/content/pull/896

**Comment by tommygonzaleza** [comment]
- [ ] Clean HTML code, only use markdown.
- [ ] Change the `sayHi` function to only return "Hello world"
- [ ] Add your keyword(s) in the last 100 words.

**Comment by rafmanrique** [comment]
- [x] Clean HTML code, only use markdown.
- [x] Change the sayHi function to only return "Hello world"
- [x]  Add your keyword(s) in the last 100 words.

[How to Call a Function in Javascript](https://github.com/rafmanrique/content/blob/how-to-call-a-function-in-javascript/src/content/how-to/how-to-call-a-function-in-javascript.md)

PR: https://github.com/breatheco-de/content/pull/896

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>1</hrs>
