### ISSUE TITLE
sqlalchemy join

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3152]
## Meta Info

- Number of words: 800 (recomendations: ~800 words for standard articles).
- Asset Type: Lesson, Article, Quiz, Project or Exercise.
- Technologies: `python, sqlachemy, sql` (only one or more preapproved technologies, check admin.4geeks.com).

## Article Information

Attach link to github markdown file with the draft lesson (even if its not done yet). 
The article mus be publised on one of the academy repositories.

## Additional Info

1. Any recommended approach for the article?

- [ ] Use the keywork in the first 100 words.
- [ ] At the top of the article include an example on how to do a join using sqlachmy and python
- [ ] Very brief explain (no more than 150 words) on what is a join with a read more link to the more laborate explanation.
- [ ] Include several examples on how to do a join
- [ ] Later on you can be more thorough on your explanation on what is a join and sqlalchemt

2. Recommended sources or articles for inspiration?

## Requirements for all assets:

- [ ] Use [ContentSEOChecker](http://contentseochecker.com/) and Grammarly to theck your SEO, spelling and readability.
- [ ] Pase in the comments a link to the draft article as a markdown file.
- [ ] Include code examples using syntax highlighter (if possible).
- [ ] Mention the primary keyword on the article title.
- [ ] Have at least 2 `h2` tags and mentrion the primary keyword at least on one of them.
- [ ] On assets with 800+ words include images, animated gifts or videos.
- [ ] Mention the primary keyword a couple of times during the article.
- [ ] If you have not already, please read [the guide on how to create an article inside the content repository.](https://github.com/breatheco-de/content/blob/master/CONTRIBUTING.md)

**Comment by rafmanrique** [comment]
### Additional Info:
- [x] Use the keyword in the first 100 words.
- [x] At the top of the article includes an example on how to do a join using sqlachemy and python
- [x] Very brief explanation (no more than 150 words) on what is a join with a read-more link to the more elaborate explanation.
- [x]  Include several examples on how to do a join
- [x] Later on, you can be more thorough in your explanation of what is a join and sqlalchemy

### Requirements for all assets:
- [x] Use [ContentSEOChecker](http://contentseochecker.com/) and Grammarly to check your SEO, spelling, and readability.
- [x]  Paste in the comments a link to the draft article as a markdown file.
- [x]  Include code examples using syntax highlighter (if possible).
- [x]  Mention the primary keyword on the article title.
- [x]  Have at least 2 h2 tags and mention the primary keyword at least on one of them.
- [x]  On assets with 800+ words include images, animated gifts, or videos.
- [x]  Mention the primary keyword a couple of times during the article.

[SQLAlchemy Join](https://github.com/rafmanrique/content/blob/sqlalchemy-join/src/content/how-to/sqlalchemy-join.md)

PR: https://github.com/breatheco-de/content/pull/905

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
