### ISSUE TITLE
Landing Page for Coding Introduction course

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3154]
Create v1 of the landing page for the coding introduction course.

You can find the design here: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=3920%3A9812

![Design preview](https://user-images.githubusercontent.com/56565994/187558132-29b9dd39-98c6-4f2f-ae06-1dc86ce6f5e4.png)

The word of the title (meet up) will be replaced:
![image](https://user-images.githubusercontent.com/56565994/187558696-9a6fb796-053b-4065-808b-e5585ddb5daf.png)

- [ ] Create the landing page on the route 4geeks.com/**learn-to-code**
- [ ] The circles in this component should be real online users.
![image](https://user-images.githubusercontent.com/56565994/187559543-fb34aa8c-54c9-4788-a873-f34322ae41b3.png)

- [ ] In the next section you should do basically the same but with the mentors, and if you click on them they should open the bobble component:
![image](https://user-images.githubusercontent.com/56565994/187560316-864ea674-8e39-40ed-9f03-a03a8e628d83.png)

- [ ] On the section of the content, when clicking on each of the buttons it should show its information on the right side:
![image](https://user-images.githubusercontent.com/56565994/187560971-7bf5cc81-ff21-4299-be4c-559a23ecb9be.png)

**Comment by tommygonzaleza** [comment]
Hey @ArielCalisaya, recuerda poner el PR en los issues para poder acceder mas rapido

**Comment by tommygonzaleza** [comment]
Tasks to have this landing page ready to launch:

- [ ] Change the image of first section (Waiting for design)
- [ ] The button of the first section should say enroll now.
- [ ] Change the url from `4geeks.com/learn-to-code/meet-up` to `4geeks.com/learn-to-code`.
- [ ] Use real users, same for the mentors (Waiting for backend)
- [ ] "Enroll"/"Join the next cohort" action should take you to another view with the rest of the details (Waiting for design)
- [ ] Review dark mode

**Comment by alesanchezr** [comment]
This is the endpoint to get users by syllabus: GET `/public/cohort/user?syllabus=coding-introduction&roles=TEACHER,ASSISTANT`

**Comment by alesanchezr** [comment]
The keyword we will used rating with meetup: `Meet up / Gathering / Party / Collect / Chapter`

**Comment by alesanchezr** [comment]
- [ ] The mentors are outside of the container.
- [ ] The events should reach the right of the container (move a little towards the right).
- [ ] New pricing section redesign.
- [ ] New modules design (wait for the content coming from the API).

**Comment by ArielCalisaya** [comment]
>Issue solved here in [PR #423](https://github.com/breatheco-de/app/pull/423)

**Comment by alesanchezr** [comment]
Falta iconos en bubbles
EL toggle de one payment y finance tiene un diseño tipo toggle

**Comment by tommygonzaleza** [comment]
Ya se agregaron los iconos en bubbles y el toggle de payment
