### ISSUE TITLE
Admin task to fill cohort history log based on the attendancy

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3155]
Use [this information](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3148) to build a script that can be runned from the admin asyncronusly and fills the entire history log (all the cohort days) based on the cohort attendace that we can get from google datastore (student activity).

- [ ] Make sure that the log list only has as many items as cohort.current_day
- [ ] If you cannot find any attendance for a single day instead of an empty array live the attendance as null on the json (null means attendance was not taken).

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/540

**Comment by alesanchezr** [comment]
[Use this file as reference](https://github.com/breatheco-de/apiv2/blob/main/breathecode/admissions/utils/cohort_log.py), add teacher_comments with none

TypeError at /admin/admissions/cohort/
get_attendancy_log() takes 1 positional argument but 3 were given

**Comment by alesanchezr** [comment]
Its not bringing real attendancy, make sure it works:

Here is a sample query for latam-pt-ml-1: 
```
GET /v1/activity/cohort/latam-pt-ml-1?slug=classroom_attendance,classroom_unattendance
```

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/583

**Comment by tommygonzaleza** [comment]
It's returning the list with the attendance and nonattendance correctly
