### ISSUE TITLE
Error en slug de mentor al modificar sus servicios

### ISSUE THREAD

**Issue by marcogonzalo** [4GeeksAcademy/About-4Geeks-Academy#3157]
iba a editar uno de mis servicios como mentor y me dice que el slug es inválido y veo que tiene una coma.

![Screenshot 2022-08-31 at 10-27-43 4Geeks Developers Community - Admin](https://user-images.githubusercontent.com/410890/187633507-2d346f7f-08bb-4439-9130-27ac96547e8e.png)

Cuando entro, se ve solo mi nombre como slug. Cuando cambio los servicios y le doy guardar, me mete toda la URL, y luego una coma y mi mi slug. Eso sucede no más presionar el botón, y al realizarse la validación, da error.

**Comment by alesanchezr** [comment]
can u try again and let me know if it works @marcogonzalo ?
