### ISSUE TITLE
Add address to the cohort information

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3158]
For the cohorts that are taught offline we need to add an "address" field that includes:

Street address.
Building.
Room number.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?node-id=5627%3A3218

**Comment by alesanchezr** [comment]
@gustavomm19 esto esta listo para cambiarlo en el landing de cada location.

**Comment by tommygonzaleza** [comment]
![image](https://user-images.githubusercontent.com/56565994/204656717-30535a25-7acb-436f-b51e-a6a8c7007f37.png)

**Comment by tommygonzaleza** [comment]
![image](https://user-images.githubusercontent.com/56565994/204656952-4a54e5ed-2722-4b38-b830-1a5fb4d85d0f.png)

**Comment by tommygonzaleza** [comment]
![image](https://user-images.githubusercontent.com/56565994/204657961-9a53dcb7-f32b-4860-a666-4c8b6785c99f.png)

**Comment by tommygonzaleza** [comment]
This is what the submenus look like now:
![image](https://user-images.githubusercontent.com/56565994/207159344-f1249a2d-ca8f-4a9c-bd60-274506b49479.png)

I think that we shouldn't make the background bigger but an invisible space only to allow the user to pass from the navbar to the options
