### ISSUE TITLE
Upgrades to the list of sessions

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3174]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-34651-648e72f5ffaa0104a9294605a502845d) 

 - [ ] Filter sessions by started_at,created_at (its a doble filter that the first one takes priority, all you have to do is pass a string to the backend sort function with both keywords separated by comma.
- [ ] Remove print and columns icon.
- [ ] Allow filtering by mentor, student and/or service, all the filters must be searchable dropdowns with multiselect.
- [ ] Allow sorting by service.

---
**Source URL**:
[https://admin.4geeks.com/mentors/sessions](https://admin.4geeks.com/mentors/sessions)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 104.0.5112.102</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x709</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by tommygonzaleza** [comment]
Functionality is working fine. Next time remember to have a different branch so the pull request only contains the changes related with this functionality
