### ISSUE TITLE
Delete services in bulk

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3175]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-34653-a5be0a92c3b9333e825d2b8fb11986b5) 

 - [ ] Only allow deleting services that don't have session or mentors.
- [ ] If several ids are given but some are invalid or have errors, at least delete the ones that you can.

---
**Source URL**:
[https://3000-breathecode-admin-okb2nnsvgk5.ws-us63.gitpod.io/mentors/services](https://3000-breathecode-admin-okb2nnsvgk5.ws-us63.gitpod.io/mentors/services)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 104.0.5112.102</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x709</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by tommygonzaleza** [comment]
API's functionality is working fine
