### ISSUE TITLE
Payment flow

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3177]
- [ ] Primero llenas tus datos basicos
- [ ] Luego nos dices en que localidad vives para poder obtener tu zona horaria y eso nos permite mostrarte 3 opciones de 3 upcoming cohorts, debes elegir una para continuar. 
- [ ] Como ultimo paso (opcional con boton de start trial) te mostrarmos el precio y formulario de pago).

**Comment by ali5uarez5** [comment]
Incluir el management suscruptions
