### ISSUE TITLE
Create view for "Live Mentorships" landing page

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3180]
The design should have the sections and information given here: https://4geeksacademy.notion.site/Live-Mentorships-View-04eae1b482c54a00a6356249b208a286

**Comment by tommygonzaleza** [comment]
The design is good, waiting for the responsive design to close the issue

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=4118%3A10718

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=4083%3A10665

**Comment by tommygonzaleza** [comment]
- [ ] Poner este componente en el slice machine

**Comment by tommygonzaleza** [comment]
Waiting for this issue: https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4173
