### ISSUE TITLE
Redesigned submit project component

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3181]
Right now the only thing you can submit when deliver an assignment is a github URL.
Lets change that.

<img width="1402" alt="Screen Shot 2022-09-02 at 11 48 39 PM" src="https://user-images.githubusercontent.com/426452/188254685-0d801753-8c2d-455a-8546-f98ca300d84a.png">

Now lets give the student the option to submit:

- [ ] A URL or a file.
- [ ] Also include a box to display a message that will be coming from `assignment.delivery_instructions`, this will come in markdown format. For example: `Please upload a PDF file that you can download from flowcv.com`
- [ ] If uploading a file, add a note on which formats are supported, for example: `Supported formats: PDF, CSV`
- [ ] Add a box to show error message if any mistake is made.

## Only for the developers

- [ ] The supported formats will be included in the assignment json: assignment.supported_mime
- [ ] If the `assignment.validate_regex_url` option is not null, use that string to validate the URL delivered by the student.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=4103%3A11258

**Comment by alesanchezr** [comment]
Ok @ArielCalisaya here is the info you need from the backend:

`GET /v1/registry/asset/<slug>`, You already use this endpoint, but it now includes 3 more properties:

```bash
    "delivery_instructions": "Add Github URL",
    "delivery_formats": "url",
    "delivery_regex_url": "https://github.com",
```

- [ ] The delivery_formats is a comma separated list of mime types, if its equal to `url` then it means no file upload its required, just a URL.
- [ ] The delivery_instructions are shown to the user in the delivery modal.
- [ ] The delivery_regex_url its only used when validating the URL.

### But what if the delivery_format its not `url`?

For example: application/pdf or image/png, etc.

You will show the drag&drop interface to upload files and call the following endpoint: 
`PUT /v1/assignment/task/<task_id>/attachment` using formdata encoding. [Here is the documentation](https://documenter.getpostman.com/view/2432393/T1LPC6ef#fd4fbc2b-9d62-454a-aee3-b28d08ef1e94).

You can also retrieve all the task attachments with `GET /v1/assignment/task/<task_id>/attachment`

### Other important notes:

A good way to approach rendering the delivery modal will be to wait for the user to open the modal, and fetch for the registry.asset details when it mounts, once you have the asset the information about delivery_formats, instructions and regex_url you can show the modal content.

Also, once the project its delivered you can show the different links to the different files that were uploaded.

We also need to update the [assigments interface](https://4geeks.com/cohort/miami-43/full-stack/v7/assignments) that the teacher uses to review assingments, if the assingment has several files its a good idea to show a tooltip when hovering the github icon, and also replacing the github icon with a generic file icon.

![Image](https://user-images.githubusercontent.com/426452/197938842-f7341157-225c-49ab-aa79-70510a3295d8.png)

**Comment by ArielCalisaya** [comment]
[PR #466](https://github.com/breatheco-de/app/pull/466)

**Comment by tommygonzaleza** [comment]
It's not showing the drag-and-drop interface when adding a different delivery format  like: application/pdf

**Comment by tommygonzaleza** [comment]
- [ ] It's not working when specifying the files that we want to receive (`application/pdf`)
- [ ] It should allow the student to add many files (remember to show the modal with many files)

**Comment by tommygonzaleza** [comment]
- [ ] The delivery url regex is not validating

**Comment by tommygonzaleza** [comment]
This modal's input is not validating the delivery_regex:
![image](https://user-images.githubusercontent.com/56565994/201996565-2ef68027-913e-47c6-b003-390a1af07b25.png)

**Comment by tommygonzaleza** [comment]
Feature added correctly
