### ISSUE TITLE
Make sure the cohort lang just can save in lowercase

### ISSUE THREAD

**Issue by jefer94** [4GeeksAcademy/About-4Geeks-Academy#3191]
![image](https://user-images.githubusercontent.com/3018142/188651019-b0295a20-a0a5-4f42-a4c1-4c268d4b5295.png)

**Comment by tommygonzaleza** [comment]
PR: https://github.com/breatheco-de/apiv2/pull/533

**Comment by tommygonzaleza** [comment]
I already added the changes required in the review

**Comment by tommygonzaleza** [comment]
Fixed problem related to tests
