### ISSUE TITLE
En el programa de Full-Stack de Node.JS Part-Time me dice que tengo un proyecto que es obligatorio pero el programa tiene muchos más "code"

### ISSUE THREAD

**Issue by marcogonzalo** [4GeeksAcademy/About-4Geeks-Academy#3192]
Hemos iniciado varios módulos con sus respectivos code pero uno solo (el de Family Tree) aparece resaltado en amarillo y genera el mensaje que se ve en la imagen.

![image(8)](https://user-images.githubusercontent.com/410890/188691936-d454dd9a-d25e-4641-a16b-12ab14a5a57b.png)
![image(6)](https://user-images.githubusercontent.com/410890/188691943-54eed4ab-6aca-462d-bd2c-6145870eb717.png)

**Comment by alesanchezr** [comment]
Luego de dos semanas de no haber entregado la tarea es que sale el mensaje.
