### ISSUE TITLE
Use checkboxes on the instructions of the project

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3196]
Modify the instructions of the project to include a step-by-step solution with checkboxes.

Repository: https://github.com/breatheco-de/exercise-instagram-post

- [ ] You have to modify the README in both languages.
- [ ] You should specify a very step-by-step solution, including creating the files, adding the structure, to saving the repository on GitHub.

**Comment by rafmanrique** [comment]
- [x]  You have to modify the README in both languages.
- [x]  You should specify a very step-by-step solution, including creating the files, adding the structure, to saving the repository on GitHub.

[English Draft](https://github.com/rafmanrique/exercise-instagram-post/blob/master/README.md)
[Spanish Draft](https://github.com/rafmanrique/exercise-instagram-post/blob/master/README.es.md)

PR: https://github.com/breatheco-de/exercise-instagram-post/pull/25

**Comment by tommygonzaleza** [comment]
- [ ] You should use the boilerplate given in the instructions. Change the screenshots that have the repository structure
- [ ] Change all the HTML code to Markdown
- [ ] Change the black background color procedure to only apply `background: black;` to the body.
- [ ] Add the font family to the asterisk `*` instead of each element.

**Comment by rafmanrique** [comment]
- [x]  You should use the boilerplate given in the instructions. Change the screenshots that have the repository structure
- [x]  Change all the HTML code to Markdown

[English Draft](https://github.com/rafmanrique/exercise-instagram-post/blob/master/README.md)
[Spanish Draft](https://github.com/rafmanrique/exercise-instagram-post/blob/master/README.es.md)

PR: https://github.com/breatheco-de/exercise-instagram-post/pull/25

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>1</hrs>
