### ISSUE TITLE
Translate this content to english

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3197]
File: https://github.com/breatheco-de/content/blob/master/src/content/lesson/building-apis-with-nodejs-expressjs.md

This file should have another translation file.

- [x] Create a file named **building-apis-with-nodejs-expressjs.es.md** for the spanish translation.
- [x] Use the original name for the english translation

**Comment by Lorenagubaira** [comment]
PR: https://github.com/breatheco-de/content/pull/903/files
