### ISSUE TITLE
Add footnote to certificate layout

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3198]
- [ ] Add a new property `bc.certificate.models.LayoutDesign.footnote` to the [LayoutDesign](https://github.com/breatheco-de/apiv2/blob/main/breathecode/certificate/models.py#L67) that can be null as default.
- [ ] Add the footnote at the bottom of the certificate layout (this is the [repository](https://github.com/breatheco-de/certificate)).
- [ ] Here is an [example certificate](https://storage.googleapis.com/certificates-breathecode/4ae7a46bba78dc19b823e124fea120c17b45e044), add the footnote in the same line buf BEFORE the text `verify this...`

**Comment by tommygonzaleza** [comment]
Hey @gustavomm19 para la proxima, intenta hacer una rama diferente para cada issue que resuelvas. Esto para tener un PR diferente para cada issue y que podamos aceptar los cambios de cada uno por separado. Si en alguno de los cambios hay un error, va a frenar los demas issues.

En este caso, si hiciste la rama pero la hiciste a partir de la otra donde tienes los cambios del captcha entonces es casi como si la hubieses hecho en la misma rama

**Comment by tommygonzaleza** [comment]
Reviewed, this functionality is fine, but I found another bug related to a change done before. This is the issue related to it: https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3217
