### ISSUE TITLE
Bills with status "RECALCULATE" must have a warning

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3201]
There is a new status `RECALCULATE` for bc.mentorship.models.bills.status

- [ ] On the admin: If the status is `RECALCULATE` show a an alert on the [bill report](https://admin.4geeks.com/mentors/95/invoice/158) saying: `This bill needs to be recalculated because some of the sessions were modified, please click <a>here to recalculate it</a>`.
- [ ] On the mentor payments show a warning if any of the bills needs to be recalculated: `Some bills need to be recalculated, please generate the bills again`

The endpoint to recalculate is the same as always: `POST /v1/mentorship/academy/mentor/95/bill`

**Comment by tommygonzaleza** [comment]
Cypress test failed, please check the log of the Cypress test and fi the problems

**Comment by tommygonzaleza** [comment]
The code is doing the POST request but that request doesn't have any effect in the frontend, not sure what should happen when a bill is recalculated

**Comment by alesanchezr** [comment]
After recalcutaling lets update the bill on the front end details of the bill, propably you need to use a bigger serializer on POST

**Comment by tommygonzaleza** [comment]
It's not changing the status of the bill, it remains in recalculate even when you click on the recalculate link

**Comment by tommygonzaleza** [comment]
Use this alert component instead of the current one: https://admin-theme.vercel.app/material/snackbar

**Comment by tommygonzaleza** [comment]
It has the background color of the component that we suggested but I would like a lighter red instead, besides that everything is perfect
