### ISSUE TITLE
Bills with status RECALCULATE cannot be updated the status by the user

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3202]
The only way the status of a bill with "RECALCULATE" can change is if the bill is re-generated again. 

The error message must say: `This bill must be regenerated before you can update its status`

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/541

**Comment by tommygonzaleza** [comment]
Tested at postman and it doesn't allow you to change the status of the bill if the current status is RECALCULATE
