### ISSUE TITLE
Language error in Peru/Bolivia

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3206]
![Video from awesomescreenshot.com](https://www.awesomescreenshot.com/web/video/thumbnail/10973609?key=7a74c1a94d0abb346dd3e1d219130de3&size=960) 

<b>Click the link below to watch the video: </b>
 https://www.awesomescreenshot.com/video/10973609?key=7a74c1a94d0abb346dd3e1d219130de3

**Comment by mafecasvi** [comment]
In Peru url, when you change language from English to Spanish, it jumps to Bolivia 
Created by @soydanirod

**Comment by JParedesArtica** [comment]
El bug ya no existe
