### ISSUE TITLE
Teacher assistants misplaced.

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3218]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-34761-b72c9e1341c32605f29b9f870a24f40d) 

---
**Source URL**:
[https://4geeks.com/cohort/miami-xxxv/full-stack/v7](https://4geeks.com/cohort/miami-xxxv/full-stack/v7)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 104.0.5112.102</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x708</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by tommygonzaleza** [comment]
It´s still crossing over the margin:
![image](https://user-images.githubusercontent.com/56565994/189794016-83963553-a659-468a-b0cd-8546f897925b.png)

**Comment by tommygonzaleza** [comment]
If there are more than three teachers, the teacher assistants should go in the next row (Below the teachers)
