### ISSUE TITLE
Use the user's location to show the closest cohorts

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3251]
In the form of the contact's information when enrolling in the coding introduction "meet up", we should get the location (latitude and longitude) of the user from their address (provided by the user in the form).

- [ ] Given the user's latitude and longitude, it should return a list with the cohorts that are closer to the user.
- [ ] Allow the user to start typing address and autocomplete using google maps API and filter better the cohorts that show on the list.

Use the service `GET /v1/admissions/cohort/all?upcoming=true.....`

**Comment by ArielCalisaya** [comment]
>Issue solved here in [PR #423](https://github.com/breatheco-de/app/pull/423)
