### ISSUE TITLE
When opening assets with target blank

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3252]
If the user enters into the URL of a lesson, project or quiz that has target=blank, [for example this one](https://dev.4geeks.com/syllabus/sample-2/read/what-is-an-express-middleware-node), the front end should not request anything to the backend, instead it show show a block of content similar to the modal window  says:

`This content cannot be visualized inside of 4Geeks.com, please on the following button to open it on a new window`

You can still press next at the botton to go to the next content.

**Comment by alesanchezr** [comment]
Get rid of the modal when you are inside displaying the lesson content.

**Comment by ArielCalisaya** [comment]
>Issue solved here in [PR #423](https://github.com/breatheco-de/app/pull/423)
