### ISSUE TITLE
Updates to the GET upcoming cohorts service

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3253]
There is a service to get upcoming cohorts: 
`GET /v1/admissions/cohort/all?upcoming=true&sort=kickoff_date`

We need to update that service so that it can accept the `coordinates` variable on the querystring.

If coordinates is passed, it will calculate the distance between each location and this coordinates and sort the results by proximity, from the nearest to the farthest away.

- [ ] Also, lets include a boolean field on the cohorts called "available_as_sass" with help text: Academies avaiable as SASS will be sold thru 4Geeks.com
- [ ] On the querystring add `sass-true` variable to filter only the cohorts from academies that have `available_as_sass` True.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/554

**Comment by jefer94** [comment]
The word is `sass` or `saas`?
