### ISSUE TITLE
Migrate Zaps to new 4Geeks.com connector on Zapier

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3255]
Lets start by making just one test and we will do the other zaps after we confirm its successfull.

- [x] Connect with one academy at a time, do not use master connection.
- [ ] Replace all zaps from facebook, google and linkeind and make sure there is no other folder with zaps running.
- [x] Old zaps must be renamed with "deprecared" warning and turned off (only if the new one its working correctly).
- [ ] Create a new lead generation app for each academy and source, for example: Facebook Madrid, Facebook Miami, etc. Make sure the zaps have the right app_id and app_key.

**Comment by tommygonzaleza** [comment]
I already added the first zap, now we are waiting to test it in production and make sure it works fine to replace the rest of the zaps

**Comment by tommygonzaleza** [comment]
- [ ] Migrate the rest of zaps in the facebook-ads folder
