### ISSUE TITLE
Application error: a client-side exception has occurred | After log in

### ISSUE THREAD

**Issue by UmiKami** [4GeeksAcademy/About-4Geeks-Academy#3257]
Receiving application error right after log in. Happens in all browsers and different computers.

**Steps to replicate:**

1. Go to https://4geeks.com/login
2. Input credentials or login with github
3. Click submit
4. Throws error immediately right after log in

![image](https://user-images.githubusercontent.com/60261375/190272318-42e2677d-c2dc-43ce-add6-97936e3225fa.png)

**Comment by alesanchezr** [comment]
fixed.
