### ISSUE TITLE
choose program page not loading

### ISSUE THREAD

**Issue by jsowers13** [4GeeksAcademy/About-4Geeks-Academy#3259]
after clicking the "login with github" button on the landing page, I was redirected to 4geeks.com/choose-program . at that page, the main navbar rendered, but the normal page content did not load. instead, I got an error message reading "Application error: a client-side exception has occurred (see the browser console for more information)." Upon reviewing the console, I found an error of TypeError: Cannot read properties of null (reading 'toUpperCase')
    at choose-program-ac4b9bae2b9509b8.js:1:10102

along with a lengthy traceback record.

![image](https://user-images.githubusercontent.com/98606628/190272842-93eeb05c-2d5c-465d-908c-fcd3d7e8ae0f.png)
![Screenshot 2022-09-14 181836](https://user-images.githubusercontent.com/98606628/190272966-18a788cf-15a5-4569-b471-53737c5fb241.png)

**Comment by alesanchezr** [comment]
fixed.
