### ISSUE TITLE
Hola, tengo problemas cuando abro la web 4geeks, que puedo hacer para evitar este error 

### ISSUE THREAD

**Issue by Uhtred28** [4GeeksAcademy/About-4Geeks-Academy#3261]
![Captura de pantalla 2022-09-14 143624](https://user-images.githubusercontent.com/113602912/190400848-f7140cff-ef31-4a67-9fa4-9419d95cd766.png)
![Captura de pantalla 2022-09-14 144224](https://user-images.githubusercontent.com/113602912/190400853-a10c950e-8421-4342-a7e4-4de42db9e756.png)

**Comment by alesanchezr** [comment]
fixed, please refresh cache memory if not working correctly.
