### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by Aleisgar** [4GeeksAcademy/About-4Geeks-Academy#3262]
### Bug description

In the coding introduction program, on Welcome part, Internet Architecture lesson, there is a link that doesn't work. 

![image](https://user-images.githubusercontent.com/101431959/190416196-778750d4-1606-4b65-bebb-a45b928ca164.png)

### Steps to reproduce

Go to this link: [https://www.youtube.com/watch?v=0QRO3gKj3qw](url)

**Comment by jefer94** [comment]
The video is private, please give us access
