### ISSUE TITLE
Member invite is making people login but they dont have a password yet

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3263]
### Bug description

The following view has AllowAny but it does not work, its still a private URL: 
https://github.com/breatheco-de/apiv2/blob/main/breathecode/authenticate/views.py#L1489

### Steps to reproduce

On the admin, look for any invite and open it on a new window

### Expected behavior

It show display the invite information

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/553
