### ISSUE TITLE
Fix password1 and password2 on invite link

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3264]
![4Geeks-](https://user-images.githubusercontent.com/426452/190427215-39226c39-46c4-46b9-ae2b-456944cf6a5e.png)

---
**Source URL**:
[https://breathecode.herokuapp.com/v1/auth/member/invite/257149869971577380110823907690178587329](https://breathecode.herokuapp.com/v1/auth/member/invite/257149869971577380110823907690178587329)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 104.0.5112.102</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1439x708</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by tommygonzaleza** [comment]
The frontend solution is missing, you should also change the form in the frontend

**Comment by gustavomm19** [comment]
I dont know if there is any frontend to modify, the from is being rendered by the API
