### ISSUE TITLE
Start using Python constants for status, role and language strings

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3265]
Create code to avoid constants from being lowercased. 
- [ ] When a POST or PUT is received the serializer should make them uppercase somehow.
- [ ] We a GET is received we search in uppercase event if the querystring came as lowercase.

Lets enforce the rules for the following fields for now:

- [ ] SyllabusSchedule.schedule_type
- [ ] Academy.status
- [ ] Cohort.stage
- [ ] CohortUser.role
- [ ] CohortUser. finantial_status
- [ ] CohortUser. educational_status
- [ ] TimeSlot.recurrency_type

**Comment by jefer94** [comment]
Missing post and put tests https://github.com/breatheco-de/apiv2/pull/559

**Comment by alesanchezr** [comment]
Finish this tests

**Comment by jefer94** [comment]
Closed because we forgot why we reopen this issue
