### ISSUE TITLE
 review attendance doesn't work

### ISSUE THREAD

**Issue by pbullor** [4GeeksAcademy/About-4Geeks-Academy#3303]
### Bug description

When I enter to check attendance the students do not appear.

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/70356168/191285772-4853d253-cf56-4a20-bb1c-27cec8793e78.png">

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/70356168/191285890-8d7da611-6ed3-41a0-afb1-85cd89661226.png">

Link --> https://attendancy.4geeks.com/?cohort_slug=Online-Latam-9&academy=7&token=c38f8a9ec9dc3feb4a63ad2f9729ed96d54154b3

### Steps to reproduce

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/70356168/191285772-4853d253-cf56-4a20-bb1c-27cec8793e78.png">

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/70356168/191285890-8d7da611-6ed3-41a0-afb1-85cd89661226.png">

**Comment by jefer94** [comment]
This is because the cohort slug have uppercase https://github.com/breatheco-de/apiv2/pull/566
