### ISSUE TITLE
On refresh, retrieve host dynamically fro URL or localstorage

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3308]

**Comment by tommygonzaleza** [comment]
As it is not possible to change the environment variables at runtime (https://stackoverflow.com/questions/59971381/change-env-variables-at-runtime), I'm going to add a validation on every line where the `process.env.REACT_APP_API_HOST`, if there is a new host on localStorage or found in the URL (queryString), then that new host will be used
