### ISSUE TITLE
Signup flow form

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3310]
Signup flow: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=4351%3A11918

- [x] The flow starts with the url: `/signup?course=full-stack&plan=trial`
- [x] Based on the URL you can start the rest of the flow.
- [x] The signup button on the `/learn-to-code` page will take you to the old signup/login url `/login` because we want to keep the private beta for now.

## Aditional Info

To retrive cohorts use the same endpoint as always but with coordinates param: 
```
GET /cohort/all?coordinates=<latitude>,<longitude>&saas=true&course=<course_slug>&upcoming=true
```

You can get the [coordinates from the google api like this](https://github.com/4GeeksAcademy/website-v2/blob/master/src/actions.worker.js#L147).

**Comment by ArielCalisaya** [comment]
>Issue solved here in [PR #423](https://github.com/breatheco-de/app/pull/423)

**Comment by tommygonzaleza** [comment]
The flow is perfect

**Comment by alesanchezr** [comment]
Missing integration with saas cohorts,

**Comment by tommygonzaleza** [comment]
When I try to add some text in the input to check for the nearest cohorts, it gives me the following error:

I don't know if I should add an environment key in vercel so this can work
![image](https://user-images.githubusercontent.com/56565994/193637669-e085e832-dc97-4a08-87f5-ff48b229d435.png)
![image](https://user-images.githubusercontent.com/56565994/193637753-56fe4e8d-dda3-4dbe-9987-b8f6412cfddc.png)

**Comment by tommygonzaleza** [comment]
- [ ] Esta dando error (Probablemente por rerender)
- [ ] El boton (De search dates) debe ser del mismo tamaño que el input

**Comment by tommygonzaleza** [comment]
Changes added, now we should wait for the backend to connect with the upcoming cohorts

**Comment by alesanchezr** [comment]
- [ ] When the step 1 is filled you will call and endpoint to POST /auth/subscribe and create a new invite, that invite will come with status "WAITING_LIST" (probably).
- [ ] After steps 2 and 3 are filled, you will `PUT /aush/subscribe/<invite_id>` with the cohort and academy id, if the system answers with invite status "ACCEPTED" and a session token you will use that token and redirect user to the dashboard.
- [ ] If the system answers with invite status: "WAITING_LIST" you will send the user to the waiting list.

Note: if the user is already logged in, there is not need to step 1, and you can POST /auth/scrubscribe/<invite_id> on step two (instead of PUT).

**Comment by alesanchezr** [comment]
Waiting for backend: https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3470
