### ISSUE TITLE
cuanto gana un desarrollador en venezuela

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3314]

**Comment by janethkalaouz** [comment]
https://docs.google.com/document/d/1GND-YdzAQ_VQX7OXOPXO76hCOaC-TGVn/edit?usp=sharing&ouid=101554520054120089850&rtpof=true&sd=true

**Comment by alesanchezr** [comment]
Optimizar para el keyword que sale aqui en la tarjeta
