### ISSUE TITLE
4Geeks Admin tiene inconsistencias en crear el certificado

### ISSUE THREAD

**Issue by ehiber** [4GeeksAcademy/About-4Geeks-Academy#3335]
### Bug description

Se creó correctamente según el modal pero aparece como error  y que debe +12000 tareas.

He revisado la pestaña de network y no encontré información que fuera relevante. 

![image](https://user-images.githubusercontent.com/56272634/191750799-964477a1-a5ec-4d83-9b6a-049c68144eb3.png)

### Steps to reproduce

Generar el certificado a Nati de la cohorte 19 en madrid pt.

**Comment by tommygonzaleza** [comment]
The problem was fixed before
