### ISSUE TITLE
Markdown parser is not identifying code blocks

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3337]
- [ ] If a code block doesn't have an empty line before and after, it fails to show as block code
- [ ] It doesn't recognize code blocks with the type `bash session`

**Comment by ArielCalisaya** [comment]
>Issue solved here in [PR #423](https://github.com/breatheco-de/app/pull/423)

**Comment by tommygonzaleza** [comment]
It's still not working, this is how it looks like at this moment: 
![image](https://user-images.githubusercontent.com/56565994/192579121-45f32923-a7c9-4d61-9a0d-6920ece7bee9.png)

This is happening with `sqlalchemy-join` article. I already added it in the dev server

**Comment by alesanchezr** [comment]
Bug still happening with https://github.com/breatheco-de/content/edit/master/src/content/how-to/sqlalchemy-join.md

**Comment by tommygonzaleza** [comment]
The error's still happening, I saw you added some changes to the readme that's failling, maybe you can explain more about why is that required and why it can't work without those changes. That way we can avoid this error from happening again
