### ISSUE TITLE
Fix all the PR's you can on 4geeksacademy and breathecode repositories

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3338]
![Video from awesomescreenshot.com](https://www.awesomescreenshot.com/web/video/thumbnail/11262632?key=93924eb984d01f166d98d983ceb54d83&size=960) 

<b>Click the link below to watch the video: </b>
 https://www.awesomescreenshot.com/video/11262632?key=93924eb984d01f166d98d983ceb54d83

**Comment by tommygonzaleza** [comment]
https://github.com/4GeeksAcademy/
