### ISSUE TITLE
Job pages still visible when property `open` is false

### ISSUE THREAD

**Issue by ArielCalisaya** [4GeeksAcademy/About-4Geeks-Academy#3340]
### Example "Career Support Coordinator" has property `open: false` and still showing in job page
>Occurs in: https://github.com/4GeeksAcademy/website-v2/blob/master/src/templates/jobs.js

![Screenshot (13)](https://user-images.githubusercontent.com/51676628/192040832-7975e904-bcf1-4ce2-85df-2930363ab1ae.png)

**Comment by alesanchezr** [comment]
Dont hide from the list based on open: false, instead hide if visibility == 'hidden' or visibility == 'unlisted'.

Open or close does not hides anything, but it shows a warning that the job is not accepting candidates and hides the button to apply.
