### ISSUE TITLE
How to reverse a list in python

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3351]
## Meta Info

- Number of words: 1100
- Asset Type: Article (How to)
- Website: 4Geeks.com
- Primary: `How to reverse a list in python` (please make sure it's a pre-approved keyword).
- Technologies: `python`

## Article Information

Attach link to github markdown file with the draft lesson (even if it's not done yet). 
The article mus be publised on one of the academy repositories.

## Additional Info

1. Add the possible ways to reverse a list in python

## Requirements for all assets:

- [ ] Use [ContentSEOChecker](http://contentseochecker.com/) and Grammarly to check your SEO, spelling, and readability.
- [ ] Pase in the comments a link to the draft article as a markdown file.
- [ ] Include code examples using syntax highlighter (if possible).
- [ ] Mention the primary keyword on the article title.
- [ ] Have at least 2 `h2` tags and mention the primary keyword at least on one of them.
- [ ] On assets with 800+ words include images, animated gifs, or videos.
- [ ] Mention the primary keyword a couple of times during the article.

**Comment by rafmanrique** [comment]
### Additional Info:

[x] Add the possible ways to reverse a list in python

### Requirements for all assets:

[x] Use [ContentSEOChecker](http://contentseochecker.com/) and Grammarly to theck your SEO, spelling and readability.

[x] Paste in the comments a link to the draft article as a markdown file.

[x] Include code examples using syntax highlighter (if possible).

[x] Mention the primary keyword on the article title.

[x] Have at least 2 h2 tags and mention the primary keyword at least on one of them.

[x] On assets with 800+ words include images, animated gifts or videos.

[x] Mention the primary keyword a couple of times during the article.

[x] If you have not already, please read [the guide on how to create an article inside the content repository.](https://github.com/breatheco-de/content/blob/master/CONTRIBUTING.md)

[How to Reverse a List in Python](https://github.com/rafmanrique/content/blob/how-to-reverse-a-list-in-python/src/content/how-to/how-to-reverse-a-list-in-python.md)

PR: https://github.com/breatheco-de/content/pull/1003

**Comment by tommygonzaleza** [comment]
Test is not passing in the admin, it can't be pushed yet, we have to solve this before closing the issue

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
