### ISSUE TITLE
Python list extend method

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3354]
## Meta Info

- Number of words: 800
- Asset Type: Article (How to)
- Website: 4Geeks.com
- Primary: `Python list extend method` (please make sure it's a pre-approved keyword).
- Technologies: `python`

## Article Information

Attach a link to the GitHub markdown file with the draft lesson (even if it's not done yet). 
The article must be published in one of the academy repositories.

## Additional Info

1. Describe the method and the case scenarios.

## Requirements for all assets:

- [ ] Use [ContentSEOChecker](http://contentseochecker.com/) and Grammarly to check your SEO, spelling, and readability.
- [ ] Pase in the comments a link to the draft article as a markdown file.
- [ ] Include code examples using syntax highlighter (if possible).
- [ ] Mention the primary keyword on the article title.
- [ ] Have at least 2 `h2` tags and mention the primary keyword at least on one of them.
- [ ] On assets with 800+ words include images, animated gifs, or videos.
- [ ] Mention the primary keyword a couple of times during the article.

**Comment by rafmanrique** [comment]
### Additional Info

- [x] Describe the method and the case scenarios.

### Requirements for all assets:

- [x] Use [ContentSEOChecker](http://contentseochecker.com/) and Grammarly to theck your SEO, spelling and readability.

- [x] Paste in the comments a link to the draft article as a markdown file.

- [x] Include code examples using syntax highlighter (if possible).

- [x] Mention the primary keyword on the article title.

- [x] Have at least 2 h2 tags and mention the primary keyword at least on one of them.

- [x] On assets with 800+ words include images, animated gifts or videos.

- [x] Mention the primary keyword a couple of times during the article.

[Python List Extend Method](https://github.com/rafmanrique/content/blob/python-list-extend-method/src/content/how-to/python-list-extend-method.md)

PR: https://github.com/breatheco-de/content/pull/1025

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>1</hrs>

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>1</hrs>
