### ISSUE TITLE
How to update python on windows

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3355]
## Meta Info

- Number of words: 800
- Asset Type: Article (How to)
- Website: 4Geeks.com
- Primary: `How to update python on windows` (please make sure it's a pre-approved keyword).
- Technologies: `python`

## Article Information

Attach a link to the GitHub markdown file with the draft lesson (even if it's not done yet). 
The article must be published in one of the academy repositories.

## Requirements for all assets:

- [ ] Use [ContentSEOChecker](http://contentseochecker.com/) and Grammarly to check your SEO, spelling, and readability.
- [ ] Pase in the comments a link to the draft article as a markdown file.
- [ ] Include code examples using syntax highlighter (if possible).
- [ ] Mention the primary keyword on the article title.
- [ ] Have at least 2 `h2` tags and mention the primary keyword at least on one of them.
- [ ] On assets with 800+ words include images, animated gifs, or videos.
- [ ] Mention the primary keyword a couple of times during the article.

**Comment by rafmanrique** [comment]
### Requirements for all assets:

- [x] Use [ContentSEOChecker](http://contentseochecker.com/) and Grammarly to theck your SEO, spelling and readability.

- [x] Paste in the comments a link to the draft article as a markdown file.

- [x] Include code examples using syntax highlighter (if possible).

- [x] Mention the primary keyword on the article title.

- [x] Have at least 2 h2 tags and mention the primary keyword at least on one of them.

- [x] On assets with 800+ words include images, animated gifts or videos.

- [x] Mention the primary keyword a couple of times during the article.

- [x] If you have not already, please read [the guide on how to create an article inside the content repository.](https://github.com/breatheco-de/content/blob/master/CONTRIBUTING.md)

[How to Update Python on Windows](https://github.com/rafmanrique/content/blob/how-to-update-python-on-windows/src/content/how-to/how-to-update-python-on-windows.md)

PR: https://github.com/breatheco-de/content/pull/1007

**Comment by tommygonzaleza** [comment]
I should talk with Alejandro about having only one article that explains how to update python on both windows and mac instead of three different articles

**Comment by tommygonzaleza** [comment]
You have to create a different article for each of the keywords
