### ISSUE TITLE
Validacion de sessiones sin servicio esta incorrecta.

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3363]
mira esta linea de codigo esta mala:
https://github.com/breatheco-de/apiv2/blob/main/breathecode/mentorship/actions.py#L287
Hay mentores que tienen bills ya pagadas que tienen sessions sin servicios y no deberian contarse en la validacion.
Deberiamos validar solamente si hay sessiones que no hayan sido pagadas que esten sin servicios.

**Comment by tommygonzaleza** [comment]
I'm not being able to validate that query as Django doesn't allow me to add mentors without a service associated, anyway the PR has been merged by Alejandro, so I think he tested it
