### ISSUE TITLE
Configuracion de alertas coralogic

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3394]
- [ ] Errores de bd
- [ ] 500
- [ ] Cuando falla un task y hace retry (critical error solo cuando pase muchas veces en una hora).
- [ ] Errores de WebChannels.

**Comment by jefer94** [comment]
New environment variables:

- CORALOGIX_APP_NAME (heroku app)
- CORALOGIX_PRIVATE_KEY

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/593
https://github.com/breatheco-de/apiv2/pull/596

**Comment by jefer94** [comment]
This work 

- alert: https://breathecode.coralogix.com/#/insights/advancedalert?id=0b4381ed-0dac-46f9-928e-cb37c6db8f76&filter=
- warning https://breathecode.coralogix.com/#/query-new/logs?id=3BzV6Sa0ysA&page=0
- error https://breathecode.coralogix.com/#/query-new/logs?id=3BzVrVmnm41&page=0
