### ISSUE TITLE
Unificar botones de "load more" y "more students"

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3398]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-35143-afe51372e4872336c808a4d8fb5a2722) 

- [ ] La caja debe tener un max height que cuando sea alcanzado ya no crece mas sino que sale un scroll interno.
- [ ] Si ya la caja tiene el scrol interno porque llego a su max heigh, entonces cada vez que se apreta "more students" el scroll bajara para poder ver los alumnos que llegaron.
---
**Source URL**:
[https://4geeks.com/cohort/miami-XXXVI/full-stack/v7](https://4geeks.com/cohort/miami-XXXVI/full-stack/v7)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 104.0.5112.102</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x708</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by tommygonzaleza** [comment]
Remove this empty space:
![image](https://user-images.githubusercontent.com/56565994/194920989-058c095d-5cc7-4ea6-b080-ab3b28353b09.png)

**Comment by tommygonzaleza** [comment]
Space fixed
