### ISSUE TITLE
Issue with Populating Student Assignments 

### ISSUE THREAD

**Issue by karlacuevasc** [4GeeksAcademy/About-4Geeks-Academy#3400]
### Bug description

When filtering assignments in 4geeks.com, whenever we select any of the statuses from the "filter by status" drop down... We have to constantly scroll up and down so we are able to see student assignments because they won't populate right away. Please see video below on the issue - 

https://user-images.githubusercontent.com/80592328/194360748-4533dd05-b574-497a-8ca9-e6f82b8e39f4.mp4

### Steps to reproduce

You will have to log into your account in 4geeks.com ---> click on "Assignments" ---> select any of the status under "Filter by Status" drop down then scroll up and down continuously

**Comment by tommygonzaleza** [comment]
It's not showing me the actions in the dev server, I don't know how to replicate it. I tried to get to the URL directly but it show no assignments
