### ISSUE TITLE
ReCaptcha error is not allowing to send forms

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3404]
- [ ] Fix the recaptcha error.

The solution could have a `try` and `catch` so it allows the form to be submitted if Recaptcha fails.

The following error is occurring when a form is tried to be submitted:
<img width="579" alt="image" src="https://user-images.githubusercontent.com/56565994/194374588-821afcb1-d178-4527-9182-f8c9b9f1c198.png">

**Comment by tommygonzaleza** [comment]
It's still not sending the token to the backend

**Comment by alesanchezr** [comment]
Pnla en el localstorage o en el window par aque peudas ver el token
