### ISSUE TITLE
Filters on article comment pipeline

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3413]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-35160-63ac27cbd45ab21cda1baac7bc694959) 
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 104.0.5112.102</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x708</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by tommygonzaleza** [comment]
![image](https://user-images.githubusercontent.com/56565994/203381843-16b69795-2a6d-4ec7-a3de-24624dbd84a3.png)
 These filters should also look for users by name or last name, currently it only looks for the emails

**Comment by tommygonzaleza** [comment]
Besides this the filters are fine

**Comment by tommygonzaleza** [comment]
Change the filters "delivered" and "resolved" to selects so you can filter by for example: "not resolved" or "resolved"

**Comment by tommygonzaleza** [comment]
Add Jeferson's review changes

**Comment by tommygonzaleza** [comment]
The rest is working fine
