### ISSUE TITLE
Add boostrap v5's lesson translation in spanish

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3430]
- [ ] This is the link to the file https://github.com/breatheco-de/content/blob/master/src/content/lesson/bootstrap-tutorial-of-bootstrap-5.md
- [ ] Create a new file named `bootstrap-tutorial-of-bootstrap-5.es.md`

**Comment by tommygonzaleza** [comment]
The file is not published yet so I'll let you know once you can start working on it

**Comment by Lorenagubaira** [comment]
perfect!

**Comment by alesanchezr** [comment]
La lesson esta mala pq los codigos son de bootstrap 4

**Comment by Lorenagubaira** [comment]
PR: https://github.com/breatheco-de/content/pull/1014
