### ISSUE TITLE
Pasos del componente signup pueden estar o no preestablecidos

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3431]
El componente signup define tres principales informaciones:

1. usuario: Si viene nulo, habilitara el primer paso del signup y no se pasara al paso 2 hasta obtenerlos
2. cohort: Si viene nulo, habilitara el segundo paso para elegir la cohort, y no se puede avanzar al tercer paso hasta tener el cohort
3. plan: Si viene nulo, da error (No se puede renderizar). Se debera mandar por la URL.

Cualquiera de las tres informaciones se pueden especificar via url como `user_id`, `cohort_id` y `plan_id`

**Comment by alesanchezr** [comment]
Missing user_id
