### ISSUE TITLE
Landing animation

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3447]
Real Coomunity and Classmates: Devenas de avatares, un gentio.
1-1 Mentorhips
Live Classes
Collaborative Coding Jams: Codigo en crande con los cursorsitos/avatares que tipean
Live Workshops

**Comment by ali5uarez5** [comment]
https://drive.google.com/drive/folders/1NXkLGNTZCnO52DMYozdKSRxWxNRG2hgC?usp=sharing

**Comment by alesanchezr** [comment]
@ArielCalisaya este es el video que vamos a usar en la pagina de [learn to code](https://4geeks.com/learn-to-code).

**Comment by ArielCalisaya** [comment]
@alesanchezr @analiabelo98 
El video deberia tener background transparente

![Image](https://user-images.githubusercontent.com/51676628/202560393-2a9aec02-07fa-40bd-bdba-2d79110b41c7.png)

**Comment by tommygonzaleza** [comment]
Animation has been included maybe we should ask Ali to improve the resolution
