### ISSUE TITLE
Connect to slack if you have not already

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3449]
![Image](https://user-images.githubusercontent.com/426452/203453019-1a66c8be-f74c-41b9-931a-56dde98eadf8.png)

When the user clicks on `Ask in Support Chat` we should ask the user to connect to slack if it has not connected already, it can be a modal window. The user will not be allowed to ask questions otherwise.

La modal debe decir: 

```
<h1>Why connect slack</h1>

Answering your questions it's a priority for us, we will use your slack user id to track response times from our staff members and many other important performance indicators.

Also, thanks to the slack connection, our mentors will be able to instantly retrieve your profile info in depth and have more context as they interact and exchange messages with you. Giving you more efficient answers and suggestions.
```

`Connect my slack` or `Continue without connecting`

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=5403%3A19659&t=oMHc5OtYTNqxs5YO-1
