### ISSUE TITLE
Revision de structura y ortografia de contenidos de full-stack

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3450]
Siguiendo el mismo orden del alumno en 4Geeks.com, entrar al curso de full stack e ir revistando la estcrucura de cada lesson y articulo.

**Comment by Lorenagubaira** [comment]
PR: [https://github.com/breatheco-de/content/pull/1021](https://github.com/breatheco-de/content/pull/1021/files)

**Comment by Lorenagubaira** [comment]
PR: https://github.com/breatheco-de/content/pull/1024

**Comment by Lorenagubaira** [comment]
PR: https://github.com/breatheco-de/content/pull/1032

**Comment by Lorenagubaira** [comment]
https://github.com/breatheco-de/content/pull/1040

**Comment by Lorenagubaira** [comment]
https://github.com/breatheco-de/content/pull/1055/files

**Comment by alesanchezr** [comment]
Ahora esta es la prioridad ahora que ya los proyectos estan bien.

**Comment by Lorenagubaira** [comment]
- [ ] https://github.com/breatheco-de/content/pull/1241
- [ ] https://github.com/breatheco-de/content/pull/1242
