### ISSUE TITLE
A sutdent can't share the certificate

### ISSUE THREAD

**Issue by marcogonzalo** [4GeeksAcademy/About-4Geeks-Academy#3462]
### Bug description

This student tried to share the certificate but all the options throws an error. Asking about the issue I have detected there are some projects needing approval, beside this the student has access to the certificate sharing options.

So, there are two possible errors:
1) The student had all projects approved and something has happened changing the project statuses
2) System is not checking permissions correctly and it is showing a certificate that is not be ready to be shown.

### Steps to reproduce

The student has shared a video reproducing the issue: [https://4geeksacademy.slack.com/files/U0354PWH69Y/F04752NQ81X/clip_de_v__deo__2022-10-17_10_06_22_.mov](https://4geeksacademy.slack.com/files/U0354PWH69Y/F04752NQ81X/clip_de_v__deo__2022-10-17_10_06_22_.mov?origin_team=T0BFXMWMV&origin_channel=D0384HBCY1G)

### Expected behavior

1) Certificate should not be shown if student has projects without approval
2) There should be a message about what is happening to explain better the context. An error on the social  network side is not clear enough and out of our context.

**Comment by alesanchezr** [comment]
[This is the code where the student certificates are gathered](https://github.com/breatheco-de/apiv2/blob/53549c52af3a2816bb07f7870a4160c26363ef86/breathecode/certificate/views.py#L321).

All we need to do its filter the certificates to only include the ones with status PERSISTED.
