### ISSUE TITLE
Rethink project and exercise filters and cards

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3463]
Sobre los filtros:
- Solo tomar en cuenta las tecnologias mas importantes
- Replantear al dificultad
- Tomas menos espacio de la modal

Sobre las project cards:
- [ ] En moviles las tecnologias no pueden tienen mas importancia que el titulo
- [ ] Que hace con la foto
- [ ]

**Comment by alesanchezr** [comment]
-

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=4789%3A14951
