### ISSUE TITLE
Dispute reason modal is ugly

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3464]
- [ ] Clean up the input after submission.
- [ ] Make the modal prettier.
- [ ] On the "date" print tag creation date.
- [ ] The disputed readon should include how long ago was disputed: `disputed 5 months ago`.
- [ ] Under the dispute status, say "Will delete in X days" being `X = disputed_at - 10 days.` if x is a negative number say: "Will delete today"

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-35288-482e22f5179abcaa933d30fa72118056) 

---
**Source URL**:
[https://dev.admin.4geeks.com/growth/settings](https://dev.admin.4geeks.com/growth/settings)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 104.0.5112.102</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x708</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by tommygonzaleza** [comment]
I modified the message "will delete in" and "will delete today" by: "will be deleted in" and "will be deleted today"

**Comment by tommygonzaleza** [comment]
Add similar stylings to this modal

![image](https://user-images.githubusercontent.com/56565994/197885410-e0cf2abd-e40f-4066-ae1c-015854c766fa.png)
