### ISSUE TITLE
Error when updating active campaign academy

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3466]
En el PUT, Estas mandando todo el objecto event_attendancy_automation cuando deberias pasar solo el ID

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-35290-3127b5bf759af3b686c941b6c935727b) 

---
**Source URL**:
[https://dev.admin.4geeks.com/growth/settings?limit=10&offset=0](https://dev.admin.4geeks.com/growth/settings?limit=10&offset=0)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 104.0.5112.102</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x708</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by tommygonzaleza** [comment]
It's still sending the entire object:

![image](https://user-images.githubusercontent.com/56565994/197826661-598eedcf-2c1f-4ce9-b333-e6edc4169260.png)
