### ISSUE TITLE
Updates to the invite creation/update

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3470]
- [ ] Lets add a PUT /auth/subscribe/<token> to be able to update invites as well, as long as you have the token.
- [ ] If an invite its created or update with a cohort that is `available_as_saas` the invite should be immediately accepted and a `session token must be included in the response` to allow the front to login the user immediately or we can provide an endpoint to obtain a session token from an invite token but only during the first 15 min of the invite creation.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/616

**Comment by tommygonzaleza** [comment]
Reviewed and it's returning the token correctly when joining a cohort that is a saas
