### ISSUE TITLE
Add cohort name

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3471]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-35294-ae59b8411bb3df31c298fd38f3083b0c) 

---
**Source URL**:
[https://dev.4geeks.com/signup?course=coding-introduction&plan=pro&cohort_id=388](https://dev.4geeks.com/signup?course=coding-introduction&plan=pro&cohort_id=388)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 104.0.5112.102</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x708</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by tommygonzaleza** [comment]
The cohort name has been added on top of the course name
