### ISSUE TITLE
Update form to add form entry 

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3475]
Update the form that allows people to [add form entry](https://admin.4geeks.com/growth/sales/new):

- [x] The location field must be hidden the current location in the admin
- [x] The automations that show up must only be the ones with a slug
- [x] The tags must only be the ones soft or strong, also there seems to be two different fields with "tags" keep only the dropdown.
- [x] The course must show the slug as well.
- [x] utm_url must have a note: The url when the contact was filling the form, or the chat application if its coming from a chat. E.g: Whatsapp.

**Comment by tommygonzaleza** [comment]
Everything is working as expected with the updated features

**Comment by tommygonzaleza** [comment]
- [ ] Tags should be multiple select (Make it comma-separated slugs when sending it to the server)
- [ ] Automations should also be multiple select (Make it comma-separated slugs when sending it to the server)
