### ISSUE TITLE
When processing pending leads, there should be a success notification and the list should refresh automatically

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3478]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-35316-0b878190a29385448f86579d390a3371) 

- [x] Right now I don't get confirmation.
- [x] Right now the list does not refresh, I have to refresh manually.
- [x] If I try processing a lead that its not pending, it needs to notify error in red.

---
**Source URL**:
[https://admin.4geeks.com/growth/leads?limit=10&offset=0](https://admin.4geeks.com/growth/leads?limit=10&offset=0)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 104.0.5112.102</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x708</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by etolopez** [comment]
pr: https://github.com/breatheco-de/admin/pull/309

h: 3

Error message updated, still need to figure out why it's not refreshing the list

**Comment by tommygonzaleza** [comment]
It's not notifying the error in the network when the lead is not with status pending

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>3.5</hrs>
