### ISSUE TITLE
Make github number `null` and optional in freelancer/issues

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3485]
- [x] Make the `github_number` property null or optional.
- [x] This property is in the [freelance](https://github.com/breatheco-de/apiv2/tree/main/breathecode/freelance) module
- [x] Make sure you are not breaking anything in other files where this property is used

**Comment by etolopez** [comment]
PR: https://github.com/breatheco-de/apiv2/pull/621

h: 0.5

**Comment by alesanchezr** [comment]
Nisiqueira tiene migraciones?

**Comment by etolopez** [comment]
ran migrations, added an Issue and worked well without the GitHub Number as requested.

h: 0.5

**Comment by tommygonzaleza** [comment]
It's working fine now, he ran the migrations and it allows to create an Issue without GitHub number

**Comment by tommygonzaleza** [comment]
<hrs>0.5</hrs>
