### ISSUE TITLE
Django Script to retry pending leads

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3489]
Every 1 hr retry sending pending leads to active campaign.

[This is the list](https://github.com/breatheco-de/apiv2/tree/main/breathecode/marketing/management/commands) of django commands right now. We need a new command that will get all the pending leads and schedule [this async task](https://github.com/breatheco-de/apiv2/blob/main/breathecode/marketing/tasks.py#L41) to reattempt to add each single pending lead into active campagin.

**Comment by tommygonzaleza** [comment]
Changes requested
