### ISSUE TITLE
Ability to nest checkboxes on MarkdownParser

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3495]
![image](https://user-images.githubusercontent.com/426452/197338289-79f31a6b-1c77-401d-9892-f2bea142d326.jpeg)

**Comment by tommygonzaleza** [comment]
I tried to add nested checkboxes in the storybook but this is how it looks like:
![image](https://user-images.githubusercontent.com/56565994/197625575-a9c69d53-a40b-4e5a-b82d-be91e3ba0fb2.png)
