### ISSUE TITLE
New filter box design for 4Geeks.com 

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3502]
- [x] List of technologies can be filtered using the search box
- [x] The filter will be use in the projects, exercises and lessons.
- [ ] Lessons don't have a difficulty filter.
- [x] You can select several technologies at a time.

<img width="505" alt="Screen Shot 2022-10-25 at 8 34 06 AM" src="https://user-images.githubusercontent.com/426452/197778702-fc4ea09d-b9ac-4512-849e-ff4c13541c49.png">

**Comment by tommygonzaleza** [comment]
- [ ] Remove the difficulties in the lessons filter

**Comment by tommygonzaleza** [comment]
You have to remove the difficulties ONLY in the lessons view, not in the rest (Projects, How to, exercises)
