### ISSUE TITLE
Necesito un logo para blochckain y ciberseguridad

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3503]
Aprovechemos para rediseñar los logos de todos los programas:

- [ ] Full Stack Development
- [ ] DataScience y Machine Learning
- [ ] Blockchain
- [ ] Ciberseguridad

<img width="1417" alt="Screen Shot 2022-10-25 at 11 20 06 AM" src="https://user-images.githubusercontent.com/426452/197814455-07866f11-5900-447c-8334-37475b9e164c.png">

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?node-id=6185%3A6353

**Comment by alesanchezr** [comment]
- [ ] Cibersecurity no esta muy claro.
- [ ] Datascience tiene que usar charts y estadistica.

**Comment by alesanchezr** [comment]
Datascience todavia no no tiene un buen chart.
