### ISSUE TITLE
Allow login instead of signup on the signup component

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3509]
![Image](https://user-images.githubusercontent.com/426452/197895367-53ed671b-e146-4074-995f-675c268c382c.png)

**Comment by ArielCalisaya** [comment]
https://github.com/breatheco-de/app/pull/466

**Comment by tommygonzaleza** [comment]
It's showing the message but styles are a bit different

**Comment by tommygonzaleza** [comment]
Styles improved
