### ISSUE TITLE
Main dashboard

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3510]
- [ ] Ignore the events component until further notice.
- [ ] Ignore the other learning experiences until further notice.
- [ ] Keep hiding the expired programs with the warning `There are 12 programs you have already finished. click here to display them`.

### This is how the cohort should show:

![Image](https://user-images.githubusercontent.com/426452/197898418-86821ee6-a876-4bb5-bcc4-48d67ca429eb.png)

- [ ] Show the number of lessons, exercises and projects.
- [ ] Show available mentors for that cohort.

Here is the figma: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=3230%3A7718

![Image](https://user-images.githubusercontent.com/426452/197897605-7eb83982-14d3-4db1-bf8c-c2d96c62610a.png)

**Comment by alesanchezr** [comment]
- [ ] Request the active mentors for the syllabus in that academy.
- [ ] Request the entire syllabus to be able to display the course content on the box.
- [ ] Lets wait for this API endpoint to be ready. https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3920
- [ ] The hidden cohorts (inactive, etc) don't need to request any of these until they stop being hidden.

**Comment by tommygonzaleza** [comment]
- [ ] When the user didn't start a course yet, show the amount of tasks but without the fraction of how many he has accomplished

![image](https://user-images.githubusercontent.com/56565994/209720397-736c06c2-20bb-4642-a180-1b681e2dc1a1.png)
