### ISSUE TITLE
Business case unit tests for 4geeks.com API

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3512]
### Case 1: Someone is given access to 4Geeks.com cohort without payment required:

- [ ] Staff members of the academy `4geeks-chile` want to give access to one or more of its students to the `santiago-pt-2` cohort, they invite the user to 4Geeks.com and when the invite is accepted the user automatically joins to the cohort with an already active plan (no need to pay). They have access to the following:
      - [ ] Specific cohort called `santiago-pt-2` with classmates and the cohort dashboard.
      - [ ] Unlimited access to workshops `related to the same syllabus` that the cohort has, until the plan expires.
      - [ ] Unlimited mentoring sessions forever, for life.
      - [ ] Unlimited access to the cohort specific live classes until the plan expires.
      - [ ] Access to read lessons, and take exercises and projects for life.
- [ ] The plan will expire when the cohort expires (because the cohort is NOT never ending)

### Case 2: Someone is given access to 4Geeks.com cohort free trial.

- [ ] Staff members of the academy `4geeks-chile` want to give access to one or more of its students to the `santiago-prework` cohort for 7 days only, they invite the user to 4Geeks.com and when the invite is accepted the students automatically join to the cohort, no need to pay. They have access to the following:
      - [ ] Specific `never ending` cohort called `santiago-prework` with classmates and the cohort dashboard.
      - [ ] Unlimited access to workshops `related to the same syllabus` that the cohort has, until the plan expires.
      - [ ] 2 mentoring sessions that cannot be extended.
      - [ ] Unlimited access to the cohort specific live classes until the plan expires.
      - [ ] Access to read lessons, and take exercises and projects until the plan expired.
      - [ ] You access the dashboard but cannot interact with lessons, exercises or projects.
- [ ] The plan will expire after 7 days, and the cohort end date does not matter because it never ends, there is not way the user can pay for more or extend the cohort duration.

### Case 3.1: The staff members want to give extra days to someone from case 3 and 2 extra mentorships.
- [ ] Should they subscribe again the user to the plan for that cohort?

### Case 4: Someone joins thru 4geeks.com organic traffic

- [ ] Anonymus user is trying to signup for the platform free trial for a particular plan called "prework-saas" that consists of the following services:
      - [ ] Specific cohort called `prework-saas` with classmates and the cohort dashboard.
      - [ ] Unlimited access to workshops until the plan expires.
      - [ ] 3 mentoring sessions per week, that will automatically refill every week until the plan expires.
      - [ ] Access unlimited access to live classes until the plan expires.
      - [ ] Access to read lessons, and take exercises and projects until the plan expires.
      - [ ] Access to Mark assignments as Done until the plan expires.
- [ ] The plan will expire when the cohort expires (because the cohort is NOT never ending).

### Case 5: There are plans with no costs:
- [ ] The plan costs money but you don't have to pay.

**Comment by alesanchezr** [comment]
The flow for free cohors or free trials will be like this:

1. If he user is anonymus: 

- During the first signup step the user fills the email, full name, etc and the front end calls the invite endpoint... since the invite is coming from a cohort that is `available for saas` the invite is immediately accepted and and session token is send back on the payload... the front gets that token and forwards the user to the /signup?cohort=<cohort>token=<session_token> and because the querystring has the `token` variable the front end will log him/her in autoamtically.

- Step 2: Since the cohort is already in the URL the second setop will be the payment view, this payment view will start by calling (during mount) the backend to generate the payment and bag for this cohort and plan, a JSON with the bag/payment information will be responded by the backend and the information its shown to the user.

- Setp 3: The user press "pay" or "start trial" and since the backend knows that this is free or trial it will not need credit card and response a status=OK for that payment and add the user to the plan... the front end will redirect to the dashboard.

- Step 4: Since the user has already been added to the cohort, when the dashboard mounts it will ask for all the courses about that user and this new course will show up.

**Comment by tommygonzaleza** [comment]
- [ ] Se debe poder pasar el cohort al Bag con tipo Preview

**Comment by jefer94** [comment]
Raise a error if one of cohorts not exists in checking

**Comment by jefer94** [comment]
Write signals to generate the consumables
