### ISSUE TITLE
Review assignments with file uploads

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3513]
So far assignments only had a github_url to be reviewed by teachers.

But now that assignments can contain several file uploads, we need a way for the teachers to see the files when reviewing the assignments.

- [ ] Create a new component `<AssignmentFiles>` for reviewing the files as a dropdown.
- [ ] The assignment attachments are retrieved on a separate endpoint GET /assignments/task/<id>/attachments, you can do the GET request separately when `<AssignmentFiles>` component mounts and display a small loading animation inside the component while the info arrives.
- [ ] Cach the requests to avoid overwhelming the server.

https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=4833%3A14681

<img width="505" alt="Screen Shot 2022-10-26 at 11 46 17 AM" src="https://user-images.githubusercontent.com/426452/198073509-8f20dd30-cee0-46b4-972a-dc2e4860a26b.png">

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=4833%3A14681

**Comment by tommygonzaleza** [comment]
It's giving me the following error when the app is trying to fetch the assignments, it's also giving me the error in production
![image](https://user-images.githubusercontent.com/56565994/200628835-0aac8b44-9d6b-4ac3-9fa6-4c62bd5d78a6.png)

**Comment by tommygonzaleza** [comment]
It doesn't have the design shown in the picture shared by Alejandro.

This is how it's showing at this moment:
![image](https://user-images.githubusercontent.com/56565994/200632992-f91d31e8-9c1f-478b-afd1-fbe760c9ce59.png)
