### ISSUE TITLE
Rediseño de above-the-fold basado en job guaranty y bullets.

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3514]
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?node-id=6033%3A6197

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?node-id=6033%3A6197

**Comment by alesanchezr** [comment]
- [ ] El home de 4geeks va a cambiar con este diseño.
- [ ] Agregar una opcion al yml para: video_ask que si se especifica entonces entraria el diseño 2 (ver mas abajo).
- [ ] Modificar el YML para poder agregar la informacion encesaria.
- [ ] Hacer todo en un branch separado para porder iterar con calma.

## Diseño 1

<img width="427" alt="Screen Shot 2022-11-03 at 12 49 26 PM" src="https://user-images.githubusercontent.com/426452/199783688-4b257492-d1d3-4634-b572-a353a959dea3.png">

## Diseño 2

<img width="428" alt="Screen Shot 2022-11-03 at 12 49 27 PM" src="https://user-images.githubusercontent.com/426452/199783693-31ee9895-d2a3-43db-8ea0-298c0f0a1439.png">

**Comment by tommygonzaleza** [comment]
- [ ] Add only `video` and `thumb` properties to the yml and if it doesn't have the video, then you show the thumb.
```
video: "https://www.youtube.com/watch?v=PWkgaAT8pHg&t=13s"
thumb: "../../../static/images/bg/video-thumb.png"
```

**Comment by tommygonzaleza** [comment]
Funcionando bien!
