### ISSUE TITLE
Nuevo diseño a modal de filtros en 4geeks.com

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3520]
- [ ] The filter applies to lesson, exercises and projects.
- [ ] Puedes filtrar las tecnologias en el search box.
- [ ] You can select several tecnologies at once.
- [ ] You can select a dificulty (only exercises and projects)
- [ ] You can toggle the with videos or not.

<img width="539" alt="Screen Shot 2022-10-27 at 12 53 49 PM" src="https://user-images.githubusercontent.com/426452/198351825-d7aa3720-393c-4a88-ba26-214ccfff3e8c.png">

**Comment by alesanchezr** [comment]
@ali5uarez5 no queda claro como se muestra la dificultad que esta marcada, puedes clararlo?

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=2734%3A4663

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=4879%3A15008

**Comment by tommygonzaleza** [comment]
Estilos agregados corerctamente, el modal de los filtros luce bien
