### ISSUE TITLE
Mejoras al componente de premios

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3521]
Verlo en tamaño ipad es ideal para ver todos los bugs.

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-35409-f2cb1948efe3f7d572180e5d0ae507b5) 

---
**Source URL**:
[https://4geeksacademy.com/us/landing/united-way](https://4geeksacademy.com/us/landing/united-way)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 104.0.5112.102</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1444x708</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by tommygonzaleza** [comment]
The scroll bar was removed but even when it's needed, I don't think that's what we would like to have. Sometimes the scrollbar is needed

**Comment by tommygonzaleza** [comment]
- [ ] If there is a scroll, it should move automatically and you can still scroll it
