### ISSUE TITLE
MarkdownParser: Error interpretando coding inline

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3524]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-35422-244e8e8615e7a1e44b60f4dd1f9721d7) 
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 104.0.5112.102</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1393x340</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by tommygonzaleza** [comment]
I couldn't find an article where it fails, I'm assuming it's fixed
