### ISSUE TITLE
What happned with pagination

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3541]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-35467-76a763a5654083d21a457fa13f9947f4) 

---
**Source URL**:
[https://4geeks.com/cohort/miami-prework/coding-introduction/v1](https://4geeks.com/cohort/miami-prework/coding-introduction/v1)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 104.0.5112.102</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x710</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by tommygonzaleza** [comment]
When I click in load more, it doesn't load more users:
![image](https://user-images.githubusercontent.com/56565994/199314876-028bc975-479b-485a-ab31-31d64ff26698.png)

**Comment by tommygonzaleza** [comment]
it's working fine the pagination with your classmates, apply the same to alumni geeks
