### ISSUE TITLE
Crear landing de cursos

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3554]
En 4Geeks.com tenemos que hace una landing de experiencias.

- Mostrar la experiencia que tenemos ahora de "Learn to Code"
- Mostrar una sección de "Próximas experiencias" donde te puedas unir a un waiting list y elegir una o mas experiencias que te gustarían.
- La pagina va a recibir via URL una tecnología, por ejemplo `python` y asi vamos a poder saber qué experiencia recomendarte.

Incluir una sección en el landing que diga: `What is a social coding experience?` Its like coursera, but with classmates, 1-1 mentorships and live classes or worshops every day. Choose your syllabus and start learning.

En esa misma sección pones 4 cajas, una para mentorships, otra para workshops, coding jams y otra para community. Cada caja va a decir en 140 caracteres que es cada cosa.

**Comment by alesanchezr** [comment]
Tienes el link a esto para revisarlo?

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=4955%3A15404&t=qk765Je8AHnMcntG-1
