### ISSUE TITLE
Intercambiar botones para acceder a los ejercicios.

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3555]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-35494-ecfbb2d4136b8514855047281237beb5) 

---
**Source URL**:
[https://4geeks.com/interactive-exercise/object-oriented-programing-in-javascript](https://4geeks.com/interactive-exercise/object-oriented-programing-in-javascript)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 104.0.5112.102</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x710</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by tommygonzaleza** [comment]
![image](https://user-images.githubusercontent.com/56565994/199321796-9a6e4edc-6981-45f5-8674-d6e528b3a4cc.png)
Power by learn pack should be at the bottom
