### ISSUE TITLE
Landing de how'to por tecnologia esta roto

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3557]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-35496-6e0aea6890ce6506a28f5ad6ee69b1e4) 

---
**Source URL**:
[https://4geeks.com/how-to/technology/javascript](https://4geeks.com/how-to/technology/javascript)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 104.0.5112.102</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x710</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by tommygonzaleza** [comment]
It's still not showing the landing page of technologies

**Comment by tommygonzaleza** [comment]
It's working fine
