### ISSUE TITLE
Integrate with Assignment Thresholds

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3590]
This is how an assessment looks today: https://assessment.4geeks.com/quiz/english-beginners
The source code for assignments is: https://github.com/breatheco-de/assessment

Once the assignment has been finished and we know the `total score`, we are adding a new feature called **Assignment Thresholds**, this is all at the end of the assessment, the last step.

- [ ] One assignment can have many thresholds that can be fetched with `GET /assignment/<assignment_slug>/thresholds`, this is how the responso from that request looks like:

```json
[
    {
        "success_next": null,
        "fail_next": null,
        "success_message": "",
        "fail_message": "",
        "score_threshold": 2,
        "assessment": {
            "slug": "html-quiz",
            "title": "Learn about HTML"
        }
    }
]
```
For example for the `english-beginners` assignment will be: GET /assessment/english-beginners/thresholds

- [ ] Every threshold has a `score_threshold` property that represents if the threshold has been met. For example: think of the following thresholds for one assignment:
                1. score: 6
                2. score: 15
                3. score: 30
If the assignment has finished with a total score of 8, the first threshold has been achieved successfully.

- [ ] A maximum of ONE threshold can be met at a time, for example if the final score is 18 the 2nd threshold has been achieved, not the 1st one.
- [ ] Threshold also come with a `success_message` or `fail_message` property  that, if specified, will replace the message displayed at the end of the assignment for the corresponding achieved threshold.
- [ ] Threshold also come with a `success_next` or `fail_next` property that both are URLs. If those URLs are specified, the app will show a `Continue to Next Step` or `Continuar al próximo paso` button that redirects the user to the specified  URL.

**Comment by alesanchezr** [comment]
- [ ] Thresholds don't seem to be working
- [ ] If the assigment.is_instant_feedback boolean is `false` do not show the green/red feedback screens after each answer.

**Comment by aayalapalacin** [comment]
8 hours
