### ISSUE TITLE
Add flow to start a free trial with the payment module

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3613]
The backend is ready to provide you with the information related to this flow. 

The server that should do the requests to is `https://breathecode-payments.herokuapp.com/`.

1. Contact Information:
- [ ] If the user is anonymous, then you should send a request with the user's information to `POST /v1/auth/subscribe` with the user's information (first_name, last_name, and email). This request will return a token, if it doesn't return a token, then you should send the user to the waiting list.

2. Cohort Selection:
- [ ] The user should select a cohort (The cohort can come in the query strings of the url) and with this cohort selected, you should request a token from `PUT /v1/auth/subscribe` passing the cohort and email as part of the body, and using the token provided in the previous request.
> Use the token to login the user right away
- [ ] With this cohort and the token is given, you should do a request to `PUT /v1/payments/checking`, using the token and with the following body:
```
{
    "type": "PREVIEW",
    "cohort": <cohort_slug>,
    "academy": <academy_id>
}
```
> The information returned from the previous request will be used to render the payments view.
  
3. Pay:
- [ ] Using the token given in the previous step, use the following service: `/v1/payments/pay`. passing in the body the choose_period E.g.: `"choosen_period":"HALF"`
> If payment has succeeded, send the user to the dashboard

**Comment by alesanchezr** [comment]
Check for status code `409`

```
Already have an account?
It seems that you already have an account, please check your email inbox for any messages from [4Geeks.com](http://4geeks.com/).
If you know your password <a>click here to login now</a> or click here on <a>forgot password to get a new one</a>.
```

**Comment by tommygonzaleza** [comment]
- [ ] Free trial shouldn't show credit card information
- [ ] It should remember the user and skip the first step if the user already added his information
- [ ] Return step to choose cohort to the second step.
- [ ] Fix the bug that is not sending the checking request
