### ISSUE TITLE
Constancia de Estudio

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3615]
Crea una constancia de estudio para inscritos en 4Geeks Academy.

Debe tener un contenido similar a este:
[https://docs.google.com/document/d/1c_zbqAWja51SDVvKKEH6Btlt40AT40NeVimEOpqb02I/edit](https://docs.google.com/document/d/1c_zbqAWja51SDVvKKEH6Btlt40AT40NeVimEOpqb02I/edit?authuser=4)

**Comment by tommygonzaleza** [comment]
- [ ] Crea un carnet de estudiante de la academia que sirva como constancia de estudio 
![image](https://user-images.githubusercontent.com/56565994/202520703-c70b217d-cc56-4d88-9d69-b930dbad0d7b.png)

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=5344%3A18335&t=OemntVoUxl33Chw4-1

**Comment by tommygonzaleza** [comment]
El diseño debe ser horizontal

**Comment by alesanchezr** [comment]
Asi quedo: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=5624%3A19965&t=7VjuLnD1QBnklpZU-0
