### ISSUE TITLE
The asset's breathecode.registry.models.asset.category should be mandatory

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3622]
- [ ] This is the property that should be modified: https://github.com/breatheco-de/apiv2/blob/main/breathecode/registry/models.py#L273
- [ ] Make sure tests are working fine after you make your changes
- [ ] Make sure that the category property is a requirement when creating an Asset from the Django admin
- [ ] Test the endpoint to create a category as well

**Comment by tommygonzaleza** [comment]
Remember to add the amount of hours it took you to complete this task

**Comment by tommygonzaleza** [comment]
In the PR 644 you should remove solve the review provided by Jeferson

**Comment by Andresgarciasch** [comment]
Time: 6h
