### ISSUE TITLE
`<Sparkline>` Component

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3626]
![sparkline-interactive](https://user-images.githubusercontent.com/426452/201244509-37d98d4a-63c8-4474-8aa3-1be89e91128c.gif)

Based [on this article](https://gist.githubusercontent.com/intricatecloud/763e01311243f9cbf6ac283dbd13f39a/raw/7f82ce0ba901bf86d2b77652c41c00fd3f95aeca/sparkline.jsx) we can create a `<Sparkline>` component using the [fnando/sparkline](https://github.com/fnando/sparkline) javascript npm library.

- [x] make the componet as customizable as you can (colors, line stroke, fill color, labels, etc).
- [x] The sparkline must be -optionably- interactive that you can hover the mouse and read the values.
- [x] Use storybook.

**Comment by tommygonzaleza** [comment]
https://www.loom.com/share/f50b6e912fdf4550b5b59f61a36bc563
