### ISSUE TITLE
`<DottedTimeline>` Component

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3627]
# `<DottedTimeline>` Component:

![4Geeks-com-–-Figma (1)](https://user-images.githubusercontent.com/426452/201244907-8f7c3789-26c6-4179-9be3-59807b2a8e2b.png)

- [x] label: A react node element that can have any html or other react components, usually it will have an avatar and a label.
- [x] Each dot will have: color and label (the label displays on a tooltip when hovered).
- [x] All days/dots must fit on the screen unless mobile or ipads devices that will be able to swap the finger.
- [x] Use story book.
- [x] All dots must show on the screen unless mobile or table device, in that case the user will be able to swipe the finger among the dots.

## Example:

```react
<DottedTimeline 
        label={<p>Axel</p>}  
        dots={[
             { label: 'Day 1 - 4 Mar', color: '#FBFBFB' },
             { label: 'Day 2 - 8 Mar', color: '#FBFBFB' },
              ...
        ]} 
        helpText="72% attendance"
/>
```

### Special note

This component will be used for other purposes, not just attendancy.

**Comment by tommygonzaleza** [comment]
![image](https://user-images.githubusercontent.com/56565994/202021454-98fc5b74-c32a-42d1-89a7-b16d659f7767.png)
