### ISSUE TITLE
Create landing page for 30DAYSOFGEEKCODING challenge

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3630]
- [ ] Create an article while we wait for the real approach (Probably will work like a course with a syllabus)

**Comment by alesanchezr** [comment]
Esto queda para despues del lanzamiento volverlo a revisar. Tambien deberiamos hablar un poco mas sobre o que vamos a ahcer aqui porque yo esperaria que tengamos muchas funciones sociales para integrarnos a social media, etc.

**Comment by tommygonzaleza** [comment]
Okk perfecto
