### ISSUE TITLE
Implementar menu de navegacion con CSS en lugar de JS

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3640]
![Video from awesomescreenshot.com](https://www.awesomescreenshot.com/web/video/thumbnail/12424622?key=af0f1de41853721e8682a45a67bf855d&size=960) 

<b>Click the link below to watch the video: </b>
 https://www.awesomescreenshot.com/video/12424622?key=af0f1de41853721e8682a45a67bf855d 

 Tenemos un problema de SEO.
Google no logra abrir nuestro menu de navegacion principal porque require Javascript.

Si desactivas JS en tu developer tools vas a ver que los primeros 5 links si se visualizan pero ya luego los links que aparecen al hacer click no.

Necesitamos que el menu funcione sin JS y se puede lograr utilizando CSS:hover en lugar de esperar por el click.

**Comment by tommygonzaleza** [comment]
It's showing the navbar sub-menus correctly when disabling javascript
