### ISSUE TITLE
Agregar en la web el idioma del curso.

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#3651]
En este componente deberíamos agregar el idioma del curso 

<img width="829" alt="image" src="https://user-images.githubusercontent.com/62053368/201706486-0b2a959a-9b7f-4915-953f-3b8c935d0019.png">

**Comment by alesanchezr** [comment]
En el campo de idioma me gustaría poner: `As as student, you will have the ability to decide between english and spanish to consume the syllabus and content, the master classes will be taught in the language of the campus you choose`.

**Comment by victormgomezp** [comment]
¿cómo va esto?

**Comment by gustavomm19** [comment]
No había tenido chance de revisarlo porque había muchos otros issues de más alta prioridad, pero lo revisaré ahora
