### ISSUE TITLE
Create a django command to change asset's readme url

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3668]
- [ ] Create a Django command that detects all the Readme URL that looks like this `https://raw.githubusercontent.com/breatheco-de/exercise-postcard/main/README.md` and changes it to `https://github.com/breatheco-de/exercise-postcard/blob/main/README.md` notice the changes in the URL (The blob added and the domain)
- [ ] Make sure the URL that you are replacing the old one by returns status 200 when you do a request to it.
- [ ] Create the command with this path: `https://github.com/breatheco-de/apiv2/tree/main/breathecode/registry/management/commands/change_asset_readme_url.py`
- [ ] Here is the attribute that should change from the asset: https://github.com/breatheco-de/apiv2/blob/main/breathecode/registry/models.py#L289

**Comment by tommygonzaleza** [comment]
This command should look for all the assets that the readme_urls have the first structure given in the first task (`https://raw.githubusercontent.com/breatheco-de/exercise-postcard/main/README.md`) and transform it to this structure `https://github.com/breatheco-de/exercise-postcard/blob/main/README.md`, remember it should look for ALL the assets

**Comment by jefer94** [comment]
See the PR number https://github.com/breatheco-de/apiv2/pull/666

**Comment by Andresgarciasch** [comment]
pr = 'https://github.com/breatheco-de/apiv2/pull/666'

<hrs>5<hrs>

**Comment by tommygonzaleza** [comment]
<hrs>5</hrs>
