### ISSUE TITLE
Create a new table `breathecode.marketing.models.Course`

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3671]
- [ ] Create a new table `breathecode.marketing.models.Course`:

- `slug`:
- `syllabus`: Syllabus related
- `academy`:
- `status`: `ACTIVE`, `DELETED`, `ARCHIVED`
- `visibility`: `UNLISTED`, `PUBLIC`, `PRIVATE`
- `course_translations`: OneToMany a `CourseTranslation`
- `icon`: URLField

- [ ] There should be a table `CourseTranslation` that has the following properties:

- `title`:
- `description`:
- `language`: a string of 5 characters

- [ ] Create a `breathecode.marketing.serializers.CourseSmallSerializer` that returns: 
```
{
     "slug": "",
     "icon": "",
     "course_translation": [
          {
                "title": "",
                "description": "",
                "language": ""
          }
      ],
}
```
- [ ] Create a `breathecode.marketing.serializers.CourseBigSerializer` that returns: 
```
{
     "slug": "",
     "icon": "",
     "course_translation": [
          {
                "title": "",
                "description": "",
                "language": ""
          }
      ],
      "syllabus": {},
      "academy": {},
      "status": "",
      "visibility": "",
}
```
- [ ] Create a `breathecode.marketing.views.CourseView` that returns all the courses with the `CourseSmallSerializer`. This view will be used in the following service: `GET /v1/marketing/course` this service should receive the language in the headers in order to return the list of courses of that language, if no language is provided in the headers, use the function [get_user_language()](https://github.com/breatheco-de/apiv2/blob/ac7346af6289ad15f0b0d90bf72b9314c3c1abb0/breathecode/authenticate/actions.py#L311). This service should be able to receive a Course slug in the query string like this: ` GET /v1/marketing/course?course_slug=<course_slug>`, if it receives the `course_slug` then you return the `CourseBigSerializer` of the Course that has the slug given, otherwise, you should return the `CourseSmallSerializer` of all the courses.
> This view will be similar to this one: https://github.com/breatheco-de/apiv2/blob/main/breathecode/registry/views.py#L347, check how the way it returns the big serializer or the small one.

**Comment by tommygonzaleza** [comment]
Repensar como vamos a organizarnos para mostrar los productos

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/758

**Comment by tommygonzaleza** [comment]
- [ ] Convierte el field syllabus en un manyToMany

**Comment by jefer94** [comment]
done https://github.com/breatheco-de/apiv2/blob/985b9dff70ce91e52100a4db6f62c24b59efbbf5/breathecode/marketing/models.py#L723
