### ISSUE TITLE
Add unit testing to `sync_single_issue` function

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3673]
- [x] Create many tests for the `sync_single_issue` function, each test for all the different scenarios.
- [x] You should create the tests in: `breathecode/freelance/tests/actions/tests_sync_single_issue.py`.
- [x] The `sync_single_issue` function is used in this [function](https://github.com/etolopez/apiv2/blob/40160f85c76b4b93b5d7e64952bbddcfc57262f5/breathecode/freelance/tasks.py#L19), which is used in this [url](https://github.com/etolopez/apiv2/blob/github_number/breathecode/freelance/urls.py#L27)

This is the link to the function: https://github.com/etolopez/apiv2/blob/40160f85c76b4b93b5d7e64952bbddcfc57262f5/breathecode/freelance/actions.py#L55

**Comment by etolopez** [comment]
pr: https://github.com/breatheco-de/apiv2/pull/668

h: 10

**Comment by tommygonzaleza** [comment]
Improve coverage of the tests

**Comment by etolopez** [comment]
Testing has been completed.

**Comment by tommygonzaleza** [comment]
<hrs>10</hrs>
