### ISSUE TITLE
Mucho espacio en blanco en el home de 4geeksacademy

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3675]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-35786-69b7bd666f48c1ec9e238a26cd6720b2) 

---
**Source URL**:
[https://website-v2-git-fork-gustavomm19-new-header-geeksacademy.vercel.app/](https://website-v2-git-fork-gustavomm19-new-header-geeksacademy.vercel.app/)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 104.0.5112.102</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x710</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by tommygonzaleza** [comment]
Please sync your branch with the branch of the main repository (branch development) and try to redeploy it

**Comment by tommygonzaleza** [comment]
We should add additional space on top and the design will change, let's wait for the design
