### ISSUE TITLE
Updates to de media gallery

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3676]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-35787-a382c20673a0dbd73a243e1e8df9ee17) 

 - [x] Allow filtering media by "from" date. This should happen when the date input its updated (no need to apply button).
- [x] Allow filtering media by "to" date. This should happen when the date input its updated (no need to apply button).
- [x] To filter the medias by date ("from" and "to") you should include in the backend these filters. Here is an example of another service that filters by date: https://github.com/breatheco-de/apiv2/blob/3b246450ac1b047a7224e202010a6e0653315d70/breathecode/marketing/views.py#L364
- [x] Radiobuttons for the "type" filter are taking to much space, replace them with a toggle button with icons like this ones: https://mui.com/material-ui/react-toggle-button/
- [x] In the sorting dropdown replace "default" with "Sort by".

---
**Source URL**:
[https://admin.4geeks.com/media/gallery](https://admin.4geeks.com/media/gallery)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 104.0.5112.102</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x710</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by etolopez** [comment]
Pr: 
Frontend:
https://github.com/breatheco-de/admin/pull/310

Backend: 
https://github.com/breatheco-de/apiv2/pull/651

h: 7

**Comment by tommygonzaleza** [comment]
Why did you remove the LockIcon?

**Comment by etolopez** [comment]
Listos los cambios en este PR.

**Comment by tommygonzaleza** [comment]
You have to change the icons by icons provided by the designer, I'll add the link here so you can get them

**Comment by etolopez** [comment]
https://github.com/breatheco-de/admin/pull/311

total hours: 7.5

**Comment by tommygonzaleza** [comment]
It has a conflict, please solve it

**Comment by etolopez** [comment]
pr: https://github.com/breatheco-de/admin/pull/317

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>7.5</hrs>
