### ISSUE TITLE
Only students should show on the list of delivered assignments

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3679]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-35807-c23734c94fbd06a62989b79f39cd9ebc) 

---
**Source URL**:
[https://4geeks.com/cohort/miami-43/full-stack/v7/assignments](https://4geeks.com/cohort/miami-43/full-stack/v7/assignments)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 104.0.5112.102</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x710</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by ArielCalisaya** [comment]
## [Filter already exists](https://github.com/breatheco-de/app/blob/main/src/pages/cohort/%5BcohortSlug%5D/%5Bslug%5D/%5Bversion%5D/assignments.jsx#L66)
![Captura de pantalla 2022-11-18 115838](https://user-images.githubusercontent.com/51676628/202734228-96b4828a-50f5-4925-b973-ce40f3457617.png)

**Comment by tommygonzaleza** [comment]
The filter exists and it's working fine
