### ISSUE TITLE
Modal for "Direct Access Request"

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3682]
Sometimes we just want to collect a lead instead of signing up the user to 4geeks.com (soft lead).

We need a modal window that asks for name and email, after they give it, to gives direct access to a particular content they wanted to see.

**Comment by tommygonzaleza** [comment]
En el mensaje esos nombre (Python for beginners) es el nombre del asset al que esta intentando acceder, en este caso es la practica. No el de la tecnologia
