### ISSUE TITLE
Add academy_id to the header when asking for task attachments

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3697]
Cuanto llamas a `GET /v1/assignment/task/161120/attachment` tienes que pasarle el academy ID porque no queremos que cualquier persona pueda revisar cualquier assignment, solamente el staff de la academia o el alumno que lo subió.

[Slack Message](https://4geeksacademy.slack.com/archives/D03S04ZA0G7/p1668731132921529)

**Comment by tommygonzaleza** [comment]
Academy id agregado al request para getFiles()
