### ISSUE TITLE
Redesign of "How to" landing page.

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3698]
We would like to have a design different from the exercises and projects. It should be more oriented to **Questions** and **Answers**, so maybe we should redesign the cards to have the questions and part of the answer below.

You can use this link as guidance: https://stackoverflow.com/questions

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=5402%3A19373&t=oMHc5OtYTNqxs5YO-1
