### ISSUE TITLE
Create design to add the card information in order to pay

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3731]
Think about the best approach for the way we're going to show where the user is adding his card information for payment, we have to think if we want to send them to a different view, show the form in a modal, or display it right below the button of proceeding to checkout.

This is what will show up after clicking in the following button:

![image](https://user-images.githubusercontent.com/56565994/203448594-9cba5d34-6628-4354-bb21-f1e2876ab7cf.png)

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=5402%3A19373&t=oMHc5OtYTNqxs5YO-1

**Comment by alesanchezr** [comment]
Podemos hacer que el formulario sea mas preventivo?

- Solo permitir un formato especifico de fetcha de vencicmiento.
- Los numeros en la tarjeta que se agrupen.
- El margen derecho del formulario esta demasiado amplio.
- Como se muestran los errores?
