### ISSUE TITLE
Filter is not including name and lastname

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3734]
- [ ] This [filter](https://github.com/breatheco-de/apiv2/blob/3b246450ac1b047a7224e202010a6e0653315d70/breathecode/authenticate/views.py#L703) should be sensible with the email but not with the name and last name
- [ ] Improve unit tests for this service

**Comment by gustavomm19** [comment]
This issue was missdiagnosed, the real problem was in the frontend component

**Comment by tommygonzaleza** [comment]
Problem fixed in the frontend
