### ISSUE TITLE
This filter is not allowing to search by name

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3761]
### Problem

If you search by name and the name doesn't match the email, then it's not going to show that user.

### Solution Approach

We already solved this problem [here](https://github.com/breatheco-de/admin/blob/development/src/app/views/media/article_issues.jsx#L102) using the `filterOptions` prop like used there.

### Problem location:

In the admin project, go to `/admin/staff/new`

![image](https://user-images.githubusercontent.com/56565994/204653199-acee6606-49f6-4747-951f-17c4dd41f9dd.png)

**Comment by etolopez** [comment]
https://github.com/breatheco-de/admin/pull/316

h: 2

**Comment by tommygonzaleza** [comment]
It's working but there are to many changes non related to the problem in this PR

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>2</hrs>

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>2</hrs>
