### ISSUE TITLE
Actualizar logos de cursos de la pagina

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3764]
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?node-id=6185%3A6353

**Comment by tommygonzaleza** [comment]
Los logos dados (Estan en sandbox) son diferentes a los de Final:
Final:
![image](https://user-images.githubusercontent.com/56565994/208750493-3d55d919-44af-4d70-bb6d-01588305b0ac.png)

Sandbox:
![image](https://user-images.githubusercontent.com/56565994/208750563-5535052c-445c-4b1e-9d33-d59370c4edd1.png)
