### ISSUE TITLE
Top navbar should work without Javascript

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3771]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-36004-8c7c38a960c6f1d57abdc322b1854742) 

 Replicate the functionality using CSS only.

You can make the submenus show up when the mouse is hovered, similar to the changes we did in 4GeeksAcademy.com

---
**Source URL**:
[https://dev.4geeks.com/cohort/miami-xxxv/full-stack/v7](https://dev.4geeks.com/cohort/miami-xxxv/full-stack/v7)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 107.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x709</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by tommygonzaleza** [comment]
Los subheaders de learning library no estan funcionando sin JS
