### ISSUE TITLE
Change of cohort.currentDay initial value from 0 to 1 

### ISSUE THREAD

**Issue by ehiber** [4GeeksAcademy/About-4Geeks-Academy#3783]
### Bug description

Cuando inicial el tomar asistencia el input esta por defecto en 0

### Steps to reproduce

Abrir el modulo de asistencia de los profesores 

### Expected behavior

Deberia comenzar en 1

Expected time: 0.5 - 1

**Comment by tommygonzaleza** [comment]
Here is the line you should modify: https://github.com/breatheco-de/apiv2/blob/2fa757f71f1401644ae50bfdb34123f3f49d3dde/breathecode/admissions/models.py#L289

**Comment by etolopez** [comment]
Time elapsed: 

<hrs>0.5</hrs>
