### ISSUE TITLE
Event attendies are being sent to the wrong academy.

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3787]
When sending leads to activecampaign, we need to use the [event.academy](https://github.com/breatheco-de/apiv2/blob/main/breathecode/events/models.py#L149) instead of the organization academy.

Here is the line of code that should be replaced.
https://github.com/breatheco-de/apiv2/blob/af877e358ffc62d08ba6bba61dbb5f38f62d0efa/breathecode/services/eventbrite/actions/order_placed.py#L55

Note: Also implement or fix unit testing for this update.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/658
