### ISSUE TITLE
Password protect dev.4geeksacademy.com

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3789]
To fully make the development environment invisible to google its best practice to password protect the website.

We can do it based on the `NODE_ENV` to make sure its only on development.

Try with some plugins like https://www.gatsbyjs.com/plugins/@mkitio/gatsby-theme-password-protect/

**Comment by tommygonzaleza** [comment]
The environment variable that should use to determine if it is development env is `VERCEL_ENV` and the values that should add the password login are: `development` and `preview`

**Comment by tommygonzaleza** [comment]
Modifica los estilos que se estan aplicando parala vista de la password y si no funciona pon un div para que sea el quien tome los estilos
