### ISSUE TITLE
ServiceItemFeature model

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3794]
Its a marketing tool, one to many with ServiceItem, it will describe a service item in bullets for humans.

- language
- one_line_desc
- description

For example, if the service item is `Mentorship` and its quantity its `-1` then it may contain one or many features saying: "1-1 Mentorships for life"

Instructions

- [ ] Create a new endpoint to GET /v1/payments/serviceitem that returns ServiceItem with its bullet descriptions from many services (you can filter which ones on the querystring variable `plan` comma separated). Also allow specifying serviceItems with a variable `item` comma separated service item ids.

**Comment by jefer94** [comment]
Is not possible distinct between the service items if two plans had passed because a `ServiceItem` doesn't have relationship with `Plan`
