### ISSUE TITLE
El frontend no está mostrando la duración en días correcta para cada módulo

### ISSUE THREAD

**Issue by marcogonzalo** [4GeeksAcademy/About-4Geeks-Academy#3817]
### Bug description

El módulo de bootstrap debería sugerir 2 días de duración pero el frontend muestra 1. Así con todos los que tienen 2 o más días

### Steps to reproduce

https://4geeks.com/syllabus/mad-cohort-0/read/bootstrap-tutorial-of-bootstrap-5

### Anything else?

![Screenshot 2022-12-08 at 00-12-51 Syllabus Builder - BreatheCode](https://user-images.githubusercontent.com/410890/206317519-758fbbc9-dca2-4413-bd48-b2d7c620c262.png)
![Screenshot 2022-12-08 at 00-12-27 4Geeks](https://user-images.githubusercontent.com/410890/206317523-35a78091-a6cf-4d2d-9e64-3c42cc7ef9c7.png)

**Comment by tommygonzaleza** [comment]
Problem Fixed!
