### ISSUE TITLE
Only show form to edit syllabus info if the syllabus.academy_owner.id == session.academy.id

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3819]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-36103-1b77f4c3d489458f70bfddf39f657d62) 

 - [ ] We can save a lot of space and make the UI friendlier if we don't show the form to edit the syllabus for other academies.

- [ ] We should also show a warning at the top of the box saying: "This syllabus is owned by another academy, you can not make changes to its basic information".

---
**Source URL**:
[https://admin.4geeks.com/admin/syllabus/coding-for-executives](https://admin.4geeks.com/admin/syllabus/coding-for-executives)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 107.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x709</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by etolopez** [comment]
pr: https://github.com/breatheco-de/admin/pull/318

h: 4h

**Comment by tommygonzaleza** [comment]
I added a review to the PR

**Comment by etolopez** [comment]
Updated file in PR

pr: https://github.com/breatheco-de/admin/pull/318 (same).

**Comment by tommygonzaleza** [comment]
![image](https://user-images.githubusercontent.com/56565994/207454045-47671894-d743-4526-b02a-b5f052322357.png)

**Comment by tommygonzaleza** [comment]
It should also allow editing the syllabus if you belong to that academy, not if you created it

**Comment by etolopez** [comment]
Made the changes!

Total h (w/this change): <hrs>5</hrs>

**Comment by tommygonzaleza** [comment]
The non-editable inputs should look like the ones non-editable before, you modified all of them instead.

**Comment by etolopez** [comment]
Changed how the input looks.
