### ISSUE TITLE
Quitar boton de "See plans and prices"

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#3823]
### Bug description

Cuando haces clic en este botón en la vista de cada programa de estudios (ver primera imagen) se queda cargando (ver segunda imagen) y no muestra nada

<img width="957" alt="image" src="https://user-images.githubusercontent.com/62053368/206581898-dc339b74-fba7-49be-a9c1-834f58fc6a5e.png">

<img width="953" alt="image" src="https://user-images.githubusercontent.com/62053368/206581818-d9019db5-cebe-4aed-9e43-6d51a202a24c.png">

### Steps to reproduce

Cuando haces clic en este botón en la vista de cada programa de estudios (ver primera imagen) se queda cargando (ver segunda imagen) y no muestra nada

**Comment by tommygonzaleza** [comment]
Pasar la Ciudad a traves de los query strings para que se seleccione ese valor por defecto en la siguiente pagina
