### ISSUE TITLE
CORREGIR URGENTEMENTE: No se puede acceder al programa de DataScience, te lleva al de AI/ML

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#3824]
### Bug description

Al hacer clic aquí te lleva al programa de AI/ML no al programa de Data Science

<img width="947" alt="image" src="https://user-images.githubusercontent.com/62053368/206582646-afe2ff49-4d79-43d8-861d-3d505066b5b7.png">

### Steps to reproduce

Clic en programs y luego en Data Science y te llevará a AI/ML no a Data Science

**Comment by tommygonzaleza** [comment]
Error fixed
