### ISSUE TITLE
WEBSITE: Cambiar nombre del botón para Chile - No aplica el nombre actual

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/About-4Geeks-Academy#3826]
**Is your feature request related to a problem? Please describe.**
En la página en la sección de precios, el botón dice APLICAR, y en Chile se dice POSTULAR 

https://4geeksacademy.com/es/coding-bootcamps/full-stack-part-time
https://4geeksacademy.com/es/coding-bootcamps/full-stack-full-time

![Captura de pantalla 2022-12-08 213415](https://user-images.githubusercontent.com/48845580/206596364-0b4475a2-cf1d-4f6b-a49b-200783b3e64e.png)

**Describe the solution you'd like**
Colocar la opción para que las personas que ingresen a ver los precios de CHILE diga POSTULAR
Se debe cambiar en todos los programas. 

**Describe alternatives you've considered**

**Additional context**

**Comment by jatv93** [comment]
@alesanchezr pueden revisar esto?

**Comment by alesanchezr** [comment]
@gustavomm19 cada sede tiene la oportunidad de especificar como va a decir el boton de "aplicar" en su idioma, eso ocurre [aqui en el YML de la location](https://github.com/4GeeksAcademy/website-v2/blob/master/src/data/location/santiago-chile.es.yaml#L30).

Vamos a hacer q este componente utilize ese campo para llenar el boton de aplicar.
Creo que esto ya se hace con el boton de aplicar que esta en el navbar, esta personalizado por locacion.
