### ISSUE TITLE
Mala generacion de los substasks en el MarkdownReader

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/About-4Geeks-Academy#3828]
### Bug description

The check works in a wrong way

https://user-images.githubusercontent.com/48845580/206786250-032eeea3-ef5f-4707-89d5-ba6e701ae821.mp4

### Steps to reproduce

Go to the Syllabus: Land a Job in Tech
Go to the lesson Interview Preparation

Mark the checks 

### Expected behavior

It only should mark 1 check at a time and when you unmarked it should just unmark that check

**Comment by alesanchezr** [comment]
Ariel este bug esta pasando porque la forma en que estas generando los IDs no es la correcta, ademas me di cuenta que estas sobreescribiendo las tareas originales que llegan desde el backend? porque?

Vamos a seguir la siguiente logica:

El primer obtetivo es que puedas generar el ID de la tarea desde el front end y comprarlo con los que llegan del backend y que haga match con alguna, porque es esto tan importante? Porque eso garantiza constitencia: Tanto el back como el front van a revisar esa data despues.

Esta es la formula con la que el backend genera el ID: 

```
task['id'] = hashlib.md5(task['label'].encode('utf-8')).hexdigest()
``` 
Si te fijas no es mas que un hash MD5 del label.

Ahora mismo parece que el front end no esta generando bien ese label, porque estas ignorando caracteres especiales. No ignores nada! Solamente el `- [ ] ` que va al principio de la linea, de resto toda la linea forma parte del label.

Luego tienes que aplicarle el hash a ese label.

Tienes que garantizar que tu hash es igual al ID que llega del backend.

**Comment by alesanchezr** [comment]
el codigo que me pasaste no creo que resuelva el problema, tu necesitas poder generar ese slug y posterior id convirtiendo TODO EL CONTENIDO en un slug, no solamente una parte de el. No puedes ponerte a poner condicionales a ver si el .tagName === 'strong' porque son demasiados casos diferentes, lo mejor es cambiar la estrategia.
Tienes que lograr obtener todo el contenido del bullet en formato de texto, por ejemplo hay una función de react llamada renderToString que te devuelve el HTML de un component de react.
En lugar de getNodeText(children[i]) seria renderToString(children[i])
