### ISSUE TITLE
4Geeks Academy - Miami Coding Bootcamp, Madrid España, Santiago de Chile and Caracas · 4Geeks Academy

### ISSUE THREAD

**Issue by ThaniaCorro** [4GeeksAcademy/About-4Geeks-Academy#3830]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-9712-36144-bf352d5c098fc16b621d92138f6ec7e6) 

 No salen los planes de financiamiento con FLEVO de Venezuela

---
**Source URL**:
[https://4geeksacademy.com/es/financiacion](https://4geeksacademy.com/es/financiacion)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1366x768</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366x600</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>Zoom Level</strong></td><td>50%</td></tr></table>

**Comment by alesanchezr** [comment]
Pero esto no lo tienen que agregar uds? Esos son los YML @jatv93

**Comment by jatv93** [comment]
Eso es Vzla @alesanchezr, Chile aparece sin problemas pero si tiene un error en el botón:

![image](https://user-images.githubusercontent.com/48845580/207196155-d927f82d-7ec0-4141-aa68-0a20ec51b7a0.png)

Dice Apply y debe decir Postular

**Comment by ThaniaCorro** [comment]
Venezuela no tiene creado slug dentro del YML para poder colocar la información.
