### ISSUE TITLE
URGE no aparecen los programas correctos

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#3846]
### Bug description

En financiación no aparecen los programas correctos https://4geeksacademy.com/es/financiacion

![image](https://user-images.githubusercontent.com/62053368/207421279-3012fb2c-3137-4f55-82b8-927edda8ef2d.png)

### Steps to reproduce

https://4geeksacademy.com/es/financiacion
cuando le das a programas aparecen los anteriores no los nuevos.

**Comment by tommygonzaleza** [comment]
Solved
