### ISSUE TITLE
Spanglish on Website Spanish Version

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/About-4Geeks-Academy#3847]
### Bug description

This button should be in Spanish not in English

![image](https://user-images.githubusercontent.com/48845580/207437461-dbbcc079-66ad-448d-9016-b9715ce5971f.png)

### Steps to reproduce

Go to any program and roll to Planes y Precios 

https://4geeksacademy.com/es/coding-bootcamps/full-stack-part-time
https://4geeksacademy.com/es/coding-bootcamps/full-stack-full-time
https://4geeksacademy.com/es/coding-bootcamps/curso-datascience-machine-learning

### Expected behavior

Debe decir: Ver planes y precios

**Comment by tommygonzaleza** [comment]
![image](https://user-images.githubusercontent.com/56565994/210613983-18e374c1-6cf7-47f3-b542-9649450e02a1.png)

It still showing the button text in english

**Comment by tommygonzaleza** [comment]
Button is fine but the text with the page in english is in spanish
![image](https://user-images.githubusercontent.com/56565994/210652594-a777f548-74b4-40b7-aeaf-2d483cc9a7fe.png)
