### ISSUE TITLE
Delivery Project Not Necessary on GeekFORCE Syllabus

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/About-4Geeks-Academy#3849]
### Bug description

Este proyecto no es entregable 

![image](https://user-images.githubusercontent.com/48845580/207445696-18d0aafa-964a-4708-a9e3-4aa311a09f5f.png)

### Steps to reproduce

Ve al Syllabus Land a Job in Tech, ve al proyecto Interview Preparation 

### Expected behavior

No hay entregables, no debe existir esa opción.

**Comment by tommygonzaleza** [comment]
Fixed
