### ISSUE TITLE
Does not appear the SEO Title and the SEO Meta Decription on the Blog

### ISSUE THREAD

**Issue by Jsolis4geeks** [4GeeksAcademy/About-4Geeks-Academy#3867]
The SEO Title and The Meta Description are well-defined on the blog at the [GitHub link](https://github.com/4GeeksAcademy/blog/blob/main/blog/are-coding-bootcamps-worth-it.us.md) but when you research the [page](https://4geeksacademy.com/us/coding-bootcamps/are-coding-bootcamp-worth-it) it does not appear.

![image](https://user-images.githubusercontent.com/118853358/207904133-739cb274-e79e-408f-9827-73cf57978cb6.png)

**Comment by alesanchezr** [comment]
That article does not exists, we have to redirect to:
https://4geeksacademy.com/us/trends-and-tech/are-coding-bootcamp-worth-it

**Comment by Jsolis4geeks** [comment]
> That article does not exists, we have to redirect to: https://4geeksacademy.com/us/trends-and-tech/are-coding-bootcamp-worth-it

I see the article with the URL that I provided avobe
