### ISSUE TITLE
Make home site redirect to the respective language

### ISSUE THREAD

**Issue by Jsolis4geeks** [4GeeksAcademy/About-4Geeks-Academy#3868]
If a user visits our page 4geeksacademy.com (root).

It needs to be redirected to the detected language:
https://github.com/4GeeksAcademy/website-v2/blob/master/src/session.js#L96

I think you can use `navigate` gatsby function to avoid website refresh when redirecting.

If the language is `us` or `en` redirect to https://4geeksacademy.com/es/inicio
If the language is `es` redirect to https://4geeksacademy.com/en/home

**Comment by alesanchezr** [comment]
Waiting for new website deployment.

**Comment by alesanchezr** [comment]
Make a redirection here based on the detected language:
https://github.com/4GeeksAcademy/website-v2/blob/master/src/session.js#L96

I think you can use `navigate` gatsby fucntion to avoid website refresh when redirecting.
