### ISSUE TITLE
The attendance totalizer is incorrect.

### ISSUE THREAD

**Issue by pbullor** [4GeeksAcademy/About-4Geeks-Academy#3870]
The attendance totalizer is incorrect. It should be about the total of the classes executed, both for the students and the general totalizer of the court.

**Comment by tommygonzaleza** [comment]
This percentage should be the percentage of attendance of the days that the attendance has been taken, not the total days of the cohort

![image](https://user-images.githubusercontent.com/56565994/207946153-8fe845f2-8626-4f47-9f3b-3ce25d53a5cf.png)

**Comment by tommygonzaleza** [comment]
It's still not showing the percentage correctly, in the first image, the percentage shown by the arrow should be 100% as that student has attended to all the classes taken so far

**Comment by tommygonzaleza** [comment]
Fixed!
