### ISSUE TITLE
El reporte de asistencia por estudiante ha dejado de funcionar

### ISSUE THREAD

**Issue by marcogonzalo** [4GeeksAcademy/About-4Geeks-Academy#3896]
### Bug description

En el admin se veía el histórico de la asistencia de un estudiante, pero ha parado desde finales de noviembre, a pesar de que el curso ha seguido marcando la asistencia.
![Screenshot 2022-12-17 at 11-33-11 4Geeks Developers Community - Admin](https://user-images.githubusercontent.com/410890/208237680-ba685716-61fe-4dae-9d08-a2b3937511b6.png)

### Steps to reproduce

Ir al admin, entrar a un curso, y pedir el reporte del estudiante en la cohorte

**Comment by alesanchezr** [comment]
Esto se desactivo a proposito, era lo que hacia fallar las asistencias, mas adelante tenemos planificado volver a notificar los eventos de los alumnos pero estará apagado por ahora.
