### ISSUE TITLE
This doesn't apply to every location

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/About-4Geeks-Academy#3908]
This feature on the website doesn't apply to every location 

![image](https://user-images.githubusercontent.com/48845580/208489241-15dba86a-9cd7-451d-9c91-662ec04d8deb.png)

Especially this part:

![image](https://user-images.githubusercontent.com/48845580/208489332-24314ef0-833f-4bda-8661-3b94d1f1e5f9.png)

The text should change according to the location chosen on the price part or put more general information that applies to every location

**Comment by URubino4Geeks** [comment]
78% de los estudiantes no tienen experiencia en programación
88% of the grants and scholarships provided through 4Geeks are focused on helping diversity
80% de los graduados reciben becas parciales o totales

**Comment by URubino4Geeks** [comment]
Cerramos este issue para trabajarlo aca: https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4916 

Ahí está el diseño
