### ISSUE TITLE
Get CohortUser report

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3920]
Lets create a new JSON property in the [CohortUser object](https://github.com/breatheco-de/apiv2/blob/main/breathecode/admissions/models.py#L381) that tracks the status of a user in a cohort.

- [ ] This CohorUser.log will be read-only for the API, it will only be updated by the backend when the following signals trigger:
- [ ] assignment_status_updated: This new signal will trigger when the status updated, we can monitor an trigger this signal in the [Assignments.Task contructor](https://github.com/breatheco-de/apiv2/blob/main/breathecode/assignments/models.py). Once its triggered, in the admissions.receiver will handle the change and update the CohortUser.log accordinly.
- [ ] cohort_log_saved: This new signal will trigger when the [cohort.history_log is saved](https://github.com/breatheco-de/apiv2/blob/main/breathecode/admissions/utils/cohort_log.py#L125), receive the signal and compare changes in the cohort log, only update the new changes to the CohortUser's log's.

```
{
     delivered_assignments: [{ id: 23, type: 'lesson'},]
     pending_assignments: [{ id: 35, type: 'quiz'},]
     attendance: [{ date: '2024-04-26T18:39:00Z', cohortDay: 2 },],
     unattendance: [{ date: '2024-04-27T18:39:00Z', cohortDay: 5 },],
}
```

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/764
