### ISSUE TITLE
Add a help_text="If it is not a subscription, then the value fo these fields should be 0" in the model for the admin.

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3921]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-36269-bba63827874e71501397880b2e0baa7d) 

---
**Source URL**:
[https://breathecode-payments.herokuapp.com/admin/payments/plan/2/change/](https://breathecode-payments.herokuapp.com/admin/payments/plan/2/change/)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 107.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x646</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by Andresgarciasch** [comment]
https://github.com/breatheco-de/apiv2/pull/883
<hrs>1<hrs>

**Comment by tommygonzaleza** [comment]
<hrs>0.5</hrs>
