### ISSUE TITLE
El tag debe ser obligatorio al agregar o actualizar un lead

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3929]
Revisar que sea obligatorio tanto a la hora de crear como de actualizar (update).

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-36275-e86d9f6570e049efc6698504fe936699) 

---
**Source URL**:
[https://admin.4geeks.com/growth/leads/62167](https://admin.4geeks.com/growth/leads/62167)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 107.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x710</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by etolopez** [comment]
pr: https://github.com/breatheco-de/admin/pull/322

time: 20 minutes

**Comment by tommygonzaleza** [comment]
<hrs>0.34</hrs>

**Comment by etolopez** [comment]
pr: https://github.com/breatheco-de/admin/pull/324

time: <hrs>0.5</hrs>
