### ISSUE TITLE
Cambiar keywords en español para las landings de cada sede

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3934]
Buscar keywords en español para landings de cada sede.

Jennifer Toledo - Chile
Victor Gomez - España
Victor Gomez - Europa
Alissa Landra - Miami
Mafe - Latam
Puedes hablar con Edgar Navarro sobre que funciona mejor en adwords en cada pais

**Comment by Jsolis4geeks** [comment]
USA =
Chile: Propongo Cambiar "Bootcamp Programacion en Santiago de Chile" con 10 de Volumen por "Bootcamp Programacion" con 80
Argentina =
Bolivia =
Costa Rica: Cambiar "escuela de programacion" con 10 de Volumen por "Coding Bootcamp Costa Rica" con 70
Colombia =
Mexico = cambiar "Bootcamp de programacion" con 20 de Volumen por "Coding Bootcamp" con 200
Ecuador = 
Panama = 
Uruguay =
Venezuela =
Peru = 
España = 
Portugal =
