### ISSUE TITLE
Generate a new Sitemap

### ISSUE THREAD

**Issue by Jsolis4geeks** [4GeeksAcademy/About-4Geeks-Academy#3941]
Generate a new sitemap divided into sections between:

post-sitemap (with all articles)
page-sitemap (with all pages)
category-sitemap (with all categories-clusters)

The new sitemap should include all the URLs.
I suggest to use the following [gatsby plugin](https://www.gatsbyjs.com/plugins/gatsby-plugin-advanced-sitemap/?=sitemap)

**Comment by alesanchezr** [comment]
It seems we have to stop using `gatsby-plugin-sitemap` and start using [gatsby-plugin-advanced-sitemap](https://www.gatsbyjs.com/plugins/gatsby-plugin-advanced-sitemap/?=sitemap)

**Comment by Jsolis4geeks** [comment]
Is this already merged at 4geeksacademy?

https://4geeksacademy.com/sitemap.xml
