### ISSUE TITLE
Apply cache layer to `GET /v1/assignments/user/me/task`

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3943]
The query string should be taken into consideration if the query string changes, the results should also change.

Here is the view: https://github.com/breatheco-de/apiv2/blob/88f85a138b5f0a491cad548a8a790ade67ee8e06/breathecode/assignments/views.py#L435

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/882
