### ISSUE TITLE
Add warning when an asset is not synched with GitHub

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3944]
In the request where you are getting the asset's information, you will get the `last_synch_at` and `readme_updated_at` properties, if the `readme_updated_at` is greater than the `last_synch_at`, then you should show a warning saying `The asset is not synched with GitHub, please push your changes`.

If the `last_synch_at` property is `null`, then you should show a warning saying `This asset has never been synched with GitHub, please pull the information from the GitHub repository`

![image](https://user-images.githubusercontent.com/56565994/209408961-5fc7fd64-2223-4277-b17d-9eae9798072e.png)

**Comment by etolopez** [comment]
pr: https://github.com/breatheco-de/admin/pull/323

h: 3

**Comment by tommygonzaleza** [comment]
Added a review in the PR

**Comment by etolopez** [comment]
Pr ready with changes

**Comment by etolopez** [comment]
There is no `readme_updated_at` in any file or similar. Is there any other property that can be used?

**Comment by etolopez** [comment]
Changes have been made to the pr @tommygonzaleza

**Comment by tommygonzaleza** [comment]
<hrs>3</hrs>
