### ISSUE TITLE
El texto de la cabecera de la página en la propia home, se corta

### ISSUE THREAD

**Issue by marcogonzalo** [4GeeksAcademy/About-4Geeks-Academy#3950]
### Bug description

El texto principal de la home está cortado
![Screenshot 2022-12-24 at 11-44-29 Miami Coding Bootcamp Madrid España Santiago de Chile](https://user-images.githubusercontent.com/410890/209432476-0d5520c5-56ce-42c9-8553-c62d830b7d82.png)

### Steps to reproduce

Ir a la home de la web

### Anything else?

Firefox en Ubuntu

**Comment by alesanchezr** [comment]
@gustavomm19 hay que bajarlo un poco cuando exista el TopBar
