### ISSUE TITLE
Whatsap not working on the website

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/About-4Geeks-Academy#3952]
### Bug description

Cuando se actualizó el website se eliminó la opción de que los leads puedan ser redirigidos al whatsapp desde la página web, redirección que ha sido bastante útil hasta ahora.

https://4geeksacademy.com/us/coding-campus/coding-bootcamp-santiago

![image](https://user-images.githubusercontent.com/48845580/209582610-2926850d-e1b8-4b81-955e-d5894cd250e1.png)

### Steps to reproduce

Go to https://4geeksacademy.com/us/coding-campus/coding-bootcamp-santiago y ver datos de contacto

### Expected behavior

Se debe poder hacer click en el número telefónico y ser redireccionado a whatsapp de la empresa 

Link de whatsapp: https://api.whatsapp.com/send?phone=+56972848039&text=Hola+4Geeks&utm_source=web_site&utm_medium=web_site&utm_campaign=web_site&utm_id=web_site&utm_term=web_site&utm_content=Web_site

**Comment by alesanchezr** [comment]
@gustavomm19 que paso que el whatsup se desactivo? vamos a reactivarlo.

**Comment by tommygonzaleza** [comment]
Cuando le doy click en el link del telefono me redirecciona a whatsapp pero me dice que link es incorrecto
