### ISSUE TITLE
Add a new page that show the event type

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3954]
From `https://admin.4geeks.com/events/NewEvent`, add a link below the event type dropdown that should take the user to a new page that shows and allow them to manage the event types.
![image](https://user-images.githubusercontent.com/56565994/209724721-39ceafab-b976-49e8-83b9-a7fe3c439145.png).

## List of event types
Route: `/events/type/list`
This list will show all the event types with 4 columns:
- Name (with the slug under in smaller letters)
- The language flag.
- Only if your academy created the event: A toggle to show if `shared creation` is `on`. If your academy did not create the event the column should say: `Shared from 4Geeks Academy Miami` (being 4geeks academy miami the real author of this event type).
- The last column should have a `pencil` icon to redirect the user to edit the event when clicked.

## Edit/Create event type
Route: `/events/type/<type_slug>`
[This is an example on how the view to edit en event type should look like.](https://tinyurl.com/2ltcoj76).

The left side of the view should allow modifying the following event type's data only if the current academy created the event:
- Name (Text input)
- Slug (Text input)
- Description (Text Area)
- Language (Dropdown like the one used for the assets)
- Allow sharing creation with other academies (Dropdown, true or false)
Note: if you are not the academy that created the event, you can only read the information on the left side, not edit.

**On the right side: Share the event**
On the right side there is a box for the academy user to share the event with its students. It can be done by specifying the syllabus or the cohorts that you want to share the events with.

The URL that you should use to get all the eventtypes is: `GET /v1/events/academy/eventype`

The URL that you should use for a specific eventtype is `GET /v1/events/academy/eventype/<eventtype_slug>`

The URL in the front where the page that has the list of eventtypes will be: `https://admin.4geeks.com/events/type/list`, and for specific eventtype: `https://admin.4geeks.com/events/type/<eventtype_slug>`

On this [issue](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3953) we are creating the endpoint to modify the eventtypes

Expected time: 10 - 14

**Comment by etolopez** [comment]
pr: https://github.com/breatheco-de/admin/pull/338

Hours: Many.

At the moment, we still need information from the backend where we receive for Eventypes.Visibility_settings in order for the view to show Shared settings.

**Comment by tommygonzaleza** [comment]
En la lista de event types no se debe mostrar los events que no sean de esta academia cuyo `allow_shared_creation` sea True

**Comment by tommygonzaleza** [comment]
Ya deberias poder recibir `Eventypes.Visibility_settings`

**Comment by etolopez** [comment]
pr: https://github.com/breatheco-de/admin/pull/338

Every functionality is working up till now. The only thing we need is a post/put for the visibility settings aside from just using the one in the Event Type.

After this, we can update the modal to point to that endpoint and successfully add/update visibility settings inside each event type.

hrs: <hrs>14</hrs>

**Comment by etolopez** [comment]
pr: https://github.com/breatheco-de/admin/pull/338

**Comment by tommygonzaleza** [comment]
- [ ] Modifica el nombre del componente `JoinEvents`, y revisa que tienes un codigo comentado en ese mismo componente
- [ ] Cambia el nombre de la carpeta `EditAddEventTypes` por `EventTypesForm`
- [ ] Se modifico el componente `events/events.jsx`, ahi no hace falta modificar la url

**Comment by etolopez** [comment]
pr: https://github.com/breatheco-de/admin/pull/338

El codigo quedo comentado porque hace falta el backend para que esa funcionalidad del boton funcione. Una vez que eso este listo, quitamos el comentario y agregamos el PUT/DELETE para que funcione ese boton. 

Ahorita solo se muestra la info, pero no podemos agregar Visibility_settings.

**Comment by tommygonzaleza** [comment]
- [ ] Poner la bandera del language al lado del nombre al inicio

**Comment by etolopez** [comment]
pr: https://github.com/breatheco-de/admin/pull/338

Hice el cambio, pero ahora en el backend hay un "icon_url" que esta por defecto y no deja hacer cambios. 

Agregue un avatar image para despues porque recuerdo que Alejandro queria que eso estuviese implementado tambien para mas tarde

**Comment by tommygonzaleza** [comment]
- [ ] Agrega un campo para subir una imagen, utiliza el mismo [componente](https://github.com/breatheco-de/admin/blob/3fa285edf85a503d9c6ba42570a535b08ca24ea1/src/app/views/media/components/AssetMeta.js#L48) que se usa en el preview de los assets
- [ ] Muestra la bandera de esta manera:
![Screenshot 2023-02-28 at 2 23 13 PM](https://user-images.githubusercontent.com/56565994/221944979-b2bdc16c-e745-47bd-886b-3f8a7cb2c323.png)
- [ ] Utilizar valor de `EventType.icon_url` en la lista de event types

**Comment by etolopez** [comment]
pr: https://github.com/breatheco-de/admin/pull/338

Made changes

**Comment by tommygonzaleza** [comment]
- [ ] Eventtypes with language == `'en'` or `'us'` should show the us flag

**Comment by etolopez** [comment]
pr: https://github.com/breatheco-de/admin/pull/338

<hrs>0.5 </hrs>

**Comment by tommygonzaleza** [comment]
![Screenshot 2023-03-14 at 2 12 28 PM](https://user-images.githubusercontent.com/56565994/225099175-c90b4c56-fe35-4299-a2a4-4e1e02a20506.png)

**Comment by etolopez** [comment]
pr: https://github.com/breatheco-de/admin/pull/338

**Comment by tommygonzaleza** [comment]
- [ ] Para el dropdown de language de un event type, se deben usar los lenguajes de la misma manera en que se usa en los assets
- [ ] En el request de `GET /v1/events/academy/eventype?allow_shared_creation=true`, debes incluir el querystring `?allow_shared_creation=true`

**Comment by etolopez** [comment]
pr: https://github.com/breatheco-de/admin/pull/338

<hrs>0.5 </hrs>

**Comment by tommygonzaleza** [comment]
Esperando por este [issue](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4683)

**Comment by tommygonzaleza** [comment]
<hrs>14</hrs>

**Comment by tommygonzaleza** [comment]
Solucionar conflictos en el PR

**Comment by etolopez** [comment]
Listos los cambios!

**Comment by tommygonzaleza** [comment]
Esperando a que termine este issue: https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4820

**Comment by tommygonzaleza** [comment]
<hrs>14</hrs>
