### ISSUE TITLE
Funcionalidad de LiveClass

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3955]
- Las clases se generan automaticamente cada vez que se crea o edita un bc.admissions.CohortSchedule.
- Solo se van a generar LiveClass que ocurrirán en el futuro, el pasado no importa.
- Crear un endpoint para empezar o terminar la clase que podrá se llamado por quien tenga el capability `start_or_end_class`. Por ejemplo: `PUT /event/liveclass/12/status`
- Si un profesor se le olvida cerrar clases el ended_at quedara nulo y deberia haber un cronjob que cierre las clases automaticamente después de 30 min, y se le debe mandar una notificacion al profe para que no ocurra de nuevo.

Propiedades:
- cohort: mandatorio
- academy: mandatorio
- log: sera un JSON llenara automáticamente con los acontecimientos de la clase (lista de personas que entraron, etc.). Esto se va a definir en otro issue.
- started_at: null por defecto, luego se llena con la fecha en que empezó el evento.
- ended_at: null por defecto, luego se llena con la fecha en que termino el evento
- starting_at: timestamp planificado para el inicio de esta clase
- ending_at: timestamp planificado para el fin de esta clase
- remote_meeting_url: mandatorio
- created_at (automatic)
- updated_at (automatic)

## Obtener mis clases

`GET /event/me/liveclass`
Este endpoint devolverá una lista de todas las clases magistrales que un alumno tiene.

- [ ] Paginar el endpoint.
- [ ] Si el querystring dice `upcoming=true` entonces solo las clases con ended_at=null.
- [ ] También poder filtrar por fecha `start` y `end`
- [ ] Poder filtrar por `cohort` y por `academy`.
- [ ] Poder filtrar pot `syllabus`.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/701/files

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/701
