### ISSUE TITLE
Add a new endpoint where you can ask for an event URL

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3956]
Create the endpoint `GET /v1/events/me/join/<event_id>`, which returns a JSON with the event including the event URL.

If the user has not paid, then it should throw a ValidationError with status code 402, and the following message: `Your current plan does not allow you to join this event`

**Comment by jefer94** [comment]
Actually have a message, I think use that message is not sufficient descriptive because the consumables should come from subscription, plan financing and individual consumables
