### ISSUE TITLE
Configure Event Types in Production Environment

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3962]

**Comment by alesanchezr** [comment]
Ya to cree estos event types en ambos idiomas:

HTML/CSS
JS Beginner
JS Advanced
Python Beginner
Geekforce Free
Geekforce Premium
Data Science Beginner
Data Science Advanced
Other Full Stack Technologies Workshop
Tech not taught by 4Geeks

Todavia esta faltando crear la visibilidad para cada academia.

**Comment by tommygonzaleza** [comment]
Visibility settings were created for each academy. There are no visibility settings filtering events by cohort or syllabus yet
