### ISSUE TITLE
Terminar de Implementar componente que muestra los eventos de un alumno

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#3983]
The following endpoint: `GET /v1/events/me/join/<event_id>` gives you all the events a user can attend.

Integrate that endpoint with the <LiveEvents> component.

Note: An endpoint with live class will be available soon, that will need to integrate as well, [here is the issue](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3955).

**Comment by tommygonzaleza** [comment]
When a user clicks on an event to join the event, get all the event's information and use the property `live_stream_url` which is the URL that you should redirect the user to.

**Comment by tommygonzaleza** [comment]
Waiting for this [issue](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4002)

**Comment by tommygonzaleza** [comment]
Use the endpoint `GET /v1/events/academy/event/<event_id>` to get all the event's information
