### ISSUE TITLE
Test error

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/About-4Geeks-Academy#399]
Exercise 06.4 in javascript-arrays-exercises-tutorial

Test: x (fail) 1. Loop the array but jumping two items at a time instead of just one at a time

That is not asked in the instructions 

And the increasingValue is not 0 at the beginning as the instructions say

**Comment by alesanchezr** [comment]
Hey @jatv93 you are completely right, we are fixing this.

**Comment by alesanchezr** [comment]
Fixed @jatv93, if you download a new copy of the exercises or type on the console: 
```javascript
git pull https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial master
```

You will get the solutions.
