### ISSUE TITLE
Agregar tiempo de vida estimado a los planes

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#3997]
Agregar tiempo de vida estimado a los planes pero ese valor debe estar nulo si el plan es una subscripcion. Este campo debe ser un timedelta.

Este valor se va a utilizar cuando sea un plan no renovable que dura X cantidad de tiempo, ya existe un campo en la base de datos para saber si un plan no es renovable `is_renewable`.

Si `is_renewable` is True, `duration` debe ser `null`, si `is_renewable` is False, entonces no puede ser `null`.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/709

**Comment by tommygonzaleza** [comment]
El modelo esta bien pero falta la implementacion, en que va a impactar en los cronjobs? Tasks asincronos?

**Comment by tommygonzaleza** [comment]
Waiting for the Django transactions that will be implemented on this [issue](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4258)
