### ISSUE TITLE
Test Javascript Array

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/About-4Geeks-Academy#400]
Exercise 06.5 in javascript-arrays-exercises-tutorial

x (fail) 1. Do not use the reverse function

Even when it's not used the error appears

**Comment by alesanchezr** [comment]
Sorry @jatv93 I cannot replicate this error, can you show me the code of your solution?

**Comment by jatv93** [comment]
`let inverted = [];
for(let i = mySampleArray.length-1; i>=0;i--){
    console.log(mySampleArray[i]);
}`

**Comment by alesanchezr** [comment]
Thank you!!!! Its fixed now 😆
