### ISSUE TITLE
Payment options for subscriptions

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4001]
If the property `financing_options` is empty, then it is a subscription and you should show all the options that you receive in the checking endpoint:

`amount_per_half`
`amount_per_month`
`amount_per_quater`
`amount_per_year`

If one of these values is `0`, then you shouldn't show it.

**Comment by tommygonzaleza** [comment]
You should send the cohort id as an integer, you shouldn't send a list

**Comment by tommygonzaleza** [comment]
Sigue fallando el flujo, ahora por la academia...

**Comment by tommygonzaleza** [comment]
- [ ] It's not showing all the payment options.
- [ ] It's showing undefined instead of how often it will be paid

![image](https://user-images.githubusercontent.com/56565994/213054153-3c1b4f7b-4d69-41f9-82f9-ed149122f170.png)

**Comment by tommygonzaleza** [comment]
It's also using the wrong chosen period, as the only one showed was the MONTH, I chose it, and it used the YEAR instead. Remember chosen_period should be selected by the user

**Comment by tommygonzaleza** [comment]
Hay un problema con el flujo, esta descrito en este video: https://www.loom.com/share/66b2267fb6a245fbbcbf67d46822488c

**Comment by tommygonzaleza** [comment]
And it should say 20$ x month, 200$ x year, the time (month, year, quater, half) will always be the same

**Comment by ArielCalisaya** [comment]
>Solved with PR [sync main to development #612](https://github.com/breatheco-de/app/pull/612)

**Comment by tommygonzaleza** [comment]
And it should say 20$ x month, 200$ x year, the time (month, year, quarter, half) will always be the same. It should be added in the cards as well
