### ISSUE TITLE
Crear YML de los clusters en 4geeksacademy.com

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4005]
En la carpeta ./src/data/clusters vas tienes que ir agregando dos YML para cada cluster, ingles y español.

El contenido con:

1. Toda la metadata bien puesta
2. Un párrafo que incluya keyword y CTA.
3. Una foto que llame la atencion.

**Comment by tommygonzaleza** [comment]
Crea un prompt de chatGPT en el que los textos sean mas directos, menos infantiles, que funcione para SEO segun la keyword, utiliza el prompt que paso Alejandro

**Comment by alesanchezr** [comment]
Voltea las descripciones para que hable primero del tema y luego la prte generica de como redactamos los articulos etc.

**Comment by Jsolis4geeks** [comment]
https://github.com/4GeeksAcademy/website-v2/pull/1567
