### ISSUE TITLE
Migration of learnpack website to gatsby

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4006]
Redo learnpack home and about sites from webflow to Jekyll:
https://learnpack-969ddd.webflow.io/
https://learnpack-969ddd.webflow.io/about

**Comment by tommygonzaleza** [comment]
- [ ] Remove images of dots from the footer (The one that returns the error)
- [ ] Fix bug related to the navbar

**Comment by tommygonzaleza** [comment]
- [ ] Change the font to the one used in webflow

**Comment by aayalapalacin** [comment]
> 

complete: https://github.com/learnpack/website

**Comment by tommygonzaleza** [comment]
<img width="295" alt="Screenshot 2023-01-24 at 5 27 35 PM" src="https://user-images.githubusercontent.com/56565994/214421706-85a30274-f5eb-4ea8-b22c-fd616979186e.png">
Add LearnPack icon

**Comment by aayalapalacin** [comment]
Hours: 20

**Comment by tommygonzaleza** [comment]
<hrs>20</hrs>
