### ISSUE TITLE
Revisar titulo, escritura y errores de 20 proyectos

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4008]
- [x] https://github.com/4GeeksAcademy/jwt-authentication-with-node-react/pull/3
- [x] https://github.com/4GeeksAcademy/interview-preparation/pull/10
- [x] https://github.com/4GeeksAcademy/code-rick-and-morty-with-node/pull/1
- [x] https://github.com/4GeeksAcademy/code-rest-api-node-with-express/pull/1
- [x] https://github.com/4GeeksAcademy/create-form-node-js/pull/1
- [x] https://github.com/breatheco-de/starwars-data-model-typeorm-node/pull/3
- [x] https://github.com/4GeeksAcademy/build-your-full-stack-developer-resume/pull/10
- [x] https://github.com/4GeeksAcademy/machine-learning-final-project/pull/1
- [x] https://github.com/4GeeksAcademy/ml-webapp-using-streamlit-tutorial/pull/2
- [x] https://github.com/4GeeksAcademy/image-classifier-project-tutorial/pull/2/files
- [x] https://github.com/4GeeksAcademy/alternative-time-series-project/pull/1
- [x] https://github.com/breatheco-de/starwars-data-model-typeorm-node/pull/3
- [x] https://github.com/4GeeksAcademy/time-series-project-tutorial/pull/1
- [x] https://github.com/4GeeksAcademy/boosting-algorithms-project-tutorial/pull/2
- [x] https://github.com/4GeeksAcademy/optimize-github-profile/pull/7
- [x] https://github.com/4GeeksAcademy/naive-bayes-project-tutorial/pull/2
- [x] https://github.com/4GeeksAcademy/decision-tree-project-tutorial/pull/2
- [x] https://github.com/4GeeksAcademy/regularized-linear-regression-project-tutorial/pull/1
- [x] https://github.com/4GeeksAcademy/random-forest-project-tutorial/pull/2
- [x] https://github.com/4GeeksAcademy/logistic-regression-project-tutorial/pull/2
- [x] https://github.com/4GeeksAcademy/data-preprocessing-project-tutorial/pull/6
- [x] https://github.com/4GeeksAcademy/linear-regression-project-tutorial/pull/2
- [x] https://github.com/4GeeksAcademy/web-scraping-project-tutorial/pull/2
- [x] https://github.com/4GeeksAcademy/connecting-to-a-sql-database-project-tutorial/pull/7
- [x] https://github.com/4GeeksAcademy/descriptive-statistics-exercises-project-with-python/pull/2
- [x] https://github.com/4GeeksAcademy/create-form-node-js/pull/2
- [x] https://github.com/4GeeksAcademy/ml-webapp-using-flask-tutorial/pull/2
- [x] https://github.com/4GeeksAcademy/probability-distribution-exercises-project-with-python/pull/2
- [x] https://github.com/4GeeksAcademy/algorithm-optimization-project-machine-learning/pull/3
- [x] https://github.com/4GeeksAcademy/probability-exercises-project-in-python/pull/2
- [x] https://github.com/breatheco-de/calculus-and-algebra-problems-with-python/pull/7
- [x] https://github.com/4GeeksAcademy/hypothesis-testing-exercises-project-with-python/pull/2
- [x] https://github.com/4GeeksAcademy/k-nearest-neighbors-project-tutorial/pull/2
- [x] https://github.com/4GeeksAcademy/k-means-project-tutorial/pull/3
- [x] https://github.com/breatheco-de/exercise-todo-list-react-context/pull/2
- [x] https://github.com/4GeeksAcademy/interacting-with-the-twitter-api-project-tutorial/pull/2
- [x] https://github.com/breatheco-de/jwt-authentication-with-flask-react/pull/9
- [ ] https://github.com/4GeeksAcademy/realestate-datacleanup-exercise/pull/3
- [ ] https://github.com/breatheco-de/exercise-starwars-blog-api/pull/14
- [ ] https://github.com/breatheco-de/exercise-personal-portfolio-react/pull/3
- [ ] https://github.com/breatheco-de/exercise-starwars-data-modeling/pull/26
- [ ] https://github.com/breatheco-de/exercise-terminal-challenge/pull/43
- [ ] https://github.com/breatheco-de/exercise-unit-test-with-jest/pull/44
- [ ] https://github.com/breatheco-de/exercise-tictactoe-react/pull/5
- [ ] https://github.com/breatheco-de/exercise-todo-list-react-with-fetch/pull/4
- [ ] https://github.com/breatheco-de/exercise-battleship-vanillajs/pull/2
- [ ] https://github.com/breatheco-de/exercise-sorting-cards-with-select/pull/4
- [ ] https://github.com/breatheco-de/exercise-multi-view-react-collaborative-website/pull/2
- [ ] https://github.com/breatheco-de/exercise-sorting-cards-with-bubble/pull/5
- [ ] https://github.com/breatheco-de/exercise-meetup-clone-react/pull/3
- [ ] https://github.com/breatheco-de/exercise-contact-list/pull/9
- [ ] https://github.com/breatheco-de/exercise-random-card/pull/19
- [ ] https://github.com/breatheco-de/exercise-contact-list-context/pull/69
- [ ] https://github.com/breatheco-de/exercise-family-tree-static-api/pull/3
- [ ] https://github.com/breatheco-de/exercise-todo-list-api/pull/2
- [ ] https://github.com/breatheco-de/exercise-queue-management-api/pull/3
- [ ] https://github.com/breatheco-de/python-flask-api-tutorial/pull/57
- [ ] https://github.com/breatheco-de/urban-dictionary-project-tutorial/pull/6
- [ ] https://github.com/breatheco-de/exercise-conditional-profile-card/pull/69
- [ ] https://github.com/breatheco-de/tutorial-project-excuse-generator-javascript/pull/18
- [ ] https://github.com/breatheco-de/exercise-tictactoe-cli-python/pull/1
- [ ] https://github.com/breatheco-de/exercise-compression-algorithm-python/pull/1
- [ ] https://github.com/breatheco-de/exercise-landing-page-with-react/pull/12
- [ ] https://github.com/breatheco-de/exercise-postcard/pull/73
- [ ] https://github.com/breatheco-de/exercise-instagram-post/pull/29
- [ ] https://github.com/breatheco-de/exercise-instagram-feed-bootstrap/pull/34
- [ ] https://github.com/breatheco-de/exercise-excuse-generator-python-cli/pull/4
- [ ] https://github.com/breatheco-de/exercise-random-card-cli-python/pull/3
- [ ] https://github.com/breatheco-de/exercise-queue-management-cli-python/pull/7
- [ ] https://github.com/breatheco-de/exercise-todo-list-cli-with-cloud/pull/7
- [ ] https://github.com/breatheco-de/exercise-todo-list-cli-python/pull/10

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/jwt-authentication-with-node-react/pull/3

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/interview-preparation/pull/10

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/code-rick-and-morty-with-node/pull/1

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/code-rest-api-node-with-express/pull/1

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/create-form-node-js/pull/1

**Comment by Lorenagubaira** [comment]
PR: https://github.com/breatheco-de/starwars-data-model-typeorm-node/pull/3

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/build-your-full-stack-developer-resume/pull/10

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/machine-learning-final-project/pull/1

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/ml-webapp-using-streamlit-tutorial/pull/2

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/image-classifier-project-tutorial/pull/2/files

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/ml-webapp-using-flask-tutorial/pull/2/files

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/alternative-time-series-project/pull/1

**Comment by Lorenagubaira** [comment]
PR: https://github.com/breatheco-de/starwars-data-model-typeorm-node/pull/3

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/time-series-project-tutorial/pull/1

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/boosting-algorithms-project-tutorial/pull/2

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/optimize-github-profile/pull/7

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/naive-bayes-project-tutorial/pull/2

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/decision-tree-project-tutorial/pull/2

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/regularized-linear-regression-project-tutorial/pull/1

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/random-forest-project-tutorial/pull/2
