### ISSUE TITLE
The description should be able to be modified like the preview image

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4011]
The description should be able to be modified like the preview image. It should be a new card in the meta info, it will be a textarea. remember to modify the value `description` from the asset.

![image](https://user-images.githubusercontent.com/56565994/210884670-3947d145-0c81-4358-9ab3-4acebb15ad6d.png)

**Comment by etolopez** [comment]
pr:  https://github.com/breatheco-de/admin/pull/346

<hrs> 1 </hrs>

**Comment by tommygonzaleza** [comment]
Make it a textarea instead of an input

**Comment by tommygonzaleza** [comment]
- [ ] Add a words counter in the description card.
- [ ] Remove the message of `"Edit asset's description"`.

**Comment by etolopez** [comment]
pr: https://github.com/breatheco-de/admin/pull/346

<hrs>2.5</hrs>

**Comment by tommygonzaleza** [comment]
![Screenshot 2023-03-14 at 2 30 51 PM](https://user-images.githubusercontent.com/56565994/225103553-e1497427-b86d-4812-8615-3243f1f94660.png)

**Comment by etolopez** [comment]
pr: https://github.com/breatheco-de/admin/pull/346

h:<hrs>0.5</hrs>

**Comment by tommygonzaleza** [comment]
Esta dando un error con los assets que no tienen description. Dice que se esta intentando acceder a length de undefined

**Comment by etolopez** [comment]
Listo el pr: https://github.com/breatheco-de/admin/pull/346

**Comment by tommygonzaleza** [comment]
<hrs>5.5</hrs>
