### ISSUE TITLE
On the gitpod user expiration, do not suggest deletion of active teachers, TA's and mentors

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4017]
[This code](https://github.com/breatheco-de/apiv2/blob/4ef306bbbb24d5e7c2fac177fd71d70455b7f5a6/breathecode/authenticate/actions.py#L118) set the expiration of gitpod accounts. The script runs once every day.

- [ ] If a gitpod user is found that belongs to a teacher or TA from an active cohort, the expiration date should be set to the cohort last day of class.
- [ ] If a gitpod user is found that belongs to a mentor that is active and its included actively in a service that is being shown to the students, the expiration date should be postponed for 15 days.
- [ ] Create a group unit tests for the whole function.

**Comment by tommygonzaleza** [comment]
We are not going to use Gitpod anymore
