### ISSUE TITLE
Don't allow to receive a list of cohorts or plans in the `PUT /v1/payments/checking`

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4039]
Add a validation here to return a ValidationException if the variable cohort is a list.

Refactor the code to accept strings and numbers instead of lists.

The same happens for the plan, it should only be a string, and it can't be a list

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/703
