### ISSUE TITLE
Allow filtering by `AssetTechnology.sort_priority` in the endpoint `GET /v1/registry/academy/technology/`

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4043]
- [ ] You will have to modify the view used for this endpoint, which you can find [here](https://github.com/breatheco-de/apiv2/blob/main/breathecode/registry/views.py#L112)
- [ ] Here is an example of filtering by [language](https://github.com/breatheco-de/apiv2/blob/main/breathecode/registry/views.py#L136). You will have to do something similar but with the property `sort_priority`.

Expected time: 1 - 2

> Remember to ask all the questions you may have

**Comment by tommygonzaleza** [comment]
Ya agregaste los ultimos cambios que te pidio Jeferson?

**Comment by tommygonzaleza** [comment]
Este [issue](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4738) esta esperando por esta funcionalidad. Es urgente para el lanzamiento

**Comment by Andresgarciasch** [comment]
<tmr>1.5<tmr>
