### ISSUE TITLE
Proposal for customdata needed for DevCycle Feature Flags

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4057]
Based on [this documentation](https://docs.devcycle.com/docs/sdk/client-side-sdks/react#identifying-users) it seems we need to specify to DevCycle any custom data we want to use for decision making when toggling features.

- [ ] Which variables are we going to be including in the information we send to DevCycle?
- [ ] When can the by included? Please do it as early as possible in the app livecycle.
- [ ] Which variables will be private or public?

**Comment by tommygonzaleza** [comment]
https://www.notion.so/4geeksacademy/Feature-Flags-87b06b2812164f4a970f246cc2cc07c1
