### ISSUE TITLE
Bug for cohort not defined

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4060]
I think there is a bug on [this line of code](https://github.com/breatheco-de/apiv2/blob/09a5d5464528ca9ca701ceb1d7cc5095d9ddd04b/breathecode/events/views.py#L205) because the `cohort` variable is not defined.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/708
