### ISSUE TITLE
Review stale issues 

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4062]
There are too many issues in stale, we should close or reasign them.
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues?q=is%3Aopen+is%3Aissue+label%3Astale

**Comment by tommygonzaleza** [comment]
10 stale issues reviewed this week

**Comment by tommygonzaleza** [comment]
Voy a cerrar este issue ya que esta tarea se convirtio en una tarea recurrente de todas las semanas
