### ISSUE TITLE
EventType's release

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4063]
- [ ] #4208
- [x] Documentation [about recurring events](https://www.notion.so/4geeksacademy/About-Recurring-Workshops-357b54b2f8ed471384acf47bb4cfa127) that links to [event types for details on the types](https://www.notion.so/4geeksacademy/Event-Types-cc13815dd05c4085942cf430a662beef).
- [x] Configure feature flags.
- [x] Create a spreadsheet or notion with the calendar for the upcoming events and which campus will take care of it.
- [ ] #4703
- [x] Turn feature flag on so the event components is available to students. (Will be turned on Tuesday Feb 21st)

Note: We are not going to be using the same marketing platform we already have, 4geeks.com does not have any tools for promoting events right now.

**Comment by tommygonzaleza** [comment]
Modify the Workshops' notion document
