### ISSUE TITLE
4Geeks Developers Community - Admin

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4065]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-36602-466c412f93ca09278be7f51de0d9cd36) 

 No está tomando los tags, dice que se debe llenar el campo, cuando el mismo ya tiene uno seleccionado.

---
**Source URL**:
[https://admin.4geeks.com/growth/sales/new](https://admin.4geeks.com/growth/sales/new)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 109.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1366x768</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366x657</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by etolopez** [comment]
Taggs appear to be working fine without any changes!

![Image](https://user-images.githubusercontent.com/83386931/222922720-35a95254-05b1-48e0-a403-44f257f78021.PNG)
