### ISSUE TITLE
Array Test Not Found

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/About-4Geeks-Academy#408]
Exercise 10.1 in javascript-arrays-exercises-tutorial

 ➔ 🚫 No test script found on the exercise files

From this one to the last one there are no test

**Comment by alesanchezr** [comment]
No pude replicar esto 🤔  si tiene prueba.

**Comment by alesanchezr** [comment]
Este error te sigue dando?

**Comment by jatv93** [comment]
Hice un git pull https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial master por si acaso, pero me da el mismo error.
