### ISSUE TITLE
Website esta mostrando cohorts de MDC

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4081]
### Bug description

Then the calendar is displaying "all locations" it should only show the ones from 4Geeks, no the other schools like mdc.
<img width="1247" alt="Screen Shot 2023-01-17 at 2 59 29 PM" src="https://user-images.githubusercontent.com/426452/213000898-d7d68ae2-1be0-44b2-9dbd-67c6ee730531.png">

Only this academies should show up on the calendar:
https://tinyurl.com/2osmrjge

### Steps to reproduce

1. Go to https://4geeksacademy.com/us/next-dates
2. Choose "all locations"
3. The "web development" cohorts will show up but they are not from our locations.

**Comment by aayalapalacin** [comment]
@alesanchezr yo no veo ninguno que no pertence de 4geeks segun el documento 
<img width="767" alt="image" src="https://user-images.githubusercontent.com/95265085/215234689-ebf7e3e5-ed3e-4ab9-8109-4ecbfcd17c06.png">

<img width="521" alt="image" src="https://user-images.githubusercontent.com/95265085/215234652-ed1643d2-6d14-47c0-a57e-a2da24f280f9.png">

Lo puedo mirar- que es el repo?

**Comment by tommygonzaleza** [comment]
A mi tampoco me aparecen las de mdc, parece estar resuelto
