### ISSUE TITLE
FeatureFlag front-end Implementation 

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4084]
Based on the [Launchdarkly documentation](https://docs.launchdarkly.com/sdk/client-side/react/react-web?site=launchDarkly#example-app) and our [FeatureFlag Guidelines](https://www.notion.so/4geeksacademy/Feature-Flags-87b06b2812164f4a970f246cc2cc07c1) let setup the FeatureFlag functionality on the codebase.

- [ ] Add `blocking` implementation HOC of the LunchDarkdly API as context to the main app.
- [ ] [Identify the user](https://docs.devcycle.com/docs/sdk/client-side-sdks/react#identifying-users) when `login`, when it lands directly into any website `using the token` querystring, and again when `clicking into a cohort dashboard`.
- [ ] Reset the user on `logout` or when `login` again or when `landing into a landing page using the token in the querystring`.
- [ ] Build small landing page to test feature toggles live based on the current session.
- [ ] You should communicate the session object with Launchdarkly in three crucial moments, when the sessions starts, when the user logs in, and when the user access to the cohort's dashboard.

**Comment by tommygonzaleza** [comment]
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4056
