### ISSUE TITLE
Esrtategia de link building

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4102]
Sientate a plantear una estrategia de link building
- [ ] Que tecnicas existen para saber cuales podriamos usar? Link reclamation, Resource link building, Skyscraper and modified skyscraper, 10x content, Guestographics, Ego bait.
- [ ] Plantar una o dos tecnicas y como las podriamos usar.

Sobre la utilizacion de linkhunter.
Basados en el analis que se hizo en #4041 vamos a usar linkhunter free trial y ver como nos va.

- [ ] Cual paginas podemos optimizar con link building?
- [ ] Que tipo de templates hay para saber que paginas podemos optimizar.
- [ ] Hay algun tempalte o idea que podriamos usar para optimizar "full stack developer" [con este landing page](https://4geeksacademy.com/us/coding-bootcamps/part-time-full-stack-developer).
- [ ] Sera que solo podemos optimizar blog postos?

**Comment by Jsolis4geeks** [comment]
Entre las estrategias propongo las plantedas en este articulo de ahrefs https://ahrefs.com/blog/link-building-strategies/ especificamente 3.

**Outreach:** la cual se encuentra mucho mejor explciada en este articulo de [Semrush](https://www.semrush.com/blog/link-building-outreach/?kw=&cmp=US_SRCH_DSA_Blog_EN&label=dsa_pagefeed&Network=g&Device=c&utm_content=622080552642&kwid=dsa-1754723153193&cmpid=18348486859&agpid=145169431190&BU=Core&extid=60113851361&adpos=&gclid=Cj0KCQiAw8OeBhCeARIsAGxWtUzQZxGqrSpmft7_HDmmKFnCC2tC-gzGVjc0SFL-pLX2nXiyD7wsKj0aAlTsEALw_wcB) y tiene varias ramas, en lo personal creo que la menos peligrosa y mas beenficiosa para la compañia en cuanto a Outreach puede ser la de Skyscraper, no recomiendo Guest Posting porque puede ser mal calificada por Google, aunque se pudiera intentar.

**Broken link building:** La construcción de enlaces rotos implica tres pasos: Encontrar un enlace roto relevante en un sitio web; crear algo similar al recurso roto; pedir al webmaster que el link al recurso inactivo lo modifique por el nuestro. (esta es Link Reclamation)

**Menciones no vinculadas:** A veces, las personas mencionan a la empresa sin un enlace, esta estrategia consiste en escribirles para ver si quieren enlazarnos.

**Marketing de Afiliados**: Otra estrategia muy utilizada es la de los enlaces de afiliados, por ejemplo que por cada persona que compre un curso proveniente de un enlace especifico la persona que da ese enlace gana una pequeña comision.

**Comment by Jsolis4geeks** [comment]
Con respecto a LinkHunter, estoy todavia tratando de acceder a la app paa comenzar a testarla pero si se puede atacar la keyword de Full Stack Developer para esa landing.

**Comment by Jsolis4geeks** [comment]
Necesito ayuda para crear el template y linkear als cuentas de correo

**Comment by alesanchezr** [comment]
ya el template fue creado, vamos a probar con la campaña de Incluir a 4Geeks en listados
