### ISSUE TITLE
3 articulos para la proxima semana

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4103]
1. software-engineer-portfolio
2. software-engineer-in-berlin
3. coding-bootcamp-in-berlin

**Comment by Jsolis4geeks** [comment]
https://admin.4geeks.com/media/asset/software-engineer-portfolio
https://admin.4geeks.com/media/asset/software-engineer-in-berlin
https://admin.4geeks.com/media/asset/coding-bootcamp-in-berlin

**Comment by Jsolis4geeks** [comment]
https://admin.4geeks.com/media/asset/how-to-update-python-version
https://admin.4geeks.com/media/asset/how-to-update-python-in-terminal
