### ISSUE TITLE
When creating a new asset in the SEO view it's not including category

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4110]
It should include a category field in the modal as it is mandatory in the backend

![image](https://user-images.githubusercontent.com/56565994/213552710-fdaa3cd6-8228-413e-89fd-616b55016d78.png)

**Comment by etolopez** [comment]
pr: https://github.com/breatheco-de/admin/pull/331
h: <hrs>7</hrs>

**Comment by tommygonzaleza** [comment]
I already did this
