### ISSUE TITLE
Conceptualizar Workshops v1.0

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4124]
Main messages: 

What's a workshop: Is a recurring event that aways has the same structure, purpose and topic. For example: Basics of Javascript.
- The speakers may change from workshop to workshop.
- The exercise/activity may change from workshop to workshop.
- Workshops will revolve around technologies, users can subscribe to a workshop technology.
- The difficulty needs to be consisten, it won't vary from workshop to workshop.
- The purpose will be consistent.

- [x] Que otros mensajes hay que incluir en el landing?
- [ ] Notification model: Users can ask to be notified about workshops.
- [x] Diseño de landing

**Comment by tommygonzaleza** [comment]
Contenido para el diseño: https://www.figma.com/file/DmbZeNT2RdEQHpaknWVB1z/Workshops-Landing-Page?node-id=0%3A1&t=FCS2JcZxKaUjSMjg-1
