### ISSUE TITLE
Mover syllabus de "admin" a "admissions"

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4140]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-36742-c577897063a52781e605fe3d17bfa1b2) 

---
**Source URL**:
[https://admin.4geeks.com/media/asset](https://admin.4geeks.com/media/asset)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x673</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by aayalapalacin** [comment]
https://github.com/breatheco-de/admin/pull/336

**Comment by tommygonzaleza** [comment]
You forgot to change the path from `/admin/syllabus` to `/admissions/syllabus`. I fixed it for you

**Comment by tommygonzaleza** [comment]
It's not working, it's giving 404 when trying to get there, maybe you have to change more files than the navigation

**Comment by tommygonzaleza** [comment]
If you go to the details view of a syllabus it has the following URL: `/admin/syllabus/your-first-job`, instead of admin it should be admissions

**Comment by aayalapalacin** [comment]
> If you go to the details view of a syllabus it has the following URL: `/admin/syllabus/your-first-job`, instead of admin it should be admissions

@tommygonzaleza fixed the url for the detailed view and also fixed the add new syllabus url as well (was also admin)

**Comment by tommygonzaleza** [comment]
- [ ] You have to move the URLs to the /views/admissions/routes.js

**Comment by aayalapalacin** [comment]
> PR: [breatheco-de/admin#336](https://github.com/breatheco-de/admin/pull/336)

@tommygonzaleza moved url's to  correct folder PR: [https://github.com/breatheco-de/admin/pull/336](url)

**Comment by tommygonzaleza** [comment]
![Uploading Screenshot 2023-02-08 at 11.46.14 AM.png…]()

**Comment by aayalapalacin** [comment]
> ![Screenshot 2023-02-08 at 11 46 14 AM](https://user-images.githubusercontent.com/56565994/217579316-10acfc79-7635-4396-b8cf-804412370637.png)

@tommygonzaleza on the syllabus.jsx the Admin routeSegment was to "/ " path. So, that is what I put the Admissions path to.

**Comment by tommygonzaleza** [comment]
You have to add how many hours it took you to solve this issue

**Comment by aayalapalacin** [comment]
Hours: 5 
@tommygonzaleza

**Comment by tommygonzaleza** [comment]
<hrs>5</hrs>
