### ISSUE TITLE
Reporte de todos los entregables de una cohort

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4141]
Vamos a utilizar el mismo componente que usamos para la [vista de asistencia](https://tinyurl.com/2kb9uwks) pero ahora para mostrar assignments. Sera una lista de todos los alumnos uno debajo de otro y cada alumno con punticos de sus entregables.

<img width="1104" alt="Screen Shot 2023-01-23 at 1 00 36 PM" src="https://user-images.githubusercontent.com/426452/214114903-46a39db1-1eb4-4a13-a6c1-b3ed9beaa07a.png">

- [ ] Cada caja sera un alumno y cada puntico es un assignment del alumno.
- [ ] Primero te traes todos los proyectos de ese syllabus y version, los pintas de color gris en todos los alumnos porque todavía no hay información sobre ese proyecto, luego cambiaran de color cuando el resto de la información llegue del API.
- [ ] Los status de un proyecto son: Delivered (yellow), Approved (green) , Rejected (red), Undelivered (red), si no tienes informacion sobre si un alumno hizo o no un proyecto lo dejas en gris.
- [ ] SI hago hover en el puntico me dice el nombre del assignment.
- [ ] Si hago click en el puntico me muestra una modal con la misma caja que hoy en día se usa para mostrar [detalles de un entregable](https://tinyurl.com/2h9ol492). Si el puntico era gris, entonces no vamos a tener mucha info y tendremos que decir `"No information available about this project for this student"`
- [ ] El resto de las funcionalidades de la caja de detalles del entregable se mantiene igual, puedo revisarlo, aprobarlo, ver los documentos que se entregaron, etc.
- [ ] Agregar un nuevo filtro por `task_type` (Tipo de assignment), el cual debe filtrar por defecto por proyecto, pero permitiendo quitar el filtro para poder ver todos los assignments.
- [ ] Actualmente el endpoint retorna la lista de assignments no ordenada por estudiante. Se debe crear un serializador que retorne a los estudiantes con una lista de sus tasks adentro del diccionario.
- [ ] El endpoint a utilizar es `GET /v1/assignments/academy/cohort/<int:cohort_id>/task`. Sin embargo, se debe modificar la vista utilizada [CohortTaskView](https://start.4geeksacademy.com/deploy/heroku-postgress) para que permita dos tipos de request:
- Pedir los task de un usuario en especifico: Si recibe `?student=id` entonces debe retornar solo una lista con los tasks del usuario como lo hace actualmente.
- Pedir una lista de los tasks de los usuarios de una cohort: Si no recibe el student en los query strings, entonces debe mostrar la lista de estudiantes con sus tasks con el serializador nuevo

**Comment by alesanchezr** [comment]
Falta documentacion 

- [ ] El componente tabs debe documentar se por si solo.
- [ ] Documentar componente de filtros
- [ ] Documentar componente de sort
- [ ] Documentar la vista en general

**Comment by tommygonzaleza** [comment]
Aqui puedes ver la [documentacion](https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=7298%3A39952&t=7MOeaLhyfhfzAjbR-1)

**Comment by tommygonzaleza** [comment]
![Screenshot 2023-05-16 at 3 58 36 PM](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/56565994/23caf795-db0f-477f-97d0-736efd5b5003)

**Comment by tommygonzaleza** [comment]
Muestra los proyectos mandatorios asi:
![Screenshot 2023-05-16 at 4 39 37 PM](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/56565994/c44c9646-79fa-4c92-a999-4cf479135f6b)

Basicamente debes encerrar los circulos en un div, a este div padre del circulo le agregas padding top y bottom, y border-bottom con el color del icono mandatorio

**Comment by tommygonzaleza** [comment]
- [ ] Cuando el task no tiene status no se debe mostrar el circulo
![Screenshot 2023-05-16 at 4 42 10 PM](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/56565994/4f214d03-063d-4283-9f57-930981e17f65)

- [ ] El contenido de los tabs esta desalineado
![Screenshot 2023-05-16 at 4 43 59 PM](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/56565994/ce04252f-77e1-4819-a136-5e774e00e4ad)

- [ ] Si se le quita un filtro (Siendo este el unico) y se le da apply, debe mostrarse sin filtros tal como cuando se le da a clear

**Comment by tommygonzaleza** [comment]
- [ ] Para el underline que marca los proyectos mandatorios, utiliza el color del icono de mandatorio
- [ ] Pon el height del boton (donde esta el icono de project view) mas alto

**Comment by tommygonzaleza** [comment]
- [ ] Disminuir el espacio entre los botonos del toggle y la lista 
- [ ] Poner el filtro por educational status como active por defecto
- [ ] Reemplazar el icono (Falta que yo te lo pase)
