### ISSUE TITLE
Dropdown for "choose program" on the /apply need to load from ./data/courses/*.yml

### ISSUE THREAD

**Issue by Jtoledo88** [4GeeksAcademy/About-4Geeks-Academy#4145]
### Bug description

Is important to remove the software engineer option in english and spanish please.

![IMG_8541](https://user-images.githubusercontent.com/32654829/214157052-461caaee-5c64-4744-b541-899808dfd96d.jpg)

### Steps to reproduce

Go to this url  https://4geeksacademy.com/es/aplica/?lang=es

**Comment by tommygonzaleza** [comment]
- [ ] Pareciera que no necesitas traerte ninguna info del yml de choose_program
- [ ] Eliminar los yml de [choose_program](https://github.com/4GeeksAcademy/website-v2/blob/master/src/data/components/choose_program/choose_program.us.yaml), no debe haber redundancia de datos, puedes consumir los datos de los ymls de [courses](https://github.com/4GeeksAcademy/website-v2/blob/master/src/data/course)
