### ISSUE TITLE
Modificar yml de ./data/page/news.yml

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4159]
- [x] Agregar mas noticias a la lista en el YML de [page en ingles](https://github.com/4GeeksAcademy/website-v2/blob/master/src/data/page/press.us.yml) y [en español](https://github.com/4GeeksAcademy/website-v2/blob/master/src/data/page/press.en.yml). 
- [ ] Las imagenes no deben estar pixeladas.
- [x] El cintillo de logos debe ser el mismo del home, con los mismos logos.

**Comment by URubino4Geeks** [comment]
Agregamos más noticias al listado, en inglés y español, y el cintillo de logos tiene los mismos del homepage.

Falta revisar por qué se pixelan las fotos
