### ISSUE TITLE
Use the <ProgramCard> instead of <ProgramList>

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4164]
This issue is waiting for #4189

- [ ] Let's start using the `<ProgramCard>` component instead of the `<ProgramList>`, the program list will be discarted.
- [ ] When it says `3/30 lessons` the number `3` is the total number of completed lessons and `30` is the total number of lessons in the syllabus (even if the module has not been opened yet). Same applies for the other types of content

**Comment by alesanchezr** [comment]
This issue is waiting for https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4189

**Comment by tommygonzaleza** [comment]
Here we specified the services and scenarios: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=6445%3A23157&t=t3n4G37d06cqSOIP-1

**Comment by tommygonzaleza** [comment]
Las cohorts que tienen `isHiddenOnPrework=true` si se van a mostrar, lo unico que no se muestra es el boton para ingresar y se muestra un mensaje en vez: https://github.com/breatheco-de/app/pull/571/files

**Comment by tommygonzaleza** [comment]
Revisa el review en el PR

**Comment by tommygonzaleza** [comment]
There is an error in Programs.jsx

![Screenshot 2023-02-14 at 7 29 52 PM](https://user-images.githubusercontent.com/56565994/218886426-3cff6f53-beda-4ee1-9719-3c942fbca60f.png)

**Comment by tommygonzaleza** [comment]
Aqui esta la documentacion completa de los posibles escenarios del ProgramCard y como se debe mostrar en cada uno de ellos, incluyendo los servicios a utilizar. (Servicios como `GET /v1/marketing/courses` y `GET /v1/payments/me/subscription` todavia requieren algunos cambios)
