### ISSUE TITLE
Component <LiveEvent> ⋅ Storybook Docs

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4165]
Add 4 stories to the component:

1. Live class soon: With 2 upcoming events and one upcoming live 
class in the next 5min
2. Live class but not soon: With 2 upcoming events 
and one upcoming live class in 5 hours.
3. No classes: No live classes but 2 upcoming events. If the LiveClass date is empty, It should show the nearest workshop in the same place the Live Class is usually shown.
4. Upcoming events not imminent: 2 upcoming events tomorrow.
5. Inminent upcoming events: 1 imminent upcoming event and 2 others tomorrow.

- [ ] Remember to modify the font size of the text below the event/live_class title
- [ ] The icon  for the events will be received as `eventtype.icon_url`

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-36788-201883021c6a1574ad71344ccc256bfd) 

---
**Source URL**:
[https://breatheco-de.github.io/app/?path=/story/components-liveevent--default&args=liveUrl:;liveClassHash:&globals=locale:en;locales.en:English;locales.es:Spanish](https://breatheco-de.github.io/app/?path=/story/components-liveevent--default&args=liveUrl:;liveClassHash:&globals=locale:en;locales.en:English;locales.es:Spanish)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x710</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by tommygonzaleza** [comment]
El efecto de radar debe ser del mismo color que el icono que tiene adentro. En el caso de no poder obtener el color del icono pues que sea azul como se esta haciendo en el default con los demas

![Screenshot 2023-02-06 at 11 35 18 AM](https://user-images.githubusercontent.com/56565994/217014817-7aac4d8c-
abeb-45ee-91ac-274cc2ed1c32.png)
