### ISSUE TITLE
Backlink SoloEduca

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4177]
soloeduca . com
soloeduca . com/como-aprender-a-programar-los-mejores-cursos-de-programacion-informatica/

**Comment by Jsolis4geeks** [comment]
Estuve revisando su sitio web y a menos que les ofrezcamos dinero no nos van a linkear, puesto que ni siquiera linkean sitios gratis, cuando mencionan ejemplo a Coursera linkean un articulo interno hablando de Coursera, pero no a Coursera en si porque es su competidor directo.

**Comment by alesanchezr** [comment]
Ellos no son un curso o competidor, solo mencionan cursos como el nuestro.

**Comment by alesanchezr** [comment]
Cancelado, el email ya no existe.
