### ISSUE TITLE
Requirements for <ProgramCard> Component

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4189]

**Comment by tommygonzaleza** [comment]
Here you have all possible scenarios: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=5068%3A16160&t=ljJ4OXppEYJ9RbIR-1

**Comment by tommygonzaleza** [comment]
Add all this to storybook

**Comment by tommygonzaleza** [comment]
The rocket should be on the right side of the card:
![Screenshot 2023-02-07 at 6 35 35 PM](https://user-images.githubusercontent.com/56565994/217382202-e223ab35-ca23-4b4b-9d35-97ef73418509.png)
