### ISSUE TITLE
When I create an article it is shown as public by default

### ISSUE THREAD

**Issue by Jsolis4geeks** [4GeeksAcademy/About-4Geeks-Academy#4193]
### Bug description

At the time of creating an article by default it is shown as public on the Admin, this should be shown as private.

Should not be allowed being published if visibility is private.to be

### Steps to reproduce

1 - Open Admin https://admin.4geeks.com/
2 - Create a new asset
3 - Review the status of the asset 
![image](https://user-images.githubusercontent.com/118853358/214872913-54bd6c6f-4c7f-4eb1-8329-8ff7e740e3c0.png)
 It should not be public

**Comment by tommygonzaleza** [comment]
- [ ] You have to modify the default value to `PRIVATE` [here](https://github.com/breatheco-de/apiv2/blob/0bdea3196a96751a0a3e44d7825346b32a307eba/breathecode/registry/models.py#L330)
- [ ] Add unit test or modify them
