### ISSUE TITLE
Redactar partnership request para backing con cobuild

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4196]
Authority: 40

Idea: podemos pedirles que hagan un blog post diciendo que hicieron un parnership con nosotros y van a contratar a unos de nuestros alumnos del curso de full stack.

- [ ] Debemos redactar el blog post.

**Comment by Jsolis4geeks** [comment]
Desde 4Geeks Academy queriamos contactarlos para explorar la posibilidad de una asociación entre nuestras empresas. Somos una escuela de programación que se dedica a proporcionar una capacitación de alta calidad a estudiantes de todo el mundo, y estamos seguros de que una colaboración con Cobuild podría ser una gran oportunidad para ambas empresas.

Queremos proponerles que nos ayuden a anunciar nuestra asociación en su blog y así mejorar nuestro perfil de backlinks en cuanto a SEO. Pensamos que esta asociación sería una gran oportunidad para nuestras empresas, y nos encantaría poder discutir más detalles sobre cómo podríamos trabajar juntos en el futuro.

Saludos.

**Comment by alesanchezr** [comment]
Elegir 2 blog posts para poner nuestros links alli a nuestros clusters.

**Comment by Jsolis4geeks** [comment]
Full Stack Developer: https://www.cobuildlab.com/blog/role-of-a-full-stack-developer
software development: https://cobuildlab.com/blog/software-development-for-new-products

**Comment by Jsolis4geeks** [comment]
Full Stack Developer: https://www.cobuildlab.com/blog/role-of-a-full-stack-developer  - image:https://tinyurl.com/2ocztkxb
software development: https://cobuildlab.com/blog/software-development-for-new-products  - image:https://tinyurl.com/2ojq2fo4

**Comment by URubino4Geeks** [comment]
Ya le escribimos para el backlink, esperando respuesta
