### ISSUE TITLE
Que paso con el enlace del ciec?

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4197]
ciec . edu . co/es/observatorio/pedagogia-e-innovacion/plataformas-educativas-que-ahora-son-gratuitas/

is a 404 and was linking to https://4geeksacademy.com/ we could contact secretariogeneral@ciec . edu . co to let them know about this and we might get the link back.

**Comment by alesanchezr** [comment]
Vamos a escribirle un correo a ellos para ver que paso.

**Comment by URubino4Geeks** [comment]
Se le escribió a secretariogeneral@ciec . edu . co el 31/03. Volvimos a escribirle el 14/04, aún sin respuesta.

**Comment by URubino4Geeks** [comment]
@alesanchezr Respondieron del CIEC:

"Buenos dias. La página se renovó y henos eliminado artículo. Gracias

Oscar A. Pérez Sayago"
