### ISSUE TITLE
Averiguar como usar el ahref content-explorer para conseguir potenciales fuentes de backlinks

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4201]
1. Revisa [esta herramienta](https://app.ahrefs.com/content-explorer).
2. Entregame un resumen de lo que podemos hacer para usarlo.

**Comment by Jsolis4geeks** [comment]
Ya estoy viendo videos al respecto, se pudiera usar esta herramienta para hacer la estrategia de Broken Backlink


![Image](https://user-images.githubusercontent.com/118853358/215901823-de732656-ba0a-4ea3-936c-1a5369aa8669.png)

**Comment by Jsolis4geeks** [comment]
Ya aprendi a usarla, es bastante simple, puedes leer sobre la herramienta en este articulo de 5 min 

https://app.ahrefs.com/academy/how-to-use-ahrefs/content-explorer/
