### ISSUE TITLE
Enviar campaña de PDF crash course para ver si nos agregan el enlace

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4202]
1. Tenemos este downloadable de [python crash course](https://4geeksacademy.com/us/downloadable/python-crash-course).
2. El keyword tiene dificultad de `3` y `900` visitas al mes.
3. Que le podemos hacer?

**Comment by Jsolis4geeks** [comment]
Cual es el descargable?

**Comment by Jsolis4geeks** [comment]
https://4geeksacademy.com/us/downloadable/python-crash-course

**Comment by Jsolis4geeks** [comment]
Lo he intentado descargar varias veces y no funciona 


![Image](https://user-images.githubusercontent.com/118853358/217710174-4267e7bb-3f18-47a7-b1ce-fc539d33c7fe.png)

**Comment by Jsolis4geeks** [comment]
Una vez optimzado se pudiera hacer un outreach a estas paginas para proponerles un enlace al descargable.

https://app.ahrefs.com/content-explorer/results/all/score_desc?topic=learn%20python&mode=news&filter-broken-pages=all&publish_type=all&published=all&first_seen=all&chart-range=last_6_months&page=1&results-per-page=50&report-languages=1%2CtotalTraffic%2Cdesc&report-websites=1%2CtotalTraffic%2Cdesc&report-authors=1%2CtotalTraffic%2Cdesc

**Comment by Jsolis4geeks** [comment]
Approved

**Comment by Jsolis4geeks** [comment]
Donwloaded 1000 pages to send emails

**Comment by Jsolis4geeks** [comment]
[learn-python_contentexplorer-overview_2023-02-15_11-55-46.csv](https://github.com/4GeeksAcademy/About-4Geeks-Academy/files/10745471/learn-python_contentexplorer-overview_2023-02-15_11-55-46.csv)

**Comment by Jsolis4geeks** [comment]
Voy a atacar ahora als primeras 250, si le añado muchas a Link Hunter puede que falle la app

**Comment by Jsolis4geeks** [comment]
Recomiendo tambien con el python crash revisar este tipo de campaña 

![Image](https://user-images.githubusercontent.com/118853358/219269524-e8140751-811e-4dfb-a54a-6083bb92bc27.png)

**Comment by Jsolis4geeks** [comment]
Template:




Hello, my name is Jonathan, and I take care of media relations at 4Geeks Academy.

I recently saw an article on your website mentioning our competitors, and I'm worried that 4Geeks Academy was not mentioned. Is there any reason for this?

Here is the website I read: https://www.packtpub.com/product/practical-css3-mastery-course-video/9781803232324

4Geeks Academy is a premier coding bootcamp with brick & mortar locations and an online presence in multiple countries. We offer lifetime career support, 10 dollars in scholarships, or a money-back guarantee. Our innovative platform, 4Geeks.com, provides interactive coding and instant feedback. We have graduated over 3000 students with an 84% job placement rate, named top 10 by Newsweek and top 35 by CourseReport and Switchup.

We want to be included in your article. How can I help?

**Comment by alesanchezr** [comment]
aprobado, enviar.

**Comment by Jsolis4geeks** [comment]
https://v2.linkhunter.com/websites/1666230?q=contacted

Enviado

**Comment by alesanchezr** [comment]
Faltan 3 tandas mas para enviar.

**Comment by Jsolis4geeks** [comment]
Batch #2: https://v2.linkhunter.com/campaigns/aejandro-sanchez-python-crash-downloadable-2

Batch #3: https://v2.linkhunter.com/campaigns/aejandro-sanchez-python-crash-downloadable-3

Batch #4: https://v2.linkhunter.com/campaigns/aejandro-sanchez-python-crash-downloadable-4
