### ISSUE TITLE
Link building strategy for "aprender a programar" cluster.

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4203]
https://4geeksacademy.com/es/aprender-a-programar/aprender-a-programar-desde-cero

**Comment by Jsolis4geeks** [comment]
Waiting for issue #4273

**Comment by alesanchezr** [comment]
Falta modificar el template para agregar información sobre el referral program, hay que decir que el link debe ir a aprender a programar con el url conteniendo el referral id por ejemplo: 

```
https://4geeksacademy.com/es/aprender-a-programar/aprender-a-programar-desde-cero?ref=vbsy6
```

**Comment by Jsolis4geeks** [comment]
Revisar esrto que hay unos enlaces a aprender a programar.

https://app.ahrefs.com/v2-site-explorer/best-by-links/subdomains?anchorRules=&domainNameRules=&externalLimit=50&externalOffset=0&externalSort=refdomains&externalSortDirection=desc&followType=all&highlightChanges=30d&history=all&internalLimit=50&internalOffset=0&internalSort=linksToTarget&internalSortDirection=desc&refPageTitleRules=&refPageUrlRules=&selectedTab=external&surroundingRules=&target=https%3A%2F%2Fopen-bootcamp.com%2F&targetHttpCode=404&targetPageTitleRules=&targetUrlRules=

**Comment by alesanchezr** [comment]
Esperar a tener full stack developer terminado primero.

**Comment by alesanchezr** [comment]
seguimos esperando por fulls takc primero
