### ISSUE TITLE
Revisar estos backlinks para Full Stack Developer de coursera

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4204]
Vamos a ver si hay algunos que podamos replicar

https://app.ahrefs.com/v2-site-explorer/backlinks/exact?dr=10-&followType=dofollow&grouping=all&highlightChanges=none&history=all&limit=50&offset=0&sort=linkeddomains&sortDirection=desc&target=www.coursera.org%2Farticles%2Ffull-stack-developer)

**Comment by Jsolis4geeks** [comment]
Los revise y los puse en esta campaña de Link Hunter, esta a la espera del template.

https://v2.linkhunter.com/campaigns/aejandro-sanchez-coursera-full-stack-developer

**Comment by Jsolis4geeks** [comment]
Usar el template: Reclamo de Backlinks

**Comment by Jsolis4geeks** [comment]
Ready, you can check the task here: https://v2.linkhunter.com/websites/1664881?c=5278&amp;q=contacted
