### ISSUE TITLE
Refund policy cannot be published because of warning

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4205]
You can test it on this article: 4geeks-academy-refund-policy

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-36811-6540919e3a27f3e6d8db5b7db0d13af6) 

---
**Source URL**:
[https://admin.4geeks.com/media/asset/4geeks-academy-refund-policy](https://admin.4geeks.com/media/asset/4geeks-academy-refund-policy)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x710</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by tommygonzaleza** [comment]
Solved
