### ISSUE TITLE
Translate Code of Conduct and Ethics to spanish

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4206]
Here is the article: https://github.com/breatheco-de/content/blob/master/src/content/misc/code-of-conduct-and-ethics.md

**Comment by Lorenagubaira** [comment]
PR: https://github.com/breatheco-de/content/pull/1232

**Comment by tommygonzaleza** [comment]
Dale formato con titulos y separando los parrafos

**Comment by tommygonzaleza** [comment]
Cual es el PR con tus cambios en el caso de que este listo?
