### ISSUE TITLE
Translate Terms and Condition to spanish

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4207]
Here is the link: https://github.com/breatheco-de/content/blob/master/src/content/misc/terms-and-conditions.md

**Comment by tommygonzaleza** [comment]
We'll keep them only in english

**Comment by Lorenagubaira** [comment]
PR: https://github.com/breatheco-de/content/pull/1229

**Comment by alesanchezr** [comment]
tienen un spanish y un texto cortado, revisa el code review.

**Comment by Lorenagubaira** [comment]
corregido

**Comment by tommygonzaleza** [comment]
Dale formato con titulos y parrafos separados
