### ISSUE TITLE
Redo learn in public project with Jekyll

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4237]
- [ ] Use [Jekyll](https://jekyllrb.com/) to create an app that allows the students to add a yml with their profile information into a folder, and the app should get all those YMLs and convert them into pages in the app.
- [ ] We are doing something similar to [what we currently have](https://github.com/4GeeksAcademy/About-4Geeks-Academy/) but with fewer functionalities, we don't want to generate an HTML. We only want to show a list of students and to be able to open one of the students and see their profile (Which information should be gotten from the YMLs)

Expected time: 16 - 24

**Comment by aayalapalacin** [comment]
nvm install 12 && nvm use 12 && npm install && npm run start

**Comment by aayalapalacin** [comment]
<img width="359" alt="image" src="https://user-images.githubusercontent.com/95265085/220692227-d3066d0e-3aa0-4f56-b5a2-ef1178100729.png">

**Comment by aayalapalacin** [comment]
@tommygonzaleza with [https://github.com/aayalapalacin/About-4Geeks-Academy/tree/version-2](url) I have the completed new version of learn in public project.

**Comment by aayalapalacin** [comment]
@tommygonzaleza finished learn in public project with vanilla js, ready for review: [https://github.com/aayalapalacin/learn-in-public-vanillajs](url)

**Comment by tommygonzaleza** [comment]
- [ ] Use node's versions 18+
- [ ] The profile picture is not being showed
- [ ] The background color should take the entire screen

**Comment by tommygonzaleza** [comment]
<hrs>28.125</hrs>
