### ISSUE TITLE
Show the warning in the asset view if the text is modified

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4238]
- [ ] If you modify the asset it should tell you that it is out of sync and you should push your changes. We already have an alert for similar purposes, we should reuse the alert but for this new case

Expected time: 2 - 4

**Comment by etolopez** [comment]
pr: https://github.com/breatheco-de/admin/pull/341
h: 2

**Comment by tommygonzaleza** [comment]
- [ ] You should also use the warning shown in the AssetMarkdown, reuse it here.
- [ ] The warning should only be shown if the markdown has been modified, currently, there is no condition to prevent showing it
- [ ] Add another warning in the box where the user pulls from GitHub

**Comment by etolopez** [comment]
pr: https://github.com/breatheco-de/admin/pull/341

h: <hrs>2 </hrs>

**Comment by tommygonzaleza** [comment]
- [ ] The markdown has not been modified and the modal is still being shown, add the validation

**Comment by tommygonzaleza** [comment]
- [ ] The warning should be removed once the user pulls from GitHub
- [ ] The warning shouldn't be shown when the user pull from GitHub without changing anything

**Comment by tommygonzaleza** [comment]
There is a conflict in the PR

**Comment by tommygonzaleza** [comment]
<hrs>5</hrs>

**Comment by tommygonzaleza** [comment]
Fix the PR

![Image](https://user-images.githubusercontent.com/56565994/225133162-987ba9e7-a08f-4cde-b6ec-9ddd7d12a684.png)

**Comment by etolopez** [comment]
Listo

**Comment by tommygonzaleza** [comment]
<hrs>5</hrs>
