### ISSUE TITLE
Modify endpoint `GET /v1/payments/me/subscription`

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4253]
- [ ] The [endpoint](https://github.com/breatheco-de/apiv2/blob/ac7346af6289ad15f0b0d90bf72b9314c3c1abb0/breathecode/payments/urls.py#L27) should retrieve both `Subscriptions` and `PlanFinancing` of the user.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/755

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/709
