### ISSUE TITLE
Unit test the LiveClass object generation (django commands)

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4254]
[Build Live classes](https://github.com/breatheco-de/apiv2/blob/main/breathecode/events/management/commands/build_live_classes.py)

[Close live classes](https://github.com/breatheco-de/apiv2/blob/main/breathecode/events/management/commands/close_live_classes.py)

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/739

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/741
