### ISSUE TITLE
Se estan generando clases en el pasado

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4265]
Al momento de [construir los live classes](https://github.com/breatheco-de/apiv2/blob/main/breathecode/events/management/commands/build_live_classes.py) se estan generando todas aquellas `Live Classes` de cohorts que no han terminado.

Los comando estan bien, [pero pareciera que el task](https://github.com/breatheco-de/apiv2/blob/main/breathecode/events/tasks.py#L98) necesita correcciones en el calculo de starting_at y ending_at.

```py
    starting_at = DatetimeInteger.to_datetime(timeslot.timezone, timeslot.starting_at)
    ending_at = DatetimeInteger.to_datetime(timeslot.timezone, timeslot.ending_at)
```

El starting_at: deberia tomar en cuenta la fecha de inicio de la cohort, si el timeslot es weekly entonces lo unico que nos importa de ese timelust es: `Su dia de la semana` y `la hora de inicio y fin`. La fecha como tal no tiene relevancia.

Por ejemplo: Si el el timeslot.starting_at dice `lunes 30 de agosto` pero la cohort empieza el `lunes 23 de septiembre` entonces ignoramos todas las fechas hasta el `22 de septiembre`. El starting_at seria desde el `lunes` 23 de septiembre.

El `timeslot.ending_at` solamente se usa para calcular el timedelta que tiene conrespecto al timeslot.starting_at, eso nos dice cuanto deberia durar una clase.

- [ ] Aprovechar para hacer las pruebas unitarias de este command y el task tambien.
- [ ] Evitar generar clases en el pasado.

<img width="803" alt="Screen Shot 2023-02-01 at 12 17 52 PM" src="https://user-images.githubusercontent.com/426452/216115364-cd05f765-cf24-485d-9bcb-bc64b803a9c5.png">

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/739
