### ISSUE TITLE
Boton de intrucciones del profesor no hace nada

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4268]
Deberia mostrarme las instrucciones del dia.
Estoy intentando entrar a la cohort MDC-21
En realidad no hace nada, no muestra nada ni se mueve ni nada.

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-36896-4cdc6959ff870ffc67fb04d531e85163) 

---
**Source URL**:
[https://dev.4geeks.com/syllabus/mdc-21/read/intro-to-prework](https://dev.4geeks.com/syllabus/mdc-21/read/intro-to-prework)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x710</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by tommygonzaleza** [comment]
It's still not showing even the message when clicking on the instructions button
