### ISSUE TITLE
Incluir schema tags en paginas del website

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4272]
- [ ] Incluir schema tag a todos los cursos (ingles y español)
- [ ] Incluir schema organization tag al home en ingles para `/us/index` y español para `/es/inicio`
- [ ] Incluir el schema article tag en todos los posts.
- [ ] Incluir schema website tag en todas paginas que no sean cursos ni blog posts.

Para entender los schema tags, revisar comentarios en este issue [#4171](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4171)

**Comment by tommygonzaleza** [comment]
- [ ] Dejar schema BlogPosting y quitar Article
- [ ] Arreglar problema relacionado al description en BlogPosting
- [ ] Cambiar el schema de Course, el valor name debe ser el seo_title
- [ ] Remover BlogPosting de campus y agregar School en vez
