### ISSUE TITLE
Campaña de Broken Link Building coursera

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4273]
- [ ] No envies la campaña sin que yo la revise just antes.
- [ ] Este podria ser un template:

```txt
Subject: Broken link on your winter activities article

Hi Laura,

Wanted to let you know there’s a broken link in your article 10 Winter Outdoor Activities Your Family Will Love (https://www.familyfun.net/2012/winter-outdoor-activities).

You’re linking to U.S. Sledding (https://sledding.us) in point #3… and that no longer exists.

Never fear! I run a website that has an even more comprehensive guide to sledding all around the U.S. (https://www.americasledding.com/). You could swap it in for the broken link.

Let me know if you’re interested and I can send it over,

Joe Michaels

Founder, American Sledding

P.S. I’d also love to talk about sharing your site in our weekly newsletter. It’s perfect for our 30,000+ subscribers!
```

**Comment by Jsolis4geeks** [comment]
Estaba intentando lo de la campaña de broken LinkBuilding y dice que para eso se necesita un plan mayor de ahrefs.



![Image](https://user-images.githubusercontent.com/118853358/216876417-1099ecbe-766b-423c-9087-fcb1e491a26b.png)

**Comment by Jsolis4geeks** [comment]
En su lugar hice una seleccion de URL con blogs donde recomiendan Full Stack Developer Course para ver si se consigue algun backlink

**Comment by Jsolis4geeks** [comment]
Revisar este articulo

https://alturainteractive.com.mx/como-obtener-resultados-mediante-la-adquisicion-de-links-rotos-en-tu-estrategia-de-link-building/

**Comment by Jsolis4geeks** [comment]
En cuanto a esta estrategia estuve usando el site explorer para identificar de una forma distinta los 404, desde los mismos competidores, por ejemplo analizar Coursera desde el punto de vista de Backlinks y filtrarlo por los 404 y de ahi buscar las webs que los estan enlazando y hacer outreach para que nos pongan a nosotros en lugar de a ellos, esto se puede hacer con todos los competidores.

Ejemplo: https://app.ahrefs.com/v2-site-explorer/best-by-links/subdomains?externalLimit=50&externalOffset=0&externalSort=refdomains&externalSortDirection=desc&followType=all&highlightChanges=30d&history=all&internalLimit=50&internalOffset=0&internalSort=linksToTarget&internalSortDirection=desc&selectedTab=external&target=coursera.org%2F&targetHttpCode=404

Si esta estrategia te parece bien la empiezo a implementar

**Comment by Jsolis4geeks** [comment]
https://ahrefs.com/blog/broken-link-building/

**Comment by Jsolis4geeks** [comment]
Hello, my name is Jonathan, and I take care of media relations at 4Geeks Academy.

I recently was searching around your website and noticed a link to one page of Coursera that is Broken, this is an SEO error and could decrease your performance in Google. Here I propose to you a website that could be a perfect replacement for your link to Coursera: https://4geeksacademy.com/us/coding-bootcamps/part-time-full-stack-developer

Here is the website I read: [Website's URL]

4Geeks Academy is a premier coding bootcamp with brick & mortar locations and an online presence in multiple countries. We offer lifetime career support, 10 dollars in scholarships, or a money-back guarantee. Our innovative platform, 4Geeks.com, provides interactive coding and instant feedback. We have graduated over 3000 students with an 84% job placement rate, named top 10 by Newsweek and top 35 by CourseReport and Switchup.

We want to be included in your article. How can I help?

**Comment by Jsolis4geeks** [comment]
Ready, you can find it in this task at Link Hunter: https://v2.linkhunter.com/websites/1666023?c=5284&amp;q=contacted
