### ISSUE TITLE
Componente `ShowPrices`

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4274]
1. Debe poder mostrar un plan financiado y las opciones de financiacion.
2. Debe poder mostrar una subscripcion con opciones anual, y mensual
3. Free trieal si esta disponble

Ya tienes el diseño no te pongas a inventar.
Asegurate que funcione en todos los cases: En landing de coding introduction afuera, en el compoente `<OfferModal>` y en la pagina de pago.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=6807%3A80681&t=2odh6vIj6KAVpIh0-1

**Comment by alesanchezr** [comment]
Falta el caso cuando quieres comprar un curso, deberia tener subscripcion y free trial

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=6908%3A109348&t=wf0VHWfXlpg6JOsb-1

**Comment by tommygonzaleza** [comment]
Waiting for [issue](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3970) to add the services that will be consumed by front end
