### ISSUE TITLE
Lessons only in English - Data Science Prework (Spanish Version)

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/About-4Geeks-Academy#4317]
### Bug description

In the Data Science Prework, the following lessons are only in English, even when you choose Spanish Version 

Introduction to numpy
Introduction to Pandas
Intro to Pyplot

![image](https://user-images.githubusercontent.com/48845580/216996576-a98ee5ff-15ba-497c-9c37-2739a871791a.png)

### Steps to reproduce

Go to:

https://4geeks.com/es/syllabus/machine-learning-prework/ or https://4geeks.com/es/syllabus/spain-ds-ml-prework

Find the lessons and choose Spanish Version

### Expected behavior

Have the lesson in Spanish as the rest of the information

**Comment by tommygonzaleza** [comment]
Reported in the admin, translation will be added next week
