### ISSUE TITLE
Project Real Estate Data Cleanup - Data Science Prework

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/About-4Geeks-Academy#4318]
### Bug description

![image](https://user-images.githubusercontent.com/48845580/216997082-12680e13-a705-42bb-994e-6374e57fe3c0.png)

The Project doesn't load in Spanish Version 

### Steps to reproduce

Go to https://4geeks.com/es/syllabus/machine-learning-prework/ or https://4geeks.com/es/syllabus/spain-ds-ml-prework

Go to the last project and choose Spanish Version 

### Expected behavior

The Project information should be in Spanish

**Comment by tommygonzaleza** [comment]
Translation will be added for next week
