### ISSUE TITLE
Implement SEO Friendly infinit scroll pagination practices

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4327]
Following this article from google, lets implement paginator component that can be reused with any rendering component:
https://developers.google.com/search/blog/2014/02/infinite-scroll-search-friendly

```
<PaginatedView
     renderComponent={(props) => <CourseCard {...props} />}
     queryFunction={() => fetch('some_url', options)}
>
```

For example, for the following URL: `https://4geeks.com/lessons`, we should have the following:

- [ ] First page is `https://4geeks.com/lessons` with a `<link rel="next" ahref="/lessons?page=2" />` between the `<head>` tags (not the body).
- [ ] Second page is: `/lessons?page=2` with a `<link rel="prev" ahref="/lessons" />` and `<link rel="next" ahref="/lessons?page=3" />`
- [ ] Last page is: `/lessons?page=3` with a `<link rel="prev" ahref="/lessons?page=2" />`

About the load more anchor:

- [ ] The anchor to "load more" should always exist if there is any more content to load and if needs to be an anchor `<a>` that points to the next "page".
- [ ] when the scroll reaches the bottom the can be replaced with javascript with a "loading" animation instead while the new content gets loaded.
- [ ] If a website without javascript loads the page, it should be able to click on the "load more" anchor to load the next page.

Where to apply this changes?

It occurs to me that you build a **Higher Order Component** to implement this in a more general way that can later be used anywhere?

**Comment by tommygonzaleza** [comment]
- [ ] On the fifth page it's showing only two lessons.
<img width="1397" alt="Screenshot 2023-02-21 at 2 57 39 PM" src="https://user-images.githubusercontent.com/56565994/220435016-50f993e8-94fe-44a9-ab50-1dd84b0e9a65.png">

- [ ] When you get to the fifth page, it's showing too many pages to go previous or next.
<img width="546" alt="Screenshot 2023-02-21 at 2 59 45 PM" src="https://user-images.githubusercontent.com/56565994/220435186-6ad5d18d-c1da-42d0-8a8f-06abaa2e38ab.png">

**Comment by tommygonzaleza** [comment]
- [ ] When you try to open a project, it goes to 404 page because it's missing the difficulty in the path
- [ ] Add a redirect that if it sends you to a project without the difficulty, it redirects you to the correct one

**Comment by tommygonzaleza** [comment]
Si la pagina no tiene javascript, al final de la pagina 1 va a decir "load more" y te va a a llevar a la pagina 2, si estas sen la pagina 2 sera a pagina 3 y asi sucesivamente.

Si la pagina si tiene javascript, javascript va a escuchar el click en el boton de load more y hacer un prevent default para que cuando le hagan click deje de llevar a la pagina 2, en su lugar va a cargar el contenido del json de la pagina dos en el HTML de la misma pagina 1 al final.

Si lo vuelven a aprender, como ya se trajo la pagina 2, ahora se traera la pagina 3.

Y si haces scroll y llegas al final, tambien se traera el contenido del json de la proxima pagina

**Comment by tommygonzaleza** [comment]
Cuando javascript esta deshabilitado el Load more solo te lleva a la segunda pagina, si le das a load more de nuevo no te lleva a la tercera.

Con Javascript habilitado no se muestra el boton de load more sino que se esta mostrando los numeros de las paginas.

**Comment by tommygonzaleza** [comment]
- [ ] No esta llevando a las siguientes paginas al darle click a load more
