### ISSUE TITLE
El video de los lessons no debe estar por encima de las instrucciones del profesor

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4335]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-36938-be4989b47cf732a4e41c301ffc994ee6) 

---
**Source URL**:
[https://4geeks.com/syllabus/mdc-21/read/what-is-the-internet](https://4geeks.com/syllabus/mdc-21/read/what-is-the-internet)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1446x710</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by tommygonzaleza** [comment]
Me esta dando un error `Application error: a client-side exception has occurred (see the browser console for more information).`
