### ISSUE TITLE
Identificar sitios para PBN

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4347]
Reconociendo que Github ha sido bueno como un backlink generator, revisemos otros sites que podrian funcionar.
- [ ] Para cada sitio proponer el "porque" y "como" serán esos backlinks.

**Github**
Para publicar tutorials, en los README.md colocaremos referencias a:
- [ ] Incluir link original al tutorial en 4geeks.com
- [ ] Incluir link al autor en 4geeks.com
- [ ] Incluir link a tutorial similares de la misma tecnologia.

**Youtube.com**
Al publicar un video tutorial:
- [ ] Incluir link original al tutorial en 4geeks.com
- [ ] Incluir link a tutorial similares de la misma tecnologia.

https://gist.github.com/sabrysuleiman/4d546ddaaf0c0bec215f0fad96f9223c

**Comment by Jsolis4geeks** [comment]
After a deep Research found this sites:

Reddit.com
Wikipedia
Github.com
Vimeo.com
Scoop.it
Eleconomista.es
Medium.com
Slideshare.net
Visual.ly
Wikidot.com
foro.serpadres.es
Cruzroja.es
Gust.com
Instructables.com
Notegraphy.com
Puromarketing.com
Dailymotion.com
Reverbnation.com
Generaccion.com
Livejournal.com
Instapaper.com
CSSlight.com
Storify.com
Intensedebate.com
Giphy.com
Hogarmania.com
espanol.answers.yahoo.com
