### ISSUE TITLE
Añadir video de la cámara de comercio de Madrid a la página web

### ISSUE THREAD

**Issue by mmiranda4geeks** [4GeeksAcademy/About-4Geeks-Academy#4348]
Tenemos un vídeo que se grabó a partir de una entrevista que se le hizo a Victor en la cámara de comercio, donde se habla de 4geeks, beneficios, por qué elegirnos. Tiene un buen potencial de ventas para estar en la web.

Link del vídeo:
https://drive.google.com/drive/folders/1xerKzmxYbDZaUcdtRsISkLhq7qNGHE7Z

El vídeo falta editarlo (cortar los logos de la cámara), pero queremos saber si es posible dejarlo en la web sobretodo en la sección de "why 4geeks".

**Comment by alesanchezr** [comment]
Si se puede, pero es algun partnership o algo? Porque si no pareciera que lo mejor es ponerlo en la seccion de prensa per destacado.

**Comment by mmiranda4geeks** [comment]
> Si se puede, pero es algun partnership o algo? Porque si no pareciera que lo mejor es ponerlo en la seccion de prensa per destacado.

En realidad es un vídeo "entrevista" donde se habla de 4geeks, beneficios, etc... o sea realmente explica muy bien 4geeks como tal. En prensa no sé qué tanto se vería bien, podríamos probar.
