### ISSUE TITLE
Agregar componentes al slice machine

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4352]
- [ ] Todos los compoentes empiezan con Mkt
- [ ] `MktTwoColumnSideImage`: se le puede modificar background, bordes, title, subtitle, description, button_url, button_label, image_url, image_position: right,left.
- [ ] `MktOneColumn`: sele puede modificar title, subtitle, description, button_url, button_label, image_url

- [ ] `MkOneColumntKPI`: here da el one column todas sus propiedades menos `image_url`, en lugar del `image_url` tiene una lista de KPIs.

- [ ] `MktTestimonials`: lista de testimoniales.

- [ ] `MktJumbotron`: Caja con Titulo (optional), texto (optional) y botón (optional).

**Comment by alesanchezr** [comment]
Falta documentar esto.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=6805%3A29535&t=9m1aD9SttL4smBsU-1

**Comment by tommygonzaleza** [comment]
Esta documentado en el link de figma

**Comment by tommygonzaleza** [comment]
- [ ] Poner border-radious en 0 para que sean rectos
