### ISSUE TITLE
Unit tests cases for Payments Module

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4353]
- [ ] Cualquier usuario cuyo feature flag `api.release.enable_consume_mentorships` sea falso, podrá acceder a los servicios de mentoría de forma ilimitada sin importar el plan que tenga.
- [ ] Si un usuario cuyo  feature flag `api.release.enable_consume_mentorships` sea verdadero, podra acceder a mentorias  si tiene al menos un credito. 
- [ ] Si un usuario cuyo  feature flag `api.release.enable_consume_mentorships` sea verdadero, no podra acceder a una mentoria si el consumibles asociado a la mentoria no tiene creditos.
- [ ] Cualquier usuario cuyo feature flag `api.release.enable_consume_live_events` sea falso, podrá obtener el URL de los servicios de eventos (Workshops) de forma ilimitada.
- [ ] Cualquier usuario cuyo feature flag `api.release.enable_consume_live_class` sea falso, podrá obtener el URL de la clase de forma ilimitada.
- [ ] Cuando un usuario paga un plan, se deben crear todos los consumibles relacionados a los service items asociados al plan.
- [ ] Cuando la fecha es igual a la fecha de `subscription.valid_until`, la subscripcion debe cambiar de status a `DEPRECATED`
- [ ] Cuando la fecha es igual a la fecha de `subscription.next_payment_at`, se debe intentar hacer el pago. De ser exitoso el pago, se debe renovar `subscription.valid_until`, `subscription.next_payment_at` y `subscription.status`.
- [ ] Cuando la fecha es igual a la fecha de `subscription.next_payment_at`, se debe intentar hacer el pago. De fallar el pago, se debe actualizar el `subscription.status` a `PAYMENT_ISSUE`.
- [ ] Cuando una subscripcion es cancelada, no se deben hacer mas pagos.
- [ ] Cuando la fecha es igual a la fecha de `PlanFinancing.valid_until`, el `PlanFinancing` debe cambiar de status a `DEPRECATED`
- [ ] Cuando la fecha es igual a la fecha de `PlanFinancing.next_payment_at`, se debe intentar hacer el pago. De ser exitoso el pago, se debe renovar `PlanFinancing.valid_until`, `PlanFinancing.next_payment_at` y `PlanFinancing.status`.
- [ ] Cuando la fecha es igual a la fecha de `PlanFinancing.next_payment_at`, se debe intentar hacer el pago. De fallar el pago, se debe actualizar el `PlanFinancing.status` a `PAYMENT_ISSUE`.
- [ ] Cuando se hayan hecho la totalidad de los pagos agendados por el `PlanFinancing`, ya no se debe cobrar mas. (Por ejemplo, si un PlanFinancing requiere de tres pagos de 50$, la idea es que una vez que se hayan hecho los tres pagos entonces ya no se deba pagar mas).
- [ ] El endpoint `PUT /v1/payments/checking` debe retornar financing option en el array si el plan tiene un FinancingOption asociado

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/820

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/872/files

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/blob/main/breathecode/payments/management/commands/make_charges.py
