### ISSUE TITLE
4Geeks Academy website: Connect the `contact us` form with the API

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#436]
Hours: <hrs>3</hrs>
Here is the repo: https://github.com/4GeeksAcademy/website-v2

Here is an example on how the apply was done: https://github.com/4GeeksAcademy/website-v2/blob/master/src/templates/apply.js#L35

**Comment by alesanchezr** [comment]
aprobado.

**Comment by alesanchezr** [comment]
se le agrego una hora mas porque hizo el textarea smart.

**Comment by Jtoledo88** [comment]
Horas pagadas en junio
