### ISSUE TITLE
Confirmar el pull cuando se van a perder cambios

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4364]
Si el Asset.readme_updated_at > al Asset. last_synch_at
debe confirmarse antes de hacer el pull de github.

Usar el [componente ConfirmAlert](https://github.com/breatheco-de/admin/blob/master/src/app/components/ConfirmAlert.jsx).

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-36978-d86a670960663e8210a55c5fe6401b9e) 

---
**Source URL**:
[https://admin.4geeks.com/media/asset/4geeks-academy-refund-policy](https://admin.4geeks.com/media/asset/4geeks-academy-refund-policy)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1446x710</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by tommygonzaleza** [comment]
- [ ] The markdown has not been modified and the modal is still being shown, add the validation
- [ ] It's not allowing to pull including the meta info (Also override meta info option)
