### ISSUE TITLE
Day 25- Practice: Python Loops and Lists (gitpod: python-lists-loops-programming-exercises)

### ISSUE THREAD

**Issue by Tozzigh** [4GeeksAcademy/About-4Geeks-Academy#437]
**Day 25 - Practice: Python Loops and Lists - 'Techno_beat' exercise 16**

 There is an error in the test, the print statment is:  
'Drop the base !!!Break the base!!! Drop the base !!!Break the base!!! Drop the base !!!Break the base!!!'

should be:  'Drop the base Drop the base Drop the base !!!Break the base!!! '

![err](https://user-images.githubusercontent.com/61799388/85223340-bb8f9d00-b3c2-11ea-9272-e3ce4db5f710.PNG)

**Comment by alesanchezr** [comment]
U r right. 

I think i fixed it! Thank you!

**Comment by Tozzigh** [comment]
> 
> 
> U r right.
> 
> I think i fixed it! Thank you!

Rigth now it works fine!
