### ISSUE TITLE
Crear iconos para EventTypes

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4373]
Para los event types de tecnologias deben ser estandar e incluyendo el icono de la tecnologia, para tipos diferentes usar colores diferentes

Crear icono para los siguientes EventTypes:

- GeekTalk (Presentacion de proyectos finales)
- GeekForce (Ayuda con el perfil de carrera)
- Data science
- Javascript
- Python
- HTML/CSS
- Otras tecnologias Full Stack
- Otra Tecnologia

**Comment by alesanchezr** [comment]
- [ ] usar el navpill para poner el type del evento junto a la hora
- [ ] Entregar un icono para cada tipo de evento
- [ ] Reducir texto de time para que sea pequeño

**Comment by alesanchezr** [comment]
Cerrandola porque migro a #4419
