### ISSUE TITLE
No ofrecer la opción de entrega de código en el prework

### ISSUE THREAD

**Issue by marcogonzalo** [4GeeksAcademy/About-4Geeks-Academy#439]
Cuando la gente que hace el prework ve la opción de "entregar" en los ejercicios, se bloquea y se angustia porque no entiede cómo entregar el proyecto (porque no se ha visto Git aún). 

Sería ideal desactivar la entrega para el prework y también corregir cualquier referencia o sugerencia de entregar código para cualquier contenido de esa fase.

**Comment by alesanchezr** [comment]
@Andrearcastillo sobre este tema, se me ocurre que pongamos un tutorial de como entregar un ejercicio.

Sabes de que trata esta funcionalidad? Tenemos que sentarnos a revisarla en la proxima reunion.

**Comment by alesanchezr** [comment]
SI se va a pedir la entrega, se hizo un tutorial en como hacerlo.
