### ISSUE TITLE
Incluir landing de tecnologia en el sitemap de tecnologias

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4395]
Sitemap: https://4geeks.com/technologies-sitemap.xml

Debemos incluir las landings nuevas que no son de lesson, exercise or project. Por ejemplo:
```
https://4geeks.com/technology/javascript
https://4geeks.com/technology/python
.
.
https://4geeks.com/technology/<slug>
```

**Comment by tommygonzaleza** [comment]
Para poder chequear que estan en el sitemap, se debe hacer redeploy de dev y chequear el sitemap, podemos hacerlo en la reunion ya que no tengo acceso a vercel

**Comment by tommygonzaleza** [comment]
- [ ] Agregar validaciones para que no se agreguen slugs que tengan espacios
- [ ] Agregar solo los landing de las tecnologias madres en el sitemap.
