### ISSUE TITLE
Traducciones al español estan mal (revision general)

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4397]
Pareciera que los excerps estan guardandose en ingles:

- [ ] Las lessons no tengo idea de porque están en ingles, ellas tienen su propio excerpt.
- [ ] Los proyectos y ejercicios tenemos que actualizarles el learn.json para agregar las descripciones y titulos con multilang, [aqui esta un ejemplo del project de instagram post con su learn.con ya traducido](https://github.com/breatheco-de/exercise-instagram-post/blob/master/learn.json#L14).

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-37005-8e4f9f631064b23a3bb68d3e93d87f4a) 

---
**Source URL**:
[https://app-git-fork-tommygonzaleza-main-geeksacademy.vercel.app/es/interactive-exercises/technology/python](https://app-git-fork-tommygonzaleza-main-geeksacademy.vercel.app/es/interactive-exercises/technology/python)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x710</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by tommygonzaleza** [comment]
Falta hacer redeploy de la rama master desde vercel pero no tengo acceso

**Comment by tommygonzaleza** [comment]
Se revisaron todos los assets, articulos, proyectos, ejercicios y lecturas

**Comment by tommygonzaleza** [comment]
Ejercicios listos, learn.json ya fue modificado, ahora faltan los proyectos.

**Comment by tommygonzaleza** [comment]
Incluir validacion en el comando audit de LearnPack
