### ISSUE TITLE
Broken link building code academy full stack

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4411]

**Comment by Jsolis4geeks** [comment]
Igual que soy henry este sitio no tiene broken links.

https://app.ahrefs.com/v2-site-explorer/best-by-links/subdomains?anchorRules=&domainNameRules=&externalLimit=50&externalOffset=0&externalSort=refdomains&externalSortDirection=desc&followType=all&highlightChanges=30d&history=all&internalLimit=50&internalOffset=0&internalSort=linksToTarget&internalSortDirection=desc&refPageTitleRules=&refPageUrlRules=&selectedTab=external&surroundingRules=&target=https%3A%2F%2Fwww.codecademy.com%2F&targetHttpCode=404&targetPageTitleRules=&targetUrlRules=
