### ISSUE TITLE
Documentar escenarios del componente `<ProgramCard />`

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4414]
Agregar posibles escenarios al componente.

- [ ] Muestra el flujo de los posibles escenarios

Diseño: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=6445%3A23157&t=t3n4G37d06cqSOIP-1

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=6904%3A39013&t=wf0VHWfXlpg6JOsb-1
