### ISSUE TITLE
Agregar componente `PublicCourseCard` a storybook

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4415]
![Image](https://user-images.githubusercontent.com/426452/219444801-e71ee35b-b829-4353-aa04-b4b9a1f1abbb.png)

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=6909%3A109748&t=wf0VHWfXlpg6JOsb-1

**Comment by alesanchezr** [comment]
falta documentarle las opciones

**Comment by tommygonzaleza** [comment]
Agrega el componente con los diferentes escenarios planteados en el figma

**Comment by tommygonzaleza** [comment]
Permite modificar los campos en el storybook

**Comment by tommygonzaleza** [comment]
- [ ] El icon debe ser pasado como el link de la imagen, se va a utilizar la imagen recibida por `marketing.course.icon_url`
- [ ] `isAvailableAsSaas` no debe ser incluido como una propiedad de este componente.

**Comment by tommygonzaleza** [comment]
- [ ] El icon no va a ser una imagen con el fondo incluido, sera solo el icono, tenemos que agregarle el color igual que antes como una propiedad nueva
