### ISSUE TITLE
Add filter by language for assets

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4418]
- [ ] Allow filtering assets by language.
- [ ] The filter already exists in the backend you have to add it in the query string like this: `?language=<language>`. `<language>` could be `"es"`, `"us"`, etc
- [ ] Here is the view in the admin: https://admin.4geeks.com/media/asset
- [x] The filter should be a dropdown with the possible languages, show the flag and abbreviation

Expected time: 1 - 3 hrs

**Comment by etolopez** [comment]
pr: https://github.com/breatheco-de/admin/pull/345

<hrs> 0.5 </hrs>

**Comment by tommygonzaleza** [comment]
None of the filters (language and category) are working

**Comment by etolopez** [comment]
pr: https://github.com/breatheco-de/admin/pull/345

issues fixed

**Comment by etolopez** [comment]
Made the change: 

https://github.com/breatheco-de/admin/pull/345/commits/a149f0947952cb0b5beb5a38cccfeee4cd81968b

**Comment by tommygonzaleza** [comment]
Hrs: <hrs>1</hrs>
