### ISSUE TITLE
No veo el component o atomo de un workshop solo

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4419]
Cree yo esto temporalmente, pero me gustaria poder tener ese componente para usarlo cuando quiera y tener todas las variaciones tambien:

- [ ] Cuando el evento esta transcurriendo ahora mismo.
- [ ] Cuando esta por empezar.
- [ ] Cuando empieza en 2 horas.
- [ ] Cuando empieza en 2 dias.
- [ ] Con los 3 diferentes iconos posiblemente par apoder variarlos en el diseño.

[Yo cree este mientras tanto](https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=6864%3A33655&t=SSO28y2mD9jmREBz-0).

<img width="347" alt="Screen Shot 2023-02-16 at 6 43 49 PM" src="https://user-images.githubusercontent.com/426452/219513116-5f0a41a9-33f0-4253-be5f-c92f30b9d3df.png">

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=6807%3A29742&t=rm7nXMpS4sZKLcr3-1

Este es el componente, si haces doble clic en el icono, vas a poder elegir desde el menu de la derecha cual mostrar en property 4, y vas a poder elegir el estado en property 5.

**Comment by alesanchezr** [comment]
Incluir los iconos para los workshops que son de una tecnologia:

Geekpal
Geekforce
Otras tecnologias no enseñadas por 4geeks.
Otras tecnologias full-stack.
