### ISSUE TITLE
Contactar a e-student para scar un review de 4geeksacademy full stack y otro de datascience

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4420]
e-student . org/contact/

**Comment by Jsolis4geeks** [comment]
![image](https://user-images.githubusercontent.com/118853358/225211144-20e6da90-ac27-4eff-9c05-576976c2e662.png)

Already sent it.

**Comment by Jsolis4geeks** [comment]
Contacted through LinkedIn

**Comment by Jsolis4geeks** [comment]
Hello, my name is Alejandro Sanchez, CEO of 4Geeks Academy. After reviewing your website I think that a partnership between our webs will be a good fit for both of us.

Please let me know your thoughts.
Thanks
