### ISSUE TITLE
Backlinks a news anyway y techstory

### ISSUE THREAD

**Issue by Jsolis4geeks** [4GeeksAcademy/About-4Geeks-Academy#4427]
Answers emails from sites that already answered.

**Comment by Jsolis4geeks** [comment]
EL que cobra 30 USD por los enlaces tiene un DA de 66, no estaria mal pedir uno o dos enlaces, lo dejo a tu juicio.

https://www.newsanyway.com/

**Comment by Jsolis4geeks** [comment]
El que cobra 125USd por articulo: techstory.in

Tiene un DA de 77

**Comment by alesanchezr** [comment]
aprobados ambos: news anyway  y techstory

**Comment by Jsolis4geeks** [comment]
newsany way



![Image](https://user-images.githubusercontent.com/118853358/222344884-dde3a1c5-3a34-4941-899f-97ddec72068c.png)



tech story



![Image](https://user-images.githubusercontent.com/118853358/222345056-74363a37-2585-4c77-9e04-e7b831f0cb1f.png)

**Comment by alesanchezr** [comment]
esperando por respuesta de ambos.

**Comment by alesanchezr** [comment]
backlinks anyway ya subido, el de techstory ya lo pagamos y falta q lo suban.

**Comment by alesanchezr** [comment]
te pase la foto del comprobante de pago, creo que techstory tiene que aceptar el pago.

**Comment by Jsolis4geeks** [comment]
Ya completado
