### ISSUE TITLE
Update Intenlinking Strategy fo Full Stack Developer

### ISSUE THREAD

**Issue by Jsolis4geeks** [4GeeksAcademy/About-4Geeks-Academy#4434]
Edit Internlinking Strategies

**Comment by alesanchezr** [comment]
seguimos esperando por al cluster que se publique

**Comment by Jsolis4geeks** [comment]
In  progress

**Comment by Jsolis4geeks** [comment]
1. https://admin.4geeks.com/media/asset/how-to-pay-for-a-coding-bootcamp
2. https://admin.4geeks.com/media/asset/software-engineer-salary-germany
3. https://admin.4geeks.com/media/asset/coding-bootcamp-miami
4. https://admin.4geeks.com/media/asset/senior-full-stack-developer-salary
5. https://admin.4geeks.com/media/asset/full-stack-developer-job-description
6. https://admin.4geeks.com/media/asset/full-stack-bootcamp
7. https://admin.4geeks.com/media/asset/full-stack-developer-vs-software-engineer
8. https://admin.4geeks.com/media/asset/full-stack-developer-portfolio
9. https://admin.4geeks.com/media/asset/coding-bootcamp-in-berlin
10. https://admin.4geeks.com/media/asset/software-engineer-salary-germany

**Comment by Jsolis4geeks** [comment]
En ingles son solo esos los que se puede hacer el update, pues son los unicos articulos que se han publicado desde que se comenzó a crear la estrategia de optimizacion que estan en ingles y constituyen una oportunidad para hacer interlinking a esta keyword.
