### ISSUE TITLE
Utilizar consumibles para Workshops

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4437]
- [ ] Se debe generar un link para cada evento, el cual llevara al usuario a un landing sencillo generado por el backend, en este momento se chequearan los consumibles del usuario para ver si puede acceder al workshop, de ser asi lo redirecciona al workshop y se consume el consumible de forma asincrona.

**Comment by tommygonzaleza** [comment]
[Issue](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3956) creado para esto antes, discutir juntos cual es el mejor approach entre ambos

**Comment by jefer94** [comment]
The landing for what?

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/870
