### ISSUE TITLE
Agregar items a `payments.models.AbstractIOweYou`

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4440]
- [ ] Estos valores se deben agregar al momento de la compra
- [ ] Add this three foreign keys, but we have to make sure this 3 items match exactly with the possible cohorts, service sets and eventtype sets that the PlanServiceItem is allowing:
- cohort = models. ForeignKey (Cohort, on_delete=models.CASCADE)
- mentorshipservice_set = models. ForeignKey (MentorshipServiceSet, on_delete=models.CASCADE)
- eventtype_set = models. ForeignKey (EventTypeSet, on_delete=models.CASCADE)

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/769
