### ISSUE TITLE
Review 10 lessons from Full Stack Syllabus

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4447]

**Comment by Lorenagubaira** [comment]
- [ ] https://github.com/breatheco-de/content/pull/1272
- [ ] https://github.com/breatheco-de/content/pull/1273
- [ ] https://github.com/breatheco-de/content/pull/1283

**Comment by Lorenagubaira** [comment]
- [ ] https://github.com/breatheco-de/content/pull/1301
- [ ] https://github.com/breatheco-de/content/pull/1302
- [ ] https://github.com/breatheco-de/content/pull/1303
- [ ] https://github.com/breatheco-de/content/pull/1306
- [ ] https://github.com/breatheco-de/content/pull/1307
- [ ] https://github.com/breatheco-de/content/pull/1308
- [ ] https://github.com/breatheco-de/content/pull/1311
- [ ]
