### ISSUE TITLE
Identificar sitios para backlinks

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4456]
Basado en lo que hace open bootcamp revisar que podemos hacer.

**Comment by Jsolis4geeks** [comment]
Una de las principales razones del crecimiento de Open Bootcamp son estos enlaces desde Hubspot

![image](https://user-images.githubusercontent.com/118853358/222038281-ace4a67e-ab0b-48a2-8831-bf7e3fd5bee7.png)

**Comment by Jsolis4geeks** [comment]
La mayoria de sus enlaces son pagos y esa es parte de su estrategia de posicionamiento, pagar por backlinks. Estoy corriendo una campaña en link hunter para identificar sitios de Guest Posting, para que la revises

**Comment by Jsolis4geeks** [comment]
https://v2.linkhunter.com//websites/1670743?c=5300&q=prospects
