### ISSUE TITLE
Optimizar campus de caracas en español para curso de informatica

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4457]
Hemos cambiado la URL y la keyword por la que vamos a posicionarnos:

https://4geeksacademy.com/es/coding-campus/curso-informatica-caracas-venezuela

**Comment by Jsolis4geeks** [comment]
Already did, and did not have to do much since the keyword was already implemented in Title, H1, and only updated the Meta Description.

This is the link to the pull request: https://github.com/4GeeksAcademy/website-v2/pull/1597
