### ISSUE TITLE
Rediseñar vista antes de que empiece un workshop

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4465]
En [este archivo](https://github.com/breatheco-de/apiv2/blob/main/breathecode/events/templates/countdown.html) hay una mini pagina web que tiene todo lo que necesita para trabajar: Tiene su CSS, su html y su javascript. (Utilizando una version minima de react).

Para probar el template debes ir a `/v1/events/me/event/600/join?token=<session token>`

Debes pasarle un token real y un ID de un evento real que no haya empezado todavia.

Este es el nuevo diseño que estamos buscando.
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=6986%3A33091&t=8ECMsOv1pqlQI2zQ-0

 Expected time: 2 - 4 hrs

**Comment by tommygonzaleza** [comment]
No se necesita este rediseño
