### ISSUE TITLE
Actualizar link building campaigns

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4469]
https://www.notion.so/4geeksacademy/SEO-6a79982bf38047c69dcec88aea478b9a

**Comment by Jsolis4geeks** [comment]
Lost access to Notion, already asked to Ariana

**Comment by alesanchezr** [comment]
ya tienes acceso

**Comment by Jsolis4geeks** [comment]
Completed
