### ISSUE TITLE
Subscriptions con status FREE_TRIAL deben retornarse en `GET /v1/payments/me/subscription`

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4470]
Las subscriptions con status FREE_TRIAL tambien deben retornarse en `GET /v1/payments/me/subscription`

**Comment by jefer94** [comment]
This already happens, you can use my account to test it https://breathecode-test.herokuapp.com/v1/payments/me/subscription

**Comment by tommygonzaleza** [comment]
Yes I confused the bug reported yesterday through slack
