### ISSUE TITLE
I don't appear as a GeekFORCE mentor

### ISSUE THREAD

**Issue by vancieta** [4GeeksAcademy/About-4Geeks-Academy#4471]
### Bug description

![image (6)](https://user-images.githubusercontent.com/116301809/221266465-94906571-347b-40aa-82c8-6bf151ca1bd3.png)
I don't appear as a GeekFORCE mentor on the 4geeks.com page, only Valentina Jimenez appears, so students can't schedule meetings with me there.

### Steps to reproduce

Try to book a meeting with me on the 4geeks platform

### Expected behavior

Appear as a mentor

### Anything else?

I checked the admin view, and everything seems okay, so I don't know what could be happening.

**Comment by tommygonzaleza** [comment]
Solved!
