### ISSUE TITLE
que hacer si tengo dos live classes a la vez?

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4493]
Hay un raro caso (que ya me ocurrio) que habian dos clases a la misma vez, deberiamos preguntarle al usuario a cual quiere entrar: `There are two master classes happening right now: Which one would you like to join?`

Tener en cuenta que pueden ser mas de dos, pueden ser 4 o cinco, etc.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=6738%3A27095&t=ajdhuxjK0MdFNB1j-1

**Comment by alesanchezr** [comment]
Se decidio que si haces click en la parte de live classes se va a expandir, pero dejando todavia colapsada la parte de eventos, eos solo va a ocurrir si hay mas de un solo live class (que e smuy raro). Tambien se va a incluir la cuenta de cuantos live classes hay afuera.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=6738%3A27095&t=8pq0prWVOuS7WYLF-1
