### ISSUE TITLE
Al agregar dos PlanServiceItem a un mismo plan, el servicio de checking no consigue cohorts asociadas al plan

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4497]
El servicio `PUT /v1/payments/checking` retorna `"No se proporcionan cohortes para los planes: <plan>"`.

![Screenshot 2023-02-28 at 8 27 54 PM](https://user-images.githubusercontent.com/56565994/222014028-abee8cd5-7325-48e5-86ce-7401975a9a3e.png)

## Pasos para replicar el bug:

1. Crea una cohort o utiliza una existente
2. Crea un Plan.
3. Crea dos PlanServiceItem asociados a la misma cohort.
4. Intenta acceder desde el flujo del signup a la cohort pasandola por el querystring con este formato: `https://dev.4geeks.com/es/signup?cohort=<cohort_id>`
5. No va a poder encontrar una cohort asociada al plan por lo que fallará el servicio de Checking.

## Resultado esperado:

El servicio de checking deberia retornar los datos del plan y poder ver el resumen de la compra
![Screenshot 2023-02-28 at 8 34 14 PM](https://user-images.githubusercontent.com/56565994/222014870-b310ea4a-e8d9-420f-9864-b4793e1b3cf8.png)

**Comment by jefer94** [comment]
I can't replicate this
