### ISSUE TITLE
Include icon for projects that are mandatory for graduations

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4499]
This is the service to retrieve [syllabus information](https://documenter.getpostman.com/view/2432393/T1LPC6ef#0cc8e3a9-a1bc-428e-b9a8-b2c180362c7b). Please retrieve the syllabus in the version that corresponds with the cohort version.

Look for [assignments that are mandatory](https://tinyurl.com/2hjdqcay).

Use that information to display an icon on the task that specifies if its mandatory or not. [This icon can be similar to the one used to show the students mandatory projects](https://tinyurl.com/2mv9ag82).

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-37184-609738c36da504941d58044afd91708a) 

---
**Source URL**:
[https://4geeks.com/cohort/mad-cohort-0/assignments?academy=6](https://4geeks.com/cohort/mad-cohort-0/assignments?academy=6)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x711</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=6939%3A42080&t=ajdhuxjK0MdFNB1j-1

**Comment by tommygonzaleza** [comment]
Estya bueno esto pero el PR tiene los cambios del componente RecommendedCourses que si tienen un error
