### ISSUE TITLE
`chosen_period`y `how_many_installments` no debe ser mandatorio siempre

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4502]
<img width="1112" alt="Screenshot 2023-03-01 at 6 56 35 PM" src="https://user-images.githubusercontent.com/56565994/222285384-e1b21208-4fa6-4406-b5b5-b2ae775b934b.png">

- [ ] `chosen_period`y `how_many_installments` no debe ser mandatorio para plans que tengan todos los valores en cero (price_per_month, price_per_quater, price_per_year, price_per_half, y que no tenga financing options) 
- [ ] Agregar opciones posibles de `chosen_period` en el mensaje de error que da cuando el chosen_period es invalido.

## Para replicarlo:

Haz un request al servicio `POST /v1/payments/pay` con el siguiente payload:
```
{
    type: "PREVIEW",
    token: "684f775908d14a3a62effe5398bacd2316b19601",
    chosen_period: "WEEK"
}
```

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/812
