### ISSUE TITLE
Enviar campaña de Guest Posting para conseguir proveedores en español 

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4508]
It seems this campaign its not about pay published to allow us to post on their blogs, this is not about payments, the guest posting is about quality. Alejandro's email will be used to contact possible guest posting options.

- [x] What will be the template?
- [ ] Build campaign on link hunter.

**Comment by Jsolis4geeks** [comment]
Here is the link to the task on Link Hunter:
https://v2.linkhunter.com/campaigns/aejandro-sanchez-full-stack-developer-course-guest-posting-2

Here is the Template I recommend:

Hello [Name],

My name is Alejandro Sanchez and I’m the CEO of 4 Geeks Academy. I noticed our websites are very closely related so I wanted to contact you in regards to establishing a content partnership.

Assuming you’re interested, I would contribute a unique piece of content exclusively for your website. I have extensive experience with technology as long as 8000 Followers on Twitter and 4000 on LinkedIn. I am confident I could produce an article that your audience would find interesting and engaging.

I’ve included a few samples of my past work below for your reference.
https://4geeksacademy.com/es/desarrollador-full-stack/cuanto-gana-un-desarrollador-full-stack
https://4geeksacademy.com/es/coding-campus/online-bootcamp-programacion

Don’t hesitate to reach out with any questions or concerns.

Thank you.

4Geeks Academy is a premier coding bootcamp with brick & mortar locations and an online presence in multiple countries. We offer lifetime career support, 10 dollars in scholarships, or a money-back guarantee. Our innovative platform, 4Geeks.com, provides interactive coding and instant feedback. We have graduated over 3000 students with an 84% job placement rate, named top 10 by Newsweek and top 35 by CourseReport and Switchup.

**Comment by Jsolis4geeks** [comment]
En el template podriamos hablar del affiliate program, que te parece?

**Comment by Jsolis4geeks** [comment]
Will leave for next week, lets give a break to the gmail account

**Comment by Jsolis4geeks** [comment]
https://v2.linkhunter.com/websites/1675085?c=5315&amp;q=contacted

Sent

**Comment by URubino4Geeks** [comment]
La prioridad ahora es conseguir proveedores en español, vamos a lanzar más campañas para conseguirlos

**Comment by Jsolis4geeks** [comment]
Este caso se parece mucho al de conseguir proveedores de referencia en español, de todas formas lo voy a dejar para la next week, dado que no quiero sobrecargar el email

**Comment by Jsolis4geeks** [comment]
Completed, please close Issue
