### ISSUE TITLE
When an article is updated it should confirm if the `published_at` datetime should be updated as well

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4518]
- [x] The confirmation should not occur if the status of the article is not PUBLISHED
- [ ] Use the [ConfirmAlert component](https://github.com/breatheco-de/admin/blob/master/src/app/components/ConfirmAlert.jsx).
- [x] Ask the user: `Do you wish to update the asset published date?` and 2 options buttons to be possibly clicked: `No,  don't update the published date` (in blue), `Yes, update the published date`
- [ ] If "yes" option is chosen you will send the new published_at date in the payload.

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-37199-914684815f89c2ee4204b86b99f94f55) 

---
**Source URL**:
[https://admin.4geeks.com/media/asset/marco-de-politicas-de-reembolso-de-4geeks-academy](https://admin.4geeks.com/media/asset/marco-de-politicas-de-reembolso-de-4geeks-academy)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x711</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by alesanchezr** [comment]
@tommygonzaleza please reasign

**Comment by etolopez** [comment]
pr : https://github.com/breatheco-de/admin/pull/347

h: <hrs>4 </hrs>

**Comment by tommygonzaleza** [comment]
- [ ] The request to update the asset should be done after the user select an option in the modal where they can choose to modify the publish date or not

**Comment by etolopez** [comment]
pr : https://github.com/breatheco-de/admin/pull/347

hr: <hrs> 2 </hrs>

**Comment by tommygonzaleza** [comment]
- [ ] The request to update the asset should be done after the user select an option in the modal where they can choose to modify the publish date or not. In this way, only one request will be done instead of modifying the asset twice

**Comment by tommygonzaleza** [comment]
<img width="1205" alt="Screenshot 2023-03-14 at 4 41 16 PM" src="https://user-images.githubusercontent.com/56565994/225131397-dfe83a63-f3c6-45cb-bb83-97233c734286.png">

**Comment by tommygonzaleza** [comment]
Tienes un error de sintaxis en el codigo, solucionalo para que pueda hacerse el redeploy

**Comment by etolopez** [comment]
https://github.com/breatheco-de/admin/pull/347

listo

**Comment by tommygonzaleza** [comment]
<hrs>7</hrs>
