### ISSUE TITLE
Prohibir recomprar trials

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4521]
Estas son las validaciones que se deben hacer para los diferentes escenarios:

- [ ] Los planes que SI tienen trial pero NO son renovables mas nunca se puede comprar.
- [ ] Los planes que Si tienen trial pero SI son renovables, se puede volver a comprar pero sin trial.
- [ ] Los planes que No tienen trial se puede comprar mil veces, no importa si son renovables.

> Nota: Al momento de crear la bolsa no permitir la opcion de free trial en los casos que corresponda

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/811
