### ISSUE TITLE
Add service to cancel or reactivate a subscription

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4525]
- [ ] Add the service `PUT /v1/payments/me/subscription/<subscription_id>/cancel`
- [ ] Add unit tests.
- [ ] For reactivating, it should be done like the way a plan is paid normally. But in the endpoint of pay or checking, it should validate if the user already has a subscription to reactivate it if it's the case

**Comment by alesanchezr** [comment]
De acuerdo con cancel… pero…

Reactovate no es lo mismo que comprar? Si vuelves a comprar se reactiva, para q queremos un endpoint?

**Comment by tommygonzaleza** [comment]
Si creo que tienes razon, podria hacerse directamente desde comprar, pero que el endpoint de pay deberia validar si esa persona ya tiene una subscripcion asociada a ese plan y de ser asi reactivarla para reutilizar la subscripcion

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/804

**Comment by tommygonzaleza** [comment]
Changes requested in the PR
