### ISSUE TITLE
Agregar ForeignKey `subscription.upgraded_subscription_to` a `Subscription`

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4527]
- [ ] Agregar ForeignKey con `subscription.upgraded_subscription_to`. Asegurarse que funcione como OneToOne
- [ ] Agregar ForeignKey con `subscription.upgraded_plan_financing_to`. Asegurarse que funcione como OneToOne

Esto se va a utilizar para que el frontend pueda filtrar aquellas subscriptions que son free trial si ya se les hizo upgrade, sino si se quiere mostrar

**Comment by alesanchezr** [comment]
Y porque no se hace a traves del offer @tommygonzaleza

**Comment by tommygonzaleza** [comment]
Se penso tambien esa opcion pero si se cambia el plan del planoffer, entonces no vamos a poder llevar un registro de a cual plan hizo upgrade. Tomamos esta via para poder armar una arquitectura lista para el analisis de datos por si en un futuro se quiere analizar.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/804

**Comment by tommygonzaleza** [comment]
No se va a usar esta implementacion
