### ISSUE TITLE
Request Syllabus form

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#453]
Hrs: <hrs>2</hrs>

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-4109-16153-8d854ec76179c0a588d8cdd16fe0f131) 

 - El form debe validar igual que contact-us o apply.
- El boton de enviar debe estar siempre visible.
- Si presionas enviar y no es valido entonces aparece rojo el boton de enviar.
- Si hay algun campo vacio no permite enviar (prevencion).

---
**Source URL**:
[https://www.facebook.com/](https://www.facebook.com/)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 83.0.4103.106</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1422x685</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by alesanchezr** [comment]
aprobado

**Comment by Jtoledo88** [comment]
Pagado en Julio 2020
