### ISSUE TITLE
Error when trying to pay/start a Free Trial Plan

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4530]
URL: https://breathecode-test.herokuapp.com/v1/payments/pay

Error:
<img width="1380" alt="Screenshot 2023-03-03 at 7 36 21 PM" src="https://user-images.githubusercontent.com/56565994/222854967-f01fb003-632d-48f8-acdd-4f056e656e09.png">

Payload:
<img width="1312" alt="Screenshot 2023-03-03 at 7 34 18 PM" src="https://user-images.githubusercontent.com/56565994/222854757-8ec05bb6-86aa-4f3f-9caf-ea54d806a99c.png">

### Servicio Checking:

Payload:
<img width="1380" alt="Screenshot 2023-03-03 at 7 35 13 PM" src="https://user-images.githubusercontent.com/56565994/222854894-1c5b9fad-bae5-4d65-a602-5785d4cdd85e.png">

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/802

**Comment by jefer94** [comment]
![image](https://user-images.githubusercontent.com/3018142/223243551-e0b76f3d-7483-42e6-93b6-e1ab33091868.png)
