### ISSUE TITLE
PlanFinancingCard en seccion de my subscriptions.

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4534]
En la seccion de my subscriptions se pueden mostrar tarjetas de dos tipos de planes posibles que el usuario puede consumir: Subscriptions y PlanFinancing.

Las subscripciones son los planes renovables cuyo pago se hara de forma recurrente en la cantidad de tiempo establecida y que al dejar de pagar el plan culmina

Los PlanFinancing son los planes que tienen un precio y se puede pagar en un solo pago o por cuotas, sin embargo la duracion del plan es independiente del tiempo que se dure pagando los planes

Se debe crear una tarjeta en la seccion del perfil (My subscriptions) pero para los PlanFinancing.

**Comment by alesanchezr** [comment]
Falta documentar un poco mas
