### ISSUE TITLE
Change placeholder on deliver input on the initial projects in fullstack 18w courses 

### ISSUE THREAD

**Issue by ehiber** [4GeeksAcademy/About-4Geeks-Academy#4543]
### Bug description

This project is requesting a github url, but the placeholder is giving an example of a gitpod snapshot for some reason.

![image](https://user-images.githubusercontent.com/56272634/223172401-f2c760d9-d8a3-41e7-ba3b-98b031c84bc5.png)

### Steps to reproduce

1. Look for the `instagram with bootstrap` exercise in the cohort dashboard.
2. Try to submit one.
3. Look at the input placeholder.

### Expected behavior

The placeholder need to say github and not gipod, the instructions are right

**Comment by alesanchezr** [comment]
no logro confirmar esto, asi me sale a mi: 
<img width="1009" alt="Screen Shot 2023-03-06 at 12 44 52 PM" src="https://user-images.githubusercontent.com/426452/223190056-27605091-6719-4a53-80d1-46637bc7e0cb.png">

Tu lograste confirmarlo @ehiber ?

**Comment by ehiber** [comment]
Lo acabo de confirmar, he malinterprado la situación, en efecto esta bien el placeholder
