### ISSUE TITLE
Un usuario no puede tener mas de una subscripcion asociada a un mismo plan

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4555]
- [ ] Un usuario no puede tener mas de una Subscripcion o PlanFinancing asociado a un mismo plan.
- [ ] Al momento de hacer el checking no debe permitir agregar un plan al que ya tiene una Subscripcion o PlanFinancing asociado
- [ ] Al momento de hacer el pay no debe permitir si ya tiene una Subscripcion o PlanFinancing asociado al mismo plan
- [ ] Un usuario puede comprar un plan del que ya tiene una subscripcion si y solo si la subscripcion que ya tiene esta con status `CANCELLED` o `DEPRECATED`. Esta es la manera en la que se permitira reactivar subscripciones

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/811
