### ISSUE TITLE
Crea vistas del flujo de Sign Up en mobile

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4558]

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=4236%3A12001&t=HV2fp80hbfCNJIcn-1

**Comment by alesanchezr** [comment]
- [ ] En la version móvil tiene que ser un acordión para que todo quede mas visible.
