### ISSUE TITLE
Implementar waiting lists a los planes

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4563]
- [ ] Agregar campo `has_waiting_list` a los planes, (por defecto sea falso).
- [ ] EL metodo `/v1/auth/subscribe/` debe generar el token automaticamente y aprobar el invite si hay una cohort o sylalbus con cohorts cuyo`cohort.available_for_saas=True` y ademas el plan no puede tener `plan.has_waiting_list=True`.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/807

**Comment by tommygonzaleza** [comment]
- [ ] Agregar un OneToMany en la tabla `Plan` hacia invite.
- [ ] Agregar en el serializador de un invite el `Plan` asociado.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/869

**Comment by tommygonzaleza** [comment]
Por que en el serializador hay `plan` y `plans`?

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/899
