### ISSUE TITLE
Improvements to the view to update a cohort

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4567]
Small changes any student can do

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-8083-37260-51c2507aac44b8e436453282ade8b14e) 

---
**Source URL**:
[https://admin.4geeks.com/admissions/cohorts/new](https://admin.4geeks.com/admissions/cohorts/new)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1440x900</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440x711</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@2x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by etolopez** [comment]
pr: https://github.com/breatheco-de/admin/pull/348

H: <hrs>0.5 </hrs>
