### ISSUE TITLE
Revisar que la imagen se este reemplazando

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4571]
- [ ] Las imagenes de los assets se descargan y se agregan al bucket para luego ser reemplazadas en el readme por la url del bucket, [Aqui](https://github.com/breatheco-de/apiv2/blob/727074ef9d15fd46516710c54ac0eda83b0ffa39/breathecode/registry/tasks.py#L392) ocurre el reemplazo, se debe chequear que este funcionando correctamente.
- [x] Las imagenes no deben reemplazarse en el readme_raw.
- [ ] Solo reemplazar imagenes que no esten en la tabla AssetImage ni en el valor `AssetImage.bucket_url`
- [x] [Aqui](https://github.com/breatheco-de/apiv2/blob/727074ef9d15fd46516710c54ac0eda83b0ffa39/breathecode/registry/tasks.py#LL371C54-L371C54) Deberia filtrarse que exista uno con ese original_url o con ese bucket_url
- [x] Incluir pruebas unitarias

**Comment by jefer94** [comment]
Pero si se modifican solo en el readme raw en que momento caen en el readme que es el que llega al frontend?

**Comment by tommygonzaleza** [comment]
Creo que tienes razon, deberia modificarse en ambos?

**Comment by tommygonzaleza** [comment]
- [ ] Agregar prueba que asegure que el readme_raw no se esta modificando. Puedes hacer un hash del readme_raw antes y despues.
- [ ] Agregar prueba con varias imagenes el readme, asegurandose que todas se reemplacen correctamente. agrega imagenes con ruta relativa, ruta absoluta a nuestra pagina y otras.
