### ISSUE TITLE
Cookie consent report

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4588]
Refactor cookie GDPR compliance.
We need to chage the way 3rd party cookies are load to allow cookiebot to block them.
https://drive.google.com/file/d/1Lsr0t59KrSy97IHiRpjCP_Lq_GT7RHdf/view?usp=share_link

**Comment by tommygonzaleza** [comment]
No aparece el banner

**Comment by tommygonzaleza** [comment]
Esta bloqueando a este [issue](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5159)
