### ISSUE TITLE
On the pricing secion of the website add fucntionality to the review guidebook form

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#459]
Hrs: <hrs>2</hrs>

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-4109-16376-64bc77905bd2bb378e80e9f8bb277fe9) 

---
**Source URL**:
[https://8000-d69fe0f8-bdc8-4b0b-9763-3a7c4b773c8d.ws-us02.gitpod.io/us/pricing](https://8000-d69fe0f8-bdc8-4b0b-9763-3a7c4b773c8d.ws-us02.gitpod.io/us/pricing)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 83.0.4103.116</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1886x685</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by alesanchezr** [comment]
aprobado.

**Comment by Jtoledo88** [comment]
Pagado en Julio 2020
