### ISSUE TITLE
Finish the account for ClickBank

### ISSUE THREAD

**Issue by Jsolis4geeks** [4GeeksAcademy/About-4Geeks-Academy#4591]
https://accounts.clickbank.com/master/create-account

**Comment by Jsolis4geeks** [comment]
The account creation led to an error, I am currently writing to support an email to talk to them.

**Comment by Jsolis4geeks** [comment]
![image](https://user-images.githubusercontent.com/118853358/225198351-4e0cea84-925e-46a2-a524-8ebddc42c764.png)

**Comment by Jsolis4geeks** [comment]
When Finally got an answer from them they banned my ClickBank account, again sent an email asking for an explanation

**Comment by Jsolis4geeks** [comment]
Still has not received anything from them I sent another email

**Comment by Jsolis4geeks** [comment]
After sending the 2nd email, they requested this:

![image](https://user-images.githubusercontent.com/118853358/228710460-e28b9e02-b774-4532-9c54-23301f341b0a.png)

Note: A KYC verification from me as a person, I asked about what we could do to list a company.

**Comment by URubino4Geeks** [comment]
I'll be in charge of this issue now, I'll try to get the ClickBank account up

**Comment by URubino4Geeks** [comment]
Haven't found a way to go around the issue with the phone number

**Comment by URubino4Geeks** [comment]
We'll migrate this strategy to 4Geeks.com
