### ISSUE TITLE
Select one backlink from MotherLink to test

### ISSUE THREAD

**Issue by Jsolis4geeks** [4GeeksAcademy/About-4Geeks-Academy#4592]
https://app.motherlink.io/login?redirect=%2Fbasket

**Comment by Jsolis4geeks** [comment]
Selected this one:

![image](https://user-images.githubusercontent.com/118853358/224465979-60ff38bd-76d0-40cb-9025-e6583ecabe63.png)

**Comment by alesanchezr** [comment]
Falta preparar el contenido, ya se pago.

**Comment by Jsolis4geeks** [comment]
Ya me escribieron para mandar el contenido, recomiendo hacer algo de Brand para hablar de la empresa

**Comment by Jsolis4geeks** [comment]
Este es el Contenido para mandar al website: **https://docs.google.com/document/d/1PEOiTvcFx3MvRBl0JGEvEqFarGaCDmesGqsT6P-_ZD0/edit**

**Comment by Jsolis4geeks** [comment]
Ya se envió el contenido optimizado y se aprobó, estaré actualizando este caso pronto

**Comment by Jsolis4geeks** [comment]
Queda abierto hasta que lo publiquen

**Comment by URubino4Geeks** [comment]
Seguimos esperando

**Comment by Jsolis4geeks** [comment]
Posted: https://www.archyde.com/why-should-you-learn-to-code-in-a-coding-bootcamp-like-4geeks-academy/

**Comment by URubino4Geeks** [comment]
Esperando por @alesanchezr para revisarlo
