### ISSUE TITLE
GetPlanSerializer debe retornar si tiene al menos un available_cohorts

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4633]
En el serializador [GetPlanSerializer](https://github.com/breatheco-de/apiv2/blob/0bdea3196a96751a0a3e44d7825346b32a307eba/breathecode/payments/serializers.py#L205) se debe incluir un campo nuevo llamado `has_available_cohorts` que determinara a traves de una funcion si el plan tiene available_cohorts o no.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/814
