### ISSUE TITLE
Agregar alerta que recuerde que esta en free trial en dashboard de cohort

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4642]
![Screenshot 2023-03-15 at 1 22 57 PM](https://user-images.githubusercontent.com/56565994/225391350-38acdfed-27aa-4474-b5fe-4ca94b9c69b5.png)

La alerta debe decir: `"You are currently on a free trial, some features might be limited. Upgrade your plan to have unlimited access!"`

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=7598%3A35895&t=jaQepP4FGY5uWyNO-1

**Comment by tommygonzaleza** [comment]
@ArielCalisaya Reutilizar componente del warning de cuando faltan por hacer algunas tareas mandatorias
