### ISSUE TITLE
Agregar `abstractioweyou.status` EXPIRED

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4647]
- [ ] Agregar el status `EXPIRED` a este [modelo](https://github.com/breatheco-de/apiv2/blob/0bdea3196a96751a0a3e44d7825346b32a307eba/breathecode/payments/models.py#L723)
- [ ] Agregar en el cronjob [make_charges](https://github.com/breatheco-de/apiv2/blob/0bdea3196a96751a0a3e44d7825346b32a307eba/breathecode/payments/management/commands/make_charges.py) para que modifique el status a `EXPIRED` de los `subscriptions` y `planfinancing` cuyo `valid_until`ya haya pasado

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/819

**Comment by tommygonzaleza** [comment]
FREE_TRIAL deberia poder expirarse no?
