### ISSUE TITLE
Si un plan es renovable, no debe tener time of life

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4648]
- [ ] Si un plan es renovable (Subscriptions), no debe tener time of life, ya que el tiempo de vida del plan se rige del tiempo de los pagos (Si se paga mensual, trimestral, semestral o anual)
- [ ] Si un plan no es renovable (Plan Financing), entonces debe tener un time of life y time of life unit, los cuales regiran el valor del `valid_until`.
- [ ] Actualmente hay una validacion que pide lo contrario, debe removerse

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/818
