### ISSUE TITLE
Optimize all the website forms

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#466]
Hrs: <hrs>1</hrs>

The following forms: Apply, Syllabus Request, Review Guidebook, Hiring Partners and Newsletter.

- When typing on an input it gets very slow.
- I should not be able to click on submit again if its still loading.
- Implement debouncing on the input and textareas.

**Comment by alesanchezr** [comment]
Aprobado

**Comment by Jtoledo88** [comment]
Pagado en Julio 2020
