### ISSUE TITLE
Toggle para job guarantee

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4678]
- [ ] Agregar un toggle para agregar job guarantee a cualquier plan
- [ ] Re-diseño del componente del pricing
- [ ] La grafica negra con las estadisticas pasara a ser fondo blanco y tratar de hacerla quedar como una seccion normal.

**Comment by tommygonzaleza** [comment]
- [ ] Agregar mas vida en el componente

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?node-id=6987%3A9857&t=h2It06mVzBsqF7gJ-1

**Comment by URubino4Geeks** [comment]
Pedir a @ali5uarez5 actualizar los colores del componente de precios

**Comment by alesanchezr** [comment]
fondo negro no quedo, poner otro color.

**Comment by tommygonzaleza** [comment]
Se deben hacer [estos cambios](https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?node-id=6987%3A9857&t=ZXO0uxrQMVG65yvw-1) a la seccion de pricing del website

**Comment by tommygonzaleza** [comment]
Se esta haciendo en este otro issue: https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4916
