### ISSUE TITLE
Hacer una version reducida del componente de mentorias 

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4679]
Este es el [componente](https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=5903%3A20339&t=KSp3zGjut9F5IGH6-1). Se debe hacer una version reducida en donde se haga mas llamativo agendar una mentoria.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=7729%3A36470&t=VaaN0sD5GqkBspaj-1

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=7956%3A39412&t=GMl7xrgSUKQuVhsS-1

**Comment by tommygonzaleza** [comment]
- [ ] Mostrar el componente diferente con una info mas llamativa cuando no tiene mentorias disponibles

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=8136%3A39901&t=FD655ei7rBQPAZou-1

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=8830%3A41938&t=U6IXTfw8QBmz5btu-1  

(falta documentar).

**Comment by tommygonzaleza** [comment]
No se va a documentar, ya fue implementado
