### ISSUE TITLE
Consumir workshops desde el Back End

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4689]
- [ ] Agregar campo `event_type.free_for_bootcamps` que debe ser un boolean.
- [ ] Agregar campo `event.free_for_bootcamps` debe ser un boolean, puede ser null y en caso de ser null en el momento de creacion, se le debe asignar el valor del `event_type.free_for_bootcamps`
- [ ] Si la persona tiene una cohort `available_as_saas=false` (Al menos una), Esto lo puedes buscar a traves de las cohorts de los cohort user de ese usuario. y ademas el evento es `free_for_bootcamps=True`, entonces no consume.
- [ ] Si la persona tiene una cohort `available_as_saas=false` (Al menos una), Esto lo puedes buscar a traves de las cohorts de los cohort user de ese usuario. y ademas el evento es `free_for_bootcamps=False`, entonces consume.
- [ ] Si la persona no tiene una cohort `available_as_saas=false` (ni una), Esto lo puedes buscar a traves de las cohorts de los cohort user de ese usuario. Sin importar el valor del evento `free_for_bootcamps`, SI consume.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/894

**Comment by tommygonzaleza** [comment]
Se pidieron cambios en el PR

**Comment by tommygonzaleza** [comment]
- [ ] Solucionar las pruebas que se rompieron

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/904
