### ISSUE TITLE
El boton de "report a bug" en el breathecode-ide deberia pre-llenar el issue

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#469]
Hrs: <hrs>1</hrs>

El breathecode-cli tiene un boton para reportar un bug, [puedes leer mas al respecto aqui](https://github.com/breatheco-de/main-documentation/issues/38)

Me acabo de enterar que github permite pre-llenar los inputs del formulario para crear un nuevo issue utilizando variables en el querystring, puedes [leer mas al respecto aqui](https://eric.blog/2016/01/08/prefilling-github-issues/).

Te deja pre llenar estos campos:
```
Title
Description
Labels
Milestone
Assignee
```

Deberiamos prellenar en la descripcion del issue: 

1. El URL del repositorio de los ejercicios que el alumno esta haciendo en ese momento.
2. El ejercicio que el alumno esta haciendo en ese momento de la lista de todos los ejercicios.
3. El URL actual del workspace de gitpod (si se puede).
4. El github username del usuario que reporta (si lo tienes).

**Comment by alesanchezr** [comment]
aprobado.

**Comment by Jtoledo88** [comment]
Pagado en Julio 2020
