### ISSUE TITLE
Diseño Card de un Marketing Course

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4700]
Se mostraran en el dashboard abajo de "Your active programs"

![Screenshot 2023-03-22 at 3 05 28 PM](https://user-images.githubusercontent.com/56565994/227010790-0490fe54-cdb5-4cfb-9425-4a84f07afa70.png)

- [ ] La informacion que se debe mostrar del curso es el icono, el titulo, una breve descripcion y unos bullets con lo que aprenderan. Hay que intentar hacerlo mas llamativo.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=7961%3A39947&t=GMl7xrgSUKQuVhsS-1
