### ISSUE TITLE
Solución para poder enviar emails 

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4708]
Reemplazar linkhunter con otra viana q si deje mandar correos y hacer follow up: Un CRM?

**Comment by Jsolis4geeks** [comment]
Completado:  Lo hice desañadiendo la cuenta de correo con problemas de todas las cuentas y añadiendo una de mis cuentas personales, luego eliminé la que tenia problemas y la volví a añadir para otra vez ponerla en todas las cuentas a la que estaba asignada antes, eliminando nuevamente mi cuenta personal de Link Hunter.
