### ISSUE TITLE
Buscar backlinks en las paginas mas importantes de venezuela

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4710]
Cuales paginas nos gustan de vzla para buscar backlinks?

**Comment by Jsolis4geeks** [comment]
Waiting for Tania

**Comment by Jsolis4geeks** [comment]
Tania entregó 4 sitios que estan en esta campaña, solo falta revisar si el template es correcto, no se si se quiera pagar por estos sitios o no.

https://v2.linkhunter.com/campaigns/aejandro-sanchez-special-campaign-for-chile-and-venezuela-tania

Template: 

Hola [Nombre], mi nombre es Alejandro Sánchez, CEO de 4Geeks Academy.

Actualmente estamos buscando un selecto grupo de bloggers para hacer una asociación. Quería contactarte porque creo que tu blog sería una buena opción.

Estamos interesados en patrocinar una publicación en tu blog destacando uno de nuestros productos: nuestro curso Full Stack Developer.

En cuanto a precios, ¿cuáles son tus tarifas para este tipo de contenido patrocinado?

Esperamos tener una asociación mutuamente beneficiosa.

Gracias.

4Geeks Academy es un destacado bootcamp de programación con ubicaciones físicas y presencia en línea en varios países. Ofrecemos soporte de carrera de por vida, 10 dólares en becas o una garantía de devolución de dinero. Nuestra innovadora plataforma, 4Geeks.com, ofrece programación interactiva y retroalimentación instantánea. Hemos graduado a más de 3000 estudiantes con una tasa de colocación laboral del 84%, nombrados entre los mejores 10 por Newsweek y los mejores 35 por CourseReport y Switchup.

**Comment by URubino4Geeks** [comment]
Voy a crear un listado de 25+ páginas para backlinking

**Comment by URubino4Geeks** [comment]
https://docs.google.com/spreadsheets/d/1-XYZuyK5FLbF1eYCVVJSKHBkLH_3nR7itDdtf5XumuM/edit?usp=sharing

**Comment by Jsolis4geeks** [comment]
La campaña se envió para esos sitios:

https://v2.linkhunter.com/websites/1763819?q=contacted
