### ISSUE TITLE
Trivia Campaigns

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4713]
Please take in to consideration that none of this feature will be a part of the extension, all of them live in the django admin.

- [x] Create a TriviaCampaign table (a.k.a: TC)
- [x] The TC will contain a property TextField called `TC.brief` that will contain some information needed for the LLM to generate questions in a better way, this brief is hard coded as text but it can be generated by answering some basic initial questions about he organization [like this questions](https://docs.google.com/spreadsheets/d/1s0o_purMCRl3YgZqd4sbZPPh2Icl_fOQpg-ohLa3wCk/edit#gid=1214741996). In the future we will have. TriviaCampaignType that will include this questions and we will ask them to the quest to automatically generate the brief for each trivia depending on the type. for now, we will hard code the brief ourselves.
- [x] One TC contains many questions.
- [x] TC belong to an organization and are created by one user.
- [x] Only experts or the org admin can create trivia campaigns.
- [x] TC have a creation date, and status (DRAFT, ANSWERING, DONE).
- [x] In the admin panel, create a bulk action to "generate questions" automatically for that trivia campaign, it will use chatgpt to generate 50 questions that will be answered by experts. 
- [x] The trivia campaign must show in the admin how many questions it has generated and how many have been answered.
- [x] Trivia campaigns can contain many purpose's included that need to be specificed before generating the questions.
- [x] Backend: Only allow answering completions with TC.status "ANSWERING" or without trivia campaigns

```
only_answered = TC.objects.filter(status=ANSWERING).flatten_by(id).
.filter(Q(trivia_campaign_set__status=ANSWERING) | Q(trivia_campaign_set__id__in=only_answered)

```
- [x] Frontend: Only display completions to be answered with TC.status "ANSWERING" or without trivia campaigns.

**Comment by alesanchezr** [comment]
still missing some bullets.

**Comment by Charlytoc** [comment]
TriviaCampaign completions must be generated async
