### ISSUE TITLE
Replicar exactamente todos los backlinks de esta pagina

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4714]
https://app.ahrefs.com/v2-site-explorer/backlinks?anchorRules=&domainNameRules=&followType=all&grouping=group-similar&highlightChanges=30d&history=all&limit=50&mode=exact&offset=0&refPageTitleRules=&refPageUrlRules=&sort=traffic&sortDirection=desc&surroundingRules=&target=https%3A%2F%2Fwww.lewagon.com%2Ftech-jobs%2Fweb-development%2Ffull-stack-developer&targetUrlRules=

**Comment by URubino4Geeks** [comment]
Hay que revisar este issue, el URL no funciona para ver la info

**Comment by URubino4Geeks** [comment]
Hay que enviar el template de "Por que no estás enlazando a 4GeeksAcademy?" a los que hacen backlink a esa página

**Comment by Jsolis4geeks** [comment]
Se envió la campaña:

https://v2.linkhunter.com/websites/1763840?q=contacted
