### ISSUE TITLE
Revisar validacion de planes gratuitos

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4775]
No sabemos para que se hizo esta validacion pero no la vemos necesaria, la comentamos pero necesitamos que revises para que esta y se vuelva a poner de ser necesaria.

Esta es la validacion: https://github.com/breatheco-de/apiv2/blob/cf135faba6d6913b441a5c848bb61f82ee33d5f4/breathecode/payments/views.py#L1103

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/blob/6b0f2cf1c2f0a3b21a97d5c586917f3506911654/breathecode/payments/views.py#L1370
