### ISSUE TITLE
Subir referencias conseguidos a notion

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4778]
No todos los backlinks, sino los que conseguimos gracias al esfuerzo manual y que teniamos planficiados conseguir.

**Comment by Jsolis4geeks** [comment]
Se hace muy complicado identificar los que se consiguieron por esfuerzo manual, xq tendria que revisar los mas de 1000 sitios contactados y contrastar esos datos, estuve revisando unos pero es bastante informacion para clasificar.

**Comment by Jsolis4geeks** [comment]
Revisar los ultimos 3 meses

**Comment by Jsolis4geeks** [comment]
[Backlinks 4geeksacademy Organicos.xlsx](https://github.com/4GeeksAcademy/About-4Geeks-Academy/files/11218270/Backlinks.4geeksacademy.Organicos.xlsx)

Here is the selection

**Comment by URubino4Geeks** [comment]
https://docs.google.com/spreadsheets/d/1s2_VlAL0oIGA6BwC_nZ01SFG4xCtZoay/edit?usp=sharing&ouid=118213388949117180814&rtpof=true&sd=true

**Comment by Jsolis4geeks** [comment]
In progress

**Comment by Jsolis4geeks** [comment]
Almost done, I'm still cleaning it

**Comment by URubino4Geeks** [comment]
Still in progress
