### ISSUE TITLE
Agregar call to action a assets

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4797]
Este es el figma de como se debe ver la [seccion](https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=6565%3A25169&t=bT6knNt5sXK8A1sz-1)

Reutiliza el componente de MarketingCourse

Debes consumir el servicio: `GET /v1/marketing/course?technologies=javascript,arrays` (Pasando las tecnologias del asset)

- [ ] Si no recibe ningun curso al filtrar por tecnologia, debe hacer otro request sin filtrar por tecnologia
- [ ] Debes cachear el servicio `GET /v1/marketing/course`

**Comment by gustavomm19** [comment]
Courses related to this article

**Comment by gustavomm19** [comment]
IMPORTANTE: Agregar la extencion de cache al get

**Comment by tommygonzaleza** [comment]
- [ ] En mobile se debe permitir hacer swipe y se debe poder ver el segundo curso.
