### ISSUE TITLE
Los assets se estan creando en ingles por defecto

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4810]
Como se estan creando en ingles por defecto, no permite agregarle una categoria en español.

- [ ] El asset debe tomar el lenguaje de la categoria

Expected time: 1 - 3 hrs

**Comment by etolopez** [comment]
pr: https://github.com/breatheco-de/admin/pull/354

H: <hrs>1.5</hrs>

**Comment by tommygonzaleza** [comment]
Quitar input del lenguaje y hacer que se muestren categorias de todos los lenguajes en la modal, y que al ser escogida una, que el asset tome el lenguaje de la categoria

**Comment by etolopez** [comment]
pr: https://github.com/breatheco-de/admin/pull/354

H: <hrs>0.5</hrs>

**Comment by etolopez** [comment]
pr: https://github.com/breatheco-de/admin/pull/354

listo

**Comment by tommygonzaleza** [comment]
<hrs>2</hrs>
