### ISSUE TITLE
No se esta llenando el valor de allow shared creation en event types

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4820]
<img width="1456" alt="Screenshot 2023-04-04 at 10 49 36 AM" src="https://user-images.githubusercontent.com/56565994/229833100-ddd20733-154f-44a0-827d-594417946c0c.png">

Expected time: 1 hr

**Comment by etolopez** [comment]
pr: https://github.com/breatheco-de/admin/pull/338

hr: <hrs> 0.5 </hrs>

**Comment by tommygonzaleza** [comment]
<hrs>0.5</hrs>
