### ISSUE TITLE
Borrar propiedades de `AcademyService`

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4826]
- [ ] Borrar las propiedades `cohort_patterns` y `available_cohorts` de la tabla [AcademyService](https://github.com/breatheco-de/apiv2/blob/eb7fca361065bb716a1dbf1cd7f9011caedd8b33/breathecode/payments/models.py#L354)
- [ ] Se deben agregar las propiedades `bundle_size` (que determina cuantos se incluyen), `max_items` con el `help_text="How many items can be bought in total, it doens't matter the bundle size"`, `max_amount` `help_text="Limit total amount, it doesn't matter the bundle size"`, `discount_ratio` `help_text="Determines the price of the bundle (price_per_unit*bundle_size*discount_ratio)"`.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/863
