### ISSUE TITLE
El servicio `GET /v1/payments/me/consumables` debe retornar el balance de consumibles

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4827]
- [x] Este balance de consumibles debe incluir para cada uno (mentorship_service_set, event_type_set), los datos de este [objeto](https://github.com/breatheco-de/apiv2/blob/eb7fca361065bb716a1dbf1cd7f9011caedd8b33/breathecode/payments/tests/urls/tests_me_service_consumable.py#L860)
- [x] Tambien se debe crear el endpoint `POST /v1/payments/consumables/checkout` el cual recibe cuantos consumibles se van a comprar, de que service_set y a que precio.
- [x] Se debe agregar `GET /v1/payments/mentorship_service_set/<mentorship_service_set_id>` el cual debe retornar los `AcademyService` relacionados a este mentorship_service_set.
- [x] Se debe agregar `GET /v1/payments/event_type_set/<event_type_set_id>` el cual debe retornar los `AcademyService` relacionados a este event_type_set.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/855
