### ISSUE TITLE
Update every interactive exercises intructions to reference codespaces

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4831]
Aqui esta la lista de todos los ejercicios interactivos: https://github.com/4GeeksAcademy/Interactive-Tutorials

- [ ] Asegurarse de que esta parte de "one click" isntallation y tambien la instalacion local esten ocultas entre etiquetas `<--hide-->`
- [ ] Incluir referencia a codespaces primero que la de Gitpod
- [ ] Aprovechar que estamos editando esto y en la parte superior agregar una referencia al README en español con la bendera de españa que diga: *Estas instrucciones [están disponibles en 🇪🇸 español](x) :es:*
- [ ] No debes esconder la nota referente a los tests

## One click installation (recommended):

You can open these exercises in just a few seconds by clicking: [Open in Codespaces](https://codespaces.new/?repo=4GeeksAcademy/css-layouts-tutorial-exercises) (recommended) or [Open in Gitpod](https://gitpod.io#https://github.com/4GeeksAcademy/css-layouts-tutorial-exercises.git).

> Once you have VSCode open the LearnPack exercises should start automatically. If exercises don't run automatically you can try typing on your terminal: `$ learnpack start`

------ VERSION EN ESPAÑOL --------

## Instalación en un clic (recomendado)

Puedes empezar estos ejercicios en pocos segundos haciendo clic en: [Abrir en Codespaces](https://codespaces.new/?repo=4GeeksAcademy/css-layouts-tutorial-exercises) (recomendado) o [Abrir en Gitpod](https://gitpod.io#https://github.com/4GeeksAcademy/css-layouts-tutorial-exercises.git).

> Una vez ya tengas abierto VSCode, los ejercicios de LearnPack deberían empezar automáticamente; si esto no sucede puedes intentar empezar los ejercicios escribiendo este comando en tu terminal: `$ learnpack start`

**Comment by Lorenagubaira** [comment]
- [ ] https://github.com/4GeeksAcademy/html-tutorial-exercises-course/pull/111
- [ ] https://github.com/4GeeksAcademy/html-forms-tutorial-exercises/pull/48
- [ ] https://github.com/4GeeksAcademy/css-tutorial-exercises-course/pull/107
- [ ] https://github.com/4GeeksAcademy/css-layouts-tutorial-exercises/pull/38
- [ ] https://github.com/4GeeksAcademy/bootstrap-exercises-tutorial/pull/50
- [ ]

**Comment by tommygonzaleza** [comment]
Escribir a Alejandro para que acepte los PRs que faltaron por hacer merge
