### ISSUE TITLE
Crear landing 20 million

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4869]
[Este](https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?node-id=7025%3A10646&t=jc4F4rXFKIW2yQ26-1) es el diseño del landing que se debe agregar.

Debes agregar componentes nuevos que no existen para las secciones de _Funds in execution_ (El componente se llamara `ScholarshipProjects` y tendra su propio yml) y para las tarjetas de la seccion de _success cases_ (el componente debe llamarse `ScholarshipSuccessCases` y debe tener su propio YML)

Debes agregar el yml con una data base, luego esta sera modificada (Es importante para tener la estructura del yml hecha)

**Comment by tommygonzaleza** [comment]
En la primera seccion todos los textos deben estar centrados, chequea el figma de nuevo y compara cada seccion para asegurarte de que este igual

**Comment by tommygonzaleza** [comment]
Agregale mas margin-top al titulo y quizas quitale un poco al carousel que esta abajo, asi todo se ve junto bien cuando entras a la pagina

**Comment by URubino4Geeks** [comment]
Queda pendiente realizar el YML
