### ISSUE TITLE
Permitir filtrar por `sort_priority` en el servicio `GET /v1/registry/technology`

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4879]
Este filtro ya se esta haciendo en la vista [AcademyTechnologyView](https://github.com/breatheco-de/apiv2/blob/2bbf86f47f893e6b5a5454b34a38b174b9e3cf41/breathecode/registry/views.py#L115), funciona de la misma manera

- [ ] Corrige los tests que hagan falta

**Comment by Andresgarciasch** [comment]
https://github.com/breatheco-de/apiv2/pull/856

<hrs>1<hrs>

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>
