### ISSUE TITLE
Incluir Flexbox y si es posible CSS Grid en la lesson de Doing Layouts

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#488]
**Is your feature request related to a problem? Please describe.**
No es relacionada a un problema, solo que en España piden mucho flex box y CSS Grid, de hecho otros lo explican y deberíamos actualizarnos nosotros también. Debemos seguir explicando Dsiplay y Float por el legacy code pero sería bueno agregar estas 2 cosas. 

**Describe the solution you'd like**
Que se agregue en la clase de Doing Layouts (https://student.breatheco.de/course/full-stack-ft.v1/2/l/css-layouts) Flexbox y si se puede o se considera CSS Grid.

**Describe alternatives you've considered**
Que al menos se coloque flexbox, css grid al menos un link para que lo conozcan.

**Additional context**
La clase es esta: https://student.breatheco.de/course/full-stack-ft.v1/2/l/css-layouts

**Comment by JimenaEB** [comment]
Lo veo perfecto, pero yo entonces sustituiría bootstrap, o al menos la parte del grid de bootstrap

**Comment by victormgomezp** [comment]
Hola, no me queda claro, se ha subido flexbox al contenido del prework?.

**Comment by JimenaEB** [comment]
Yo empecé a trabajar en ello y tenía una buena parte, pero luego surgieron otras prioridades.
No se si se reasignó. Yo esperaba retomarlo
