### ISSUE TITLE
Crear script para modificar los TimeSlot cuya hora no esta bien generada

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4886]
Por el cambio de hora en algunos paises respecto a estados unidos, algunos timeslots de las clases y eventos quedaron con una hora equivocada. Para solucionarlo, creemos un script que genere todos los timeslots de nuevo y modifque aquellos que queden diferentes al creado antes.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/862
