### ISSUE TITLE
Syllabus Infographic Component

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#489]
Hrs: <hrs>10</hrs>
Realizar en SVG una infografia que muestre la linea de tiempo a lo largo del viaje del alumno dentro de la academia.

![SM8uWMB4I6](https://user-images.githubusercontent.com/426452/87694376-1f0bb100-c75c-11ea-90c7-d638812f78b7.gif)

**Comment by alesanchezr** [comment]
aprobado

**Comment by Jtoledo88** [comment]
Pagado en Julio 2020
