### ISSUE TITLE
Investigar razones por las que el indexamiento de 4Geeks funciona diferente a Academy

### ISSUE THREAD

**Issue by URubino4Geeks** [4GeeksAcademy/About-4Geeks-Academy#4897]

**Comment by Jsolis4geeks** [comment]
Se hizo la primera parte, estoy trabajando en la segunda

**Comment by Jsolis4geeks** [comment]
HAce unos dias se aprobó un issue que se había enviado en enero, por lo que los niveles de indexación deben subir en los proximos dias, es de notar que el proceso de indexación de nuevas URL puede tardar semanas o incluso meses en algunos casos, adjunto algunos articulos que apoyan esta teoría.

En esta foto:
![image](https://user-images.githubusercontent.com/118853358/233249095-012bade5-0348-46f1-b50c-81d062160446.png)

Se puede apreciar el movimiento en caunto al numero de crawls que hace Google en 4Geeks Academy, cabe destacar que este numero de Crawls disminuyó considerablemente a finales de Marzo, coincidiendo con [Google Core Update de Marzo 2023](https://www.searchenginejournal.com/google-rolls-out-march-2023-core-algorithm-update/482389/) lo que puede haber significado un decrecimiento en cuanto a esto.
