### ISSUE TITLE
Cambiar keyword de landing de Machine Learning Bootcamp

### ISSUE THREAD

**Issue by URubino4Geeks** [4GeeksAcademy/About-4Geeks-Academy#4898]
https://4geeksacademy.com/us/coding-bootcamps/machine-learning-engineering

Cambiar keyword a Machine Learning Bootcamp

**Comment by Jsolis4geeks** [comment]
YA estaba actualizado para Machine Learning Course, por lo que solo era cambiar muy poco

Pull: https://github.com/4GeeksAcademy/website-v2/pull/1623
