### ISSUE TITLE
Buscar proveedores de referencias en español

### ISSUE THREAD

**Issue by URubino4Geeks** [4GeeksAcademy/About-4Geeks-Academy#4899]
Clusters en español

- 🇪🇸 [Aprender a programar](https://4geeksacademy.com/es/aprender-a-programar/aprender-a-programar-desde-cero).
- 🇪🇸 [Carrera de programación](https://4geeksacademy.com/es/carrera-de-programacion/carrera-de-programacion-es).
- 🇪🇸 [Full Stack Developer Bootcamp](https://4geeksacademy.com/es/coding-bootcamps/desarrollador-full-stack).
- 🇪🇸 [Full Stack Developer](https://4geeksacademy.com/es/full-stack-developer/desarrollador-full-stack).
- 🇪🇸 [Curso Programacion desde Cero](https://4geeksacademy.com/es/curso-de-programacion-desde-cero/?lang=es)

Algunas tareas:

Llenar lista de proveedores en español en el listado de Excel. 

- [x] Utilizar linkhunter para descubrir proveedores que esta usando la competencia.
- [x] Elegir 3 paginas de motherlink para español.
- [ ] Elegir 3 paginas de paperclub para español.
- [x] Incluir proveedores de Thania
- [x] Agregar proveedores de las otras sedes en español.

**Comment by Jsolis4geeks** [comment]
Se hizo la primera parte en otro issue, estoy trabajando en la segunda

**Comment by Jsolis4geeks** [comment]
En cuanto a la campaña en Link Hunter, se enviaron 350 solicitudes en las siguientes campañas para las keywords (basadas en España):

Sponsored Campaign Spanish - Desarrollador Full Stack
Full Stack Developer
Full Stack Developer que es

https://v2.linkhunter.com/websites/1769802?c=5448&q=prospects
https://v2.linkhunter.com/websites/1769889?c=5449&q=prospects
https://v2.linkhunter.com/websites/1769954?q=prospects&c=5450

**Comment by Jsolis4geeks** [comment]
En cuanto a elegir de Paper.Club estoy a la espera de que se pague la orden anterior, pues no se pueden crear 2 al mismo tiempo

**Comment by Jsolis4geeks** [comment]
Aqui esta hecha la seleccióm de sitios en español de motherlink:

https://app.motherlink.io/basket

**Comment by alesanchezr** [comment]
Falta pagar, alejandro

**Comment by Jsolis4geeks** [comment]
En cuanto a la campaña en Link Hunter, se enviaron 350 solicitudes en las siguientes campañas para las keywords (basadas en España):

Sponsored Campaign Spanish - Desarrollador Full Stack
Full Stack Developer
Full Stack Developer que es

https://v2.linkhunter.com/websites/1769802?c=5448&q=prospects
https://v2.linkhunter.com/websites/1769889?c=5449&q=prospects
https://v2.linkhunter.com/websites/1769954?q=prospects&c=5450

También se enviaron campañas referentes a:

Aprender a programar
Carrera de programación
full stack bootcamp

https://v2.linkhunter.com/websites/1776750?c=5471&amp;q=contacted
https://v2.linkhunter.com/websites/1776800?c=5472&amp;q=contacted

**Comment by alesanchezr** [comment]
Todavia no se han enviado campañas de "porque no haz mencionado a 4geeks" ni tampoco "404 links"

**Comment by Jsolis4geeks** [comment]
Por favor revisar este articulo, es uno de los de motherlink, el que tenia los requerimientos para que fuera algo relacionado al medio ambiente.
https://docs.google.com/document/d/1WjNXfpGAyQS15523ZjXPX5LoF-c8Bx45q4XJreWvZ7g/edit#heading=h.9rhu1jds2930

**Comment by Jsolis4geeks** [comment]
Ya le escribí a las personas del Bootcamp Noruego para hablar sobre el intercambio de enlaces

**Comment by Jsolis4geeks** [comment]
Ya se enviaron las campañas de xq no has mencionado a 4Geeks, quedaría las de 404
