### ISSUE TITLE
Agregar `.vscode/settings.json` a todos los ejercicios y boilerplates

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4907]
Tal como se hace en [este repositorio](https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial)

Este es el contenido del archivo `.vscode/settings.json`:

```js
{
    "files.autoSave": "afterDelay",
    "files.autoSaveDelay": 700,
    "editor.minimap.enabled": false,
    "workbench.editorAssociations": {   
        "*.md": "vscode.markdown.preview.editor"
    }
}
```

Debes añadir el nombre de la carpeta en el archivo `.gitignore`, como se hace en [esta linea ](https://github.com/4GeeksAcademy/javascript-arrays-exercises-tutorial/blob/49973b1d7b756dd62fe10456fb3ceaf580cca426/.gitignore#L7)y la siguiente

Debes agregarlo en todos los repositorios de ejercicios y boilerplates, puedes encontrarlos aca:

- https://github.com/4GeeksAcademy/Interactive-Tutorials
- https://github.com/4GeeksAcademy/Templates-Boilerplates

**Comment by Lorenagubaira** [comment]
- [ ] https://github.com/4GeeksAcademy/html-hello/pulls
- [ ] https://github.com/4GeeksAcademy/vanillajs-hello/pull/64
- [ ] https://github.com/4GeeksAcademy/react-flask-hello/pull/138
- [ ] https://github.com/4GeeksAcademy/flask-rest-hello/pull/32
- [ ]

**Comment by Lorenagubaira** [comment]
2. Interactive exercises:

- [ ] https://github.com/breatheco-de/exercise-postcard/pull/87
- [ ] https://github.com/4GeeksAcademy/html-tutorial-exercises-course/pull/115
- [ ] https://github.com/4GeeksAcademy/html-forms-tutorial-exercises/pull/49
- [ ] https://github.com/4GeeksAcademy/css-tutorial-exercises-course/pull/114
- [ ] https://github.com/4GeeksAcademy/css-layouts-tutorial-exercises/pull/40
- [ ] https://github.com/4GeeksAcademy/bootstrap-exercises-tutorial/pull/51
- [ ] https://github.com/4GeeksAcademy/javascript-dom-tutorial-exercises/pull/70
- [ ] https://github.com/4GeeksAcademy/javascript-events-tutorial-exercises/pull/26
- [ ] https://github.com/4GeeksAcademy/javascript-beginner-exercises-tutorial/pull/120
- [ ] https://github.com/4GeeksAcademy/javascript-functions-exercises-tutorial/pull/86
- [ ]

**Comment by tommygonzaleza** [comment]
Alejandro debe aceptar los PRs porque no tengo permisos, escribele
