### ISSUE TITLE
Agregar componente `<JobGuaranteeSmall>` en diferentes landings

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4910]
El componente esta detallado aqui #4566 y este es el link al que vamos a llevar por ahora cuando presionas [conditions apply](https://storage.googleapis.com/4geeks-academy-website/PDF%20and%20Docs/Conditions%20Job%20Guaranteed%20Program.pdf) y [en español](https://storage.googleapis.com/4geeks-academy-website/PDF%20and%20Docs/Condiciones%20y%20Requerimientos%20Job%20Guaranteed%20Program.pdf)

- [En el template de curso, tanto fullstack, datascience, etc. (ingles y español)](https://www.awesomescreenshot.com/image/38961650?key=97ee9f1de0ec77631237c56b4e3667bd)

- [En el landing de campus](https://www.awesomescreenshot.com/image/38971358?key=4b0a726c44fa83ec05a74792b7cc0e12)

**Comment by tommygonzaleza** [comment]
El componente debe ir abajo de la seccion de **About the program**

**Comment by tommygonzaleza** [comment]
El componente debe tener un max-width para los elementos internos, para que estos se encuentren centrado y que a los lados quede espacio vacio y ya.

Asi se ve ahora:
![Screenshot 2023-05-02 at 12 41 51 PM](https://user-images.githubusercontent.com/56565994/235730592-5d8e10e7-6ae5-4ae6-92b9-55eba7cf612b.png)

Y se debe ver asi:
![Screenshot 2023-05-02 at 12 43 56 PM](https://user-images.githubusercontent.com/56565994/235730864-99b2bd8f-3f14-4c77-8268-a19a82c66c3a.png)
