### ISSUE TITLE
Crear componente `MktEventCards` para landing de workshops

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4913]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=7186%3A35556&t=UYq5BlBT1b9ltJlC-1

- [ ] Empieza creando el `<EventCard>` que sera usado en muchos lugares (ponlo en storrybook) [figma](https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=7186%3A35556&t=UYq5BlBT1b9ltJlC-1)
- [ ] Luego crea el `<MktEventCards>` para usar en slice machine [figma](https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=8325%3A40734&t=aSz6g6Pl4k5SpRFl-1).

**Comment by tommygonzaleza** [comment]
- [ ] Falta publicar el componente `MktEventCards` en prismic
