### ISSUE TITLE
En al vista de signup movil ocultar el filtro de ciudad si ya filtre

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4914]
Mostrar directo la lista de ciudad y que diga `Currently displaying class near Caracas` y un boton de eliminar ese filtro para volver a mostrar el paso anterior.

<img width="181" alt="Screenshot 2023-04-14 at 12 09 38 PM" src="https://user-images.githubusercontent.com/426452/232098407-1b4f2ddd-6a22-444d-9f01-118cff795b82.png">

**Comment by alesanchezr** [comment]
El diseño esta casi listo pero no sera un dropdown sino que la caja se expandira para permitirite escribir la ciudad, se parece mas a un acordion cuando le das click.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=7470%3A35388&t=Kgc5SZ622nQGyuNT-1
