### ISSUE TITLE
Updated pricing section design on 4geeksacademy website

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4916]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/38971312?key=809ca86fc5124595352e1aac231238fb&size=orig) 

---
**Source URL**:
[https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?node-id=5600-3110&t=BTonObIfgmsY32kV-0](https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?node-id=5600-3110&t=BTonObIfgmsY32kV-0)

**Comment by tommygonzaleza** [comment]
Se esta comentando este cambio en este issue: https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/3908

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=6987%3A9857&t=ojFZ3iqPB4cryHD0-1
