### ISSUE TITLE
Traducir los README.md de cada uno de los pasos del tutorial

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4922]
El tutorial de [Excuse Generator Javascript CLI](https://github.com/breatheco-de/excuse-generator-javascript-cli) se debe traducir, las intrucciones de cada uno de los proyectos se encuentra en la carpeta `./.learn/exercises`

**Comment by Lorenagubaira** [comment]
PR: https://github.com/breatheco-de/excuse-generator-javascript-cli/pull/3
