### ISSUE TITLE
set the Spanish readme the same as the English one

### ISSUE THREAD

**Issue by Lorenagubaira** [4GeeksAcademy/About-4Geeks-Academy#4924]

**Comment by Lorenagubaira** [comment]
https://github.com/4GeeksAcademy/object-oriented-javascript-tutorial-exercises/blob/master/README.md

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/object-oriented-javascript-tutorial-exercises/pull/18

**Comment by tommygonzaleza** [comment]
I don't have permissions, Alejandro must accept the PR
