### ISSUE TITLE
create translation in spanish

### ISSUE THREAD

**Issue by Lorenagubaira** [4GeeksAcademy/About-4Geeks-Academy#4942]
https://github.com/4GeeksAcademy/java-beginner-exercises

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/java-beginner-exercises/pull/3

**Comment by tommygonzaleza** [comment]
Escribir a Alejandro para que acepte el PR, yo no tengo permisos para aceptarlo. Ya fue revisado
