### ISSUE TITLE
This link is not working https://github.com/breatheco-de/content/blob/master/lesson/4geeks-teaching-tools

### ISSUE THREAD

**Issue by ehiber** [4GeeksAcademy/About-4Geeks-Academy#4956]
### Bug description

the teaching tools is not working in this leasons

![image](https://user-images.githubusercontent.com/56272634/233146379-61edc98c-e503-4ccb-b254-7a1e1a29d2a2.png)
![image](https://user-images.githubusercontent.com/56272634/233146409-ba0ad915-af78-440f-9af7-d8f08ce3928c.png)

https://4geeks.com/lesson/what-is-github-codespaces
https://4geeks.com/es/lesson/tutorial-de-github-codespaces

### Steps to reproduce

Click to teaching tools link on https://4geeks.com/lesson/what-is-github-codespaces

**Comment by tommygonzaleza** [comment]
Ya se agrego el link correcto
