### ISSUE TITLE
Feedback button for projects 

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4958]
Actualmente el feedback que se da en los proyectos se encuentra un poco oculto, es dificil saber cuando una tarea tiene feedback del profesor.

Se debe agregar un boton o algun icono que deje saber que hay un comentario para que pueda ver los detalles de la entrega. Y el checkmark se queda para marcar la tarea como lista.

<img width="1409" alt="Screenshot 2023-04-19 at 3 19 48 PM" src="https://user-images.githubusercontent.com/56565994/233178505-3bd1ac04-a35b-407f-afc3-c4b68c469cd0.png">

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=8641%3A41110&t=XQUacuWieNlGlpZX-1

**Comment by tommygonzaleza** [comment]
Poner solo el icono, utilizar el icono del code review
