### ISSUE TITLE
Texto pequeño 

### ISSUE THREAD

**Issue by Gfervic** [4GeeksAcademy/About-4Geeks-Academy#496]
En mi mac de 15" los p se ven muy pequeños y casi pegados. Considerar algo de line-height para los p y de letter spacing para los headings

![Screenshot 2020-07-18 at 13 58 05](https://user-images.githubusercontent.com/28119213/87852027-ba3c8c00-c8fe-11ea-9f28-07522edf029a.png)

**Comment by alesanchezr** [comment]
Hey @plucodev can try adding 2px to all fonts or specially normal fonts like p tags?
