### ISSUE TITLE
Headers en heroes

### ISSUE THREAD

**Issue by Gfervic** [4GeeksAcademy/About-4Geeks-Academy#497]
El texto de los headers no se le bien en los heroes

Añadir un div negro con alpha para que se pueda leer mejor el texto en blanco

Ver screenshot

![Screenshot 2020-07-18 at 14 11 29](https://user-images.githubusercontent.com/28119213/87852298-02f54480-c901-11ea-90ec-51f4fc27687f.png)

**Comment by alesanchezr** [comment]
Cerrado porque ahce referencia a https://github.com/4GeeksAcademy/website-v2/issues/246
