### ISSUE TITLE
Cambios en vista de checkout en el paso de contact information

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4971]
<img width="1470" alt="Screenshot 2023-04-20 at 9 44 04 AM" src="https://user-images.githubusercontent.com/56565994/233386202-6bbf4300-2964-472b-8583-0fd4801326fe.png">

Se deben agregar dos checkbox, uno para aceptar los privacy policy y otro para aceptar los terms and conditions, busca ejemplos de como se hacen en otras paginas

Haz solo una propuesta donde el form este centrado pero con los inputs uno encima del otro, haciendolo mas pequeño. La otra en la que se encuentre el form a la izquierda y un dibujo o animacion a la derecha NO debes hacerla

**Comment by ali5uarez5** [comment]
El componente tiene un buliano para mostrar u ocultar la imagen. 

https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=4208%3A11449&t=QgNcZ8OZGX89PfY7-1

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=8721%3A42687&t=QgNcZ8OZGX89PfY7-1
