### ISSUE TITLE
Convertir el boton de gitpod en una modal para elegir provisioning vendor

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#4973]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/39138843?key=763c189790f7772d27507811bcccb771&size=orig) 

 - [ ] El logo de gitpod no va a aparecer mas en el boton sino el de learnpack en su lugar.
- [ ] Cuando se aprete el boton aparecera una modal que dice:

```
You can open these exercises instantly with VSCode Online using one of the following vendors:
```

Luego aparecen dos cajas que puedes hacerle click: Gitpod o Github Codespaces (los logos de cada uno).

Debajo en letras chiquitas dice: 

Click on one of these links to learn more about [GitHub Codespaces](https://4geeks.com/lesson/what-is-github-codespaces) or [Gitpod](https://4geeks.com/lesson/how-to-use-gitpod).

---
**Source URL**:
[https://4geeks.com/interactive-exercise/object-oriented-programing-in-javascript](https://4geeks.com/interactive-exercise/object-oriented-programing-in-javascript)

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=9167%3A44102&t=yTjHaO02bMxJDsrF-1

**Comment by tommygonzaleza** [comment]
Mismo issue que [este](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5497)
