### ISSUE TITLE
Diseño de Call To Action para vender cursos en articulos

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#4982]
Crear componente `MktSideRecommendedCourses`, el cual es una version reducida y que debe ir a la izquierda de los articulos. Debe ser una version reducida del componente [MktRecommendedCourses](https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=8306%3A41178&t=NpTrA1IpHxOtwYc3-1), se inicio pensando en algo similar pero para workshops, como esto: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=7705%3A35921&t=IF2GGS32Lax2YYm7-1

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=2563%3A3760&t=Yh3kIKTsShaFKXmk-1
