### ISSUE TITLE
Liberar keywords de clusters importantes que fueron usadas en legacy articles

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#5001]
Tenemos unos 6 clusters que son prioridad ahora mismo, creo que algunas de las keywords relacionadas a esos clusters fueron mal utilizadas, por ejemplo: 

- `aprender a programar` esta usada en el mismo articulo que `aprender a programar desde cero`, vamos a separarlos y que el nuevo apunte al cluster.
- `como aprender a programar` fue hecho con un articulo legacy que no esta optimizado, vamos a cambiarle la keyword a ese articulo por una que tenga mas sentido y asi liberamos `como aprender a programar` que es una keyword de mucha calidad.

Por favor revisa los clusters improtantes, deben haber muchos otros casos asi que nos van a liberar keywords importantes.

**Comment by Jsolis4geeks** [comment]
Completed, all articles from LATAM and Miami were reviewed.

**Comment by URubino4Geeks** [comment]
Ya se liberaron las keywords
