### ISSUE TITLE
Cambios al componente usado para profiles en meet our speakers

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#5004]
Entregar otra propuesta: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=6565%3A25100&t=qWTtPU6u4hZ98rpR-1

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=8539%3A40918&t=vYR2TKKaNAZJBMou-1

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=6565%3A25100&t=1QjaSvzK1tzFteFx-1

**Comment by alesanchezr** [comment]
Falta solo corregir los iconos de redes sociales para que se parezcan al dieseño, bajarse un iconset de flaticon.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=6565%3A25100&t=y9sRt6menoZ172HF-1
