### ISSUE TITLE
Usar el artículo de Data Science para la keyword de Machine Learning Bootcamp en referencias

### ISSUE THREAD

**Issue by URubino4Geeks** [4GeeksAcademy/About-4Geeks-Academy#5010]
- [ ] Cambiar keyword del artículo de Bootcamp Data Science Chicago a Machine Learning
- [ ] Utilizarlo para publicarlo en referencias
https://docs.google.com/document/d/17BNgm29FXbdfydN02CTFHogULT92QSTGMsMx67NKPC0
https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4779

**Comment by Jsolis4geeks** [comment]
Para esto seria necesario basicamente reescribir el artículo, pues el contexto es centrado completamente a Data Science, lo puedo editar o lo podemos dejar para posicionar la Keyword de Data Science.

**Comment by URubino4Geeks** [comment]
Bootcamp datascience chicago (Briefing para mandar al escritor para el nuevo artículo del blog)

- Start the article mentioning that chicago has a great datascience offering with prominent internacion bootcamps like 4Geeks Academy, relevant national bootcamps like General Assembly but also some local vendors like Metis.
- List all the following bootcamps and add one paragraph describing them: Flatiron School, Data Science Dojo, General Assembly, Metis, Promotable.
- Add an additional section about that 4Geeks recently opened operations in chicaco and chicago students will have all the premium benefits that 4Geeks online students have. Speak about the beffits of the 4geeks offering including Job Guarantee, Unlimited mentorships and career support for life, etc. Also mention 4geeks awards.
- Add also a pagragrah to speak about some of the universities that offer data programs like Northwestern, University of Illinois and University of Chicago.
- What are the betefits or tradeoffs or studying at the universit vs bootcamp level in datascience in chicago.
- Finish the article promoting 4geeks to anyone looking for a fast creer change and universities for more deep long term understanding.

**Comment by Jsolis4geeks** [comment]
Completed
