### ISSUE TITLE
Review assignments with code review

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#5012]
# Del lado del profesor

```txt
This project needs to have at least 3 code reviews in order to be accepted or rejected.
```
Un boton queue diga: `Start Code Review`

Los botones de aprobar y rechazar y el campo para escribir el feedback van a star ocultos hasta queue por lo menos haya 3 code reviews.

Si ya hay tres code reviews, entonces el mensaje dira:

```txt
This project already has 3 code reviews; you can continue reviewing the code or approve/reject the entire project.
```

Si ya hay tres code reviews entonces aparecen los botones de aceptar, rechazar pero tambien el de continue reviewing.

Agregar icono de code review con la lupita que diga cuantos code revies se han marcado, si de las click al icono te llev a revisar los code reviews.

Tambien en algun lado poner "Click here to learn more about code reviews at 4Geeks."

# Del lado del alumno

En la [modal de rechazo](https://www.awesomescreenshot.com/image/39338539?key=714701f121b35a26342d6dc246f25f53) colocar un mensaje y boton/icono para revisar los code reviews, el mensaje sera algo tipo:  `This feedback also includes 3 code reviews, click here to read and rate your feedback`. Y el boton dice "Read and rate the feedback".

Si el project fue aceptado [esta modal](https://4geeks.com/cohort/miami-45/full-stack/v7) debe tambien mostrar el mensaje de los code reviews que tiene y un boton para leer los reviews y darles feedback.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=8720%3A42119&t=QgNcZ8OZGX89PfY7-1

**Comment by tommygonzaleza** [comment]
- [ ] Quitar el boton de code review y agregarlo con el link
- [ ] Quitar 3/3 code reviews
- [ ]

**Comment by ali5uarez5** [comment]
Review asignment: teacher https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=8714%3A41731&t=aRw2ecW9lkgp06XH-1

Review asignment: student https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=8718%3A42045&t=aRw2ecW9lkgp06XH-1

**Comment by tommygonzaleza** [comment]
Agregaste tu el comentario en figma. Falta agregar el text area en otra modal

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=8714%3A41731&t=gMfbyekafYV6GtkA-1

**Comment by tommygonzaleza** [comment]
@Charlytoc Aqui tienes el diseño del front en donde los profesores y estudiantes pueden ver la revision de un proyecto
