### ISSUE TITLE
Cuando está el traductor de google para el sitio, la aplicación se rompe.

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#5019]
Adjunto video donde se ve el error.
https://www.awesomescreenshot.com/video/16907529?key=b01a0d3521e53877c438489e5b370668

> Aqui esta el issue original: https://github.com/breatheco-de/apiv2/issues/874

**Comment by pbullor** [comment]
@tommygonzaleza como va? consulta, esto está solucionado supuestamente? porque acabo de probarlo y sigue persistiendo el error.

**Comment by tommygonzaleza** [comment]
Ariel el error sigue pasando en produccion

**Comment by tommygonzaleza** [comment]
- [ ] El logo no se esta mostrando bien, no se si es por un cambio en este PR o en otro
![Screenshot 2023-07-17 at 11 13 23 PM](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/56565994/0963f1d1-226b-496d-b095-d2209cc0ed9d)

**Comment by tommygonzaleza** [comment]
- [ ] Tambien me muestra este error en la pagina del curso de javascript
![Screenshot 2023-07-17 at 11 19 51 PM](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/56565994/5878685c-b43c-4c4d-b918-ee91a647cbff)
