### ISSUE TITLE
Public ask for non-technical writer

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#5038]
- [x] Create typeform to accept writer applicants, [similar to this one](https://admin.typeform.com/form/ZrMACSgH/create?block=e5b2e48840ddffa8).
- [x] Connect to the notion database `SEO Writters`
- [x] Create job opening on the website, similar to this one but its a non-technical writter.
- [x] Write slack post about it, here is a sample:

```
Hello, 4Geeks community!
We have an exciting job opportunity for anyone who loves to write. We're looking for Non-technical writer's to join our team of freelancers and create clear, concise, and engaging about the ed-tech industry and our school. 

It's a part-time and freelance job with no hourly commitment. 
You can read more details about it and apply here in English and Spanish.
```
- [x] Add English and Spanish links at the end in the Slack post.
- [x] Speak with marketing and RRHH to publish job openings on all of our social media.
- [ ] Send an email to reject TECHNICAL writing applicants to give them a second chance, don't become a NON-TECHNICAL writer.

**Comment by URubino4Geeks** [comment]
Typeform job application form: https://admin.typeform.com/form/ywHMe8ff/create?block=d8893194-12a8-4115-bf0f-b0a40d99d0f9

**Comment by URubino4Geeks** [comment]
Job post: https://github.com/4GeeksAcademy/website-v2/pull/1639

**Comment by alesanchezr** [comment]
Se aprobo el PR, esperando deploy.

**Comment by URubino4Geeks** [comment]
Vamos a contactar a los escritores que nos gustan para que escriban un 1er artículo de prueba. Si el artículo nos gusta, los contratamos para más artículos, sino se descartan
