### ISSUE TITLE
Se debe evitar el consumo al unirte un evento si tu eres el host

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#5050]
- [ ] Agregar `event.event_host` el cual sera una relacion con un usuario
- [ ] Agregar `event.host_bio` el cual debe ser un texto de maximo 160 caracteres.
- [ ] Evitar consumir si el usuario es el event_host del evento

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/882
