### ISSUE TITLE
Artícle Title: Expresiones Regulares Javascript

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#5055]
## Keywords & Synonims:

expresiones regulares javascript
expresiones regulares en javascript
validar expresiones regulares javascript
expresiones regulares javascript online

Language: Spanish

Important: [Please review the following Writers Welcome Tutorial](https://www.notion.so/4geeksacademy/Writers-Welcome-Tutorial-6a056b9a89d74b51b47692998d6d679f)

**Comment by danielmoret** [comment]
https://github.com/breatheco-de/content/pull/1424

**Comment by tommygonzaleza** [comment]
<hrs>1</hrs>

**Comment by tommygonzaleza** [comment]
<hrs>0</hrs>
