### ISSUE TITLE
Hacer linkbuilding para 4Geeks

### ISSUE THREAD

**Issue by URubino4Geeks** [4GeeksAcademy/About-4Geeks-Academy#5077]
Necesitamos ejecutar una estrategia de linkbuilding para 4Geeks. Inicialmente necesitamos: 

- [ ] Revisar las campañas existentes en Linkhunter para ejecutarlas para 4Geeks
- [ ] Revisar qué otras campañas podemos ejecutar para 4Geeks

**Comment by Jsolis4geeks** [comment]
Para 4Geeks recomiendo usar la estrategia de Broken LinkBuilding, la de xq no estan enlazando a 4Geeks y tambien se pueden promover los enlaces a los How to como forma de solucionar cuestiones.

Quedaria definir los principales competidores, a mi entender son:

- [ ] Platzi
- [ ] w3school
- [ ] geekforgeeks
