### ISSUE TITLE
Bill academies based on provisioning vendor activity

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#5085]
At the end of the month we are getting this log of activities from the provisioning vendors:

[Gitpod.csv](https://github.com/4GeeksAcademy/About-4Geeks-Academy/files/11401799/bquxjob_8333d74_1877ae4796f.csv)
[Codespaces.csv](https://github.com/4GeeksAcademy/About-4Geeks-Academy/files/11401803/log_of_activities.csv)

We need and algorithm that based on those CSV can upload that data and create [ProvisioningActivity's](https://github.com/breatheco-de/apiv2/blob/main/breathecode/provisioning/models.py#L117) and attribute each of those that activities to the respective [ProvisioningBill](https://github.com/breatheco-de/apiv2/blob/main/breathecode/provisioning/models.py#L91) to the academy were the student belongs.

## For Github

This is how you know if a student activity should be billed to a particular academy:

If the student has a `GithubAcademyUserLog` with values `GithubAcademyUserLog.storage_status='SYNCHED'` and `GithubAcademyUserLog.storage_action='ADD'`, during the same period in time were the activity took place.... the activity should be billed to that `GithubAcademyUserLog.GithubAcademyUser.academy`

## How to bill gitpod

In the case of gitpod do not use GithubAcademyUser, we cannot rely on that information.
For billing Gitpod all we can do is compare the github username found on the csv file with the ProfileAcademy, if the user has multiple profile academies then you can use the CohortUser to see which cohort the user was active that matches with the consumption dates in the CSV.

**Comment by tommygonzaleza** [comment]
- [ ] Falta calcular el precio de gitpod

**Comment by tommygonzaleza** [comment]
- [ ] Se deben utilizar permissions en vez de capabilities .
- [ ] Se tiene que cambiar el URL de `/v1/provisioning/academy/upload` a `/v1/provisioning/admin/upload`.

**Comment by tommygonzaleza** [comment]
- [ ] Agregale un nuevo status a la tabla `GithubAcademyUser` que sea `PAYMENT_CONFLICT`, este se va a cobrar a todas las academias en los bills que se generen

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/931

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/938

**Comment by tommygonzaleza** [comment]
- [ ] Permitir generar un CSV a partir de una ProvisioningBill

**Comment by jefer94** [comment]
https://stackoverflow.com/questions/32545632/how-can-i-download-a-file-using-window-fetch
