### ISSUE TITLE
Agregar propiedad `admissions.cohort.intro_video`

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#5113]
- [ ] Agregar la propiedad `intro_video` a las cohorts, la cual debe permitir agregar el link a un video que sera introductorio

**Comment by tommygonzaleza** [comment]
Blocking this [issue](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5110)

**Comment by Andresgarciasch** [comment]
<hrs>1.5<hrs>

**Comment by Andresgarciasch** [comment]
https://github.com/breatheco-de/apiv2/pull/881

**Comment by tommygonzaleza** [comment]
<hrs>1.5</hrs>
