### ISSUE TITLE
Parent functions

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#5117]
Following the [usual designs we have in our graphs](https://github.com/Lorenagubaira/machine-learning-content/blob/master/02-stats/calculus.md), we need a cheat sheet that shows all the part functions.

![parent-functions](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/426452/86958ce6-9317-4961-ac14-9aa482c27543)
![original-3964893-1](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/426452/1de0dd8d-95da-47e5-85b5-f21abfe50f4b)

![original-5772595-1](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/426452/3e85ff52-0932-4151-aecb-94bb2a9fce2f)

**Comment by Lorenagubaira** [comment]
PR: https://github.com/4GeeksAcademy/calculus-and-algebra-with-python/pull/6

**Comment by tommygonzaleza** [comment]
Alejandro tiene que aceptar el PR
