### ISSUE TITLE
El servicio `GET /v1/payments/me/service/consumable` esta fallando

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#5132]
El servicio esta retornando el balance de los consumibles vacio, cuando en verdad la persona si tiene consumibles.

## Pasos para reproducirlo:

1. Utiliza el token del usuario `5106`.
2. Si revisas en `https://breathecode-test.herokuapp.com/admin/payments/consumable/53/change/`, existe el consumible.
3. Pero cuando utilizo el servicio, retorna el balance vacio (Un array vacio en cada una de las propiedades)

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/889/files

**Comment by tommygonzaleza** [comment]
![Screenshot 2023-05-11 at 1 40 33 PM](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/56565994/b78cffa1-4c9b-4774-a8ee-745a29f8ede2)

**Comment by tommygonzaleza** [comment]
Sigue generandose mal el balance no? Con -1 por defecto
