### ISSUE TITLE
`<Feedback>` component.

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#5139]
In the dashboard leets create a new "feedback" component that will say: `Get feedback from senior mentors and Rigobot, our artificial intelligence. Learn more.`

The box will contain 3 icons with notifications: Code Reviews (and the amount of code reviews pending to be read), LearnPack and the amount of suggestions from learnpack, Mentors (suggestions from mentors in your class or mentorship sessions)

This box will be placed in the dashboard the same way the workshops are.

- [ ] If you are not connected to Rigobot, it has to say "Connect to Rigo".
- [ ] If you are already connected it shows the 3 icons with the unread red bubble numbers on each.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=8988%3A42627&t=PIfAI8HCkuc4QZvw-1

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=8988%3A42627&t=VBmDTLjah13LjtiU-1

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=8988%3A42627&t=y9sRt6menoZ172HF-1

**Comment by tommygonzaleza** [comment]
- [ ] Agregar icono con mensaje de cuantos feedbacks hay sin leer
