### ISSUE TITLE
Desarrollar pagina de Job guarantee

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#5144]
Basado en el issue #4793 desarrollar esa pagina.

Reutilizar todos los componentes que peudas.

**Comment by tommygonzaleza** [comment]
Los componentes se estan alargando mucho por la pagina cuando el tamaño de la pantalla es grande, deben funcionar igual que los de la pagina de 4geeks que mantienen el mismo width que cuando estan en una pantalla desktop normal.
![Screenshot 2023-06-13 at 12 18 01 PM](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/56565994/e7c6ad86-12f7-4f6f-8d28-830dcc0c7311)
![Screenshot 2023-06-13 at 12 16 52 PM](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/56565994/2278c490-5bcb-428a-8226-07309279540c)
