### ISSUE TITLE
Add new `meta_info.cluster` property to the./data/location ymls

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#5145]
This will be used to fetch for the blogposts under that cluster and display the 4 most recent ones on the location landing page.

**Comment by tommygonzaleza** [comment]
Todos los location deben tener un cluster por defecto para que se muestren articulos en el blog aunque no tenga articulos propios del location

**Comment by tommygonzaleza** [comment]
- [ ] Los articulos se deben ordenar segun los clusters en el orden que esten en el array de izquierda a derecha, revisa si ya se hace por defecto, sino agregar un sort
