### ISSUE TITLE
Agregar video introductorio en el dashboard de la cohort

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#5146]
El video debe poderse colapsar, cuando esta colapsado se debe ver el progreso del estudiante en la cohort. Cuando no esta colapsado (El video se ve), no se debe ver el progreso de ala cohort

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=8986%3A42579&t=PIfAI8HCkuc4QZvw-1

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=8986%3A42579&t=Pb929hUDIJGSLcQd-1

Final
