### ISSUE TITLE
Ocultar nota de traduccion a español en projectos y ejercicios cuando se ven desde 4Geeks.com

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#5181]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/39932791?key=248f4e3dd2c0869b668e2306c199fb64&size=orig) 

---
**Source URL**:
[https://4geeks.com/syllabus/fake-coding-introduction/practice/js-beginner](https://4geeks.com/syllabus/fake-coding-introduction/practice/js-beginner)

**Comment by tommygonzaleza** [comment]
Ya fueron revisados todos
