### ISSUE TITLE
Bajarle el stroke para que funcione en tamaño más pequeño

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#5189]
[Este icono](https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=7298%3A40096&t=1EVvUBxwVwdJ7sxE-1) debes bajarle el stroke para que se pueda ver bien si se pone pequeño

**Comment by ali5uarez5** [comment]
![Image](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/105449728/270bf8fe-604e-449b-8f00-8b35ed5cb5fa)

**Comment by ali5uarez5** [comment]
![Image](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/105449728/d0a26ae4-6cbc-43d0-93a5-e215e9d076fe)

**Comment by tommygonzaleza** [comment]
Se va a probar con este icono y luego se cerrara de funcionar

**Comment by tommygonzaleza** [comment]
Se solicito el cambio en este [issue](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4141)
