### ISSUE TITLE
Algunas tecnologias en los tutoriales dan 404

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#5194]
- [ ] Si le as click a REST da 404 pero Python si funciona.
- [ ] Tambien esta ocurriendo en los lessons, [mira esto](https://www.awesomescreenshot.com/image/39942847?key=f5dcb049d9fbc699a23f2485d953b8a2).

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/39942778?key=045fe93d48a6644020e154a0317f14e9&size=orig)

**Comment by tommygonzaleza** [comment]
Me sigue dando 404 con algunas tecnologias
