### ISSUE TITLE
Mejoras al landing de aprender-a-programar-ve

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#5195]
- [x] Agregar [componente de reviews](https://www.awesomescreenshot.com/image/39943064?key=7f9bdd654a2c6de16c48f99adbd22e68) que puedes encontrar en el [landing de clark](https://4geeksacademy.com/us/landing/clark-scholarship).
- [x] Agregar diseñado para [hacerte exitoso](https://www.awesomescreenshot.com/image/39943171?key=352eaaf35d53c8a8b20ab4c753a3865e) como en el [landing de node](https://4geeksacademy.com/es/landing/curso-node-js).
- [x] El [nro de tlf esta malo](https://www.awesomescreenshot.com/image/39942986?key=ee1920e135823055954f5e28dfc078ce).
- [x] [La foto esta mala](https://www.awesomescreenshot.com/image/39943196?key=3226dc05ad4230581038ada495533eeb).

**Comment by URubino4Geeks** [comment]
![Image](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/129084465/4d4703c7-ac12-4869-894c-a23f1cdfc76c)
