### ISSUE TITLE
Reporte de conversiones por landing page

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#5196]
https://analytics.google.com/analytics/web/#/analysis/p281853246/edit/70pYYLZXQHGA_3LLGSWHSw

- [x] Listado de todos los landings con mas conversiones `request_more_info` y `website lead`.
- [x] Total de sessiones
- [x] Total de converiones.
- [x] Convertion rate.
- [x] Poder comparar los diferentes tipos de utm sources y cual es mas efectivo convirtiendo.

**Comment by URubino4Geeks** [comment]
Ya que en GA4 no existe la dimensión de Landing Page, hicimos un workaround con una custom dimension a través de Tag Manager: https://twooctobers.com/blog/reporting-on-ga4-landing-pages-in-looker-studio/

Estamos esperando a que se popule la data para esta dimensión antes de crear el reporte.

**Comment by URubino4Geeks** [comment]
https://analytics.google.com/analytics/web/#/p281853246/reports/explorer?params=_u..pageSize%3D25%26_u..nav%3Dmaui%26_r.explorerCard..rowsPerPage%3D25&r=5252037191&collectionId=5029264759
