### ISSUE TITLE
Python flask api tutorial doesn't work in codespaces

### ISSUE THREAD

**Issue by ehiber** [4GeeksAcademy/About-4Geeks-Academy#5197]
### Bug description

https://github.com/breatheco-de/python-flask-api-tutorial failed the 003 test with the correct answer and don't allow continue

### Steps to reproduce

Follow the excercise intructions 
![image](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/56272634/a7f0f616-73aa-4dc9-b3aa-58c1c18aa973)

### Expected behavior

Pass the test

### Anything else?

I think codespace don't reconigze the flask library with pipenv

**Comment by alesanchezr** [comment]
A mi esto nome esta pasando, me funciona perfecto.

**Comment by tommygonzaleza** [comment]
Yo si pude replicar el error

**Comment by tommygonzaleza** [comment]
Con Gitpod si funciona bien, pero me esta pasando con codespaces y local

**Comment by tommygonzaleza** [comment]
Resuelto en este [PR](https://github.com/breatheco-de/python-flask-api-tutorial/pull/70)
