### ISSUE TITLE
Refrescamiento del landing de GeekPal y GeekForce

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#5235]
Refrescar el diseño para que se parezca mas a nuestra nueva imagen de marca

**Comment by ali5uarez5** [comment]
Geekforce: https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=7497%3A13028&t=IO8it2CBAMAWoqPD-1

**Comment by ali5uarez5** [comment]
Geekpal: https://www.figma.com/file/0kfc9La5QthLyu927siuCw/Website-Project?type=design&node-id=7489%3A12061&t=IO8it2CBAMAWoqPD-1
