### ISSUE TITLE
GET /v1/finetuning/coderevision/[coderevision_id]

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#5255]
Obtener detalles de un solo coderevision.

Seguridad:
Solo puedes obtenerlo si eres el que hizo el revision o de los que le hicieron el revision.

Payload:
Metele todos los juguetes.

**Comment by Charlytoc** [comment]
- [ ] The response if the user if not allowed to see the code revision must be formatted
