### ISSUE TITLE
Revisar listado de posibles referencias

### ISSUE THREAD

**Issue by URubino4Geeks** [4GeeksAcademy/About-4Geeks-Academy#5260]
Chike Erinna. El resto de la información está en un correo (Un listado de proveedores de referencias).

**Comment by Jsolis4geeks** [comment]
Ya se añadió toda la información a la [Sheet de LinkBuilding](https://docs.google.com/spreadsheets/d/1MzdQuREbNdexuq3-H_nJbahzvQIncrzo/edit#gid=763993417)
