### ISSUE TITLE
Agregar un `data` atributo opcional al `breathecode.utils.ValidationException`

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#5274]
Este atributo llamado `data` que es opcional, puede ser cualquier diccionario. 

La idea es que al levantar la excepcion se le pueda pasar un diccionario con informacion util para el front end para entender mejor porque ocurrio esa excepcion.

**Comment by tommygonzaleza** [comment]
Bloqueando a este [issue](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5273)

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/947
