### ISSUE TITLE
Prevent login without accepting invites with email validated

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#5276]
- [x] We must include a `UserInvite.is_email_validated` property that will be false by default.

- [x] When a user is trying to login we have to check if the user has at least `one` UserInvite with `status=ACCEPTED` and `is_email_validated=true`.

- [ ] If there is no invites with is_email_validated=true we shouldn't send a token to the user in the request
- [ ] We should also include in the ValidationException a data object with the invite id and status, this data will be used by the front end if the user wants to re-send the invitation email (check [#5274](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5274))

- [x] We should also provide the front end with a new endpoint to resent invites, this endpoint will rest the invite hash and expiration as well, and of course re-send the email to the user inbox.

- [ ] We should also prevent the email to be updated on invites, we can make email `read_only=True` on the serializer for updating the UserInvite.

- [ ] Lets create a django command that sets is_email_validated=true to all legacy invites from academies that are not available_as_saas

**Comment by tommygonzaleza** [comment]
Blocking this [issue](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5421)

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/947
