### ISSUE TITLE
Update the login to block users without validated emails

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#5278]
Based on #5276 the backend will return a 400 error with some `data` property if the user tries to login without having its email validated.

The front needs to make sure that if the response status 400 is received and the `data` property is a UserInvite with `is_email_validated=false` it needs to show a modal window with the `details` property from the exception (like always) but also a button to resend the invite, the `data` will contain the invite information.

**Comment by tommygonzaleza** [comment]
Este issue esta obsoleto, fue reemplazado por [este](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/5421)
