### ISSUE TITLE
Modificar el servicio `/v1/auth/subscribe` en el caso `plan.has_waiting_list=True`

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#5290]
Si `plan.has_waiting_list=True`, entonces el servicio no debe mostrar un `ValidationException` sino crear el invite con status=WAITING_LIST y ya. De ser `plan.has_waiting_list=False`, entonces debe crear el invite con status=ACCEPTED (Si las demas condiciones que ya estan se cumplen)

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/939
