### ISSUE TITLE
Students are telling me they can't submit their projects

### ISSUE THREAD

**Issue by vancieta** [4GeeksAcademy/About-4Geeks-Academy#5326]
### Bug description

![Screenshot 2023-06-02 at 3 35 40 PM](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/116301809/2b720b10-dd3a-4c5a-b07b-51550d55724c)

### Steps to reproduce

Try to submit a project on the "construye tu perfil profesional" program

### Expected behavior

To let them submit the project

**Comment by tommygonzaleza** [comment]
@ArielCalisaya Revisa por que ocurre este error, puede ser por algo en el backend (De ser asi lo reasignamos) como puede ser tambien por un problema en el frontend que esta haciendo mal el request
