### ISSUE TITLE
Rediseño de landing para entrar a workshops

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#5335]
Agregar mejoras a este landing, aqui esta el figma: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=7031%3A32971&t=7eP8EZsRcScxD4iD-1

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=9400%3A43809&t=xwvfh2CQcYb4WzLc-1

**Comment by tommygonzaleza** [comment]
[Asi](https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=9672%3A45460&mode=design&t=ZDpzIZJ70n7EvR3I-1) deberia verse cuando esta en vivo el evento y el usuario esta loggeado
