### ISSUE TITLE
Prevent adding to waiting list if the user has invites "PENDING".

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#5338]
Asi como hoy en dia [validamos el plan y la cohort para auto-aceptar invites](https://github.com/breatheco-de/apiv2/blob/main/breathecode/authenticate/serializers.py#L1108). Debemos hacer una validation similar:

Si un usuario esta subscribiendose a un invite, pero tiene otro invite que esta pending, es mejor retornar un error que diga: `Check your email! You have a pending invitation link that needs to be accepted.`, en esa excepcion enviar el objeto del invite para que el front end pueda implementar el boton de "resend".

Por otro lado, si un usuario esta subscribiendose a un invite pero ya tiene otro user UserInvite.status==ACCEPTED deberiamos retornar un error: "You are already a member of 4Geeks.com, go ahead an log in."

🔥 Importante!

No cambies el ProfileAcademy.status, se debe mantener como invite para que el alumno acepte explícitamente la invitación a esa academia.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/939

**Comment by tommygonzaleza** [comment]
- [ ] Estas validaciones que se agregaron solo deben pasar si el autor es nulo, o del mismo autor
