### ISSUE TITLE
Agregar listado de referencias de Luis Carter a BD

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#5350]
https://drive.google.com/file/d/19q_7ZjOBTIvt8md55OWdbE_j4kEvcrJh/view?usp=drive_link

**Comment by Jsolis4geeks** [comment]
Completed, check here https://docs.google.com/spreadsheets/d/1MzdQuREbNdexuq3-H_nJbahzvQIncrzo/edit#gid=763993417
