### ISSUE TITLE
Corregir no-follow en referencia ingeniumweb

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#5351]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/web/image/thumbnail/40546347?key=e825cbfdc6f6b00aa16ae7cd3eaae340&size=orig)

**Comment by Jsolis4geeks** [comment]
Ya los contacté pero como tal no tienen ninguna obligación de ponernos este enlace como Do-Follow, ya que pusieron como Do-follow el de Full Stack Developer Course y ellos explican desde un principio que admiten por ese precio 1 solo enlace, no dos, nosotros añadimos 2 para ver si los aceptan, pero es sabido que algunos no lo van a hacer.

![Screenshot 2023-06-08 005434](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/118853358/774c5e6a-394b-4497-bf5e-9d6dab264fd9)
