### ISSUE TITLE
Cambios en modelo de UserInvite para agregar plan y course

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#5357]
En [este servicio](https://github.com/breatheco-de/apiv2/blob/bd733078e9fbd0d569290705bea32eaac6fc33dc/breathecode/authenticate/serializers.py#L1069) estamos creando un invite cuando un usuario se subscribe a 4geeks.com

Debemos agregar a los invites dos propiedades (claves foraneas): Plan y Couse.

- [ ] El `plan` es opcional y lo obtenemos del body payload cuando se hace `POST v1/auth/subscribe`
- [ ] El `course` es opcional y lo obtenemos del body payload cuando se hace `POST v1/auth/subscribe`, debe hacer match con marketing.models.course.

- [ ] Si el `course` lo obtenemos existosamente y lo encontramos en la BD, tambien deberiamos llenar el userinvite.academy basados en el course.academy.
- [ ] Si el course lo obtenemos exitosamente, entonces tambien podemos llenar el userinvite.syllabus.

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/951
