### ISSUE TITLE
Autoaceptar `UserInvite` en ciertos casos

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#5385]
Los UserInvite se deben autoaceptar siempre a excepcion de los siguientes casos (En estos casos no se autoacepta):

- Se esta subscribiendo a traves de un plan que tiene `plan.has_waiting_list=True`
- Si ya tiene otro `UserInvite` con cualquier status (En este caso no se debe ni crear el invite)

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/939

**Comment by tommygonzaleza** [comment]
- [ ] Incluir el status en el serializador del Invite

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/940/files
