### ISSUE TITLE
Elegir 3 nuevas referencias para españa

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#5386]
- 🇪🇸 [Aprender a programar](https://4geeksacademy.com/es/aprender-a-programar/aprender-a-programar-desde-cero).
- 🇪🇸 [Carrera de programación](https://4geeksacademy.com/es/carrera-de-programacion/carrera-de-programacion-es).
- 🇪🇸 [Full Stack Developer Bootcamp](https://4geeksacademy.com/es/coding-bootcamps/desarrollador-full-stack).
- 🇪🇸 [Full Stack Developer](https://4geeksacademy.com/es/full-stack-developer/desarrollador-full-stack).
- 🇪🇸 [Curso Programacion desde Cero](https://4geeksacademy.com/es/curso-de-programacion-desde-cero/?lang=es)

**Comment by Jsolis4geeks** [comment]
Completado pendiente a Pago

**Comment by Jsolis4geeks** [comment]
Completado
