### ISSUE TITLE
Los logos de universidades o certificados no se ven bien en dark mode

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#5410]
Propon soluciones para esto, las que tengo en mente son agregar un background claro a toda la seccion o agregarle un background a cada uno de los logos

![IMG_8239](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/56565994/2db3313e-3a72-4f74-bd75-47ff118396a8)

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=9491%3A44397&t=y8qERhBTMvPoNaOl-1
