### ISSUE TITLE
Cohort Dashboard for teachers and students

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#544]
Hrs: <hrs>10</hrs>

When the teacher/student opens a cohort they will see this dashboard:

![MHjPrjafAc](https://user-images.githubusercontent.com/426452/88839860-a0763100-d1a9-11ea-8f63-3095602d6de6.gif)

**Comment by mortegac** [comment]
woow..  this is really cool. 🚀
