### ISSUE TITLE
Tutorial de ejercicio de 12 HTML PREWORK no sigue las instrucciones

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#545]
**Describe the bug**
El tutorial del ejercicio 12 no sigue las instrucciones, dice que debes utilizar el atributo style para resolverlo y no lo resuelve de esa manera.

**To Reproduce**
1. Go to Ejercicio 12 de HTML del prework y leer las instrucciones que dicen:  Use the style attribute inside the first tr tag to set height and border color, compararlo con el Tutorial.
(https://bb248537-9a77-4598-964e-96538f286744.ws-eu01.gitpod.io/)
2. Click on tutorial

**Expected behavior**
EL ejercicio se debería resolver siguiendo las instrucciones

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alesanchezr** [comment]
se movio el bug a learnpack
