### ISSUE TITLE
Agregar fondos de pantalla para las fotos automaticas de los articulos

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#5460]
Los articulos generan fotos de manera automatica en las que aparece el titulo del articulo, estas son usadas para ser publicadas en un post en las redes en donde se avisa que se publico dicho articulo.

- [ ] Crear 5 imagenes de fondo para que se puedan alternar con los diferentes articulos

<img width="1455" alt="Screenshot 2023-06-16 at 5 24 59 PM" src="https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/56565994/bf2b6a97-ec7e-4dac-aba8-c78c847597d7">

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=2683%3A4527&t=m0hoXEfO2IgIwsPW-1

**Comment by tommygonzaleza** [comment]
Yo agregue las imagenes en este [PR](https://github.com/breatheco-de/app/pull/955)
