### ISSUE TITLE
Diseñar modal que indique que tiene que aceptar la invitacion en el email

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#5463]
Se debe diseñar una modal basandose en [esta](https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=2298%3A3048&t=132WRngVfZXb1bS7-1), que indique: 

1. Existe el caso de que el user intente hacer login pero no haya validado su correo, entonces se muestra esta modal, en la que puede darle click para que le reenviemos el email. 

2. Una vez enviado el email, la modal debe mostrar que se pudo enviar el email con exito, por lo que el diseño debe cambiar, quizas con un check verde.

```
Confirm your email address

We sent a confirmation email to: testing@4geeks.com, please check your email and click on the confirmation link.
```

- [ ] Tambien diseñar otra modal pero que sea para avisar que el ese usuario ya existe y que se diriga a hacer login, con un link a login, debe incluir tambien un link para recuperar contraseña

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=9599%3A45220&t=m0hoXEfO2IgIwsPW-1

**Comment by tommygonzaleza** [comment]
- [ ] Agrega caso en el que el email ya fue reenviado, en este caso se debe mostrar
