### ISSUE TITLE
Ajustar como se recibe la metadata de los CSV de Provisioning Activity de Gitpod

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#5522]
La metadata ya no llega como un JSON, ahora la metadata llega como columnas nuevas en el archivo, aqui un archivo de ejemplo
[gitpod-usage-4geeks-20230501-20230531.csv](https://github.com/4GeeksAcademy/About-4Geeks-Academy/files/11887649/gitpod-usage-4geeks-20230501-20230531.csv)

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/965

**Comment by tommygonzaleza** [comment]
![Image](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/56565994/0a20296f-bfbe-4ea5-9386-458a45456541)

**Comment by jefer94** [comment]
https://github.com/breatheco-de/apiv2/pull/975
