### ISSUE TITLE
Corregir amount de Provisiong Bill 

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#5526]
Actualmente esta marcando todos los bills en 10$

**Comment by jefer94** [comment]
It's false
![image](https://github.com/4GeeksAcademy/About-4Geeks-Academy/assets/3018142/3bda7c3d-5905-4a99-b04d-f96ba256cb8f)

**Comment by tommygonzaleza** [comment]
Es porque los estaba redondeando a 10 cuando eran menores de 10 no?
