### ISSUE TITLE
Crear diseño del landing de workshops cuando ya se termino

### ISSUE THREAD

**Issue by tommygonzaleza** [4GeeksAcademy/About-4Geeks-Academy#5534]
Si el workshop ya se termino el landing debe indicar que este workshop ya se termino, luego tener una seccion con el video del workshop. Otra seccion con los workshops que estan por venir, reutiliza las cards del landing de workshops publico.

**Comment by ali5uarez5** [comment]
https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=9750%3A50104&mode=design&t=lLKvMpP0DPgqYs1T-1

**Comment by tommygonzaleza** [comment]
- [ ] Debes agregar el componente de workshops, aqui esta el diseño de ambas versiones: https://www.figma.com/file/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?type=design&node-id=6565%3A25100&mode=design&t=HOUdqfbFEtgNzxdq-1

> La version de la izquierda es cuando esta live, la de la derecha es cuando no ha iniciado. Ambos te redireccionan al landing de ese workshop.

**Comment by tommygonzaleza** [comment]
Recuerda que ambos redireccionan al landing del workshop, no al workshop

**Comment by tommygonzaleza** [comment]
No esta mostrando todos los eventos que estan por venir, que restriccion pusiste que esta filtrando y mostrando solo dos eventos?
