### ISSUE TITLE
Sustituir el uso de float por flex

### ISSUE THREAD

**Issue by unocongafas** [4GeeksAcademy/About-4Geeks-Academy#577]
El contenido y los ejercicios del día 1 (PT), se explica y fomenta el uso de la propiedad CSS float para cambiar el posicionamiento de elementos en bloque.

El uso de float esta siendo abandonado por la industria ya que tiene ciertas limitaciones que dificulta la creación de diseños web modernos.

Actualmente, se esta generalizando el uso de flex para modificar el posicionamiento de los elementos en bloque, siendo este conjunto de propiedades CSS la base de muchos de los nuevos marcos de trabajo.

Algunos enlaces con información relativa a flex:

- https://css-tricks.com/snippets/css/a-guide-to-flexbox/
- https://lenguajecss.com/css/maquetacion-y-colocacion/flexbox/

**Comment by alesanchezr** [comment]
@unocongafas estabamos revisando el Syllabus y no encontramos una referencia a flex por ningun lado, creo que el unico lugar es en las video soluciones. Si ves alguna referencia a flex que se nos haya escapado nos puedes decir donde esta exactamente?
