### ISSUE TITLE
Control de versiones de Bootstrap

### ISSUE THREAD

**Issue by unocongafas** [4GeeksAcademy/About-4Geeks-Academy#579]
El contenido de la clase [Working with Bootstrap](https://student.breatheco.de/course/full-stack.v3/2/l/bootstrap-tutorial-of-bootstrap-4) y los ejercicios relacionados utilizan versiones de Boostrap.

Cuando los alumnos buscan la documentación de Bootstrap generalmente utilizan la ultima versión y en algunos casos el comportamiento o la presentación de los componentes se ha modificado ligeramente, en algunos casos, cuando trabajan por pares uno de los dos esta viendo una documentación que el otro no ve por contemplar versiones diferentes o aplican estilos que en la versión de bootstrap del ejercicio aun no estan implementados.

Como es muy difícil mantener todo el contenido y ejercicios actualizado a la última versión de bootstrap, quizas la solución pasa por explicar a los alumnos, las versiones de bootstrap, como actualizarlas en las páginas HTML y seguir la última versión de la documentación.

**Comment by ElviraQDP** [comment]
se añadirá una nota en en día del profesor recordando usar la última versión de Bootstrap

**Comment by alesanchezr** [comment]
- Para modificar el lado del profesor hay que hace rla modificacion manualmente dentro del repository de syllabus
- Para modificar el alumno se modifica el lesson directamente
