### ISSUE TITLE
Introducción a Gitpod y permisos con Github

### ISSUE THREAD

**Issue by ghost** [4GeeksAcademy/About-4Geeks-Academy#580]
Gitpod es una herramienta increible que tiene muchas utilizades increibles para simplificar el trabajo, pero, el sistema de permisos para los repositorios es complejo de configurar, algunas personas que utilizan gitpod con su cuenta de github no puede trabajar con git desde la consola porque les falta los permisos, además algunas utilizades que son importantes no se estan utilizando. 

La forma de solucionarlo fue, entrar en [Marketplace](https://github.com/marketplace/gitpod-io) e instalar/conceder permisos.

Algunas de las caracteristicas que considero se pueden explicar para mejorar el trabajo colaborativo es el compartir los espacios de trabajo (Share running Workspace), por ejemplo, para solucionar dudas, les pido que me compartan su espacio de trabajo y les añado ejemplo en su código para que puedan verlo y que el código quede sincronizado, tambien, con algunos errores a la hora de instalar dependencias de python me fue muy util.

Además, una pequeña guia donde se explique como abrir un repositorio en gitpod para que prueben: https://gitpod.io/#

**Comment by marcogonzalo** [comment]
Creo que esto debería incluirse en el prework, ya que allí tienen que crear la cuenta en Github para poder usar Gitpod.

**Comment by ElviraQDP** [comment]
https://guides.github.com/activities/hello-world/
