### ISSUE TITLE
Dar un poco más de contenido sobre interfaz de usuario

### ISSUE THREAD

**Issue by marcogonzalo** [4GeeksAcademy/About-4Geeks-Academy#589]
No esperaría que una persona se gradúe experta en UI, pero sí que tenga las nociones y el criterio básico para hacer una interfaz limpia:

- Incluir un concepto más amplio de lo que es una interfaz de usuario
- KISS
- Menos es más
- Call to action
- Dejar algunos conceptos sobre usabilidad, para dar orientación y criterio sobre cómo hacer una interfaz "usable".

**Comment by alesanchezr** [comment]
@marcogonzalo en que dia sugieres que hagamos esto? Recuerda que los dias que vamos a agregar son todos de backend, esta dificil...
