### ISSUE TITLE
Learn react: Mas completa en español q en ingles

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#622]
https://github.com/breatheco-de/content/blob/master/src/content/lesson/learn-react-js-tutorial.md

**Comment by ElviraQDP** [comment]
https://github.com/breatheco-de/content/edit/master/src/content/lesson/learn-react-js-tutorial.es.mdhttps://github.com/breatheco-de/content/edit/master/src/content/lesson/learn-react-js-tutorial.es.md

check content regarding class component before editing content
