### ISSUE TITLE
ERROR DAY 28

### ISSUE THREAD

**Issue by rlence** [4GeeksAcademy/About-4Geeks-Academy#625]
**Describe the bug**
bug in the teachers page on day 28, in the title it says to work with the flask framework but when one reads the class of the day specifies or the examples that are put it is with the django framework

**To Reproduce**
1. Go to 'day 28'
3. Scroll down to '#20 The Django Framework (interactive).'

**Expected behavior**
See de Flask framework

**Screenshots**

![Captura de pantalla 2020-10-14 a las 21 30 01](https://user-images.githubusercontent.com/40366311/96036221-748f5100-0e64-11eb-8b48-5a26da075762.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alesanchezr** [comment]
@rlence a que cohorte le estas dando clase? Estamos revisando el syllabus y no vemos esa explicación de django, nos puedes confirmar si el problema persiste de tu lado? eso fue actualizado hace un par de semanas creemos.

Tambein puedes pasarnos el URL o screenshot de toda la pantalla en el momento en que ves esa información

**Comment by alesanchezr** [comment]
@ElviraQDP ya fue solucionado me dice @rlence
