### ISSUE TITLE
Share certificate does not work on mobile

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#653]
This is a but for issue #468, you can't shar eon mobile because the linkedin API is deprecated for mobile.

What can we do fix this? @Omonroy36

**Comment by victormgomezp** [comment]
Esta funcionalidad es importante para lograr que la gente nos haga publicidad gratis.
¿Alejandro ya se puede descargar el certificado desde la web? ¿cómo se hace?

**Comment by Omonroy36** [comment]
This have been solved.
