### ISSUE TITLE
Create one lesson about HTTP

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#654]
Use this as inspiration and add the video to the lesson: 
https://www.youtube.com/watch?v=WYf1s3R1L8c&feature=youtu.be

Here is a deep explanation to a student:
https://youtu.be/s6_-c0LFDRo

PR: https://github.com/breatheco-de/content/pull/320

**Comment by ElviraQDP** [comment]
should be move to "in progress"

**Comment by alesanchezr** [comment]
- [ ] Agregar explicacion a PATCH tambien
- [ ] Agregar un diagrama

**Comment by alesanchezr** [comment]
its all black becas is missin a `"""`
https://content.breatheco.de/en/lesson/what-is-http

**Comment by ElviraQDP** [comment]
https://github.com/breatheco-de/content/pull/415
