### ISSUE TITLE
Lesson about Data-Modeling using the Crowfoot Notation

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#662]
Here is the notation:
https://www.vertabelo.com/blog/crow-s-foot-notation/

Here is a 3rd party video explanation:
https://www.youtube.com/watch?v=QpdhBUYk7Kk

Here are some exercises:
http://fileadmin.cs.lth.se/cs/education/eda216/exercises/dbtexercises.pdf

> ⚠️ IMPORTANT: After you finish the lesson make sure is added to the syllabus days on full-stack and full-stack full time.

**Comment by ElviraQDP** [comment]
revision: https://github.com/breatheco-de/content/pull/340
