### ISSUE TITLE
[12pt] Cohorts Details Admin

### ISSUE THREAD

**Issue by Omonroy36** [4GeeksAcademy/About-4Geeks-Academy#672]
hrs: <hrs>17<hrs>

Using the new admin theme complete de the `./admin/cohorts/<slug>` edit page using the breathecode API.

The requirement details are the following:

1. [3pt] Update cohort info: The left side form must be prefilled with the cohort slug, start time, end time and language.
2. The right side form list can be edited with the following:
  - [x] [1pt] Delete a member of the cohort
  - [x] [1pt] Add student to a cohort
  - [x] [1pt] List members of the cohort
  - [x] [1pt] Financial status 
  - [x] [1pt] Educational status
  - [x] [1pt] update Role 
3. [3pt] The autocomplete component should request all the users in the database and suggest names while trying to find an user, the autocomplete must be asynchronous. 

All the components needed to complete this issue are provided by the theme so every component should go accordingly.

@alesanchezr

**Comment by alesanchezr** [comment]
I need:

1. Get all **users** filtered by name, only a substring of the name as well (LIKE).
2. Get all **users** filtered from one particular cohort id.

**Comment by alesanchezr** [comment]
added 5 hours for migrating to reduct and "change cohrot stage" functionality.

**Comment by alesanchezr** [comment]
Listo para pagar

**Comment by alesanchezr** [comment]
pagado

**Comment by Jtoledo88** [comment]
pagado en enero
