### ISSUE TITLE
Warning en componentes teoría de componentes de tipo clase

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#681]
En todos los lugares donde se mencione componentes tipo clases en react, hay que agregar una alerta que diga que recomendamos el uso de hooks porque las clases son legacy.

PR:
https://github.com/breatheco-de/content/pull/352

**Comment by alesanchezr** [comment]
- [ ] We need to review the code examples because they should be multiline code blocks using three backticks instead of one, also remove the `br` and jump the line instead, also remove the `>python`.
- [ ] There is a weird `*J` at the beginning of the warnings that specify that class components are legacy.

**Comment by ElviraQDP** [comment]
https://github.com/breatheco-de/content/pull/358
