### ISSUE TITLE
Agregar concepto de Transacciones a SQL Alchemy

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#688]
https://github.com/breatheco-de/content/blob/master/src/content/lesson/everything-you-need-to-start-using-sqlalchemy.md

Ahora mismo la lesson de SQL Alchemy no habla del concepto de transaction (db.session.commit) que es muy importante en SQL Alchemy.

Necesita tu revision:
PR: https://github.com/breatheco-de/content/pull/350

**Comment by alesanchezr** [comment]
Please read a little about database transactions (commit and rollback) and how SQLAlchemy lets u use transactions using commit and rollback as well

**Comment by alesanchezr** [comment]
@JimenaEB we are going to go ahead with this, no worries you can review it later.

**Comment by ElviraQDP** [comment]
https://github.com/breatheco-de/content/pull/358
Lesson ready, needs revision to be transllated @alesanchezr

**Comment by ElviraQDP** [comment]
PR : https://github.com/breatheco-de/content/pull/358 
REview required

**Comment by ElviraQDP** [comment]
https://github.com/breatheco-de/content/pull/358
