### ISSUE TITLE
Refactor google cloud integration

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#712]
Cuando implemente la integración a google bucket estaba buscando intedependencia de las apps y por eso hay un poco de redundancia entre cada, por ejemplo el metodo para autenticar google esta duplicado.

Vamos a refactorizar eso como esta el API de slack, vamos a tener en la carpeta `/services` un archivo `google.py` the tenga una clase con todo lo concerniente a google cloud y que se archivo sea importado desde cualquier app cuando deseemos utilizar el google cloud.

> [Here is a video explanation](https://www.loom.com/share/aa82095128074a86b99324286ca19665)

**Comment by jefer94** [comment]
Done 
https://github.com/jefer94/apiv2/blob/master/breathecode/services/google_cloud/datastore.py
https://github.com/jefer94/apiv2/blob/master/breathecode/activity/views.py
https://github.com/jefer94/apiv2/blob/master/breathecode/services/google_cloud/storage.py
