### ISSUE TITLE
CohortUsers are being duplicated

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#720]
- [ ] Create a script to delete all duplicated CohortUsers
- [ ] Fix the bug to avoid more duplicate CohortUsers on the `python manage.py sync_admissions students` command.

The script must be run using Django commands on the admissions app, for example:
```py
python manage.py remove_duplicate_cohort_users
```

**Comment by jefer94** [comment]
1. remove duplicates [delete_duplicates.py](https://github.com/jefer94/apiv2/blob/master/breathecode/admissions/management/commands/delete_duplicates.py)
2. fix students and teachers script in [sync_admissions.py](https://github.com/jefer94/apiv2/blob/master/breathecode/admissions/management/commands/sync_admissions.py) with `if cohort and not CohortUser.objects.filter(user=us, cohort=cohort).count():`
3. check user cannot be added twice [tests_sync_admissions.py](https://github.com/jefer94/apiv2/blob/master/breathecode/admissions/tests/management/commands/tests_sync_admissions.py)

**Comment by alesanchezr** [comment]
you don't have to do tests on the commands, because we are going to delete them eventually, just fix the commands and that is it, no unit tests.
