### ISSUE TITLE
PROBLEMA EN CONTENIDO: no sirve el link ni en inglés ni en español

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/About-4Geeks-Academy#729]
**Describe the bug**
Este link no funciona, ni en inglés ni en español
![image](https://user-images.githubusercontent.com/62053368/101159524-d468d380-362d-11eb-8e85-c15a54600909.png)

https://breatheco.de/asset/html5-cheat-sheet no funciona ni en inglés ni en español

**To Reproduce**
1. Go to PREWORK
2. Click on MY JOURNEY / DAY 1 / LEARN HTML
3. Scroll down to Link: una de estas tags
![image](https://user-images.githubusercontent.com/62053368/101159639-feba9100-362d-11eb-9bc1-19759cc3c289.png)

**Expected behavior**
no estar roto

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Link revisado en Chile y si esta funcionando, verificar con @alesanchezr que pasa

**Comment by ElviraQDP** [comment]
Hola @victormgomezp, quizas tienes algín problema con internet? mira lo revise recién y el link está funcionando:
![image](https://user-images.githubusercontent.com/63673743/101194818-3f6dd680-363d-11eb-828c-d8d4de82b6e8.png)

**Comment by victormgomezp** [comment]
@ElviraQDP no solamente yo no lo puedo abrir, fue detectado por un estudiante y acabo de probar y no funciona. 
![image](https://user-images.githubusercontent.com/62053368/101195140-46a5dc00-365f-11eb-8db5-57df0b510937.png)

No tengo problemas de internet, me conecté a dos redes diferentes para probar y no puedo verlo. ¿Es la misma url?

**Comment by alesanchezr** [comment]
Leaving this issue for this week because the image assets are in the wrong folder.
