### ISSUE TITLE
[1pt] Upload spanish privacy and terms to the website

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#730]
[1pt] Update Spanish privacy policy and terms of use:

1. Privacy: https://docs.google.com/document/d/1NHSya_VLBXGaatmpf1pbCHjKXsOrg-S4_leIxMS7Ms4
2. Terms: https://drive.google.com/file/d/1kY4AOfkpRzDFyLD-0-3LmnjKQnyUrzmC

**Comment by plucodev** [comment]
Created Cookies and Terms of conditions in spanish.
We are missing now Terms of conditions and Cookies in english.

**Comment by alesanchezr** [comment]
Spanis links:

/privacy => /privacidad
/terms => /terminos
