### ISSUE TITLE
[3pt] Get academy staff

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#762]
GET /v1/auth/user/staff?roles=country_manager

If the user is not part of any academy, the endpoint should return 401 

If it does, then we should return only the roles from that academy.

**Comment by jefer94** [comment]
```python
    path('academy/<int:academy_id>/member', MemberView.as_view()),
    path('academy/<int:academy_id>/member/<int:user_id>', MemberView.as_view()),
```
