### ISSUE TITLE
[2pt] Add new staff to academy

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#763]
Hrs: <hrs>5</hrs>

POST /v1/auth/academy/member

- List academy member
- Edit academy member information
- Create academy member
- Invite academy member (invite true if user does not exist)

**Comment by alesanchezr** [comment]
no esta listo

**Comment by alesanchezr** [comment]
aprobado con bugs.

**Comment by alesanchezr** [comment]
por pagar

**Comment by Jtoledo88** [comment]
Pagado en Feb 2021
