### ISSUE TITLE
[2pt] As a cohort country manager I should be able to add new student

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#770]
Hrs: <hrs>5</hrs>

Este es el form: https://academy.breatheco.de/admin/students/new

POST /v1/auth/user/register

https://academy.breatheco.de/admin/students/new

**Comment by Omonroy36** [comment]
This endpoint doesnt seem to be working properly, it throws 500 error not found when doing the request

**Comment by alesanchezr** [comment]
listo para pagar

**Comment by Jtoledo88** [comment]
Pagado en enero

**Comment by Jtoledo88** [comment]
pagado en enero
