### ISSUE TITLE
[3pt] Endpoint: Update student information

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#771]
Hrs <hrs>5</hrs>
Wait for alejandro to finish the endpoint

**Comment by Omonroy36** [comment]
Hi Ale is this finished? Also i cant find the endpoint to create a new student i thought it was this one `/v1/auth/user/register` but it isnt working.

**Comment by Omonroy36** [comment]
@alesanchezr this is almost ready, i dont know if this is possible but i dont have an edpoint to see a particular user with its information something like this  GET"/academy/4/student/45" so i can prefill the form with the current information

**Comment by alesanchezr** [comment]
por pagar

**Comment by Jtoledo88** [comment]
Cuantas horas son? para poder pagar?

**Comment by Jtoledo88** [comment]
Pagado feb 2021
