### ISSUE TITLE
Integration with Applicant Tracking System to collect job openings from different portals

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#773]
We are experimenting with a new way to find amazing talent for the academy candidates using ATS and publishing jobs openings everywhere for the ISA.

We found this platform with an API that can publish on all job portals at once:
https://www.traffit.com/en/pricing/

We need to integrate with its API to fetch the leads and bring them into breathecode's marketing and lead collection engine.

**Comment by jefer94** [comment]
That is not being developed by @jhosagid7 ?
