### ISSUE TITLE
Refactoring of the AsyncAutocomplet component to unify them all in just one.

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#859]
Hrs: <hrs>4</hrs>

There should be just one AsyncAutoComplete component for the entire application that can be reused for anything.

Implement a cache layer to avoid search on the backend for the same queries.

**Comment by alesanchezr** [comment]
Si busco colby y luego busco cob y luego vuelvo a cob ya no deberia buscar cob en el backend proque ya e suna busqueda recurrente.

**Comment by alesanchezr** [comment]
aprobaro y por pagar

**Comment by Jtoledo88** [comment]
Pagado en feb 2021
