### ISSUE TITLE
Crud and list Event Information

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#860]
Hrs: <hrs>3</hrs>

- Add event image from a URL
- Update the rest of the event information

**Comment by alesanchezr** [comment]
No necesitas nada de nadie, aqui esta el endpoint:
https://github.com/breatheco-de/apiv2/commit/0f9b4dd2a6b8288ecf4205c8274aaa7ffa3489a3#diff-fc15db1c1135800c2ed8f6fe5934665da4990f4c1b62974cbf3bf4497c461d7a

**Comment by Jtoledo88** [comment]
Pagado el mes abril
