### ISSUE TITLE
Reminder script: cohort reminders

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#896]
Hrs: <hrs>6</hrs>

This is the documentation on how to create a reminder script:
https://github.com/breatheco-de/apiv2/tree/master/breathecode/monitoring/scripts

We need a script that reminds the academy about different things in a cohort:

- Sending surveys to each cohort every 4 weeks.
- If the ending date has passed and the cohort status is not ENDED.
- If the cohort stage is ENDED but there are CohortUser's with status ACTIVE.

Each reminder on a separate script.

**Comment by alesanchezr** [comment]
@marcosdevelo y @victormgomezp and @Riciglianomarcelo este reminder va a llegar por slack y por email a la academia, alguna otra cosa que crean que vale la pena recordar en una cohort?

**Comment by victormgomezp** [comment]
@alesanchezr sería interesante recordar al profesor, asistente y al director académico cosas relacionadas con los proyectos. También sería muy interesante una vez que el estudiante ha terminado, preparar un buen correo (en el idioma de la cohorte) y recordarle los próximos pasos, que debe estudiar, que debe postularse a ofertas, seguir el procedimiento en general de GeekForce.
