### ISSUE TITLE
Revisar porque el algoritmo de generacion del sitemap genera solo 138 links cuando semrush detecta 322

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#897]

**Comment by marcelovaldebenito** [comment]
Disminuyó en 100 páginas la cantidad de urls detectadas por semrush después del paso a .com.
Es importante dejar de ocupar redirects cómo comentaba en otro issue.
Espero que con el nuevo sitio tengamos la misma cantidad de urls en el sitemap y en semrush, saludos!
