### ISSUE TITLE
Revisar el sitemap (redirección)

### ISSUE THREAD

**Issue by mafecasvi** [4GeeksAcademy/About-4Geeks-Academy#898]
- [ ] cambiar nombre al sitemap
- [ ] revisar porque tiene muchos menos sites que los que son

**Comment by marcelovaldebenito** [comment]
Search Console sigue sin indexar alrededor de 150 páginas porque tienen redirects.
Está la opción de revisarlo o esperar el sitio nuevo y lanzarlo sin redirects.
Quedo atento a sus comentarios, saludos!

**Comment by marcelovaldebenito** [comment]
Revisar por qué el sitemap genera sólo 139 urls mientras semrush encuentra 431.
Después de revisar eso recomiendo cambiar el nombre del sitemap para "resetear" la revisión de search console.
