### ISSUE TITLE
Fix learning to code with python lesson

### ISSUE THREAD

**Issue by ElviraQDP** [4GeeksAcademy/About-4Geeks-Academy#911]
https://github.com/4GeeksAcademy/python-lists-loops-programming-exercises/pull/34#pullrequestreview-587701095

**Comment by alesanchezr** [comment]
- [ ] The code examples are in javascript
- [ ] Borken image
- [ ] Python does not have a switch statement.
- [ ] Migrate the animations to images
- [ ] Migrate the code examples to python using the academy repl.it account.
- [ ] any other fix you find.
