### ISSUE TITLE
Notify Refactoring

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#941]
Hrs <hrs>5</hrs>

- [ ] Implement toast notifications all over the admin
- [ ] Remove previous implementations
- [ ] Intercept Axios to notify for errors in a general way
- [ ] Success has to be notified in a local way, on every feature/form (not intercepting with axios)

**Comment by alesanchezr** [comment]
Implementar toastify en la aplicacion

**Comment by Jtoledo88** [comment]
Pagago las 5hr en abril 2021
