### ISSUE TITLE
Syllabus Builder Upgrades

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#966]
- [ ] If I close the browser tab, it should confirm only if I made some changes to the syllabus.
- [ ] When I press the button to add a new day, if should ask if I want to import from another syllabus or create a brand new day.
- [x] If I drop into the syllabus one content piece twice, the second time it should confirm with the following options: Duplicate the piece, Move to here (delete the original) or Cancel. The confirmation modal should also say in what day the original content piece was found.
- [ ] If I'm adding a lesson for the second time, it should ask if I want to replace or duplicate (keep the original).
- [x] Loading a syllabus from the API is not working properly.

**Comment by Omonroy36** [comment]
It took me 13 hours
