### ISSUE TITLE
Migrate teacher_instructions from old syllabus to new one (full-stack-ft)

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#973]
Here is a list of the instructions for each day:
https://github.com/4GeeksAcademy/academy-syllabus/tree/master/full-stack-ft/v2

We need to use the syllabus builder to add those instructions on the days.

**Comment by ElviraQDP** [comment]
en pr: https://github.com/breatheco-de/content/pull/420
