### ISSUE TITLE
Implement CMS on netlify website

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#984]
Hrs <hrs>8</hrs>

I should be able to login into the Netlify CSM for the 4Geeks website and publish articles.

- [ ] Authentication
- [ ] Create a blog post
- [ ] Preview blog post
- [ ] Update ymls
- [ ] Upload images and add them into the website

**Comment by ArielCalisaya** [comment]
PR #682 is waiting to merge with branch `master`

**Comment by ArielCalisaya** [comment]
PR from website-v2 [#682](https://github.com/4GeeksAcademy/website-v2/pull/682) is waiting to merge on branch `master`
