### ISSUE TITLE
Double check wrong exercises

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#988]
Hrs: <hrs>0.5</hrs>

There is a problem with these 3 tests on the mastering javascript:
<img width="647" alt="Screen Shot 2021-03-01 at 1 04 48 PM" src="https://user-images.githubusercontent.com/426452/109539045-d0165000-7a8e-11eb-840a-c9f52714f770.png">

**Comment by ArielCalisaya** [comment]
Solved in this [commit](https://github.com/4GeeksAcademy/master-javascript-programming-exercises/pull/28/commits/82ab47cd2d4469b3fa9fc0cf7e13fc491bb51a81)
