### ISSUE TITLE
[Front] Bulk Create CohortUser

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/About-4Geeks-Academy#994]
Hrs: <hrs>4</hrs>

1. En la vista de todos los alumnos, selecciono con un check varios.
2. En las opciones bulk me sale una para agregar a una cohorte
3. Apreto esa opción bulk y abre una modal con un dropdown para elegir la cohorte
4. Selecciono cohorte y aprendo save.
5. La lista de cohortes tiene que ser autocomplete para poder buscar.

Note: no esperes por backend, haz todos y leugo reemplazas el endpoint al momento que este listo.

**Comment by Jtoledo88** [comment]
Pagado en Marzo
